OscProb: OscProb::PMNS_Iter Class Reference
OscProb::PMNS_Iter Class Reference
Implementation of oscillations of neutrinos in matter in a three-neutrino framework.
#include <PMNS_Iter.h>
Public Member Functions
PMNS_Iter ()
Constructor.
virtual ~PMNS_Iter ()
Destructor.
virtual void SetPrec (double prec)
Set the iterative precision.
virtual void SetMix (double th12, double th23, double th13, double deltacp)
Set the all mixing parameters at once.
virtual void SetDeltaMsqrs (double dm21, double dm32)
Set both mass-splittings at once.
virtual double Prob (vectorC nu_in, int flvf)
Compute the probability of nu_in going to flvf.
virtual double Prob (vectorC nu_in, int flvf, double E)
Compute the probability of nu_in going to flvf for energy E.
virtual double Prob (vectorC nu_in, int flvf, double E, double L)
Compute the probability of nu_in going to flvf for energy E and distance L.
virtual double Prob (int flvi, int flvf)
Compute the probability of flvi going to flvf.
virtual double Prob (int flvi, int flvf, double E)
Compute the probability of flvi going to flvf for energy E.
virtual double Prob (int flvi, int flvf, double E, double L)
Compute the probability of flvi going to flvf for energy E and distance L.
virtual vectorD ProbVector (vectorC nu_in)
Compute the probabilities of nu_in going to all flavours.
virtual vectorD ProbVector (vectorC nu_in, double E)
Compute the probabilities of nu_in going to all flavours for energy E.
virtual vectorD ProbVector (vectorC nu_in, double E, double L)
Compute the probabilities of nu_in going to all flavours for energy E and distance L.
virtual vectorD ProbVector (int flvi)
Compute the probabilities of flvi going to all flavours.
virtual vectorD ProbVector (int flvi, double E)
Compute the probabilities of flvi going to all flavours for energy E.
virtual vectorD ProbVector (int flvi, double E, double L)
Compute the probabilities of flvi going to all flavours for energy E and distance L.
virtual matrixD ProbMatrix (int nflvi, int nflvf)
Compute the probability matrix.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E)
Compute the probability matrix for energy E.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E, double L)
Compute the probability matrix for energy E and distance L.
virtual double AvgProb (vectorC nu_in, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProb (int flvi, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual double AvgProbLoE (int flvi, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual vectorD AvgProbVector (vectorC nu_in, double E, double dE=0)
Compute the average probability vector over a bin of energy.
virtual vectorD AvgProbVector (int flvi, double E, double dE=0)
Compute the average probability vector over a bin of energy.
virtual vectorD AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE=0)
Compute the average probability vector over a bin of L/E.
virtual vectorD AvgProbVectorLoE (int flvi, double LoE, double dLoE=0)
Compute the average probability vector over a bin of L/E.
virtual matrixD AvgProbMatrix (int nflvi, int nflvf, double E, double dE=0)
Compute the average probability matrix over a bin of energy.
virtual matrixD AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE=0)
Compute the average probability matrix over a bin of L/E.
virtual vectorC GetMassEigenstate (int mi)
Get a neutrino mass eigenstate.
virtual void SetAngle (int i, int j, double th)
Set the mixing angle theta_ij.
virtual void SetDelta (int i, int j, double delta)
Set the CP phase delta_ij.
virtual void SetDm (int j, double dm)
Set the mass-splitting dm_j1 in eV^2.
virtual double GetAngle (int i, int j)
Get the mixing angle theta_ij.
virtual double GetDelta (int i, int j)
Get the CP phase delta_ij.
virtual double GetDm (int j)
Get the mass-splitting dm_j1 in eV^2.
virtual double GetDmEff (int j)
Get the effective mass-splitting dm_j1 in eV^2.
virtual void SetStdPars ()
Set PDG 3-flavor parameters.
virtual void SetEnergy (double E)
Set the neutrino energy in GeV.
virtual void SetIsNuBar (bool isNuBar)
Set the anti-neutrino flag.
virtual double GetEnergy ()
Get the neutrino energy in GeV.
virtual bool GetIsNuBar ()
Get the anti-neutrino flag.
virtual void SetPath (NuPath p)
Set a single path.
virtual void SetPath (double length, double density, double zoa=0.5, int layer=0)
Set a single path.
virtual void SetPath (std::vector< NuPath > paths)
Set a path sequence.
virtual void AddPath (NuPath p)
Add a path to the sequence.
virtual void AddPath (double length, double density, double zoa=0.5, int layer=0)
Add a path to the sequence.
virtual void ClearPath ()
Clear the path vector.
virtual void SetLength (double L)
Set a single path lentgh in km.
virtual void SetLength (vectorD L)
Set multiple path lengths.
virtual void SetDensity (double rho)
Set single path density in g/cm^3.
virtual void SetDensity (vectorD rho)
Set multiple path densities.
virtual void SetZoA (double zoa)
Set Z/A value for single path.
virtual void SetZoA (vectorD zoa)
Set multiple path Z/A values.
virtual void SetLayers (std::vector< int > lay)
Set multiple path layer indices.
virtual void SetStdPath ()
Set standard neutrino path.
virtual std::vector< NuPath > GetPath ()
Get the neutrino path sequence.
virtual vectorD GetSamplePoints (double LoE, double dLoE)
Compute the sample points for a bin of L/E with width dLoE.
virtual void SetUseCache (bool u=true)
Set caching on/off.
virtual void ClearCache ()
Clear the cache.
virtual void SetMaxCache (int mc=1e6)
Set max cache size.
virtual void SetAvgProbPrec (double prec)
Set the AvgProb precision.
Protected Member Functions
virtual void SolveHam ()
Just use the vacuum to start.
virtual void PropMatter ()
Propagate through matter part.
virtual void SetExpVL (NuPath p)
Set the matter propagation term.
virtual void PropagatePath (NuPath p)
Reimplement propagation.
virtual void UpdateHam ()
Build the full Hamiltonian.
virtual void SetVacuumEigensystem ()
Set the eigensystem to the analytic solution of the vacuum Hamiltonian.
virtual void InitializeVectors ()
Initialize all member vectors with zeros.
virtual bool TryCache ()
Try to find a cached eigensystem.
virtual void FillCache ()
Cache the current eigensystem.
virtual void SetCurPath (NuPath p)
Set the path currently in use by the class.
virtual void SetAtt (double att, int idx)
Set one of the path attributes.
virtual void SetAtt (vectorD att, int idx)
Set all values of a path attribute.
virtual void RotateH (int i, int j, matrixC &Ham)
Rotate the Hamiltonian by theta_ij and delta_ij.
virtual void RotateState (int i, int j)
Rotate the neutrino state by theta_ij and delta_ij.
virtual void BuildHms ()
Build the matrix of masses squared.
virtual void ResetToFlavour (int flv)
Reset neutrino state to pure flavour flv.
virtual void SetPureState (vectorC nu_in)
Set the initial state from a pure state.
virtual void Propagate ()
Propagate neutrino through full path.
virtual double P (int flv)
Return the probability of final state in flavour flv.
virtual vectorD GetProbVector ()
Return vector of probabilities from final state.
virtual std::vector< int > GetSortedIndices (const vectorD x)
Get indices that sort a vector.
virtual vectorD ConvertEtoLoE (double E, double dE)
Protected Attributes
double fPrec
Iterative precision.
double fVL
Matter potential.
complexD fExpVL
Matter phase shift.
double fPrevEnergy
complexD fHam [3][3]
The full hamiltonian.
int fNumNus
Number of neutrino flavours.
vectorD fDm
m^2_i - m^2_1 in vacuum
matrixD fTheta
theta[i][j] mixing angle
matrixD fDelta
delta[i][j] CP violating phase
vectorC fNuState
The neutrino current state.
matrixC fHms
matrix H*2E in eV^2
vectorC fPhases
Buffer for oscillation phases.
vectorC fBuffer
Buffer for neutrino state tranformations.
vectorD fEval
Eigenvalues of the Hamiltonian.
matrixC fEvec
Eigenvectors of the Hamiltonian.
double fEnergy
Neutrino energy.
bool fIsNuBar
Anti-neutrino flag.
std::vector< NuPath > fNuPaths
Vector of neutrino paths.
NuPath fPath
Current neutrino path.
bool fBuiltHms
Tag to avoid rebuilding Hms.
bool fGotES
Tag to avoid recalculating eigensystem.
bool fUseCache
Flag for whether to use caching.
double fCachePrec
Precision of cache matching.
int fMaxCache
Maximum cache size.
double fAvgProbPrec
AvgProb precision.
std::unordered_set< EigenPoint > fMixCache
Caching set of eigensystems.
EigenPoint fProbe
EigenpPoint to try.
Static Protected Attributes
static const complexD zero
zero in complex
static const complexD one
one in complex
static const double kKm2eV = 1.0 / 1.973269788e-10
km to eV^-1
static const double kK2 = 1e-3 * kNA / pow(kKm2eV,3)
mol/GeV^2/cm^3 to eV
static const double kGeV2eV = 1.0e+09
GeV to eV.
static const double kNA = 6.022140857e23
Avogadro constant.
static const double kGf = 1.1663787e-05
G_F in units of GeV^-2.
Detailed Description
Based on an approximate iterative model from:
https://doi.org/10.3390/universe6010016
............................................................................
                      Universe 6 (2020) no.1, 16
    Effects of Atomic-Scale Electron Density Profile and a Fast and
 Efficient Iteration Algorithm for Matter Effect of Neutrino Oscillation
            Mihai Horoi, Adam Zettel (Central Michigan U.)
............................................................................
Author
Joao Coelho - jcoelho@apc.in2p3.fr
Definition at line 35 of file PMNS_Iter.h.
Constructor & Destructor Documentation
PMNS_Iter()
PMNS_Iter::PMNS_Iter ()
Constructor.
See also
PMNS_Fast::PMNS_Fast
This class is restricted to 3 neutrino flavours.
Definition at line 19 of file PMNS_Iter.cxx.
: PMNS_Fast(), fPrec(1e-3) {}
~PMNS_Iter()
PMNS_Iter::~PMNS_Iter () virtual
Nothing to clean.
Definition at line 25 of file PMNS_Iter.cxx.
{}
Member Function Documentation
AddPath() [1/2]
void PMNS_Base::AddPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Add a path to the sequence defining attributes directly.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 372 of file PMNS_Base.cxx.
{
  AddPath(NuPath(length, density, zoa, layer));
}
References OscProb::PMNS_Base::AddPath().
AddPath() [2/2]
void PMNS_Base::AddPath (NuPath p) virtual inherited
Add a path to the sequence.
Parameters
p - A neutrino path segment
Definition at line 358 of file PMNS_Base.cxx.
{
  fNuPaths.push_back(p);
}
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::SetAtt(), OscProb::PMNS_Base::SetPath(), and SetTestPath().
AvgProb() [1/2]
double PMNS_Base::AvgProb (int flvi, int flvf, double E, double dE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Definition at line 1656 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProb(fNuState, flvf, E, dE);
}
References OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProb() [2/2]
double PMNS_Base::AvgProb (vectorC nu_in, int flvf, double E, double dE = 0) virtual inherited
Compute the average probability of nu_in going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Definition at line 1726 of file PMNS_Base.cxx.
{
  // Do nothing if energy is not positive
  if(E<=0) return 0;
  if(fNuPaths.empty()) return 0;
  // Don't average zero width
  if(dE<=0) return Prob(nu_in, flvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbLoE(nu_in, flvf, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::Prob().
Referenced by OscProb::PMNS_Base::AvgProb(), CheckProb(), and SaveTestFile().
AvgProbLoE() [1/2]
double PMNS_Base::AvgProbLoE (int flvi, int flvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Definition at line 1770 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbLoE(fNuState, flvf, LoE, dLoE);
}
References OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProbLoE() [2/2]
double PMNS_Base::AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of nu_in going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino intial state in flavour basis.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Definition at line 1805 of file PMNS_Base.cxx.
{
  // Do nothing if L/E is not positive
  if(LoE<=0) return 0;
  if(fNuPaths.empty()) return 0;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length/LoE);
  // Don't average zero width
  if(dLoE<=0) return Prob(nu_in, flvf);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw = 0;
  double prob = 0;
  double length = fPath.length;
  // Loop over all sample points
  for(int j=0; j<int(samples.size()); j++){
    // Set (L/E)^-2 weights
    double w = 1./pow(samples[j],2);
    // Add weighted probability
    prob += w * Prob(nu_in, flvf, length / samples[j]);
    // Increment sum of weights
    sumw += w;
  }
  // Return weighted average of probabilities
  return prob / sumw;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProb(), and OscProb::PMNS_Base::AvgProbLoE().
AvgProbMatrix()
matrixD PMNS_Base::AvgProbMatrix (int nflvi, int nflvf, double E, double dE = 0) virtual inherited
Compute the average probability matrix for nflvi and nflvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Definition at line 2035 of file PMNS_Base.cxx.
{
  matrixD probs(nflvi, vectorD(nflvf, 0));
  // Do nothing if energy is not positive
  if(E<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Don't average zero width
  if(dE<=0) return ProbMatrix(nflvi, nflvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbMatrixLoE(nflvi, nflvf, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::ProbMatrix().
AvgProbMatrixLoE()
matrixD PMNS_Base::AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability matrix for nflvi and nflvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Definition at line 2077 of file PMNS_Base.cxx.
{
  matrixD probs(nflvi, vectorD(nflvf, 0));
  // Do nothing if L/E is not positive
  if(LoE<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length/LoE);
  // Don't average zero width
  if(dLoE<=0) return ProbMatrix(nflvi, nflvf);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw = 0;
  double length = fPath.length;
  // Loop over all sample points
  for(int j=0; j<int(samples.size()); j++){
    // Set (L/E)^-2 weights
    double w = 1./pow(samples[j],2);
    matrixD sample_probs = ProbMatrix(nflvi, nflvf, length / samples[j]);
    for(int flvi=0; flvi<nflvi; flvi++){
    for(int flvf=0; flvf<nflvf; flvf++){
      // Add weighted probability
      probs[flvi][flvf] += w * sample_probs[flvi][flvf];
    }}
    // Increment sum of weights
    sumw += w;
  }
  for(int flvi=0; flvi<nflvi; flvi++){
  for(int flvf=0; flvf<nflvf; flvf++){
    // Divide by total sampling weight
    probs[flvi][flvf] /= sumw;
  }}
  // Return weighted average of probabilities
  return probs;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProbMatrix().
AvgProbVector() [1/2]
vectorD PMNS_Base::AvgProbVector (int flvi, double E, double dE = 0) virtual inherited
Compute the average probability of nu_in going to all flavours over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1896 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbVector(fNuState, E, dE);
}
References OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProbVector() [2/2]
vectorD PMNS_Base::AvgProbVector (vectorC nu_in, double E, double dE = 0) virtual inherited
Compute the average probability of nu_in going to all flavours over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
nu_in - The neutrino initial state in flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1920 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if energy is not positive
  if(E<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Don't average zero width
  if(dE<=0) return ProbVector(nu_in, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbVectorLoE(nu_in, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::ProbVector().
Referenced by OscProb::PMNS_Base::AvgProbVector().
AvgProbVectorLoE() [1/2]
vectorD PMNS_Base::AvgProbVectorLoE (int flvi, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of flvi going to all flavours over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
flvi - The neutrino starting flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1871 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbVectorLoE(fNuState, LoE, dLoE);
}
References OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProbVectorLoE() [2/2]
vectorD PMNS_Base::AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of nu_in going to all flavours over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
nu_in - The neutrino intial state in flavour basis.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1960 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if L/E is not positive
  if(LoE<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length/LoE);
  // Don't average zero width
  if(dLoE<=0) return ProbVector(nu_in);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw = 0;
  double length = fPath.length;
  // Loop over all sample points
  for(int j=0; j<int(samples.size()); j++){
    // Set (L/E)^-2 weights
    double w = 1./pow(samples[j],2);
    vectorD sample_probs = ProbVector(nu_in, length / samples[j]);
    for(int i=0; i<fNumNus; i++){
      // Add weighted probability
      probs[i] += w * sample_probs[i];
    }
    // Increment sum of weights
    sumw += w;
  }
  for(int i=0; i<fNumNus; i++){
    // Divide by total sampling weight
    probs[i] /= sumw;
  }
  // Return weighted average of probabilities
  return probs;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProbVector(), and OscProb::PMNS_Base::AvgProbVectorLoE().
BuildHms()
void PMNS_Base::BuildHms () protected virtual inherited
Build Hms = H*2E, where H is the Hamiltonian in vacuum on flavour basis and E is the neutrino energy in eV. Hms is effectively the matrix of masses squared.
This is a hermitian matrix, so only the upper triangular part needs to be filled
The construction of the Hamiltonian avoids computing terms that are simply zero. This has a big impact in the computation time.
Reimplemented in OscProb::PMNS_Decay, and OscProb::PMNS_SNSI.
Definition at line 1063 of file PMNS_Base.cxx.
{
  // Check if anything changed
  if(fBuiltHms) return;
  // Tag to recompute eigensystem
  fGotES = false;
  for(int j=0; j<fNumNus; j++){
    // Set mass splitting
    fHms[j][j] = fDm[j];
    // Reset off-diagonal elements
    for(int i=0; i<j; i++){
      fHms[i][j] = 0;
    }
    // Rotate j neutrinos
    for(int i=0; i<j; i++){
      RotateH(i,j,fHms);
    }
  }
  ClearCache();
  // Tag as built
  fBuiltHms = true;
}
References OscProb::PMNS_Base::ClearCache(), OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::RotateH().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
ClearCache()
void PMNS_Base::ClearCache () virtual inherited
Clear the cache
Definition at line 118 of file PMNS_Base.cxx.
{
  fMixCache.clear();
  // Set some better hash table parameters
  fMixCache.max_load_factor(0.25);
  fMixCache.reserve(512);
}
References OscProb::PMNS_Base::fMixCache.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), and OscProb::PMNS_NSI::SetEps().
ClearPath()
void PMNS_Base::ClearPath () virtual inherited
Clear the path vector.
Definition at line 326 of file PMNS_Base.cxx.
{
  fNuPaths.clear();
}
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
ConvertEtoLoE()
vectorD PMNS_Base::ConvertEtoLoE (double E, double dE) protected virtual inherited
Convert a bin of energy into a bin of L/E
Parameters
E - energy bin center in GeV
dE - energy bin width in GeV
Returns
The L/E bin center and width in km/GeV
Definition at line 1674 of file PMNS_Base.cxx.
{
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Define L/E variables
  vectorD LoEbin(2);
  // Set a minimum energy
  double minE = 0.1 * E;
  // Transform range to L/E
  // Full range if low edge > minE
  if(E-dE/2 > minE){
    LoEbin[0] = 0.5 * (fPath.length/(E-dE/2) + fPath.length/(E+dE/2));
    LoEbin[1] = fPath.length/(E-dE/2) - fPath.length/(E+dE/2);
  }
  // Else start at minE
  else{
    LoEbin[0] = 0.5 * (fPath.length/minE + fPath.length/(E+dE/2));
    LoEbin[1] = fPath.length/minE - fPath.length/(E+dE/2);
  }
  return LoEbin;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::NuPath::length, and OscProb::PMNS_Base::SetCurPath().
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbMatrix(), and OscProb::PMNS_Base::AvgProbVector().
FillCache()
void PMNS_Base::FillCache () protected virtual inherited
If using caching, save the eigensystem in memory
Reimplemented in OscProb::PMNS_LIV, and OscProb::PMNS_SNSI.
Definition at line 173 of file PMNS_Base.cxx.
{
  if(fUseCache){
    if(fMixCache.size()>fMaxCache){
      fMixCache.erase(fMixCache.begin());
    }
    fProbe.SetVars(fEnergy, fPath, fIsNuBar);
    for(int i=0; i<fNumNus; i++){
      fProbe.fEval[i] = fEval[i];
      for(int j=0; j<fNumNus; j++){
        fProbe.fEvec[i][j] = fEvec[i][j];
      }
    }
    fMixCache.insert(fProbe);
  }
}
References OscProb::PMNS_Base::fEnergy, OscProb::EigenPoint::fEval, OscProb::PMNS_Base::fEval, OscProb::EigenPoint::fEvec, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fMaxCache, OscProb::PMNS_Base::fMixCache, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::fProbe, OscProb::PMNS_Base::fUseCache, and OscProb::EigenPoint::SetVars().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
GetAngle()
double PMNS_Base::GetAngle (int i, int j) virtual inherited
Get the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of theta_ij
Definition at line 665 of file PMNS_Base.cxx.
{
  if(i>j){
    cerr << "WARNING: First argument should be smaller than second argument" << endl
         << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cerr << "ERROR: Theta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fTheta[i-1][j-1];
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
GetDelta()
double PMNS_Base::GetDelta (int i, int j) virtual inherited
Get the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of delta_ij
Definition at line 735 of file PMNS_Base.cxx.
{
  if(i>j){
    cerr << "WARNING: First argument should be smaller than second argument" << endl
         << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cerr << "ERROR: Delta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  if(i+1==j){
    cerr << "WARNING: Rotation " << i << j << " is real. Returning zero." << endl;
    return 0;
  }
  return fDelta[i-1][j-1];
}
References OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
GetDm()
double PMNS_Base::GetDm (int j) virtual inherited
Get the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 795 of file PMNS_Base.cxx.
{
  if(j<2 || j>fNumNus){
    cerr << "ERROR: Dm" << j << "1 not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fDm[j-1];
}
References OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
GetDmEff()
double PMNS_Base::GetDmEff (int j) virtual inherited
Get the effective mass-splitting dm_j1 in matter in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 834 of file PMNS_Base.cxx.
{
  if(j<2 || j>fNumNus){
    cerr << "ERROR: Dm_" << j << "1 not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  // Solve the Hamiltonian to update eigenvalues
  SolveHam();
  // Sort eigenvalues in same order as vacuum Dm^2
  vectorI dm_idx = GetSortedIndices(fDm);
  vectorD dm_idx_double(dm_idx.begin(), dm_idx.end());
  dm_idx = GetSortedIndices(dm_idx_double);
  vectorI ev_idx = GetSortedIndices(fEval);
  // Return difference in eigenvalues * 2E
  return (fEval[ev_idx[dm_idx[j-1]]] - fEval[ev_idx[dm_idx[0]]]) * 2*fEnergy * kGeV2eV;
}
References OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::GetSortedIndices(), OscProb::PMNS_Base::kGeV2eV, and OscProb::PMNS_Base::SolveHam().
GetEnergy()
double PMNS_Base::GetEnergy () virtual inherited
Get the neutrino energy in GeV.
Definition at line 284 of file PMNS_Base.cxx.
{
  return fEnergy;
}
References OscProb::PMNS_Base::fEnergy.
GetIsNuBar()
bool PMNS_Base::GetIsNuBar () virtual inherited
Get the anti-neutrino flag.
Definition at line 294 of file PMNS_Base.cxx.
{
  return fIsNuBar;
}
References OscProb::PMNS_Base::fIsNuBar.
GetMassEigenstate()
vectorC PMNS_Base::GetMassEigenstate (int mi) virtual inherited
Get the neutrino mass eigenstate in vacuum
States are:
  0 = m_1, 1 = m_2, 2 = m_3, etc.
Parameters
mi - the mass eigenstate index
Returns
The mass eigenstate
Definition at line 900 of file PMNS_Base.cxx.
{
  vectorC oldState = fNuState;
  ResetToFlavour(mi);
  for(int j=0; j<fNumNus; j++){
  for(int i=0; i<j; i++){
    RotateState(i,j);
  }}
  vectorC newState = fNuState;
  fNuState = oldState;
  return newState;
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_Base::RotateState().
GetPath()
vector< NuPath > PMNS_Base::GetPath () virtual inherited
Get the vector of neutrino paths.
Definition at line 347 of file PMNS_Base.cxx.
{
  return fNuPaths;
}
References OscProb::PMNS_Base::fNuPaths.
GetProbVector()
vectorD PMNS_Base::GetProbVector () protected virtual inherited
Get the vector of probabilities for current state
Returns
Neutrino oscillation probabilities
Definition at line 1366 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus);
  for(int i=0; i<probs.size(); i++){
    probs[i] = P(i);
  }
  return probs;
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::P().
Referenced by OscProb::PMNS_Base::ProbVector().
GetSamplePoints()
vectorD PMNS_Base::GetSamplePoints (double LoE, double dLoE) virtual inherited
Compute the sample points for a bin of L/E with width dLoE
This is used for averaging the probability over a bin of L/E. It should be a private function, but I'm keeping it public for now for debugging purposes. The number of sample points seems too high for most purposes. The number of subdivisions needs to be optimized.
Parameters
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Definition at line 2163 of file PMNS_Base.cxx.
{
  // Solve Hamiltonian to get eigenvalues
  SolveHam();
  // Define conversion factor [km/GeV -> 1/(4 eV^2)]
  const double k1267 = kKm2eV / (4 * kGeV2eV);
  // Get list of all effective Dm^2
  vectorD effDm;
  for(int i=0; i<fNumNus-1; i++){
    for(int j=i+1; j<fNumNus; j++){
      effDm.push_back( 2 * kGeV2eV * fEnergy * fabs(fEval[j] - fEval[i]) );
    }
  }
  int numDm = effDm.size();
  // Sort the effective Dm^2 list
  sort(effDm.begin(), effDm.end());
  // Set a number of sub-divisions to achieve "good" accuracy
  // This needs to be studied better
  int n_div = ceil( 200 * pow(dLoE/LoE,0.8) / sqrt(fAvgProbPrec/1e-4) );
  //int n_div = 1;
  // A vector to store sample points
  vectorD allSamples;
  // Loop over sub-divisions
  for(int k=0; k<n_div; k++){
    // Define sub-division center and width
    double bctr = LoE - dLoE/2 + (k+0.5)*dLoE/n_div;
    double bwdt = dLoE/n_div;
    // Make a vector of L/E sample values
    // Initialized in the sub-division center
    vectorD samples;
    samples.push_back(bctr);
    // Loop over all Dm^2 to average each frequency
    // This will recursively sample points in smaller
    // bins so that all relevant frequencies are used
    for(int i=0; i<numDm; i++){
      // Copy the list of sample L/E values
      vectorD prev = samples;
      // Redefine bin width to lie within full sub-division
      double Width = 2*min(prev[0] - (bctr - bwdt/2), (bctr + bwdt/2) - prev[0]);
      // Compute oscillation argument sorted from lowest  to highest
      const double arg = k1267 * effDm[i] * Width;
      // Skip small oscillation values.
      // If it's the last one, lower the tolerance
      if(i < numDm-1){
        if(arg<0.9) continue;
      }
      else{
        if(arg<0.1) continue;
      }
      // Reset samples to redefine them
      samples.clear();
      // Loop over previous samples
      for(int j=0; j<int(prev.size()); j++){
        // Compute new sample points around old samples
        // This is based on a oscillatory quadrature rule
        double sample = (1/sqrt(3)) * (Width/2);
        if(arg!=0) sample = acos(sin(arg)/arg)/arg * (Width/2);
        // Add samples above and below center
        samples.push_back(prev[j]-sample);
        samples.push_back(prev[j]+sample);
      }
    }// End of loop over Dm^2
    // Add sub-division samples to the end of allSamples vector
    allSamples.insert(allSamples.end(), samples.begin(), samples.end());
  }// End of loop over sub-divisions
  // Return all sample points
  return allSamples;
}
References OscProb::PMNS_Base::fAvgProbPrec, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kKm2eV, and OscProb::PMNS_Base::SolveHam().
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), and OscProb::PMNS_Base::AvgProbVectorLoE().
GetSortedIndices()
vectorI PMNS_Base::GetSortedIndices (const vectorD x) protected virtual inherited
Get the indices of the sorted x vector
Parameters
x - input vector
Returns
The vector of sorted indices
Definition at line 816 of file PMNS_Base.cxx.
{
  vectorI idx(x.size(),0);
  for(int i=0; i<x.size(); i++) idx[i] = i;
  sort(idx.begin(), idx.end(), IdxCompare(x));
  return idx;
}
Referenced by OscProb::PMNS_Base::GetDmEff().
InitializeVectors()
void PMNS_Base::InitializeVectors () protected virtual inherited
Set vector sizes and initialize elements to zero.
Definition at line 81 of file PMNS_Base.cxx.
{
  fDm    = vectorD(fNumNus, 0);
  fTheta = matrixD(fNumNus, vectorD(fNumNus,0));
  fDelta = matrixD(fNumNus, vectorD(fNumNus,0));
  fNuState = vectorC(fNumNus, zero);
  fHms     = matrixC(fNumNus, vectorC(fNumNus,zero));
  fPhases = vectorC(fNumNus, zero);
  fBuffer = vectorC(fNumNus, zero);
  fEval = vectorD(fNumNus, 0);
  fEvec = matrixC(fNumNus, vectorC(fNumNus,zero));
}
References OscProb::PMNS_Base::fBuffer, OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::fPhases, OscProb::PMNS_Base::fTheta, and OscProb::PMNS_Base::zero.
Referenced by OscProb::PMNS_Base::PMNS_Base().
P()
double PMNS_Base::P (int flv) protected virtual inherited
Compute oscillation probability of flavour flv from current state
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino final flavour.
Returns
Neutrino oscillation probability
Reimplemented in OscProb::PMNS_Deco.
Definition at line 1178 of file PMNS_Base.cxx.
{
  assert(flv>=0 && flv<fNumNus);
  return norm(fNuState[flv]);
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fNuState.
Referenced by OscProb::PMNS_Base::GetProbVector(), and OscProb::PMNS_Base::Prob().
Prob() [1/6]
double PMNS_Base::Prob (int flvi, int flvf) virtual inherited
Compute the probability of flvi going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1212 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  Propagate();
  return P(flvf);
}
References OscProb::PMNS_Base::P(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::ResetToFlavour().
Prob() [2/6]
double PMNS_Base::Prob (int flvi, int flvf, double E) virtual inherited
Compute the probability of flvi going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1287 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(flvi, flvf);
}
References OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetEnergy().
Prob() [3/6]
double PMNS_Base::Prob (int flvi, int flvf, double E, double L) virtual inherited
Compute the probability of flvi going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1350 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(flvi, flvf);
}
References OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
Prob() [4/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf) virtual inherited
Compute the probability of nu_in going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1237 of file PMNS_Base.cxx.
{
  SetPureState(nu_in);
  Propagate();
  return P(flvf);
}
References OscProb::PMNS_Base::P(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::SetPureState().
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), and OscProb::PMNS_Base::Prob().
Prob() [5/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E) virtual inherited
Compute the probability of nu_in going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1263 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(nu_in, flvf);
}
References OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetEnergy().
Prob() [6/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E, double L) virtual inherited
Compute the probability of nu_in going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1318 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(nu_in, flvf);
}
References OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbMatrix() [1/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf) virtual inherited
Compute the probability matrix for the first nflvi and nflvf states.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
Returns
Neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Deco, and OscProb::PMNS_Deco.
Definition at line 1536 of file PMNS_Base.cxx.
{
  assert(nflvi<=fNumNus && nflvi>=0);
  assert(nflvf<=fNumNus && nflvf>=0);
  // Output probabilities
  matrixD probs(nflvi, vectorD(nflvf));
  // List of states
  matrixC allstates(nflvi, vectorC(fNumNus));
  // Reset all initial states
  for(int i=0; i<nflvi; i++){
    ResetToFlavour(i);
    allstates[i] = fNuState;
  }
  // Propagate all states in parallel
  for(int i=0; i<int(fNuPaths.size()); i++){
    for(int flvi=0; flvi<nflvi; flvi++){
      fNuState = allstates[flvi];
      PropagatePath(fNuPaths[i]);
      allstates[flvi] = fNuState;
    }
  }
  // Get all probabilities
  for(int flvi=0; flvi<nflvi; flvi++){
  for(int flvj=0; flvj<nflvf; flvj++){
    probs[flvi][flvj] = norm(allstates[flvi][flvj]);
  }}
  return probs;
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::PropagatePath(), and OscProb::PMNS_Base::ResetToFlavour().
Referenced by OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Base::AvgProbMatrixLoE(), and OscProb::PMNS_Base::ProbMatrix().
ProbMatrix() [2/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E) virtual inherited
Compute the probability matrix for the first nflvi and nflvf states for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Deco.
Definition at line 1591 of file PMNS_Base.cxx.
{
 SetEnergy(E);
 return ProbMatrix(nflvi, nflvf);
}
References OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::SetEnergy().
ProbMatrix() [3/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E, double L) virtual inherited
Compute the probability matrix for the first nflvi and nflvf states for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Deco.
Definition at line 1622 of file PMNS_Base.cxx.
{
 SetEnergy(E);
 SetLength(L);
 return ProbMatrix(nflvi, nflvf);
}
References OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbVector() [1/6]
vectorD PMNS_Base::ProbVector (int flvi) virtual inherited
Compute the probability of flvi going to all flavours.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
Returns
Neutrino oscillation probabilities
Definition at line 1410 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  Propagate();
  return GetProbVector();
}
References OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::ResetToFlavour().
ProbVector() [2/6]
vectorD PMNS_Base::ProbVector (int flvi, double E) virtual inherited
Compute the probability of flvi going to all flavours for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1455 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(flvi);
}
References OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_Base::SetEnergy().
ProbVector() [3/6]
vectorD PMNS_Base::ProbVector (int flvi, double E, double L) virtual inherited
Compute the probability of flvi going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1511 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(flvi);
}
References OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbVector() [4/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in) virtual inherited
Compute the probability of nu_in going to all flavours.
Parameters
nu_in - The neutrino initial state in flavour basis.
Returns
Neutrino oscillation probabilities
Definition at line 1386 of file PMNS_Base.cxx.
{
  SetPureState(nu_in);
  Propagate();
  return GetProbVector();
}
References OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::SetPureState().
Referenced by OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), and OscProb::PMNS_Base::ProbVector().
ProbVector() [5/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E) virtual inherited
Compute the probability of nu_in going to all flavours for a given energy in GeV.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probabilities
Definition at line 1431 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(nu_in);
}
References OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_Base::SetEnergy().
ProbVector() [6/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E, double L) virtual inherited
Compute the probability of nu_in going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probabilities
Definition at line 1480 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(nu_in);
}
References OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
Propagate()
void PMNS_Base::Propagate () protected virtual inherited
Propagate neutrino state through full path
Definition at line 1134 of file PMNS_Base.cxx.
{
  for(int i=0; i<int(fNuPaths.size()); i++){
    PropagatePath(fNuPaths[i]);
  }
}
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::PropagatePath().
Referenced by OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::ProbVector().
PropagatePath()
void PMNS_Iter::PropagatePath (NuPath p) protected virtual
Propagate neutrino state through split path
Reimplemented from OscProb::PMNS_Base.
Definition at line 102 of file PMNS_Iter.cxx.
{
  SetExpVL(p);
  double dm = 0;
  for(int i=0; i<fNumNus; i++){
    if(dm<fabs(fDm[i])) dm = fabs(fDm[i]);
  }
  dm *= kKm2eV * p.length / (2 * kGeV2eV * fEnergy);
  int nsplit = sqrt(0.065 * dm * fVL / fPrec);
  if(nsplit>1){
    p.length /= nsplit;
    SetExpVL(p);
  }
  else nsplit = 1;
  for(int i=0; i<nsplit; i++){
    PMNS_Base::PropagatePath(p);
    PropMatter();
  }
}
References OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fNumNus, fPrec, fVL, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kKm2eV, OscProb::NuPath::length, OscProb::PMNS_Base::PropagatePath(), PropMatter(), and SetExpVL().
PropMatter()
void PMNS_Iter::PropMatter () protected virtual
Propagate neutrino through matter component.
Definition at line 49 of file PMNS_Iter.cxx.
{
  fNuState[0] *= fExpVL;
}
References fExpVL, and OscProb::PMNS_Base::fNuState.
Referenced by PropagatePath().
ResetToFlavour()
void PMNS_Base::ResetToFlavour (int flv) protected virtual inherited
Reset the neutrino state back to a pure flavour where it starts
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino starting flavour.
Reimplemented in OscProb::PMNS_Deco.
Definition at line 1156 of file PMNS_Base.cxx.
{
  assert(flv>=0 && flv<fNumNus);
  for (int i=0; i<fNumNus; ++i){
    if (i==flv) fNuState[i] = one;
    else        fNuState[i] = zero;
  }
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::one, and OscProb::PMNS_Base::zero.
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_Deco::ResetToFlavour().
RotateH()
void PMNS_Base::RotateH (int i, int j, matrixC & Ham) protected virtual inherited
Rotate the Hamiltonian by the angle theta_ij and phase delta_ij.
The rotations assume all off-diagonal elements with i > j are zero. This is correct if the order of rotations is chosen appropriately and it speeds up computation by skipping null terms
Parameters
i,j - the indices of the rotation ij
Ham - the Hamiltonian to be rotated
Definition at line 929 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if(fTheta[i][j]==0) return;
  double fSinBuffer = sin(fTheta[i][j]);
  double fCosBuffer = cos(fTheta[i][j]);
  double  fHmsBufferD;
  complexD fHmsBufferC;
  // With Delta
  if(i+1<j){
    complexD fExpBuffer = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    // General case
    if(i>0){
      // Top columns
      for(int k=0; k<i; k++){
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer * conj(fExpBuffer);
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer * fExpBuffer;
      }
      // Middle row and column
      for(int k=i+1; k<j; k++){
        fHmsBufferC = Ham[k][j];
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
        Ham[i][k] += fSinBuffer * fExpBuffer * conj(fHmsBufferC);
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += 2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -= 2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j] * conj(fExpBuffer)) * fSinBuffer * fExpBuffer;
      Ham[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC) * fExpBuffer;
    }
    // First rotation on j (No top columns)
    else{
      // Middle rows and columns
      for(int k=i+1; k<j; k++){
        Ham[k][j] = -conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
      }
      // Nodes ij
      fHmsBufferD = real(Ham[i][i]);
      Ham[i][j] = fSinBuffer * fCosBuffer * (Ham[j][j] - fHmsBufferD) * fExpBuffer;
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferD * fSinBuffer;
    }
  }
  // Without Delta (No middle rows or columns: j = i+1)
  else{
    // General case
    if(i>0){
      // Top columns
      for(int k=0; k<i; k++){
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer;
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer;
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -= 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j]) * fSinBuffer;
      Ham[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC);
    }
    // First rotation (theta12)
    else{
      Ham[i][j] = fSinBuffer * fCosBuffer * Ham[j][j];
      Ham[i][i] = fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
    }
  }
}
References OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), and OscProb::PMNS_SNSI::BuildHms().
RotateState()
void PMNS_Base::RotateState (int i, int j) protected virtual inherited
Rotate the neutrino state by the angle theta_ij and phase delta_ij.
Parameters
i,j - the indices of the rotation ij
Definition at line 864 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if(fTheta[i][j]==0) return;
  double sij = sin(fTheta[i][j]);
  double cij = cos(fTheta[i][j]);
  complexD buffer;
  if(i+1==j || fDelta[i][j]==0){
    buffer      = cij*fNuState[i] + sij*fNuState[j];
    fNuState[j] = cij*fNuState[j] - sij*fNuState[i];
  }
  else {
    complexD eij = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    buffer      = cij*fNuState[i] + sij*eij*fNuState[j];
    fNuState[j] = cij*fNuState[j] - sij*conj(eij)*fNuState[i];
  }
  fNuState[i] = buffer;
}
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Base::GetMassEigenstate().
SetAngle()
void PMNS_Base::SetAngle (int i, int j, double th) virtual inherited
Set the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of theta_ij
th - the value of theta_ij
Definition at line 633 of file PMNS_Base.cxx.
{
  if(i>j){
    cerr << "WARNING: First argument should be smaller than second argument" << endl
         << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cerr << "ERROR: Theta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fTheta[i-1][j-1] == th);
  fTheta[i-1][j-1] = th;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetMix(), OscProb::PMNS_Fast::SetMix(), and OscProb::PMNS_Base::SetStdPars().
SetAtt() [1/2]
void PMNS_Base::SetAtt (double att, int idx) protected virtual inherited
Set some single path attribute.
An auxiliary function to set individual attributes in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
att - The value of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 422 of file PMNS_Base.cxx.
{
  if(fNuPaths.size() != 1){
    cerr << "WARNING: Clearing path vector and starting new single path." << endl
         << "To avoid possible issues, use the SetPath function." << endl;
    SetStdPath();
  }
  switch(idx){
    case 0: fNuPaths[0].length  = att; break;
    case 1: fNuPaths[0].density = att; break;
    case 2: fNuPaths[0].zoa     = att; break;
    case 3: fNuPaths[0].layer   = att; break;
  }
}
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::SetStdPath().
Referenced by OscProb::PMNS_Base::SetDensity(), OscProb::PMNS_Base::SetLayers(), OscProb::PMNS_Base::SetLength(), and OscProb::PMNS_Base::SetZoA().
SetAtt() [2/2]
void PMNS_Base::SetAtt (vectorD att, int idx) protected virtual inherited
Set all values of a path attribute.
An auxiliary function to set individual attributes in a path sequence.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
att - The values of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 499 of file PMNS_Base.cxx.
{
  // Get the sizes of the attribute and
  // path sequence vectors
  int nA = att.size();
  int nP = fNuPaths.size();
  // If the vector sizes are equal, update this attribute
  if(nA == nP){
    for(int i=0; i<nP; i++){
      switch(idx){
        case 0: fNuPaths[i].length  = att[i]; break;
        case 1: fNuPaths[i].density = att[i]; break;
        case 2: fNuPaths[i].zoa     = att[i]; break;
        case 3: fNuPaths[i].layer   = att[i]; break;
      }
    }
  }
  // If the vector sizes differ, create a new path sequence
  // and set value for this attribute. Other attributes will
  // be taken from default single path.
  else{
    cerr << "WARNING: New vector size. Starting new path vector." << endl
         << "To avoid possible issues, use the SetPath function." << endl;
    // Start a new standard path just
    // to set default values
    SetStdPath();
    // Create a path segment with default values
    NuPath p = fNuPaths[0];
    // Clear the path sequence
    ClearPath();
    // Set this particular attribute's value
    // and add the path segment to the sequence
    for(int i=0; i<nA; i++){
      switch(idx){
        case 0: p.length  = att[i]; break;
        case 1: p.density = att[i]; break;
        case 2: p.zoa     = att[i]; break;
        case 3: p.layer   = att[i]; break;
      }
      AddPath(p);
    }
  }
}
References OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::ClearPath(), OscProb::NuPath::density, OscProb::PMNS_Base::fNuPaths, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetStdPath(), and OscProb::NuPath::zoa.
SetAvgProbPrec()
void PMNS_Base::SetAvgProbPrec (double prec) virtual inherited
Set the precision for the AvgProb method
Parameters
prec - AvgProb precision
Definition at line 2141 of file PMNS_Base.cxx.
{
  if(prec<1e-8){
    cerr << "WARNING: Cannot set AvgProb precision lower that 1e-8."
         << "Setting to 1e-8." << endl;
    prec = 1e-8;
  }
  fAvgProbPrec = prec;
}
References OscProb::PMNS_Base::fAvgProbPrec.
SetCurPath()
void PMNS_Base::SetCurPath (NuPath p) protected virtual inherited
Set the path currentlyin use by the class.
This will be used to know what path to propagate through next.
It will also check if values are changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
p - A neutrino path segment
Definition at line 311 of file PMNS_Base.cxx.
{
  // Check if relevant value are actually changing
  fGotES *= (fPath.density == p.density);
  fGotES *= (fPath.zoa == p.zoa);
  fPath = p;
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fPath, and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), and OscProb::PMNS_Deco::PropagatePath().
SetDelta()
void PMNS_Base::SetDelta (int i, int j, double delta) virtual inherited
Set the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of delta_ij
delta - the value of delta_ij
Definition at line 699 of file PMNS_Base.cxx.
{
  if(i>j){
    cerr << "WARNING: First argument should be smaller than second argument" << endl
         << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cerr << "ERROR: Delta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  if(i+1==j){
    cerr << "WARNING: Rotation " << i << j << " is real. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDelta[i-1][j-1] == delta);
  fDelta[i-1][j-1] = delta;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Decay::SetMix(), and OscProb::PMNS_Fast::SetMix().
SetDeltaMsqrs()
void PMNS_Fast::SetDeltaMsqrs (double dm21, double dm32) virtual inherited
Set both mass-splittings at once.
These are Dm_21 and Dm_32 in eV^2.
The corresponding Dm_31 is set in the class attributes.
Parameters
dm21 - The solar mass-splitting Dm_21
dm32 - The atmospheric mass-splitting Dm_32
Definition at line 57 of file PMNS_Fast.cxx.
{
  SetDm(2, dm21);
  SetDm(3, dm32 + dm21);
}
References OscProb::PMNS_Base::SetDm().
SetDensity() [1/2]
void PMNS_Base::SetDensity (double rho) virtual inherited
Set single path density.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The density of the path segment in g/cm^3
Definition at line 466 of file PMNS_Base.cxx.
{
  SetAtt(rho, 1);
}
References OscProb::PMNS_Base::SetAtt().
SetDensity() [2/2]
void PMNS_Base::SetDensity (vectorD rho) virtual inherited
Set multiple path densities.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The densities of the path segments in g/cm^3
Definition at line 582 of file PMNS_Base.cxx.
{
  SetAtt(rho, 1);
}
References OscProb::PMNS_Base::SetAtt().
SetDm()
void PMNS_Base::SetDm (int j, double dm) virtual inherited
Set the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
j - the index of dm_j1
dm - the value of dm_j1
Definition at line 771 of file PMNS_Base.cxx.
{
  if(j<2 || j>fNumNus){
    cerr << "ERROR: Dm" << j << "1 not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDm[j-1] == dm);
  fDm[j-1] = dm;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetDeltaMsqrs(), OscProb::PMNS_Fast::SetDeltaMsqrs(), and OscProb::PMNS_Base::SetStdPars().
SetEnergy()
void PMNS_Base::SetEnergy (double E) virtual inherited
Set neutrino energy in GeV.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
E - The neutrino energy in GeV
Definition at line 251 of file PMNS_Base.cxx.
{
  // Check if value is actually changing
  fGotES *= (fEnergy == E);
  fEnergy = E;
}
References OscProb::PMNS_Base::fEnergy, and OscProb::PMNS_Base::fGotES.
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::ProbVector().
SetExpVL()
void PMNS_Iter::SetExpVL (NuPath p) protected virtual
Propagate neutrino through matter component.
Definition at line 32 of file PMNS_Iter.cxx.
{
  double kr2GNe = kK2*M_SQRT2*kGf;
  kr2GNe *= p.density * p.zoa; // Matter potential in eV
  fVL = kr2GNe * kKm2eV * p.length;
  fExpVL = complexD(cos(fVL), -sin(fVL));
  if(fIsNuBar) fExpVL = conj(fExpVL);
}
References OscProb::NuPath::density, fExpVL, OscProb::PMNS_Base::fIsNuBar, fVL, OscProb::PMNS_Base::kGf, OscProb::PMNS_Base::kK2, OscProb::PMNS_Base::kKm2eV, OscProb::NuPath::length, and OscProb::NuPath::zoa.
Referenced by PropagatePath().
SetIsNuBar()
void PMNS_Base::SetIsNuBar (bool isNuBar) virtual inherited
Set anti-neutrino flag.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
isNuBar - Set to true for anti-neutrino and false for neutrino.
Reimplemented in OscProb::PMNS_Decay.
Definition at line 270 of file PMNS_Base.cxx.
{
  // Check if value is actually changing
  fGotES *= (fIsNuBar == isNuBar);
  fIsNuBar = isNuBar;
}
References OscProb::PMNS_Base::fGotES, and OscProb::PMNS_Base::fIsNuBar.
Referenced by CheckProb(), OscProb::PMNS_Base::PMNS_Base(), and SaveTestFile().
SetLayers()
void PMNS_Base::SetLayers (std::vector< int > lay) virtual inherited
Set multiple path layer indices.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
lay - Indices to identify the layer types (e.g. earth inner core)
Definition at line 612 of file PMNS_Base.cxx.
{
  vectorD lay_double(lay.begin(), lay.end());
  SetAtt(lay_double, 3);
}
References OscProb::PMNS_Base::SetAtt().
SetLength() [1/2]
void PMNS_Base::SetLength (double L) virtual inherited
Set the length for a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
L - The length of the path segment in km
Definition at line 451 of file PMNS_Base.cxx.
{
  SetAtt(L, 0);
}
References OscProb::PMNS_Base::SetAtt().
Referenced by OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::ProbVector().
SetLength() [2/2]
void PMNS_Base::SetLength (vectorD L) virtual inherited
Set multiple path lengths.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
L - The lengths of the path segments in km
Definition at line 567 of file PMNS_Base.cxx.
{
  SetAtt(L, 0);
}
References OscProb::PMNS_Base::SetAtt().
SetMaxCache()
void PMNS_Base::SetMaxCache (int mc = 1e6) virtual inherited
Set maximum number of cached eigensystems. Finding eigensystems can become slow and take up memory. This protects the cache from becoming too large.
Parameters
mc - Max cache size (default: 1e6)
Definition at line 135 of file PMNS_Base.cxx.
{
  fMaxCache = mc;
}
References OscProb::PMNS_Base::fMaxCache.
SetMix()
void PMNS_Fast::SetMix (double th12, double th23, double th13, double deltacp) virtual inherited
Set all mixing parameters at once.
Parameters
th12 - The value of the mixing angle theta_12
th23 - The value of the mixing angle theta_23
th13 - The value of the mixing angle theta_13
deltacp - The value of the CP phase delta_13
Definition at line 37 of file PMNS_Fast.cxx.
{
  SetAngle(1,2, th12);
  SetAngle(1,3, th13);
  SetAngle(2,3, th23);
  SetDelta(1,3, deltacp);
}
References OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDelta().
SetPath() [1/3]
void PMNS_Base::SetPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Set a single path defining attributes directly.
This destroys the current path sequence and creates a new first path.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 404 of file PMNS_Base.cxx.
{
  SetPath(NuPath(length, density, zoa, layer));
}
References OscProb::PMNS_Base::SetPath().
SetPath() [2/3]
void PMNS_Base::SetPath (NuPath p) virtual inherited
Set a single path.
This destroys the current path sequence and creates a new first path.
Parameters
p - A neutrino path segment
Definition at line 386 of file PMNS_Base.cxx.
{
  ClearPath();
  AddPath(p);
}
References OscProb::PMNS_Base::AddPath(), and OscProb::PMNS_Base::ClearPath().
Referenced by OscProb::PMNS_Base::SetPath(), OscProb::PMNS_Base::SetStdPath(), and SetTestPath().
SetPath() [3/3]
void PMNS_Base::SetPath (std::vector< NuPath > paths) virtual inherited
Set vector of neutrino paths.
Parameters
paths - A sequence of neutrino paths
Definition at line 337 of file PMNS_Base.cxx.
{
  fNuPaths=paths;
}
References OscProb::PMNS_Base::fNuPaths.
SetPrec()
void PMNS_Iter::SetPrec (double prec) virtual
Set iterator precision
Definition at line 92 of file PMNS_Iter.cxx.
{
  fPrec = prec;
  if(fPrec<=0) fPrec = 1e-3;
}
References fPrec.
SetPureState()
void PMNS_Base::SetPureState (vectorC nu_in) protected virtual inherited
Set the initial state from a pure state
Parameters
nu_in - The neutrino initial state in flavour basis.
Reimplemented in OscProb::PMNS_Deco.
Definition at line 1190 of file PMNS_Base.cxx.
{
  assert(nu_in.size() == fNumNus);
  fNuState = nu_in;
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fNuState.
Referenced by OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::ProbVector().
SetStdPars()
void PMNS_Base::SetStdPars () virtual inherited
Set standard oscillation parameters from PDG 2015.
For two neutrinos, Dm is set to the muon disappearance effective mass-splitting and mixing angle.
Definition at line 199 of file PMNS_Base.cxx.
{
  if(fNumNus>2){
    // PDG values for 3 neutrinos
    // Also applicable for 3+N neutrinos
    SetAngle(1,2, asin(sqrt(0.304)));
    SetAngle(1,3, asin(sqrt(0.0219)));
    SetAngle(2,3, asin(sqrt(0.514)));
    SetDm(2, 7.53e-5);
    SetDm(3, 2.52e-3);
  }
  else if(fNumNus==2){
    // Effective muon disappearance values
    // for two-flavour approximation
    SetAngle(1,2, 0.788);
    SetDm(2, 2.47e-3);
  }
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDm().
Referenced by OscProb::PMNS_Base::PMNS_Base().
SetStdPath()
void PMNS_Base::SetStdPath () virtual inherited
Set standard single path.
Length is 1000 km, so ~2 GeV peak energy.
Density is approximate from CRUST2.0 (~2.8 g/cm^3). Z/A is set to a round 0.5.
Definition at line 229 of file PMNS_Base.cxx.
{
  NuPath p;
  p.length  = 1000; // 1000 km default
  p.density = 2.8;  // Crust density
  p.zoa     = 0.5;  // Crust Z/A
  p.layer   = 0;    // Single layer
  SetPath(p);
}
References OscProb::NuPath::density, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetPath(), and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Deco::PMNS_Deco(), OscProb::PMNS_LIV::PMNS_LIV(), OscProb::PMNS_NSI::PMNS_NSI(), and OscProb::PMNS_Base::SetAtt().
SetUseCache()
void PMNS_Base::SetUseCache (bool u = true) virtual inherited
Turn on/off caching of eigensystems. This can save a lot of CPU time by avoiding recomputing eigensystems if we've already seen them recently. Especially useful when running over multiple earth layers and even more if multiple baselines will be computed, e.g. for atmospheric neutrinos.
Parameters
u - flag to set caching on (default: true)
Definition at line 109 of file PMNS_Base.cxx.
{
  fUseCache = u;
}
References OscProb::PMNS_Base::fUseCache.
Referenced by OscProb::PMNS_Base::PMNS_Base().
SetVacuumEigensystem()
void PMNS_Fast::SetVacuumEigensystem () protected virtual inherited
Set the eigensystem to the analytic solution in vacuum.
We know the vacuum eigensystem, so just write it explicitly
Definition at line 149 of file PMNS_Fast.cxx.
{
  double  s12, s23, s13, c12, c23, c13;
  complexD idelta(0.0, fDelta[0][2]);
  if(fIsNuBar) idelta = conj(idelta);
  s12 = sin(fTheta[0][1]);  s23 = sin(fTheta[1][2]);  s13 = sin(fTheta[0][2]);
  c12 = cos(fTheta[0][1]);  c23 = cos(fTheta[1][2]);  c13 = cos(fTheta[0][2]);
  fEvec[0][0] =  c12*c13;
  fEvec[0][1] =  s12*c13;
  fEvec[0][2] =  s13*exp(-idelta);
  fEvec[1][0] = -s12*c23-c12*s23*s13*exp(idelta);
  fEvec[1][1] =  c12*c23-s12*s23*s13*exp(idelta);
  fEvec[1][2] =  s23*c13;
  fEvec[2][0] =  s12*s23-c12*c23*s13*exp(idelta);
  fEvec[2][1] = -c12*s23-s12*c23*s13*exp(idelta);
  fEvec[2][2] =  c23*c13;
  fEval[0] = 0;
  fEval[1] = fDm[1] / (2 * kGeV2eV*fEnergy);
  fEval[2] = fDm[2] / (2 * kGeV2eV*fEnergy);
}
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fTheta, and OscProb::PMNS_Base::kGeV2eV.
Referenced by OscProb::PMNS_Fast::SolveHam().
SetZoA() [1/2]
void PMNS_Base::SetZoA (double zoa) virtual inherited
Set single path Z/A.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segment
Definition at line 481 of file PMNS_Base.cxx.
{
  SetAtt(zoa, 2);
}
References OscProb::PMNS_Base::SetAtt().
SetZoA() [2/2]
void PMNS_Base::SetZoA (vectorD zoa) virtual inherited
Set multiple path Z/A values.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segments
Definition at line 597 of file PMNS_Base.cxx.
{
  SetAtt(zoa, 2);
}
References OscProb::PMNS_Base::SetAtt().
SolveHam()
void PMNS_Iter::SolveHam () protected virtual
Just use the vacuum Hamiltonian to start.
Reimplemented from OscProb::PMNS_Fast.
Definition at line 60 of file PMNS_Iter.cxx.
{
  if(fGotES) return;
  // Do vacuum oscillation
  if(!fBuiltHms){
    fPath.density = 0;
    PMNS_Fast::SolveHam();
    fBuiltHms = true;
  }
  else {
    for(int i=1; i<fNumNus; i++){
      fEval[i] *= fPrevEnergy / fEnergy;
    }
  }
  fPrevEnergy = fEnergy;
  fGotES = true;
  return;
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, fPrevEnergy, and OscProb::PMNS_Fast::SolveHam().
TryCache()
bool PMNS_Base::TryCache () protected virtual inherited
Try to find a cached version of this eigensystem.
Definition at line 144 of file PMNS_Base.cxx.
{
  if(fUseCache && !fMixCache.empty()){
    fProbe.SetVars(fEnergy, fPath, fIsNuBar);
    unordered_set<EigenPoint>::iterator it = fMixCache.find(fProbe);
    if(it != fMixCache.end()){
      for(int i=0; i<fNumNus; i++){
        fEval[i] = (*it).fEval[i] * (*it).fEnergy / fEnergy;
        for(int j=0; j<fNumNus; j++){
          fEvec[i][j] = (*it).fEvec[i][j];
        }
      }
      return true;
    }
  }
  return false;
}
References OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fMixCache, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::fProbe, OscProb::PMNS_Base::fUseCache, and OscProb::EigenPoint::SetVars().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
UpdateHam()
void PMNS_Fast::UpdateHam () protected virtual inherited
Build the full Hamiltonian in matter.
Here we divide the mass squared matrix Hms by the 2E to obtain the vacuum Hamiltonian in eV. Then, the matter potential is added to the electron component.
Reimplemented in OscProb::PMNS_LIV, OscProb::PMNS_NSI, and OscProb::PMNS_SNSI.
Definition at line 73 of file PMNS_Fast.cxx.
{
  double lv = 2 * kGeV2eV*fEnergy;     // 2E in eV
  double kr2GNe = kK2*M_SQRT2*kGf;
  kr2GNe *= fPath.density * fPath.zoa; // Matter potential in eV
  // Finish building Hamiltonian in matter with dimension of eV
  for(int i=0;i<fNumNus;i++){
    fHam[i][i] = fHms[i][i]/lv;
    for(int j=i+1;j<fNumNus;j++){
      if(!fIsNuBar) fHam[i][j] = fHms[i][j]/lv;
      else          fHam[i][j] = conj(fHms[i][j])/lv;
    }
  }
  if(!fIsNuBar) fHam[0][0] += kr2GNe;
  else          fHam[0][0] -= kr2GNe;
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Fast::fHam, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kGf, OscProb::PMNS_Base::kK2, and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Fast::SolveHam().
Member Data Documentation
fAvgProbPrec
double OscProb::PMNS_Base::fAvgProbPrec protected inherited
Definition at line 256 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetSamplePoints(), and OscProb::PMNS_Base::SetAvgProbPrec().
fBuffer
vectorC OscProb::PMNS_Base::fBuffer protected inherited
Definition at line 238 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::PropagatePath(), and OscProb::PMNS_Decay::PropagatePath().
fBuiltHms
bool OscProb::PMNS_Base::fBuiltHms protected inherited
Definition at line 249 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_Decay::SetAlpha2(), OscProb::PMNS_Decay::SetAlpha3(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_Base::SetDelta(), OscProb::PMNS_Base::SetDm(), OscProb::PMNS_Decay::SetIsNuBar(), and SolveHam().
fCachePrec
double OscProb::PMNS_Base::fCachePrec protected inherited
Definition at line 253 of file PMNS_Base.h.
fDelta
matrixD OscProb::PMNS_Base::fDelta protected inherited
Definition at line 232 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::RotateState(), OscProb::PMNS_Base::SetDelta(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fDm
vectorD OscProb::PMNS_Base::fDm protected inherited
Definition at line 230 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_Base::GetDm(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Deco::PropagatePath(), PropagatePath(), OscProb::PMNS_Base::SetDm(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fEnergy
double OscProb::PMNS_Base::fEnergy protected inherited
Definition at line 243 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetEnergy(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), PropagatePath(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Fast::SetVacuumEigensystem(), SolveHam(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fEval
vectorD OscProb::PMNS_Base::fEval protected inherited
Definition at line 240 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Fast::SolveHam(), SolveHam(), and OscProb::PMNS_Base::TryCache().
fEvec
matrixC OscProb::PMNS_Base::fEvec protected inherited
Definition at line 241 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Deco::RotateState(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Base::TryCache().
fExpVL
complexD OscProb::PMNS_Iter::fExpVL protected
Definition at line 63 of file PMNS_Iter.h.
Referenced by PropMatter(), and SetExpVL().
fGotES
bool OscProb::PMNS_Base::fGotES protected inherited
Definition at line 250 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Fast::SolveHam(), SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
fHam
complexD OscProb::PMNS_Fast::fHam[3][3] protected inherited
Definition at line 64 of file PMNS_Fast.h.
Referenced by OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), and OscProb::PMNS_SNSI::UpdateHam().
fHms
matrixC OscProb::PMNS_Base::fHms protected inherited
Definition at line 235 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fIsNuBar
bool OscProb::PMNS_Base::fIsNuBar protected inherited
Definition at line 244 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetIsNuBar(), SetExpVL(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fMaxCache
int OscProb::PMNS_Base::fMaxCache protected inherited
Definition at line 254 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::SetMaxCache().
fMixCache
std::unordered_set<EigenPoint> OscProb::PMNS_Base::fMixCache protected inherited
Definition at line 258 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::ClearCache(), OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::TryCache().
fNumNus
int OscProb::PMNS_Base::fNumNus protected inherited
Definition at line 228 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::GetDm(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_Deco::GetGamma(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::P(), OscProb::PMNS_Deco::P(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Decay::PMNS_Decay(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Deco::ProbMatrix(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), PropagatePath(), OscProb::PMNS_Base::ResetToFlavour(), OscProb::PMNS_Deco::ResetToFlavour(), OscProb::PMNS_Deco::RotateState(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_Base::SetDelta(), OscProb::PMNS_Base::SetDm(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_Deco::SetGamma(), OscProb::PMNS_Base::SetPureState(), OscProb::PMNS_Deco::SetPureState(), OscProb::PMNS_Base::SetStdPars(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Fast::SolveHam(), SolveHam(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fNuPaths
std::vector<NuPath> OscProb::PMNS_Base::fNuPaths protected inherited
Definition at line 246 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ClearPath(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::GetPath(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Deco::ProbMatrix(), OscProb::PMNS_Base::Propagate(), OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
fNuState
vectorC OscProb::PMNS_Base::fNuState protected inherited
Definition at line 234 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::P(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), PropMatter(), OscProb::PMNS_Base::ResetToFlavour(), OscProb::PMNS_Base::RotateState(), and OscProb::PMNS_Base::SetPureState().
fPath
NuPath OscProb::PMNS_Base::fPath protected inherited
Definition at line 247 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_NSI::GetZoACoup(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Fast::SolveHam(), SolveHam(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fPhases
vectorC OscProb::PMNS_Base::fPhases protected inherited
Definition at line 237 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::InitializeVectors(), and OscProb::PMNS_Base::PropagatePath().
fPrec
double OscProb::PMNS_Iter::fPrec protected
Definition at line 60 of file PMNS_Iter.h.
Referenced by PropagatePath(), and SetPrec().
fPrevEnergy
double OscProb::PMNS_Iter::fPrevEnergy protected
Definition at line 65 of file PMNS_Iter.h.
Referenced by SolveHam().
fProbe
EigenPoint OscProb::PMNS_Base::fProbe protected inherited
Definition at line 259 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::TryCache().
fTheta
matrixD OscProb::PMNS_Base::fTheta protected inherited
Definition at line 231 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::RotateState(), OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fUseCache
bool OscProb::PMNS_Base::fUseCache protected inherited
Definition at line 252 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::SetUseCache(), and OscProb::PMNS_Base::TryCache().
fVL
double OscProb::PMNS_Iter::fVL protected
Definition at line 62 of file PMNS_Iter.h.
Referenced by PropagatePath(), and SetExpVL().
kGeV2eV
const double PMNS_Base::kGeV2eV = 1.0e+09 static protected inherited
Definition at line 178 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kGf
const double PMNS_Base::kGf = 1.1663787e-05 static protected inherited
Definition at line 181 of file PMNS_Base.h.
Referenced by SetExpVL(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kK2
const double PMNS_Base::kK2 = 1e-3 * kNA / pow(kKm2eV,3) static protected inherited
Definition at line 177 of file PMNS_Base.h.
Referenced by SetExpVL(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kKm2eV
const double PMNS_Base::kKm2eV = 1.0 / 1.973269788e-10 static protected inherited
Definition at line 176 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), PropagatePath(), and SetExpVL().
kNA
const double PMNS_Base::kNA = 6.022140857e23 static protected inherited
Definition at line 179 of file PMNS_Base.h.
one
const complexD PMNS_Base::one static protected inherited
Definition at line 173 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_Deco::ResetToFlavour().
zero
const complexD PMNS_Base::zero static protected inherited
Definition at line 172 of file PMNS_Base.h.
Referenced by OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Decay::PMNS_Decay(), OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_Deco::ResetToFlavour().
The documentation for this class was generated from the following files:
inc/PMNS_Iter.h
src/PMNS_Iter.cxx