OscProb: OscProb::PMNS_Base Class Reference
OscProb::PMNS_Base Class Reference abstract
Base class implementing general functions for computing neutrino oscillations.
#include <PMNS_Base.h>
Public Member Functions
PMNS_Base (int numNus=3)
Constructor.
virtual ~PMNS_Base ()
Destructor.
virtual double Prob (vectorC nu_in, int flvf)
Compute the probability of nu_in going to flvf.
virtual double Prob (vectorC nu_in, int flvf, double E)
Compute the probability of nu_in going to flvf for energy E.
virtual double Prob (vectorC nu_in, int flvf, double E, double L)
Compute the probability of nu_in going to flvf for energy E and distance L.
virtual double Prob (int flvi, int flvf)
Compute the probability of flvi going to flvf.
virtual double Prob (int flvi, int flvf, double E)
Compute the probability of flvi going to flvf for energy E.
virtual double Prob (int flvi, int flvf, double E, double L)
Compute the probability of flvi going to flvf for energy E and distance L.
virtual vectorD ProbVector (vectorC nu_in)
Compute the probabilities of nu_in going to all flavours.
virtual vectorD ProbVector (vectorC nu_in, double E)
Compute the probabilities of nu_in going to all flavours for energy E.
virtual vectorD ProbVector (vectorC nu_in, double E, double L)
Compute the probabilities of nu_in going to all flavours for energy E and distance L.
virtual vectorD ProbVector (int flvi)
Compute the probabilities of flvi going to all flavours.
virtual vectorD ProbVector (int flvi, double E)
Compute the probabilities of flvi going to all flavours for energy E.
virtual vectorD ProbVector (int flvi, double E, double L)
Compute the probabilities of flvi going to all flavours for energy E and distance L.
virtual matrixD ProbMatrix (int nflvi, int nflvf)
Compute the probability matrix.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E)
Compute the probability matrix for energy E.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E, double L)
Compute the probability matrix for energy E and distance L.
virtual double AvgProb (vectorC nu_in, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual double AvgProb (int flvi, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProbLoE (int flvi, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual vectorD AvgProbVector (vectorC nu_in, double E, double dE=0)
Compute the average probability vector over a bin of energy.
virtual vectorD AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE=0)
Compute the average probability vector over a bin of L/E.
virtual vectorD AvgProbVector (int flvi, double E, double dE=0)
Compute the average probability vector over a bin of energy.
virtual vectorD AvgProbVectorLoE (int flvi, double LoE, double dLoE=0)
Compute the average probability vector over a bin of L/E.
virtual matrixD AvgProbMatrix (int nflvi, int nflvf, double E, double dE=0)
Compute the average probability matrix over a bin of energy.
virtual matrixD AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE=0)
Compute the average probability matrix over a bin of L/E.
virtual vectorC GetMassEigenstate (int mi)
Get a neutrino mass eigenstate.
virtual void SetAngle (int i, int j, double th)
Set the mixing angle theta_ij.
virtual void SetDelta (int i, int j, double delta)
Set the CP phase delta_ij.
virtual void SetDm (int j, double dm)
Set the mass-splitting dm_j1 in eV^2.
virtual double GetAngle (int i, int j)
Get the mixing angle theta_ij.
virtual double GetDelta (int i, int j)
Get the CP phase delta_ij.
virtual double GetDm (int j)
Get the mass-splitting dm_j1 in eV^2.
virtual double GetDmEff (int j)
Get the effective mass-splitting dm_j1 in eV^2.
virtual void SetStdPars ()
Set PDG 3-flavor parameters.
virtual void SetEnergy (double E)
Set the neutrino energy in GeV.
virtual void SetIsNuBar (bool isNuBar)
Set the anti-neutrino flag.
virtual double GetEnergy ()
Get the neutrino energy in GeV.
virtual bool GetIsNuBar ()
Get the anti-neutrino flag.
virtual void SetPath (OscProb::NuPath p)
Set a single path.
virtual void SetPath (double length, double density, double zoa=0.5, int layer=0)
Set a single path.
virtual void SetPath (std::vector< OscProb::NuPath > paths)
Set a path sequence.
virtual void AddPath (OscProb::NuPath p)
Add a path to the sequence.
virtual void AddPath (double length, double density, double zoa=0.5, int layer=0)
Add a path to the sequence.
virtual void ClearPath ()
Clear the path vector.
virtual void SetLength (double L)
Set a single path lentgh in km.
virtual void SetDensity (double rho)
Set single path density in g/cm^3.
virtual void SetZoA (double zoa)
Set Z/A value for single path.
virtual void SetLength (vectorD L)
Set multiple path lengths.
virtual void SetDensity (vectorD rho)
Set multiple path densities.
virtual void SetZoA (vectorD zoa)
Set multiple path Z/A values.
virtual void SetLayers (std::vector< int > lay)
Set multiple path layer indices.
virtual void SetStdPath ()
Set standard neutrino path.
virtual std::vector< OscProb::NuPath > GetPath ()
Get the neutrino path sequence.
virtual vectorD GetSamplePoints (double LoE, double dLoE)
Compute the sample points for a bin of L/E with width dLoE.
virtual void SetUseCache (bool u=true)
Set caching on/off.
virtual void ClearCache ()
Clear the cache.
virtual void SetMaxCache (int mc=1e6)
Set max cache size.
Protected Member Functions
virtual void InitializeVectors ()
Initialize all member vectors with zeros.
virtual bool TryCache ()
Try to find a cached eigensystem.
virtual void FillCache ()
Cache the current eigensystem.
virtual void SetCurPath (OscProb::NuPath p)
Set the path currently in use by the class.
virtual void SetAtt (double att, int idx)
Set one of the path attributes.
virtual void SetAtt (vectorD att, int idx)
Set all values of a path attribute.
virtual void RotateH (int i, int j, matrixC &Ham)
Rotate the Hamiltonian by theta_ij and delta_ij.
virtual void RotateState (int i, int j)
Rotate the neutrino state by theta_ij and delta_ij.
virtual void BuildHms ()
Build the matrix of masses squared.
virtual void SolveHam ()=0
Solve the full Hamiltonian for eigenvectors and eigenvalues.
virtual void ResetToFlavour (int flv)
Reset neutrino state to pure flavour flv.
virtual void PropagatePath (OscProb::NuPath p)
Propagate neutrino through a single path.
virtual void Propagate ()
Propagate neutrino through full path.
virtual double P (int flv)
Return the probability of final state in flavour flv.
virtual std::vector< int > GetSortedIndices (const vectorD x)
Get indices that sort a vector.
virtual vectorD ConvertEtoLoE (double E, double dE)
Protected Attributes
int fNumNus
Number of neutrino flavours.
vectorD fDm
m^2_i - m^2_1 in vacuum
matrixD fTheta
theta[i][j] mixing angle
matrixD fDelta
delta[i][j] CP violating phase
vectorC fNuState
The neutrino current state.
matrixC fHms
matrix H*2E in eV^2
vectorC fPhases
Buffer for oscillation phases.
vectorC fBuffer
Buffer for neutrino state tranformations.
vectorD fEval
Eigenvalues of the Hamiltonian.
matrixC fEvec
Eigenvectors of the Hamiltonian.
double fEnergy
Neutrino energy.
bool fIsNuBar
Anti-neutrino flag.
std::vector< OscProb::NuPath > fNuPaths
Vector of neutrino paths.
OscProb::NuPath fPath
Current neutrino path.
bool fBuiltHms
Tag to avoid rebuilding Hms.
bool fGotES
Tag to avoid recalculating eigensystem.
bool fUseCache
Flag for whether to use caching.
double fCachePrec
Precision of cache matching.
int fMaxCache
Maximum cache size.
std::unordered_set< OscProb::EigenPoint > fMixCache
Caching set of eigensystems.
EigenPoint fProbe
EigenpPoint to try.
Static Protected Attributes
static const complexD zero
zero in complex
static const complexD one
one in complex
static const double kKm2eV = 1.0 / 1.973269788e-10
km to eV^-1
static const double kK2 = 1e-3 * kNA / pow(kKm2eV,3)
mol/GeV^2/cm^3 to eV
static const double kGeV2eV = 1.0e+09
GeV to eV.
static const double kNA = 6.022140857e23
Avogadro constant.
static const double kGf = 1.1663787e-05
G_F in units of GeV^-2.
Detailed Description
This is an abstract class implementing the general functions needed for setting up an oscillation calculator. The method for solving the eigensystem for the Hamiltonian must be defined in the derived classes.
See also
PMNS_Fast PMNS_NSI PMNS_Sterile
Author
Joao Coelho - jcoelho@apc.in2p3.fr
Definition at line 26 of file PMNS_Base.h.
Constructor & Destructor Documentation
PMNS_Base()
PMNS_Base::PMNS_Base (int numNus = 3)
Constructor.
Sets the number of neutrinos and initializes attributes
Default starts with a 2 GeV muon neutrino.
Path is set to the default 1000 km in crust density.
Oscillation parameters are from PDG for NH by default.
Parameters
numNus - the number of neutrino flavours
Definition at line 48 of file PMNS_Base.cxx.
                               :
fGotES(false), fBuiltHms(false), fMaxCache(1e6), fProbe(numNus)
{
  SetUseCache(true);   // Cache eigensystems
  fNumNus = numNus;    // Set the number of neutrinos
  SetStdPath();        // Set some default path
  SetEnergy(2);        // Set default energy to 2 GeV
  SetIsNuBar(false);   // Neutrino by default
  InitializeVectors(); // Initialize all vectors
  SetStdPars();        // Set PDG parameters
  ResetToFlavour(1);   // Numu by default
  ClearCache(); // Clear cache to initialize it
}
References ClearCache(), fNumNus, InitializeVectors(), ResetToFlavour(), SetEnergy(), SetIsNuBar(), SetStdPars(), SetStdPath(), and SetUseCache().
~PMNS_Base()
PMNS_Base::~PMNS_Base () virtual
Nothing to clean.
Definition at line 74 of file PMNS_Base.cxx.
{}
Member Function Documentation
AddPath() [1/2]
void PMNS_Base::AddPath (double length, double density, double zoa = 0.5, int layer = 0) virtual
Add a path to the sequence defining attributes directly.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 371 of file PMNS_Base.cxx.
{
  AddPath(NuPath(length, density, zoa, layer));
}
References AddPath().
AddPath() [2/2]
void PMNS_Base::AddPath (OscProb::NuPath p) virtual
Add a path to the sequence.
Parameters
p - A neutrino path segment
Definition at line 357 of file PMNS_Base.cxx.
{
  fNuPaths.push_back(p);
}
References fNuPaths.
Referenced by AddPath(), SetAtt(), SetPath(), and SetTestPath().
AvgProb() [1/2]
double PMNS_Base::AvgProb (int flvi, int flvf, double E, double dE = 0) virtual
Compute the average probability of flvi going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Definition at line 1630 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProb(fNuState, flvf, E, dE);
}
References AvgProb(), fNuState, and ResetToFlavour().
AvgProb() [2/2]
double PMNS_Base::AvgProb (vectorC nu_in, int flvf, double E, double dE = 0) virtual
Compute the average probability of nu_in going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Definition at line 1700 of file PMNS_Base.cxx.
{
  // Do nothing if energy is not positive
  if(E<=0) return 0;
  if(fNuPaths.empty()) return 0;
  // Don't average zero width
  if(dE<=0) return Prob(nu_in, flvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbLoE(nu_in, flvf, LoEbin[0], LoEbin[1]);
}
References AvgProbLoE(), ConvertEtoLoE(), fNuPaths, and Prob().
Referenced by AvgProb(), CheckProb(), and SaveTestFile().
AvgProbLoE() [1/2]
double PMNS_Base::AvgProbLoE (int flvi, int flvf, double LoE, double dLoE = 0) virtual
Compute the average probability of flvi going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Definition at line 1744 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbLoE(fNuState, flvf, LoE, dLoE);
}
References AvgProbLoE(), fNuState, and ResetToFlavour().
AvgProbLoE() [2/2]
double PMNS_Base::AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE = 0) virtual
Compute the average probability of nu_in going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino intial state in flavour basis.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Definition at line 1779 of file PMNS_Base.cxx.
{
  // Do nothing if L/E is not positive
  if(LoE<=0) return 0;
  if(fNuPaths.empty()) return 0;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length/LoE);
  // Don't average zero width
  if(dLoE<=0) return Prob(nu_in, flvf);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw = 0;
  double prob = 0;
  double length = fPath.length;
  // Loop over all sample points
  for(int j=0; j<int(samples.size()); j++){
    // Set (L/E)^-2 weights
    double w = 1./pow(samples[j],2);
    // Add weighted probability
    prob += w * Prob(nu_in, flvf, length / samples[j]);
    // Increment sum of weights
    sumw += w;
  }
  // Return weighted average of probabilities
  return prob / sumw;
}
References OscProb::AvgPath(), fNuPaths, fPath, GetSamplePoints(), OscProb::NuPath::length, Prob(), SetCurPath(), and SetEnergy().
Referenced by AvgProb(), and AvgProbLoE().
AvgProbMatrix()
matrixD PMNS_Base::AvgProbMatrix (int nflvi, int nflvf, double E, double dE = 0) virtual
Compute the average probability matrix for nflvi and nflvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Definition at line 2009 of file PMNS_Base.cxx.
{
  matrixD probs(nflvi, vectorD(nflvf, 0));
  // Do nothing if energy is not positive
  if(E<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Don't average zero width
  if(dE<=0) return ProbMatrix(nflvi, nflvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbMatrixLoE(nflvi, nflvf, LoEbin[0], LoEbin[1]);
}
References AvgProbMatrixLoE(), ConvertEtoLoE(), fNuPaths, and ProbMatrix().
AvgProbMatrixLoE()
matrixD PMNS_Base::AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE = 0) virtual
Compute the average probability matrix for nflvi and nflvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Definition at line 2051 of file PMNS_Base.cxx.
{
  matrixD probs(nflvi, vectorD(nflvf, 0));
  // Do nothing if L/E is not positive
  if(LoE<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length/LoE);
  // Don't average zero width
  if(dLoE<=0) return ProbMatrix(nflvi, nflvf);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw = 0;
  double length = fPath.length;
  // Loop over all sample points
  for(int j=0; j<int(samples.size()); j++){
    // Set (L/E)^-2 weights
    double w = 1./pow(samples[j],2);
    matrixD sample_probs = ProbMatrix(nflvi, nflvf, length / samples[j]);
    for(int flvi=0; flvi<nflvi; flvi++){
    for(int flvf=0; flvf<nflvf; flvf++){
      // Add weighted probability
      probs[flvi][flvf] += w * sample_probs[flvi][flvf];
    }}
    // Increment sum of weights
    sumw += w;
  }
  for(int flvi=0; flvi<nflvi; flvi++){
  for(int flvf=0; flvf<nflvf; flvf++){
    // Divide by total sampling weight
    probs[flvi][flvf] /= sumw;
  }}
  // Return weighted average of probabilities
  return probs;
}
References OscProb::AvgPath(), fNuPaths, fPath, GetSamplePoints(), OscProb::NuPath::length, ProbMatrix(), SetCurPath(), and SetEnergy().
Referenced by AvgProbMatrix().
AvgProbVector() [1/2]
vectorD PMNS_Base::AvgProbVector (int flvi, double E, double dE = 0) virtual
Compute the average probability of nu_in going to all flavours over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1870 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbVector(fNuState, E, dE);
}
References AvgProbVector(), fNuState, and ResetToFlavour().
AvgProbVector() [2/2]
vectorD PMNS_Base::AvgProbVector (vectorC nu_in, double E, double dE = 0) virtual
Compute the average probability of nu_in going to all flavours over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
nu_in - The neutrino initial state in flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1894 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if energy is not positive
  if(E<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Don't average zero width
  if(dE<=0) return ProbVector(nu_in, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbVectorLoE(nu_in, LoEbin[0], LoEbin[1]);
}
References AvgProbVectorLoE(), ConvertEtoLoE(), fNumNus, fNuPaths, and ProbVector().
Referenced by AvgProbVector().
AvgProbVectorLoE() [1/2]
vectorD PMNS_Base::AvgProbVectorLoE (int flvi, double LoE, double dLoE = 0) virtual
Compute the average probability of flvi going to all flavours over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
flvi - The neutrino starting flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1845 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  AvgProbVectorLoE(fNuState, LoE, dLoE);
}
References AvgProbVectorLoE(), fNuState, and ResetToFlavour().
AvgProbVectorLoE() [2/2]
vectorD PMNS_Base::AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE = 0) virtual
Compute the average probability of nu_in going to all flavours over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
nu_in - The neutrino intial state in flavour basis.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1934 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if L/E is not positive
  if(LoE<=0) return probs;
  if(fNuPaths.empty()) return probs;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length/LoE);
  // Don't average zero width
  if(dLoE<=0) return ProbVector(nu_in);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw = 0;
  double length = fPath.length;
  // Loop over all sample points
  for(int j=0; j<int(samples.size()); j++){
    // Set (L/E)^-2 weights
    double w = 1./pow(samples[j],2);
    vectorD sample_probs = ProbVector(nu_in, length / samples[j]);
    for(int i=0; i<fNumNus; i++){
      // Add weighted probability
      probs[i] += w * sample_probs[i];
    }
    // Increment sum of weights
    sumw += w;
  }
  for(int i=0; i<fNumNus; i++){
    // Divide by total sampling weight
    probs[i] /= sumw;
  }
  // Return weighted average of probabilities
  return probs;
}
References OscProb::AvgPath(), fNumNus, fNuPaths, fPath, GetSamplePoints(), OscProb::NuPath::length, ProbVector(), SetCurPath(), and SetEnergy().
Referenced by AvgProbVector(), and AvgProbVectorLoE().
BuildHms()
void PMNS_Base::BuildHms () protected virtual
Build Hms = H*2E, where H is the Hamiltonian in vacuum on flavour basis and E is the neutrino energy in eV. Hms is effectively the matrix of masses squared.
This is a hermitian matrix, so only the upper triangular part needs to be filled
The construction of the Hamiltonian avoids computing terms that are simply zero. This has a big impact in the computation time.
Definition at line 1062 of file PMNS_Base.cxx.
{
  // Check if anything changed
  if(fBuiltHms) return;
  // Tag to recompute eigensystem
  fGotES = false;
  for(int j=0; j<fNumNus; j++){
    // Set mass splitting
    fHms[j][j] = fDm[j];
    // Reset off-diagonal elements
    for(int i=0; i<j; i++){
      fHms[i][j] = 0;
    }
    // Rotate j neutrinos
    for(int i=0; i<j; i++){
      RotateH(i,j,fHms);
    }
  }
  ClearCache();
  // Tag as built
  fBuiltHms = true;
}
References ClearCache(), fBuiltHms, fDm, fGotES, fHms, fNumNus, and RotateH().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
ClearCache()
void PMNS_Base::ClearCache () virtual
Clear the cache
Definition at line 117 of file PMNS_Base.cxx.
{
  fMixCache.clear();
  // Set some better hash table parameters
  fMixCache.max_load_factor(0.25);
  fMixCache.reserve(512);
}
References fMixCache.
Referenced by BuildHms(), PMNS_Base(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), and OscProb::PMNS_NSI::SetEps().
ClearPath()
void PMNS_Base::ClearPath () virtual
Clear the path vector.
Definition at line 325 of file PMNS_Base.cxx.
{
  fNuPaths.clear();
}
References fNuPaths.
Referenced by SetAtt(), and SetPath().
ConvertEtoLoE()
vectorD PMNS_Base::ConvertEtoLoE (double E, double dE) protected virtual
Convert a bin of energy into a bin of L/E
Parameters
E - energy bin center in GeV
dE - energy bin width in GeV
Returns
The L/E bin center and width in km/GeV
Definition at line 1648 of file PMNS_Base.cxx.
{
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Define L/E variables
  vectorD LoEbin(2);
  // Set a minimum energy
  double minE = 0.1 * E;
  // Transform range to L/E
  // Full range if low edge > minE
  if(E-dE/2 > minE){
    LoEbin[0] = 0.5 * (fPath.length/(E-dE/2) + fPath.length/(E+dE/2));
    LoEbin[1] = fPath.length/(E-dE/2) - fPath.length/(E+dE/2);
  }
  // Else start at minE
  else{
    LoEbin[0] = 0.5 * (fPath.length/minE + fPath.length/(E+dE/2));
    LoEbin[1] = fPath.length/minE - fPath.length/(E+dE/2);
  }
  return LoEbin;
}
References OscProb::AvgPath(), fNuPaths, fPath, OscProb::NuPath::length, and SetCurPath().
Referenced by AvgProb(), AvgProbMatrix(), and AvgProbVector().
FillCache()
void PMNS_Base::FillCache () protected virtual
If using caching, save the eigensystem in memory
Definition at line 172 of file PMNS_Base.cxx.
{
  if(fUseCache){
    if(fMixCache.size()>fMaxCache){
      fMixCache.erase(fMixCache.begin());
    }
    fProbe.SetVars(fEnergy, fPath, fIsNuBar);
    for(int i=0; i<fNumNus; i++){
      fProbe.fEval[i] = fEval[i];
      for(int j=0; j<fNumNus; j++){
        fProbe.fEvec[i][j] = fEvec[i][j];
      }
    }
    fMixCache.insert(fProbe);
  }
}
References fEnergy, OscProb::EigenPoint::fEval, fEval, OscProb::EigenPoint::fEvec, fEvec, fIsNuBar, fMaxCache, fMixCache, fNumNus, fPath, fProbe, fUseCache, and OscProb::EigenPoint::SetVars().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
GetAngle()
double PMNS_Base::GetAngle (int i, int j) virtual
Get the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of theta_ij
Definition at line 664 of file PMNS_Base.cxx.
{
  if(i>j){
    cout << "Warning: First argument should be smaller than second argument" << endl;
    cout << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cout << "ERROR: Theta" << i << j << " not valid for " << fNumNus;
    cout << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fTheta[i-1][j-1];
}
References fNumNus, and fTheta.
GetDelta()
double PMNS_Base::GetDelta (int i, int j) virtual
Get the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of delta_ij
Definition at line 734 of file PMNS_Base.cxx.
{
  if(i>j){
    cout << "Warning: First argument should be smaller than second argument" << endl;
    cout << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cout << "ERROR: Delta" << i << j << " not valid for " << fNumNus;
    cout << " neutrinos. Returning zero." << endl;
    return 0;
  }
  if(i+1==j){
    cout << "Warning: Rotation " << i << j << " is real. Returning zero." << endl;
    return 0;
  }
  return fDelta[i-1][j-1];
}
References fDelta, and fNumNus.
GetDm()
double PMNS_Base::GetDm (int j) virtual
Get the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 794 of file PMNS_Base.cxx.
{
  if(j<2 || j>fNumNus){
    cout << "ERROR: Dm" << j << "1 not valid for " << fNumNus;
    cout << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fDm[j-1];
}
References fDm, and fNumNus.
GetDmEff()
double PMNS_Base::GetDmEff (int j) virtual
Get the effective mass-splitting dm_j1 in matter in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 833 of file PMNS_Base.cxx.
{
  if(j<2 || j>fNumNus){
    cout << "ERROR: Dm_" << j << "1 not valid for " << fNumNus;
    cout << " neutrinos. Returning zero." << endl;
    return 0;
  }
  // Solve the Hamiltonian to update eigenvalues
  SolveHam();
  // Sort eigenvalues in same order as vacuum Dm^2
  vectorI dm_idx = GetSortedIndices(fDm);
  vectorD dm_idx_double(dm_idx.begin(), dm_idx.end());
  dm_idx = GetSortedIndices(dm_idx_double);
  vectorI ev_idx = GetSortedIndices(fEval);
  // Return difference in eigenvalues * 2E
  return (fEval[ev_idx[dm_idx[j-1]]] - fEval[ev_idx[dm_idx[0]]]) * 2*fEnergy * kGeV2eV;
}
References fDm, fEnergy, fEval, fNumNus, GetSortedIndices(), kGeV2eV, and SolveHam().
GetEnergy()
double PMNS_Base::GetEnergy () virtual
Get the neutrino energy in GeV.
Definition at line 283 of file PMNS_Base.cxx.
{
  return fEnergy;
}
References fEnergy.
GetIsNuBar()
bool PMNS_Base::GetIsNuBar () virtual
Get the anti-neutrino flag.
Definition at line 293 of file PMNS_Base.cxx.
{
  return fIsNuBar;
}
References fIsNuBar.
GetMassEigenstate()
vectorC PMNS_Base::GetMassEigenstate (int mi) virtual
Get the neutrino mass eigenstate in vacuum
States are:
  0 = m_1, 1 = m_2, 2 = m_3, etc.
Parameters
mi - the mass eigenstate index
Returns
The mass eigenstate
Definition at line 899 of file PMNS_Base.cxx.
{
  vectorC oldState = fNuState;
  ResetToFlavour(mi);
  for(int j=0; j<fNumNus; j++){
  for(int i=0; i<j; i++){
    RotateState(i,j);
  }}
  vectorC newState = fNuState;
  fNuState = oldState;
  return newState;
}
References fNumNus, fNuState, ResetToFlavour(), and RotateState().
GetPath()
vector< NuPath > PMNS_Base::GetPath () virtual
Get the vector of neutrino paths.
Definition at line 346 of file PMNS_Base.cxx.
{
  return fNuPaths;
}
References fNuPaths.
GetSamplePoints()
vectorD PMNS_Base::GetSamplePoints (double LoE, double dLoE) virtual
Compute the sample points for a bin of L/E with width dLoE
This is used for averaging the probability over a bin of L/E. It should be a private function, but I'm keeping it public for now for debugging purposes. The number of sample points seems too high for most purposes. The number of subdivisions needs to be optimized.
Parameters
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Definition at line 2122 of file PMNS_Base.cxx.
{
  // Solve Hamiltonian to get eigenvalues
  SolveHam();
  // Define conversion factor [km/GeV -> 1/(4 eV^2)]
  const double k1267 = kKm2eV / (4 * kGeV2eV);
  // Get list of all effective Dm^2
  vectorD effDm;
  for(int i=0; i<fNumNus-1; i++){
    for(int j=i+1; j<fNumNus; j++){
      effDm.push_back( 2 * kGeV2eV * fEnergy * fabs(fEval[j] - fEval[i]) );
    }
  }
  int numDm = effDm.size();
  // Sort the effective Dm^2 list
  sort(effDm.begin(), effDm.end());
  // Set a number of sub-divisions to achieve "good" accuracy
  // This needs to be studied better
  int n_div = ceil( 20 * pow(dLoE/LoE,0.8) );
  //int n_div = 1;
  // A vector to store sample points
  vectorD allSamples;
  // Loop over sub-divisions
  for(int k=0; k<n_div; k++){
    // Define sub-division center and width
    double bctr = LoE - dLoE/2 + (k+0.5)*dLoE/n_div;
    double bwdt = dLoE/n_div;
    // Make a vector of L/E sample values
    // Initialized in the sub-division center
    vectorD samples;
    samples.push_back(bctr);
    // Loop over all Dm^2 to average each frequency
    // This will recursively sample points in smaller
    // bins so that all relevant frequencies are used
    for(int i=0; i<numDm; i++){
      // Copy the list of sample L/E values
      vectorD prev = samples;
      // Redefine bin width to lie within full sub-division
      double Width = 2*min(prev[0] - (bctr - bwdt/2), (bctr + bwdt/2) - prev[0]);
      // Compute oscillation argument sorted from lowest  to highest
      const double arg = k1267 * effDm[i] * Width;
      // Skip small oscillation values.
      // If it's the last one, lower the tolerance
      if(i < numDm-1){
        if(arg<0.9) continue;
      }
      else{
        if(arg<0.1) continue;
      }
      // Reset samples to redefine them
      samples.clear();
      // Loop over previous samples
      for(int j=0; j<int(prev.size()); j++){
        // Compute new sample points around old samples
        // This is based on a oscillatory quadrature rule
        double sample = (1/sqrt(3)) * (Width/2);
        if(arg!=0) sample = acos(sin(arg)/arg)/arg * (Width/2);
        // Add samples above and below center
        samples.push_back(prev[j]-sample);
        samples.push_back(prev[j]+sample);
      }
    }// End of loop over Dm^2
    // Add sub-division samples to the end of allSamples vector
    allSamples.insert(allSamples.end(), samples.begin(), samples.end());
  }// End of loop over sub-divisions
  // Return all sample points
  return allSamples;
}
References fEnergy, fEval, fNumNus, kGeV2eV, kKm2eV, and SolveHam().
Referenced by AvgProbLoE(), AvgProbMatrixLoE(), and AvgProbVectorLoE().
GetSortedIndices()
vectorI PMNS_Base::GetSortedIndices (const vectorD x) protected virtual
Get the indices of the sorted x vector
Parameters
x - input vector
Returns
The vector of sorted indices
Definition at line 815 of file PMNS_Base.cxx.
{
  vectorI idx(x.size(),0);
  for(int i=0; i<x.size(); i++) idx[i] = i;
  sort(idx.begin(), idx.end(), IdxCompare(x));
  return idx;
}
Referenced by GetDmEff(), and OscProb::PMNS_Deco::PropagatePath().
InitializeVectors()
void PMNS_Base::InitializeVectors () protected virtual
Set vector sizes and initialize elements to zero.
Definition at line 80 of file PMNS_Base.cxx.
{
  fDm    = vectorD(fNumNus, 0);
  fTheta = matrixD(fNumNus, vectorD(fNumNus,0));
  fDelta = matrixD(fNumNus, vectorD(fNumNus,0));
  fNuState = vectorC(fNumNus, zero);
  fHms     = matrixC(fNumNus, vectorC(fNumNus,zero));
  fPhases = vectorC(fNumNus, zero);
  fBuffer = vectorC(fNumNus, zero);
  fEval = vectorD(fNumNus, 0);
  fEvec = matrixC(fNumNus, vectorC(fNumNus,zero));
}
References fBuffer, fDelta, fDm, fEval, fEvec, fHms, fNumNus, fNuState, fPhases, fTheta, and zero.
Referenced by PMNS_Base().
P()
double PMNS_Base::P (int flv) protected virtual
Compute oscillation probability of flavour flv from current state
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino final flavour.
Returns
Neutrino oscillation probability
Reimplemented in OscProb::PMNS_Deco.
Definition at line 1177 of file PMNS_Base.cxx.
{
  assert(flv>=0 && flv<fNumNus);
  return norm(fNuState[flv]);
}
References fNumNus, and fNuState.
Referenced by Prob().
Prob() [1/6]
double PMNS_Base::Prob (int flvi, int flvf) virtual
Compute the probability of flvi going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1197 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return Prob(fNuState, flvf);
}
References fNuState, Prob(), and ResetToFlavour().
Prob() [2/6]
double PMNS_Base::Prob (int flvi, int flvf, double E) virtual
Compute the probability of flvi going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1273 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(flvi, flvf);
}
References Prob(), and SetEnergy().
Prob() [3/6]
double PMNS_Base::Prob (int flvi, int flvf, double E, double L) virtual
Compute the probability of flvi going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1336 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(flvi, flvf);
}
References Prob(), SetEnergy(), and SetLength().
Prob() [4/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf) virtual
Compute the probability of nu_in going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1220 of file PMNS_Base.cxx.
{
  assert(nu_in.size() == fNumNus);
  assert(flvf >= 0 && flvf < fNumNus);
  fNuState = nu_in;
  Propagate();
  return P(flvf);
}
References fNumNus, fNuState, P(), and Propagate().
Referenced by AvgProb(), AvgProbLoE(), and Prob().
Prob() [5/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E) virtual
Compute the probability of nu_in going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1249 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(nu_in, flvf);
}
References Prob(), and SetEnergy().
Prob() [6/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E, double L) virtual
Compute the probability of nu_in going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1304 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(nu_in, flvf);
}
References Prob(), SetEnergy(), and SetLength().
ProbMatrix() [1/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf) virtual
Compute the probability matrix for the first nflvi and nflvf states.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
Returns
Neutrino oscillation probabilities
Definition at line 1510 of file PMNS_Base.cxx.
{
  assert(nflvi<=fNumNus && nflvi>=0);
  assert(nflvf<=fNumNus && nflvf>=0);
  // Output probabilities
  matrixD probs(nflvi, vectorD(nflvf));
  // List of states
  matrixC allstates(nflvi, vectorC(fNumNus));
  // Reset all initial states
  for(int i=0; i<nflvi; i++){
    ResetToFlavour(i);
    allstates[i] = fNuState;
  }
  // Propagate all states in parallel
  for(int i=0; i<int(fNuPaths.size()); i++){
    for(int flvi=0; flvi<nflvi; flvi++){
      fNuState = allstates[flvi];
      PropagatePath(fNuPaths[i]);
      allstates[flvi] = fNuState;
    }
  }
  // Get all probabilities
  for(int flvi=0; flvi<nflvi; flvi++){
  for(int flvj=0; flvj<nflvf; flvj++){
    probs[flvi][flvj] = norm(allstates[flvi][flvj]);
  }}
  return probs;
}
References fNumNus, fNuPaths, fNuState, PropagatePath(), and ResetToFlavour().
Referenced by AvgProbMatrix(), AvgProbMatrixLoE(), and ProbMatrix().
ProbMatrix() [2/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E) virtual
Compute the probability matrix for the first nflvi and nflvf states for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probabilities
Definition at line 1565 of file PMNS_Base.cxx.
{
 SetEnergy(E);
 return ProbMatrix(nflvi, nflvf);
}
References ProbMatrix(), and SetEnergy().
ProbMatrix() [3/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E, double L) virtual
Compute the probability matrix for the first nflvi and nflvf states for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probabilities
Definition at line 1596 of file PMNS_Base.cxx.
{
 SetEnergy(E);
 SetLength(L);
 return ProbMatrix(nflvi, nflvf);
}
References ProbMatrix(), SetEnergy(), and SetLength().
ProbVector() [1/6]
vectorD PMNS_Base::ProbVector (int flvi) virtual
Compute the probability of flvi going to all flavours.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
Returns
Neutrino oscillation probabilities
Definition at line 1386 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return ProbVector(fNuState);
}
References fNuState, ProbVector(), and ResetToFlavour().
ProbVector() [2/6]
vectorD PMNS_Base::ProbVector (int flvi, double E) virtual
Compute the probability of flvi going to all flavours for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1429 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(flvi);
}
References ProbVector(), and SetEnergy().
ProbVector() [3/6]
vectorD PMNS_Base::ProbVector (int flvi, double E, double L) virtual
Compute the probability of flvi going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1485 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(flvi);
}
References ProbVector(), SetEnergy(), and SetLength().
ProbVector() [4/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in) virtual
Compute the probability of nu_in going to all flavours.
Parameters
nu_in - The neutrino initial state in flavour basis.
Returns
Neutrino oscillation probabilities
Definition at line 1354 of file PMNS_Base.cxx.
{
  assert(nu_in.size() == fNumNus);
  fNuState = nu_in;
  Propagate();
  vectorD probs(fNumNus);
  for(int i=0; i<probs.size(); i++){
    probs[i] = norm(fNuState[i]);
  }
  return probs;
}
References fNumNus, fNuState, and Propagate().
Referenced by AvgProbVector(), AvgProbVectorLoE(), and ProbVector().
ProbVector() [5/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E) virtual
Compute the probability of nu_in going to all flavours for a given energy in GeV.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probabilities
Definition at line 1405 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(nu_in);
}
References ProbVector(), and SetEnergy().
ProbVector() [6/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E, double L) virtual
Compute the probability of nu_in going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probabilities
Definition at line 1454 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(nu_in);
}
References ProbVector(), SetEnergy(), and SetLength().
Propagate()
void PMNS_Base::Propagate () protected virtual
Propagate neutrino state through full path
Reimplemented in OscProb::PMNS_Iter.
Definition at line 1133 of file PMNS_Base.cxx.
{
  for(int i=0; i<int(fNuPaths.size()); i++){
    PropagatePath(fNuPaths[i]);
  }
}
References fNuPaths, and PropagatePath().
Referenced by Prob(), and ProbVector().
PropagatePath()
void PMNS_Base::PropagatePath (OscProb::NuPath p) protected virtual
Propagate the current neutrino state through a given path
Parameters
p - A neutrino path segment
Reimplemented in OscProb::PMNS_Decay, and OscProb::PMNS_Deco.
Definition at line 1096 of file PMNS_Base.cxx.
{
  // Set the neutrino path
  SetCurPath(p);
  // Solve for eigensystem
  SolveHam();
  double LengthIneV = kKm2eV * p.length;
  for(int i=0; i<fNumNus; i++){
    double arg = fEval[i] * LengthIneV;
    fPhases[i] = complexD(cos(arg), -sin(arg));
  }
  for(int i=0;i<fNumNus;i++){
    fBuffer[i] = 0;
    for(int j=0;j<fNumNus;j++){
      fBuffer[i] += conj(fEvec[j][i]) * fNuState[j];
    }
    fBuffer[i] *= fPhases[i];
  }
  // Propagate neutrino state
  for(int i=0;i<fNumNus;i++){
    fNuState[i] = 0;
    for(int j=0;j<fNumNus;j++){
      fNuState[i] +=  fEvec[i][j] * fBuffer[j];
    }
  }
}
References fBuffer, fEval, fEvec, fNumNus, fNuState, fPhases, kKm2eV, OscProb::NuPath::length, SetCurPath(), and SolveHam().
Referenced by ProbMatrix(), Propagate(), and OscProb::PMNS_Iter::SplitPropagate().
ResetToFlavour()
void PMNS_Base::ResetToFlavour (int flv) protected virtual
Reset the neutrino state back to a pure flavour where it starts
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino starting flavour.
Reimplemented in OscProb::PMNS_Deco.
Definition at line 1155 of file PMNS_Base.cxx.
{
  assert(flv>=0 && flv<fNumNus);
  for (int i=0; i<fNumNus; ++i){
    if (i==flv) fNuState[i] = one;
    else        fNuState[i] = zero;
  }
}
References fNumNus, fNuState, one, and zero.
Referenced by AvgProb(), AvgProbLoE(), AvgProbVector(), AvgProbVectorLoE(), GetMassEigenstate(), PMNS_Base(), Prob(), ProbMatrix(), and ProbVector().
RotateH()
void PMNS_Base::RotateH (int i, int j, matrixC & Ham) protected virtual
Rotate the Hamiltonian by the angle theta_ij and phase delta_ij.
The rotations assume all off-diagonal elements with i > j are zero. This is correct if the order of rotations is chosen appropriately and it speeds up computation by skipping null terms
Parameters
i,j - the indices of the rotation ij
Ham - the Hamiltonian to be rotated
Definition at line 928 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if(fTheta[i][j]==0) return;
  double fSinBuffer = sin(fTheta[i][j]);
  double fCosBuffer = cos(fTheta[i][j]);
  double  fHmsBufferD;
  complexD fHmsBufferC;
  // With Delta
  if(i+1<j){
    complexD fExpBuffer = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    // General case
    if(i>0){
      // Top columns
      for(int k=0; k<i; k++){
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer * conj(fExpBuffer);
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer * fExpBuffer;
      }
      // Middle row and column
      for(int k=i+1; k<j; k++){
        fHmsBufferC = Ham[k][j];
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
        Ham[i][k] += fSinBuffer * fExpBuffer * conj(fHmsBufferC);
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += 2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -= 2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j] * conj(fExpBuffer)) * fSinBuffer * fExpBuffer;
      Ham[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC) * fExpBuffer;
    }
    // First rotation on j (No top columns)
    else{
      // Middle rows and columns
      for(int k=i+1; k<j; k++){
        Ham[k][j] = -conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
      }
      // Nodes ij
      fHmsBufferD = real(Ham[i][i]);
      Ham[i][j] = fSinBuffer * fCosBuffer * (Ham[j][j] - fHmsBufferD) * fExpBuffer;
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferD * fSinBuffer;
    }
  }
  // Without Delta (No middle rows or columns: j = i+1)
  else{
    // General case
    if(i>0){
      // Top columns
      for(int k=0; k<i; k++){
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer;
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer;
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -= 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j]) * fSinBuffer;
      Ham[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC);
    }
    // First rotation (theta12)
    else{
      Ham[i][j] = fSinBuffer * fCosBuffer * Ham[j][j];
      Ham[i][i] = fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
    }
  }
}
References fDelta, and fTheta.
Referenced by OscProb::PMNS_Decay::BuildHam(), and BuildHms().
RotateState()
void PMNS_Base::RotateState (int i, int j) protected virtual
Rotate the neutrino state by the angle theta_ij and phase delta_ij.
Parameters
i,j - the indices of the rotation ij
Definition at line 863 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if(fTheta[i][j]==0) return;
  double sij = sin(fTheta[i][j]);
  double cij = cos(fTheta[i][j]);
  complexD buffer;
  if(i+1==j || fDelta[i][j]==0){
    buffer      = cij*fNuState[i] + sij*fNuState[j];
    fNuState[j] = cij*fNuState[j] - sij*fNuState[i];
  }
  else {
    complexD eij = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    buffer      = cij*fNuState[i] + sij*eij*fNuState[j];
    fNuState[j] = cij*fNuState[j] - sij*conj(eij)*fNuState[i];
  }
  fNuState[i] = buffer;
}
References fDelta, fNuState, and fTheta.
Referenced by GetMassEigenstate().
SetAngle()
void PMNS_Base::SetAngle (int i, int j, double th) virtual
Set the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of theta_ij
th - the value of theta_ij
Definition at line 632 of file PMNS_Base.cxx.
{
  if(i>j){
    cout << "Warning: First argument should be smaller than second argument" << endl;
    cout << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cout << "ERROR: Theta" << i << j << " not valid for " << fNumNus;
    cout << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fTheta[i-1][j-1] == th);
  fTheta[i-1][j-1] = th;
}
References fBuiltHms, fNumNus, and fTheta.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetMix(), OscProb::PMNS_Fast::SetMix(), and SetStdPars().
SetAtt() [1/2]
void PMNS_Base::SetAtt (double att, int idx) protected virtual
Set some single path attribute.
An auxiliary function to set individual attributes in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
att - The value of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 421 of file PMNS_Base.cxx.
{
  if(fNuPaths.size() != 1){
    cout << "Warning: Clearing path vector and starting new single path." << endl;
    cout << "To avoid possible issues, use the SetPath function." << endl;
    SetStdPath();
  }
  switch(idx){
    case 0: fNuPaths[0].length  = att; break;
    case 1: fNuPaths[0].density = att; break;
    case 2: fNuPaths[0].zoa     = att; break;
    case 3: fNuPaths[0].layer   = att; break;
  }
}
References fNuPaths, and SetStdPath().
Referenced by SetDensity(), SetLayers(), SetLength(), and SetZoA().
SetAtt() [2/2]
void PMNS_Base::SetAtt (vectorD att, int idx) protected virtual
Set all values of a path attribute.
An auxiliary function to set individual attributes in a path sequence.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
att - The values of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 498 of file PMNS_Base.cxx.
{
  // Get the sizes of the attribute and
  // path sequence vectors
  int nA = att.size();
  int nP = fNuPaths.size();
  // If the vector sizes are equal, update this attribute
  if(nA == nP){
    for(int i=0; i<nP; i++){
      switch(idx){
        case 0: fNuPaths[i].length  = att[i]; break;
        case 1: fNuPaths[i].density = att[i]; break;
        case 2: fNuPaths[i].zoa     = att[i]; break;
        case 3: fNuPaths[i].layer   = att[i]; break;
      }
    }
  }
  // If the vector sizes differ, create a new path sequence
  // and set value for this attribute. Other attributes will
  // be taken from default single path.
  else{
    cout << "Warning: New vector size. Starting new path vector." << endl;
    cout << "To avoid possible issues, use the SetPath function." << endl;
    // Start a new standard path just
    // to set default values
    SetStdPath();
    // Create a path segment with default values
    NuPath p = fNuPaths[0];
    // Clear the path sequence
    ClearPath();
    // Set this particular attribute's value
    // and add the path segment to the sequence
    for(int i=0; i<nA; i++){
      switch(idx){
        case 0: p.length  = att[i]; break;
        case 1: p.density = att[i]; break;
        case 2: p.zoa     = att[i]; break;
        case 3: p.layer   = att[i]; break;
      }
      AddPath(p);
    }
  }
}
References AddPath(), ClearPath(), OscProb::NuPath::density, fNuPaths, OscProb::NuPath::layer, OscProb::NuPath::length, SetStdPath(), and OscProb::NuPath::zoa.
SetCurPath()
void PMNS_Base::SetCurPath (OscProb::NuPath p) protected virtual
Set the path currentlyin use by the class.
This will be used to know what path to propagate through next.
It will also check if values are changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
p - A neutrino path segment
Definition at line 310 of file PMNS_Base.cxx.
{
  // Check if relevant value are actually changing
  fGotES *= (fPath.density == p.density);
  fGotES *= (fPath.zoa == p.zoa);
  fPath = p;
}
References OscProb::NuPath::density, fGotES, fPath, and OscProb::NuPath::zoa.
Referenced by AvgProbLoE(), AvgProbMatrixLoE(), AvgProbVectorLoE(), ConvertEtoLoE(), PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), and OscProb::PMNS_Deco::PropagatePath().
SetDelta()
void PMNS_Base::SetDelta (int i, int j, double delta) virtual
Set the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of delta_ij
delta - the value of delta_ij
Definition at line 698 of file PMNS_Base.cxx.
{
  if(i>j){
    cout << "Warning: First argument should be smaller than second argument" << endl;
    cout << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i = j;
    j = temp;
  }
  if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
    cout << "ERROR: Delta" << i << j << " not valid for " << fNumNus;
    cout << " neutrinos. Doing nothing." << endl;
    return;
  }
  if(i+1==j){
    cout << "Warning: Rotation " << i << j << " is real. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDelta[i-1][j-1] == delta);
  fDelta[i-1][j-1] = delta;
}
References fBuiltHms, fDelta, and fNumNus.
Referenced by OscProb::PMNS_Decay::SetMix(), and OscProb::PMNS_Fast::SetMix().
SetDensity() [1/2]
void PMNS_Base::SetDensity (double rho) virtual
Set single path density.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The density of the path segment in g/cm^3
Definition at line 465 of file PMNS_Base.cxx.
{
  SetAtt(rho, 1);
}
References SetAtt().
SetDensity() [2/2]
void PMNS_Base::SetDensity (vectorD rho) virtual
Set multiple path densities.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The densities of the path segments in g/cm^3
Definition at line 581 of file PMNS_Base.cxx.
{
  SetAtt(rho, 1);
}
References SetAtt().
SetDm()
void PMNS_Base::SetDm (int j, double dm) virtual
Set the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
j - the index of dm_j1
dm - the value of dm_j1
Definition at line 770 of file PMNS_Base.cxx.
{
  if(j<2 || j>fNumNus){
    cout << "ERROR: Dm" << j << "1 not valid for " << fNumNus;
    cout << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDm[j-1] == dm);
  fDm[j-1] = dm;
}
References fBuiltHms, fDm, and fNumNus.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetDeltaMsqrs(), OscProb::PMNS_Fast::SetDeltaMsqrs(), and SetStdPars().
SetEnergy()
void PMNS_Base::SetEnergy (double E) virtual
Set neutrino energy in GeV.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
E - The neutrino energy in GeV
Definition at line 250 of file PMNS_Base.cxx.
{
  // Check if value is actually changing
  fGotES *= (fEnergy == E);
  fEnergy = E;
}
References fEnergy, and fGotES.
Referenced by AvgProbLoE(), AvgProbMatrixLoE(), AvgProbVectorLoE(), PMNS_Base(), Prob(), ProbMatrix(), and ProbVector().
SetIsNuBar()
void PMNS_Base::SetIsNuBar (bool isNuBar) virtual
Set anti-neutrino flag.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
isNuBar - Set to true for anti-neutrino and false for neutrino.
Reimplemented in OscProb::PMNS_Decay.
Definition at line 269 of file PMNS_Base.cxx.
{
  // Check if value is actually changing
  fGotES *= (fIsNuBar == isNuBar);
  fIsNuBar = isNuBar;
}
References fGotES, and fIsNuBar.
Referenced by CheckProb(), PMNS_Base(), and SaveTestFile().
SetLayers()
void PMNS_Base::SetLayers (std::vector< int > lay) virtual
Set multiple path layer indices.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
lay - Indices to identify the layer types (e.g. earth inner core)
Definition at line 611 of file PMNS_Base.cxx.
{
  vectorD lay_double(lay.begin(), lay.end());
  SetAtt(lay_double, 3);
}
References SetAtt().
SetLength() [1/2]
void PMNS_Base::SetLength (double L) virtual
Set the length for a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
L - The length of the path segment in km
Definition at line 450 of file PMNS_Base.cxx.
{
  SetAtt(L, 0);
}
References SetAtt().
Referenced by Prob(), ProbMatrix(), and ProbVector().
SetLength() [2/2]
void PMNS_Base::SetLength (vectorD L) virtual
Set multiple path lengths.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
L - The lengths of the path segments in km
Definition at line 566 of file PMNS_Base.cxx.
{
  SetAtt(L, 0);
}
References SetAtt().
SetMaxCache()
void PMNS_Base::SetMaxCache (int mc = 1e6) virtual
Set maximum number of cached eigensystems. Finding eigensystems can become slow and take up memory. This protects the cache from becoming too large.
Parameters
mc - Max cache size (default: 1e6)
Definition at line 134 of file PMNS_Base.cxx.
{
  fMaxCache = mc;
}
References fMaxCache.
SetPath() [1/3]
void PMNS_Base::SetPath (double length, double density, double zoa = 0.5, int layer = 0) virtual
Set a single path defining attributes directly.
This destroys the current path sequence and creates a new first path.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 403 of file PMNS_Base.cxx.
{
  SetPath(NuPath(length, density, zoa, layer));
}
References SetPath().
SetPath() [2/3]
void PMNS_Base::SetPath (OscProb::NuPath p) virtual
Set a single path.
This destroys the current path sequence and creates a new first path.
Parameters
p - A neutrino path segment
Definition at line 385 of file PMNS_Base.cxx.
{
  ClearPath();
  AddPath(p);
}
References AddPath(), and ClearPath().
Referenced by SetPath(), SetStdPath(), and SetTestPath().
SetPath() [3/3]
virtual void OscProb::PMNS_Base::SetPath (std::vector< OscProb::NuPath > paths) virtual
SetStdPars()
void PMNS_Base::SetStdPars () virtual
Set standard oscillation parameters from PDG 2015.
For two neutrinos, Dm is set to the muon disappearance effective mass-splitting and mixing angle.
Definition at line 198 of file PMNS_Base.cxx.
{
  if(fNumNus>2){
    // PDG values for 3 neutrinos
    // Also applicable for 3+N neutrinos
    SetAngle(1,2, asin(sqrt(0.304)));
    SetAngle(1,3, asin(sqrt(0.0219)));
    SetAngle(2,3, asin(sqrt(0.514)));
    SetDm(2, 7.53e-5);
    SetDm(3, 2.52e-3);
  }
  else if(fNumNus==2){
    // Effective muon disappearance values
    // for two-flavour approximation
    SetAngle(1,2, 0.788);
    SetDm(2, 2.47e-3);
  }
}
References fNumNus, SetAngle(), and SetDm().
Referenced by PMNS_Base().
SetStdPath()
void PMNS_Base::SetStdPath () virtual
Set standard single path.
Length is 1000 km, so ~2 GeV peak energy.
Density is approximate from CRUST2.0 (~2.8 g/cm^3). Z/A is set to a round 0.5.
Definition at line 228 of file PMNS_Base.cxx.
{
  NuPath p;
  p.length  = 1000; // 1000 km default
  p.density = 2.8;  // Crust density
  p.zoa     = 0.5;  // Crust Z/A
  p.layer   = 0;    // Single layer
  SetPath(p);
}
References OscProb::NuPath::density, OscProb::NuPath::layer, OscProb::NuPath::length, SetPath(), and OscProb::NuPath::zoa.
Referenced by PMNS_Base(), OscProb::PMNS_Deco::PMNS_Deco(), OscProb::PMNS_LIV::PMNS_LIV(), OscProb::PMNS_NSI::PMNS_NSI(), and SetAtt().
SetUseCache()
void PMNS_Base::SetUseCache (bool u = true) virtual
Turn on/off caching of eigensystems. This can save a lot of CPU time by avoiding recomputing eigensystems if we've already seen them recently. Especially useful when running over multiple earth layers and even more if multiple baselines will be computed, e.g. for atmospheric neutrinos.
Parameters
u - flag to set caching on (default: true)
Definition at line 108 of file PMNS_Base.cxx.
{
  fUseCache = u;
}
References fUseCache.
Referenced by PMNS_Base().
SetZoA() [1/2]
void PMNS_Base::SetZoA (double zoa) virtual
Set single path Z/A.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segment
Definition at line 480 of file PMNS_Base.cxx.
{
  SetAtt(zoa, 2);
}
References SetAtt().
SetZoA() [2/2]
void PMNS_Base::SetZoA (vectorD zoa) virtual
Set multiple path Z/A values.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segments
Definition at line 596 of file PMNS_Base.cxx.
{
  SetAtt(zoa, 2);
}
References SetAtt().
SolveHam()
virtual void OscProb::PMNS_Base::SolveHam () protected pure virtual
Solve the full Hamiltonian
Not implemented in base class.
Implemented in OscProb::PMNS_Decay, OscProb::PMNS_Fast, OscProb::PMNS_Iter, and OscProb::PMNS_Sterile.
Referenced by GetDmEff(), GetSamplePoints(), and PropagatePath().
TryCache()
bool PMNS_Base::TryCache () protected virtual
Try to find a cached version of this eigensystem.
Definition at line 143 of file PMNS_Base.cxx.
{
  if(fUseCache && !fMixCache.empty()){
    fProbe.SetVars(fEnergy, fPath, fIsNuBar);
    unordered_set<EigenPoint>::iterator it = fMixCache.find(fProbe);
    if(it != fMixCache.end()){
      for(int i=0; i<fNumNus; i++){
        fEval[i] = (*it).fEval[i] * (*it).fEnergy / fEnergy;
        for(int j=0; j<fNumNus; j++){
          fEvec[i][j] = (*it).fEvec[i][j];
        }
      }
      return true;
    }
  }
  return false;
}
References fEnergy, fEval, fEvec, fIsNuBar, fMixCache, fNumNus, fPath, fProbe, fUseCache, and OscProb::EigenPoint::SetVars().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
Member Data Documentation
fBuffer
vectorC OscProb::PMNS_Base::fBuffer protected
Definition at line 232 of file PMNS_Base.h.
Referenced by InitializeVectors(), PropagatePath(), and OscProb::PMNS_Decay::PropagatePath().
fBuiltHms
bool OscProb::PMNS_Base::fBuiltHms protected
Definition at line 243 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHam(), BuildHms(), OscProb::PMNS_Decay::SetAlpha2(), OscProb::PMNS_Decay::SetAlpha3(), SetAngle(), SetDelta(), SetDm(), OscProb::PMNS_Decay::SetIsNuBar(), and OscProb::PMNS_Iter::SetVacuumEigensystem().
fCachePrec
double OscProb::PMNS_Base::fCachePrec protected
Definition at line 247 of file PMNS_Base.h.
fDelta
matrixD OscProb::PMNS_Base::fDelta protected
Definition at line 226 of file PMNS_Base.h.
Referenced by GetDelta(), InitializeVectors(), RotateH(), RotateState(), SetDelta(), OscProb::PMNS_Fast::SetVacuumEigensystem(), and OscProb::PMNS_Iter::SetVacuumEigensystem().
fDm
vectorD OscProb::PMNS_Base::fDm protected
Definition at line 224 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHam(), BuildHms(), GetDm(), GetDmEff(), InitializeVectors(), OscProb::PMNS_Deco::PropagatePath(), SetDm(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SetVacuumEigensystem(), and OscProb::PMNS_Iter::SplitPropagate().
fEnergy
double OscProb::PMNS_Base::fEnergy protected
Definition at line 237 of file PMNS_Base.h.
Referenced by FillCache(), GetDmEff(), GetEnergy(), GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), SetEnergy(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Iter::SplitPropagate(), TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
fEval
vectorD OscProb::PMNS_Base::fEval protected
Definition at line 234 of file PMNS_Base.h.
Referenced by FillCache(), GetDmEff(), GetSamplePoints(), InitializeVectors(), PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SetVacuumEigensystem(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), and TryCache().
fEvec
matrixC OscProb::PMNS_Base::fEvec protected
Definition at line 235 of file PMNS_Base.h.
Referenced by FillCache(), InitializeVectors(), PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SetVacuumEigensystem(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), and TryCache().
fGotES
bool OscProb::PMNS_Base::fGotES protected
Definition at line 244 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHam(), BuildHms(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), SetCurPath(), SetEnergy(), OscProb::PMNS_NSI::SetEps(), SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Iter::SolveHam(), and OscProb::PMNS_Sterile::SolveHam().
fHms
matrixC OscProb::PMNS_Base::fHms protected
Definition at line 229 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHam(), BuildHms(), InitializeVectors(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
fIsNuBar
bool OscProb::PMNS_Base::fIsNuBar protected
Definition at line 238 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHam(), FillCache(), GetIsNuBar(), OscProb::PMNS_Iter::SetExpVL(), SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
fMaxCache
int OscProb::PMNS_Base::fMaxCache protected
Definition at line 248 of file PMNS_Base.h.
Referenced by FillCache(), and SetMaxCache().
fMixCache
std::unordered_set<OscProb::EigenPoint> OscProb::PMNS_Base::fMixCache protected
Definition at line 250 of file PMNS_Base.h.
Referenced by ClearCache(), FillCache(), and TryCache().
fNumNus
int OscProb::PMNS_Base::fNumNus protected
Definition at line 222 of file PMNS_Base.h.
Referenced by AvgProbVector(), AvgProbVectorLoE(), OscProb::PMNS_Decay::BuildHam(), BuildHms(), FillCache(), GetAngle(), OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), GetDelta(), GetDm(), GetDmEff(), OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_Deco::GetGamma(), GetMassEigenstate(), GetSamplePoints(), InitializeVectors(), P(), OscProb::PMNS_Deco::P(), PMNS_Base(), OscProb::PMNS_Decay::PMNS_Decay(), Prob(), ProbMatrix(), ProbVector(), PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), ResetToFlavour(), OscProb::PMNS_Deco::ResetToFlavour(), SetAngle(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_LIV::SetcT(), SetDelta(), SetDm(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_Deco::SetGamma(), SetStdPars(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Iter::SplitPropagate(), TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
fNuPaths
std::vector<OscProb::NuPath> OscProb::PMNS_Base::fNuPaths protected
Definition at line 240 of file PMNS_Base.h.
Referenced by AddPath(), AvgProb(), AvgProbLoE(), AvgProbMatrix(), AvgProbMatrixLoE(), AvgProbVector(), AvgProbVectorLoE(), ClearPath(), ConvertEtoLoE(), GetPath(), ProbMatrix(), Propagate(), OscProb::PMNS_Iter::Propagate(), and SetAtt().
fNuState
vectorC OscProb::PMNS_Base::fNuState protected
Definition at line 228 of file PMNS_Base.h.
Referenced by AvgProb(), AvgProbLoE(), AvgProbVector(), AvgProbVectorLoE(), GetMassEigenstate(), InitializeVectors(), P(), Prob(), ProbMatrix(), ProbVector(), PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Iter::PropMatter(), ResetToFlavour(), and RotateState().
fPath
OscProb::NuPath OscProb::PMNS_Base::fPath protected
Definition at line 241 of file PMNS_Base.h.
Referenced by AvgProbLoE(), AvgProbMatrixLoE(), AvgProbVectorLoE(), ConvertEtoLoE(), FillCache(), OscProb::PMNS_NSI::GetZoACoup(), SetCurPath(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
fPhases
vectorC OscProb::PMNS_Base::fPhases protected
Definition at line 231 of file PMNS_Base.h.
Referenced by InitializeVectors(), PropagatePath(), and OscProb::PMNS_Decay::PropagatePath().
fProbe
EigenPoint OscProb::PMNS_Base::fProbe protected
Definition at line 251 of file PMNS_Base.h.
Referenced by FillCache(), and TryCache().
fTheta
matrixD OscProb::PMNS_Base::fTheta protected
Definition at line 225 of file PMNS_Base.h.
Referenced by GetAngle(), InitializeVectors(), RotateH(), RotateState(), SetAngle(), OscProb::PMNS_Fast::SetVacuumEigensystem(), and OscProb::PMNS_Iter::SetVacuumEigensystem().
fUseCache
bool OscProb::PMNS_Base::fUseCache protected
Definition at line 246 of file PMNS_Base.h.
Referenced by FillCache(), SetUseCache(), and TryCache().
kGeV2eV
const double PMNS_Base::kGeV2eV = 1.0e+09 static protected
Definition at line 174 of file PMNS_Base.h.
Referenced by GetDmEff(), GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Iter::SplitPropagate(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
kGf
const double PMNS_Base::kGf = 1.1663787e-05 static protected
Definition at line 177 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
kK2
const double PMNS_Base::kK2 = 1e-3 * kNA / pow(kKm2eV,3) static protected
Definition at line 173 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), and OscProb::PMNS_NSI::UpdateHam().
kKm2eV
const double PMNS_Base::kKm2eV = 1.0 / 1.973269788e-10 static protected
Definition at line 172 of file PMNS_Base.h.
Referenced by GetSamplePoints(), PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::SetExpVL(), and OscProb::PMNS_Iter::SplitPropagate().
kNA
const double PMNS_Base::kNA = 6.022140857e23 static protected
Definition at line 175 of file PMNS_Base.h.
one
const complexD PMNS_Base::one static protected
Definition at line 169 of file PMNS_Base.h.
Referenced by ResetToFlavour(), and OscProb::PMNS_Deco::ResetToFlavour().
zero
const complexD PMNS_Base::zero static protected
Definition at line 168 of file PMNS_Base.h.
Referenced by OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), OscProb::PMNS_NSI::GetEps(), InitializeVectors(), OscProb::PMNS_Decay::PMNS_Decay(), ResetToFlavour(), and OscProb::PMNS_Deco::ResetToFlavour().
The documentation for this class was generated from the following files:
PMNS_Base.h
PMNS_Base.cxx