OscProb: OscProb::PMNS_SNSI Class Reference
OscProb::PMNS_SNSI Class Reference
Implementation of oscillations of neutrinos in matter in a three-neutrino framework with scalar NSI.
#include <PMNS_SNSI.h>
Public Member Functions
PMNS_SNSI ()
Constructor.
virtual ~PMNS_SNSI ()
Destructor.
virtual void SetLowestMass (double m)
Set lightest neutrino mass.
virtual double GetLowestMass ()
Get lightest neutrino mass.
virtual void SetIsOscProbAvg (bool isOscProbAvg)
Deactivate Maltoni.
virtual void SetEps (int flvi, int flvj, double val, double phase)
Set any given NSI parameter.
virtual complexD GetEps (int flvi, int flvj)
Get any given NSI parameter.
void SetNSI (double eps_ee, double eps_emu, double eps_etau, double eps_mumu, double eps_mutau, double eps_tautau, double delta_emu=0, double delta_etau=0, double delta_mutau=0)
Set the NSI parameters all at once.
virtual void SetEps_ee (double a)
Set eps_ee parameter.
virtual void SetEps_mumu (double a)
Set eps_mumu parameter.
virtual void SetEps_tautau (double a)
Set eps_tautau parameter.
virtual void SetEps_emu (double a, double phi)
Set eps_emu parameter.
virtual void SetEps_etau (double a, double phi)
Set eps_etau parameter.
virtual void SetEps_mutau (double a, double phi)
Set eps_mutau parameter.
virtual void SetElecCoup (double e)
Set electron coupling.
virtual void SetUpCoup (double u)
Set u-quark couling.
virtual void SetDownCoup (double d)
Set d-quark couling.
virtual void SetFermCoup (double e, double u, double d)
Set all fermion couplings.
virtual void SetCoupByIndex (double c, int i)
Set a given fermion coupling.
virtual double GetElecCoup ()
Get electron coupling.
virtual double GetUpCoup ()
Get u-quark couling.
virtual double GetDownCoup ()
Get d-quark couling.
virtual double GetZoACoup ()
Get effective Z/A coupling.
virtual void SetMix (double th12, double th23, double th13, double deltacp)
Set the all mixing parameters at once.
virtual void SetDeltaMsqrs (double dm21, double dm32)
Set both mass-splittings at once.
virtual void SetPremModel (OscProb::PremModel &prem)
virtual double AvgProb (int flvi, int flvf, double E, double dE)
virtual double AvgProb (int flvi, int flvf, double E, double cosT, double dcosT)
virtual double AvgProb (int flvi, int flvf, double E, double dE, double cosT, double dcosT)
virtual double AvgProb (vectorC nu_in, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProb (int flvi, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProbLoE (int flvi, int flvf, double LoE, double dLoE)
virtual double AvgProbLoE (int flvi, int flvf, double LoE, double dLoE, double cosT, double dcosT)
virtual double AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual double AvgProbLoE (int flvi, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual vectorD AvgProbVector (int flvi, double E, double dE)
virtual vectorD AvgProbVector (vectorC nu_in, double E, double dE=0)
virtual vectorD AvgProbVectorLoE (int flvi, double LoE, double dLoE)
virtual vectorD AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE=0)
Compute the average probability vector over a bin of L/E.
virtual matrixD AvgProbMatrix (int nflvi, int nflvf, double E, double dE)
virtual matrixD AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE)
virtual double ExtrapolationProb (int flvi, int flvf, double E, double dE)
Compute the probability of flvi going to flvf for an energy E+dE.
virtual double ExtrapolationProbLoE (int flvi, int flvf, double LoE, double dLoE)
Compute the probability of flvi going to flvf at LoE+dLoE.
virtual double ExtrapolationProbCosT (int flvi, int flvf, double cosT, double dcosT)
Compute the probability of flvi going to flvf for an angle cosT+dcosT.
virtual double Prob (vectorC nu_in, int flvf)
Compute the probability of nu_in going to flvf.
virtual double Prob (vectorC nu_in, int flvf, double E)
virtual double Prob (vectorC nu_in, int flvf, double E, double L)
virtual double Prob (int flvi, int flvf)
Compute the probability of flvi going to flvf.
virtual double Prob (int flvi, int flvf, double E)
virtual double Prob (int flvi, int flvf, double E, double L)
virtual vectorD ProbVector (vectorC nu_in)
virtual vectorD ProbVector (vectorC nu_in, double E)
flavours for energy E
virtual vectorD ProbVector (vectorC nu_in, double E, double L)
virtual vectorD ProbVector (int flvi)
virtual vectorD ProbVector (int flvi, double E)
virtual vectorD ProbVector (int flvi, double E, double L)
virtual matrixD ProbMatrix (int nflvi, int nflvf)
Compute the probability matrix.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E)
Compute the probability matrix for energy E.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E, double L)
virtual vectorC GetMassEigenstate (int mi)
Get a neutrino mass eigenstate.
virtual void SetAngle (int i, int j, double th)
Set the mixing angle theta_ij.
virtual void SetDelta (int i, int j, double delta)
Set the CP phase delta_ij.
virtual void SetDm (int j, double dm)
Set the mass-splitting dm_j1 in eV^2.
virtual double GetAngle (int i, int j)
Get the mixing angle theta_ij.
virtual double GetDelta (int i, int j)
Get the CP phase delta_ij.
virtual double GetDm (int j)
Get the mass-splitting dm_j1 in eV^2.
virtual double GetDmEff (int j)
Get the effective mass-splitting dm_j1 in eV^2.
virtual void SetStdPars ()
Set PDG 3-flavor parameters.
virtual void SetEnergy (double E)
Set the neutrino energy in GeV.
virtual void SetIsNuBar (bool isNuBar)
Set the anti-neutrino flag.
virtual double GetEnergy ()
Get the neutrino energy in GeV.
virtual bool GetIsNuBar ()
Get the anti-neutrino flag.
virtual void SetPath (NuPath p)
Set a single path.
virtual void SetPath (double length, double density, double zoa=0.5, int layer=0)
Set a single path.
virtual void SetPath (std::vector< NuPath > paths)
Set a path sequence.
virtual void AddPath (NuPath p)
Add a path to the sequence.
virtual void AddPath (double length, double density, double zoa=0.5, int layer=0)
Add a path to the sequence.
virtual void ClearPath ()
Clear the path vector.
virtual void SetLength (double L)
Set a single path lentgh in km.
virtual void SetLength (vectorD L)
Set multiple path lengths.
virtual void SetDensity (double rho)
Set single path density in g/cm^3.
virtual void SetDensity (vectorD rho)
Set multiple path densities.
virtual void SetZoA (double zoa)
Set Z/A value for single path.
virtual void SetZoA (vectorD zoa)
Set multiple path Z/A values.
virtual void SetLayers (std::vector< int > lay)
Set multiple path layer indices.
virtual void SetStdPath ()
Set standard neutrino path.
virtual std::vector< NuPath > GetPath ()
Get the neutrino path sequence.
virtual vectorD GetSamplePoints (double LoE, double dLoE)
Compute the sample points for a bin of L/E with width dLoE.
virtual void SetUseCache (bool u=true)
Set caching on/off.
virtual void ClearCache ()
Clear the cache.
virtual void SetMaxCache (int mc=1e6)
Set max cache size.
virtual void SetAvgProbPrec (double prec)
Set the AvgProb precision.
Protected Member Functions
virtual void UpdateHam ()
Build the full Hamiltonian.
virtual void BuildHms ()
virtual void FillCache ()
Deactivate cache.
virtual void SolveHam ()
Solve the full Hamiltonian for eigenvectors and eigenvalues.
virtual void SolveHamMatter ()
Solve the full Hamiltonian in matter.
virtual void SetVacuumEigensystem ()
Set the eigensystem to the analytic solution of the vacuum Hamiltonian.
virtual vectorD GetSamplePointsAvgClass (double LoE, double dLoE)
Compute the sample points fo a bin of L/E with width dLoE.
virtual vectorD GetSamplePointsAvgClass (double E, double cosT, double dcosT)
Compute the sample points for a bin of cosT with width dcosT.
virtual matrixC GetSamplePointsAvgClass (double InvE, double dInvE, double cosT, double dcosT)
virtual void InitializeTaylorsVectors ()
Initialize all member vectors with zeros.
virtual void SetwidthBin (double dE, double dcosT)
Set bin's widths for energy and angle.
virtual void SetCosT (double cosT)
Set neutrino angle.
virtual void BuildKE (double L)
build K matrix for the inverse of energy in mass basis
virtual void BuildKcosT ()
build K matrix for angle in flavor basis
virtual double LnDerivative ()
Compute the derivation of one layer's length.
virtual void PropagatePathTaylor (NuPath p)
Propagate neutrino through a single path.
virtual void PropagateTaylor ()
Propagate neutrino through full path.
virtual void rotateS ()
Rotate the S matrix.
virtual void rotateK ()
Rotate one K matrix.
virtual void MultiplicationRuleS ()
Product between two S matrices.
virtual void MultiplicationRuleK (Eigen::MatrixXcd &K)
Product between two K matrices.
void SolveK (Eigen::MatrixXcd &K, vectorD &lambda, matrixC &V)
Solve the K matrix for eigenvectors and eigenvalues.
template<typename T >
void TemplateSolver (Eigen::MatrixXcd &K, vectorD &lambda, matrixC &V)
Auxiliary function to choose eigensystem method.
virtual double AvgFormula (int flvi, int flvf, double dbin, vectorD flambda, matrixC fV)
Formula for the average probability over a bin of width dbin.
virtual double AvgFormulaExtrapolation (int flvi, int flvf, double dE, vectorD flambda, matrixC fV)
Formula for the extrapolation of probability.
virtual double AvgAlgo (int flvi, int flvf, double LoE, double dLoE, double L)
virtual double AvgAlgo (int flvi, int flvf, double InvE, double dInvE, double cosT, double dcosT)
virtual double AvgAlgoCosT (int flvi, int flvf, double E, double cosT, double dcosT)
virtual double AlgorithmDensityMatrix (int flvi, int flvf)
Algorithm for the transformations on the density matrix.
virtual void RotateDensityM (bool to_basis, matrixC V)
Apply rotation to the density matrix.
virtual void HadamardProduct (vectorD lambda, double dbin)
Apply an Hadamard Product to the density matrix.
virtual void InitializeVectors ()
virtual bool TryCache ()
Try to find a cached eigensystem.
virtual void SetCurPath (NuPath p)
Set the path currently in use by the class.
virtual void SetAtt (double att, int idx)
Set one of the path attributes.
virtual void SetAtt (vectorD att, int idx)
Set all values of a path attribute.
virtual void RotateH (int i, int j, matrixC &Ham)
Rotate the Hamiltonian by theta_ij and delta_ij.
virtual void RotateState (int i, int j)
Rotate the neutrino state by theta_ij and delta_ij.
virtual void ResetToFlavour (int flv)
Reset neutrino state to pure flavour flv.
virtual void SetPureState (vectorC nu_in)
Set the initial state from a pure state.
virtual void PropagatePath (NuPath p)
Propagate neutrino through a single path.
virtual void Propagate ()
Propagate neutrino through full path.
virtual double P (int flv)
Return the probability of final state in flavour flv.
virtual vectorD GetProbVector ()
virtual std::vector< int > GetSortedIndices (const vectorD x)
Get indices that sort a vector.
virtual vectorD ConvertEtoLoE (double E, double dE)
Protected Attributes
double fM
Lightest neutrino mass.
complexD fEps [3][3]
Stores each NSI parameter.
double fNSIcoup [3]
Relative NSI couplings.
complexD fHam [3][3]
The full hamiltonian.
double fcosT
Cosine of zenith angle.
double fdInvE
Bin's width for the inverse of energy.
double fdcosT
Bin's width for zenith angle.
vectorD flambdaInvE
Eigenvectors of K_invE.
vectorD flambdaCosT
Eigenvectors of K_cosTheta.
matrixC fVInvE
Eigenvalues of K_invE.
Eigen::MatrixXcd fKInvE
K matrix for the inverse of energy for the entire path.
Eigen::MatrixXcd fKcosT
K matrix for neutrino angle for the entire path.
matrixC fevolutionMatrixS
matrixC fVcosT
Eigenvalues of K_cosTheta.
matrixC fSflavor
S matrix for one layer.
matrixC fKmass
K matrix in mass basis for one layer.
matrixC fKflavor
K matrix in flavor basis for one layer.
matrixC fdensityMatrix
The neutrino density matrix state.
int fLayer
Layer index.
int fdl
Length derivative.
double fDetRadius
Detector radius.
double fminRsq
Minimum square radius.
OscProb::PremModel fPrem
Earth model used.
bool fIsOscProbAvg
Flag to call OscProb default or Maltoni average.
int fNumNus
Number of neutrino flavours.
vectorD fDm
m^2_i - m^2_1 in vacuum
matrixD fTheta
theta[i][j] mixing angle
matrixD fDelta
delta[i][j] CP violating phase
vectorC fNuState
The neutrino current state.
matrixC fHms
matrix H*2E in eV^2
vectorC fPhases
Buffer for oscillation phases.
vectorC fBuffer
Buffer for neutrino state tranformations.
vectorD fEval
Eigenvalues of the Hamiltonian.
matrixC fEvec
Eigenvectors of the Hamiltonian.
double fEnergy
Neutrino energy.
bool fIsNuBar
Anti-neutrino flag.
std::vector< NuPath > fNuPaths
Vector of neutrino paths.
NuPath fPath
Current neutrino path.
bool fBuiltHms
Tag to avoid rebuilding Hms.
bool fGotES
Tag to avoid recalculating eigensystem.
bool fUseCache
Flag for whether to use caching.
double fCachePrec
Precision of cache matching.
int fMaxCache
Maximum cache size.
double fAvgProbPrec
AvgProb precision.
std::unordered_set< EigenPoint > fMixCache
Caching set of eigensystems.
EigenPoint fProbe
EigenpPoint to try.
Static Protected Attributes
static const complexD zero
zero in complex
static const complexD one
one in complex
static const double kKm2eV = 1.0 / 1.973269788e-10
km to eV^-1
static const double kK2
mol/GeV^2/cm^3 to eV
static const double kGeV2eV = 1.0e+09
GeV to eV.
static const double kNA = 6.022140857e23
Avogadro constant.
static const double kGf = 1.1663787e-05
G_F in units of GeV^-2.
Detailed Description
This class reimplements the PMNS_NSI class to a scalar NSI scenario.
The matter potential is parametrized by epsilon parameters with dimensions of 1/mass^2 in MeV^-2.
Reference: https://doi.org/10.1103/PhysRevLett.122.211801
See also
PMNS_NSI
Author
jcoelho@apc.in2p3.fr and urahaman@km3net.de
Definition at line 26 of file PMNS_SNSI.h.
Constructor & Destructor Documentation
PMNS_SNSI()
PMNS_SNSI::PMNS_SNSI ()
Constructor.
See also
PMNS_NSI::PMNS_NSI
This class is restricted to 3 neutrino flavours.
Definition at line 19 of file PMNS_SNSI.cxx.
                     : PMNS_NSI()
{
  SetIsOscProbAvg(true);
  SetLowestMass(0);
}
References SetIsOscProbAvg(), and SetLowestMass().
~PMNS_SNSI()
PMNS_SNSI::~PMNS_SNSI () virtual
Nothing to clean.
Definition at line 29 of file PMNS_SNSI.cxx.
{}
Member Function Documentation
AddPath() [1/2]
void PMNS_Base::AddPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Add a path to the sequence defining attributes directly.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 317 of file PMNS_Base.cxx.
{
  AddPath(NuPath(length, density, zoa, layer));
}
References OscProb::PMNS_Base::AddPath().
AddPath() [2/2]
void PMNS_Base::AddPath (NuPath p) virtual inherited
Add a path to the sequence.
Parameters
p - A neutrino path segment
Definition at line 307 of file PMNS_Base.cxx.
{ fNuPaths.push_back(p); }
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::SetAtt(), OscProb::PMNS_Base::SetPath(), and SetTestPath().
AlgorithmDensityMatrix()
double PMNS_Maltoni::AlgorithmDensityMatrix (int flvi, int flvf) protected virtual inherited
Algorithm for the transformations on the density matrix
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
Returns
Average neutrino oscillation probability
Definition at line 1099 of file PMNS_Maltoni.cxx.
{
  fdensityMatrix[flvi][flvi] = 1;
  RotateDensityM(true, fVcosT);
  HadamardProduct(flambdaCosT, fdcosT);
  RotateDensityM(false, fVcosT);
  RotateDensityM(true, fVInvE);
  HadamardProduct(flambdaInvE, fdInvE / kGeV2eV);
  RotateDensityM(false, fVInvE);
  RotateDensityM(false, fevolutionMatrixS);
  return real(fdensityMatrix[flvf][flvf]);
}
References OscProb::PMNS_Maltoni::fdcosT, OscProb::PMNS_Maltoni::fdensityMatrix, OscProb::PMNS_Maltoni::fdInvE, OscProb::PMNS_Maltoni::fevolutionMatrixS, OscProb::PMNS_Maltoni::flambdaCosT, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Maltoni::fVcosT, OscProb::PMNS_Maltoni::fVInvE, OscProb::PMNS_Maltoni::HadamardProduct(), OscProb::PMNS_Base::kGeV2eV, and OscProb::PMNS_Maltoni::RotateDensityM().
Referenced by OscProb::PMNS_Maltoni::AvgAlgo().
AvgAlgo() [1/2]
double PMNS_Maltoni::AvgAlgo (int flvi, int flvf, double InvE, double dInvE, double cosT, double dcosT) protected virtual inherited
Algorithm for the compute of the average probability over a bin of 1oE and cosT
Algorithm for computing the average probability over a bin of 1oE and cosT
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
InvE - The neutrino 1/E value in the bin center in GeV-1
dInvE - The 1/E bin width in GeV-1
cosT - The cosine of the neutrino angle
dcosT - The cosT bin width
Returns
Average neutrino oscillation probability
Definition at line 1065 of file PMNS_Maltoni.cxx.
{
  fPrem.FillPath(cosT);
  SetPath(fPrem.GetNuPath());
  // reset K et S et Ve et lambdaE
  InitializeTaylorsVectors();
  SetEnergy(1 / InvE);
  SetCosT(cosT);
  SetwidthBin(dInvE, dcosT);
  fminRsq = pow(fDetRadius * sqrt(1 - cosT * cosT), 2);
  // Propagate -> get S and K matrix (on the whole path)
  PropagateTaylor();
  // DiagolK -> get VE and lambdaE
  SolveK(fKInvE, flambdaInvE, fVInvE);
  SolveK(fKcosT, flambdaCosT, fVcosT);
  return AlgorithmDensityMatrix(flvi, flvf);
}
References OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::fDetRadius, OscProb::PremModel::FillPath(), OscProb::PMNS_Maltoni::fKcosT, OscProb::PMNS_Maltoni::fKInvE, OscProb::PMNS_Maltoni::flambdaCosT, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Maltoni::fminRsq, OscProb::PMNS_Maltoni::fPrem, OscProb::PMNS_Maltoni::fVcosT, OscProb::PMNS_Maltoni::fVInvE, OscProb::EarthModelBase::GetNuPath(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Maltoni::SetCosT(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Base::SetPath(), OscProb::PMNS_Maltoni::SetwidthBin(), and OscProb::PMNS_Maltoni::SolveK().
AvgAlgo() [2/2]
double PMNS_Maltoni::AvgAlgo (int flvi, int flvf, double LoE, double dLoE, double L) protected virtual inherited
Algorithm for the compute of the average probability over a bin of LoE
Algorithm for the compute of the average probability over a bin of LoE
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
L - The length of the path in km
Returns
Average neutrino oscillation probability
Definition at line 594 of file PMNS_Maltoni.cxx.
{
  // Set width bin as 1/E
  double d1oE = dLoE / L;
  // reset K et S et Ve et lambdaE
  InitializeTaylorsVectors();
  SetEnergy(L / LoE);
  SetwidthBin(d1oE, 0);
  // Propagate -> get S and K matrix (on the whole path)
  PropagateTaylor();
  // DiagolK -> get VE and lambdaE
  SolveK(fKInvE, flambdaInvE, fVInvE);
  // return fct avr proba
  return AvgFormula(flvi, flvf, d1oE / kGeV2eV, flambdaInvE, fVInvE);
}
References OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Maltoni::fKInvE, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Maltoni::fVInvE, OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Maltoni::SetwidthBin(), and OscProb::PMNS_Maltoni::SolveK().
Referenced by OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), and OscProb::PMNS_Maltoni::AvgProbVectorLoE().
AvgAlgoCosT()
double PMNS_Maltoni::AvgAlgoCosT (int flvi, int flvf, double E, double cosT, double dcosT) protected virtual inherited
Algorithm for the compute of the average probability over a bin of cosT
Algorithm for the compute of the average probability over a bin of cosT
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
cosT - The cosine of the neutrino angle
dcosT - The cosT bin width
Returns
Average neutrino oscillation probability
Definition at line 913 of file PMNS_Maltoni.cxx.
{
  // reset K et S et Ve et lambdaE
  InitializeTaylorsVectors();
  SetEnergy(E);
  SetCosT(cosT);
  SetwidthBin(0, dcosT);
  fPrem.FillPath(cosT);
  SetPath(fPrem.GetNuPath());
  fminRsq = pow(fDetRadius * sqrt(1 - cosT * cosT), 2);
  // Propagate -> get S and K matrix (on the whole path)
  PropagateTaylor();
  // DiagolK -> get VE and lambdaE
  SolveK(fKcosT, flambdaCosT, fVcosT);
  // Compute average
  return AvgFormula(flvi, flvf, fdcosT, flambdaCosT, fVcosT);
}
References OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Maltoni::fdcosT, OscProb::PMNS_Maltoni::fDetRadius, OscProb::PremModel::FillPath(), OscProb::PMNS_Maltoni::fKcosT, OscProb::PMNS_Maltoni::flambdaCosT, OscProb::PMNS_Maltoni::fminRsq, OscProb::PMNS_Maltoni::fPrem, OscProb::PMNS_Maltoni::fVcosT, OscProb::EarthModelBase::GetNuPath(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Maltoni::SetCosT(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Base::SetPath(), OscProb::PMNS_Maltoni::SetwidthBin(), and OscProb::PMNS_Maltoni::SolveK().
AvgFormula()
double PMNS_Maltoni::AvgFormula (int flvi, int flvf, double dbin, vectorD lambda, matrixC V) protected virtual inherited
Formula for the average probability of flvi going to flvf over a bin of width dbin using the Maltoni method.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
dbin - The width of the bin
lambda - The eigenvalues of K
V - The eigenvectors of K
Returns
Average neutrino oscillation probability
Definition at line 450 of file PMNS_Maltoni.cxx.
{
  vectorC SV = vectorC(fNumNus, 0);
  for (int i = 0; i < fNumNus; i++) {
    for (int k = 0; k < fNumNus; k++) {
      SV[i] += fevolutionMatrixS[flvf][k] * V[k][i];
    }
  }
  complexD buffer[fNumNus];
  for (int n = 0; n < fNumNus; n++) { buffer[n] = SV[n] * conj(V[flvi][n]); }
  complexD sinc[fNumNus][fNumNus];
  for (int j = 0; j < fNumNus; j++) {
    sinc[j][j] = 1;
    for (int i = 0; i < j; i++) {
      double arg = (lambda[i] - lambda[j]) * dbin / 2;
      sinc[i][j] = sin(arg) / arg;
      sinc[j][i] = sinc[i][j];
    }
  }
  complexD P = 0;
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i < fNumNus; i++) {
      P += buffer[i] * conj(buffer[j]) * sinc[j][i];
    }
  }
  return real(P);
}
References OscProb::PMNS_Maltoni::fevolutionMatrixS, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::P().
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), and OscProb::PMNS_Maltoni::AvgProbVectorLoE().
AvgFormulaExtrapolation()
double PMNS_Maltoni::AvgFormulaExtrapolation (int flvi, int flvf, double dE, vectorD lambda, matrixC V) protected virtual inherited
Fomula for the propability for flvi going to flvf for an energy E+dE using the Maltoni method from a reference energy E.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
dE - The energy variation in GeV
lambda - The eigenvalues of K
V - The eigenvectors of K
Returns
Neutrino oscillation probability
Definition at line 1289 of file PMNS_Maltoni.cxx.
{
  vectorC SV = vectorC(fNumNus, 0);
  for (int i = 0; i < fNumNus; i++) {
    for (int k = 0; k < fNumNus; k++) {
      SV[i] += fevolutionMatrixS[flvf][k] * V[k][i];
    }
  }
  complexD buffer[fNumNus];
  for (int n = 0; n < fNumNus; n++) { buffer[n] = SV[n] * conj(V[flvi][n]); }
  complexD expo[fNumNus][fNumNus];
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i < fNumNus; i++) {
      double arg = (lambda[j] - lambda[i]) * dE;
      expo[j][i] = exp(complexD(0.0, arg));
    }
  }
  complexD P = 0;
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i < fNumNus; i++) {
      P += buffer[i] * conj(buffer[j]) * expo[j][i];
    }
  }
  return real(P);
}
References OscProb::PMNS_Maltoni::fevolutionMatrixS, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::P().
Referenced by OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), and OscProb::PMNS_Maltoni::ExtrapolationProbLoE().
AvgProb() [1/5]
double PMNS_Maltoni::AvgProb (int flvi, int flvf, double E, double cosT, double dcosT) virtual inherited
Compute the average probability over a bin of cosTheta with a Taylor expansion
Compute the average probability of flvi going to flvf over a bin of angle cost with width dcosT using the Maltoni method.
IMPORTANT: The PremModel object used must be set by this class using the function SetPremModel.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
cosT - The cosine of the neutrino angle
dcosT - The cosT bin width
Returns
Average neutrino oscillation probability
Definition at line 876 of file PMNS_Maltoni.cxx.
{
  // reset K et S et Ve et lambdaE
  InitializeTaylorsVectors();
  SetEnergy(E);
  SetCosT(cosT);
  SetwidthBin(0, dcosT);
  fPrem.FillPath(cosT);
  SetPath(fPrem.GetNuPath());
  fminRsq = pow(fDetRadius * sqrt(1 - cosT * cosT), 2);
  // Propagate -> get S and K matrix (on the whole path)
  PropagateTaylor();
  // DiagolK -> get VE and lambdaE
  SolveK(fKcosT, flambdaCosT, fVcosT);
  // Compute average
  return AvgFormula(flvi, flvf, fdcosT, flambdaCosT, fVcosT);
}
References OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Maltoni::fdcosT, OscProb::PMNS_Maltoni::fDetRadius, OscProb::PremModel::FillPath(), OscProb::PMNS_Maltoni::fKcosT, OscProb::PMNS_Maltoni::flambdaCosT, OscProb::PMNS_Maltoni::fminRsq, OscProb::PMNS_Maltoni::fPrem, OscProb::PMNS_Maltoni::fVcosT, OscProb::EarthModelBase::GetNuPath(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Maltoni::SetCosT(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Base::SetPath(), OscProb::PMNS_Maltoni::SetwidthBin(), and OscProb::PMNS_Maltoni::SolveK().
AvgProb() [2/5]
double PMNS_Maltoni::AvgProb (int flvi, int flvf, double E, double dE) virtual inherited
Compute the average probability over a bin of energy with a Taylor expansion
Compute the average probability of flvi going to flvf over a bin of energy E with width dE using the Maltoni method.
This gets transformed into L/E, since the oscillation terms have arguments linear in 1/E and not E.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Reimplemented from OscProb::PMNS_Base.
Definition at line 507 of file PMNS_Maltoni.cxx.
{
  if (fIsOscProbAvg == true) return PMNS_Base::AvgProb(flvi, flvf, E, dE);
  // Do nothing if energy not positive
  if (E <= 0) return 0;
  if (fNuPaths.empty()) return 0;
  // Don't average zero width
  if (dE <= 0) return Prob(flvi, flvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbLoE(flvi, flvf, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Maltoni::fIsOscProbAvg, OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::Prob().
Referenced by OscProb::PMNS_Maltoni::AvgProb(), and OscProb::PMNS_Maltoni::AvgProbLoE().
AvgProb() [3/5]
double PMNS_Maltoni::AvgProb (int flvi, int flvf, double E, double dE, double cosT, double dcosT) virtual inherited
Compute the average probabilit over a bin of cosTheta and energy with a Taylor expansion
Compute the average probability of flvi going to flvf over a bin of energy E and angle cosT with width dE and dcosT using the Maltoni method.
IMPORTANT: The PremModel object used must be set by this class using the function SetPremModel.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
dE - The energy bin width in GeV
cosT - The cosine of the neutrino angle
dcosT - The cosT bin width
Returns
Average neutrino oscillation probability
Definition at line 961 of file PMNS_Maltoni.cxx.
{
  if (E <= 0) return 0;
  if (cosT > 0) return 0;
  if (fNuPaths.empty()) return 0;
  // Don't average zero width
  if (dE <= 0 && dcosT == 0) return Prob(flvi, flvf, E);
  if (dE <= 0) return AvgProb(flvi, flvf, E, cosT, dcosT);
  if (dcosT == 0) return AvgProb(flvi, flvf, E, dE);
  vectorD Ebin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbLoE(flvi, flvf, Ebin[0], Ebin[1], cosT, dcosT);
}
References OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::Prob().
AvgProb() [4/5]
double PMNS_Base::AvgProb (int flvi, int flvf, double E, double dE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Reimplemented from OscProb::PMNS_Base.
Definition at line 98 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProb(fNuState, flvf, E, dE);
}
AvgProb() [5/5]
double PMNS_Base::AvgProb (vectorC nu_in, int flvf, double E, double dE = 0) virtual inherited
Compute the average probability of nu_in going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Reimplemented from OscProb::PMNS_Base.
Definition at line 88 of file PMNS_Base.cxx.
{
  // Do nothing if energy is not positive
  if (E <= 0) return 0;
  if (fNuPaths.empty()) return 0;
  // Don't average zero width
  if (dE <= 0) return Prob(nu_in, flvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbLoE(nu_in, flvf, LoEbin[0], LoEbin[1]);
}
AvgProbLoE() [1/4]
double PMNS_Maltoni::AvgProbLoE (int flvi, int flvf, double LoE, double dLoE) virtual inherited
Compute the average probability over a bin of LoE with a Taylor expansion
Compute the average probability of flvi going to flvf over a bin of energy L/E with width dLoE using the Maltoni method.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Reimplemented from OscProb::PMNS_Base.
Definition at line 548 of file PMNS_Maltoni.cxx.
{
  if (fIsOscProbAvg == true)
    return PMNS_Base::AvgProbLoE(flvi, flvf, LoE, dLoE);
  if (LoE <= 0) return 0;
  if (fNuPaths.empty()) return 0;
  // Don't average zero width
  if (dLoE <= 0) return Prob(flvi, flvf, fPath.length / LoE);
  // Get sample points for this bin
  vectorD samples = GetSamplePointsAvgClass(LoE, dLoE);
  double avgprob = 0;
  double L       = fPath.length;
  double sumw    = 0;
  // Loop over all sample points
  for (int j = 1; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    avgprob += w * AvgAlgo(flvi, flvf, samples[j], samples[0], L);
    // Increment sum of weights
    sumw += w;
  }
  // Return weighted average of probabilities
  return avgprob / sumw;
}
References OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Maltoni::fIsOscProbAvg, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Maltoni::GetSamplePointsAvgClass(), OscProb::NuPath::length, and OscProb::PMNS_Base::Prob().
Referenced by OscProb::PMNS_Maltoni::AvgProb(), and OscProb::PMNS_Maltoni::AvgProbLoE().
AvgProbLoE() [2/4]
double PMNS_Maltoni::AvgProbLoE (int flvi, int flvf, double LoE, double dLoE, double cosT, double dcosT) virtual inherited
Compute the average probability over a bin of cosTheta and LoE with a Taylor expansion
Compute the average probability of flvi going to flvf over a bin of energy L/E and cosT with width dLoE and dcosT using the Maltoni method.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
IMPORTANT: The PremModel object used must be set by this class using the function SetPremModel.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
cosT - The cosine of the neutrino angle
dcosT - The cosT bin width
Returns
Average neutrino oscillation probability
chg ici
Definition at line 1008 of file PMNS_Maltoni.cxx.
{
  if (LoE <= 0) return 0;
  if (cosT > 0) return 0;
  // if (fNuPaths.empty()) return 0;
  // Don't average zero width
  if (dLoE <= 0 && dcosT == 0) return Prob(flvi, flvf, fPath.length / LoE);
  if (dLoE <= 0)
    return AvgProb(flvi, flvf, fPath.length / LoE, cosT, dcosT);
  if (dcosT == 0) return AvgProbLoE(flvi, flvf, LoE, dLoE);
  // Make sample with 1oE and not LoE
  matrixC samples = GetSamplePointsAvgClass(LoE / fPath.length,
                                            dLoE / fPath.length, cosT, dcosT);
  int rows = samples.size();
  int cols = samples[0].size();
  double avgprob = 0;
  double sumw    = 0;
  // Loop over all sample points
  for (int k = 1; k < int(rows); k++) {
    for (int l = 1; l < int(cols); l++) {
      // Set (L/E)^-2 weights
      double w = 1. / pow(real(samples[k][l]), 2);
      avgprob +=
          w * AvgAlgo(flvi, flvf, real(samples[k][l]), real(samples[0][0]),
                      imag(samples[k][l]), imag(samples[0][0]));
      // Increment sum of weights
      sumw += w;
    }
  }
  // Return average of probabilities
  return avgprob / ((sumw));
}
References OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Base::fPath, OscProb::PMNS_Maltoni::GetSamplePointsAvgClass(), OscProb::NuPath::length, and OscProb::PMNS_Base::Prob().
AvgProbLoE() [3/4]
double PMNS_Base::AvgProbLoE (int flvi, int flvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Reimplemented from OscProb::PMNS_Base.
Definition at line 102 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbLoE(fNuState, flvf, LoE, dLoE);
}
AvgProbLoE() [4/4]
double PMNS_Base::AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of nu_in going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino intial state in flavour basis.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Reimplemented from OscProb::PMNS_Base.
Definition at line 92 of file PMNS_Base.cxx.
{
  // Do nothing if L/E is not positive
  if (LoE <= 0) return 0;
  if (fNuPaths.empty()) return 0;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length / LoE);
  // Don't average zero width
  if (dLoE <= 0) return Prob(nu_in, flvf);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw   = 0;
  double prob   = 0;
  double length = fPath.length;
  // Loop over all sample points
  for (int j = 0; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    // Add weighted probability
    prob += w * Prob(nu_in, flvf, length / samples[j]);
    // Increment sum of weights
    sumw += w;
  }
  // Return weighted average of probabilities
  return prob / sumw;
}
AvgProbMatrix()
matrixD PMNS_Maltoni::AvgProbMatrix (int nflvi, int nflvf, double E, double dE) virtual inherited
Compute the average probability matrix over a bin of energy using a Taylor expansion
Compute the average probability matrix for nflvi and nflvf over a bin of energy E with width dE using the Maltoni method.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Reimplemented from OscProb::PMNS_Base.
Definition at line 767 of file PMNS_Maltoni.cxx.
{
  if (fIsOscProbAvg == true)
    return PMNS_Base::AvgProbMatrix(nflvi, nflvf, E, dE);
  matrixD probs(nflvi, vectorD(nflvf, 0));
  // Do nothing if energy is not positive
  if (E <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Don't average zero width
  if (dE <= 0) return ProbMatrix(nflvi, nflvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbMatrixLoE(nflvi, nflvf, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Maltoni::fIsOscProbAvg, OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::ProbMatrix().
AvgProbMatrixLoE()
matrixD PMNS_Maltoni::AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE) virtual inherited
Compute the average probability matrix over a bin of L/E using a Taylor expansion
Compute the average probability matrix for nflvi and nflvf over a bin of L/E with width dLoE using the Maltoni method.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Reimplemented from OscProb::PMNS_Base.
Definition at line 800 of file PMNS_Maltoni.cxx.
{
  if (fIsOscProbAvg == true)
    return PMNS_Base::AvgProbMatrixLoE(nflvi, nflvf, LoE, dLoE);
  matrixD probs(nflvi, vectorD(nflvf, 0));
  if (LoE <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  double L = fPath.length;
  // Don't average zero width
  if (dLoE <= 0) return ProbMatrix(nflvi, nflvf, L / LoE);
  // Get sample points for this bin
  vectorD samples = GetSamplePointsAvgClass(LoE, dLoE);
  double sumw = 0;
  // Loop over all sample points
  for (int j = 1; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    for (int flvi = 0; flvi < nflvi; flvi++) {
      for (int flvf = 0; flvf < nflvf; flvf++) {
        // if (!TryCacheK())
        if (flvi == 0 && flvf == 0)
          probs[flvi][flvf] +=
              w * AvgAlgo(flvi, flvf, samples[j], samples[0], L);
        else
          probs[flvi][flvf] +=
              w * AvgFormula(flvi, flvf, fdInvE / kGeV2eV, flambdaInvE, fVInvE);
      }
    }
    // Increment sum of weights
    sumw += w;
  }
  for (int flvi = 0; flvi < nflvi; flvi++) {
    for (int flvf = 0; flvf < nflvf; flvf++) {
      // Divide by total sampling weight
      probs[flvi][flvf] /= sumw;
    }
  }
  // Return weighted average of probabilities
  return probs;
}
References OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::fdInvE, OscProb::PMNS_Maltoni::fIsOscProbAvg, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Maltoni::fVInvE, OscProb::PMNS_Maltoni::GetSamplePointsAvgClass(), OscProb::PMNS_Base::kGeV2eV, OscProb::NuPath::length, and OscProb::PMNS_Base::ProbMatrix().
Referenced by OscProb::PMNS_Maltoni::AvgProbMatrix().
AvgProbVector() [1/2]
vectorD PMNS_Maltoni::AvgProbVector (int flvi, double E, double dE) virtual inherited
Compute the average probability vector over a bin of energy using a Taylor expansion
Compute the average probability of flvi going to any flavour over a bin of energy E with width dE using the Maltoni method.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
dE - The energy bin width in GeV
Returns
Average probability for all outgoing flavours
Reimplemented from OscProb::PMNS_Base.
Definition at line 671 of file PMNS_Maltoni.cxx.
{
  if (fIsOscProbAvg == true) return PMNS_Base::AvgProbVector(flvi, E, dE);
  vectorD probs(fNumNus, 0);
  // Do nothing if energy is not positive
  if (E <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Don't average zero width
  if (dE <= 0) return ProbVector(flvi, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbVectorLoE(flvi, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Maltoni::fIsOscProbAvg, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::ProbVector().
AvgProbVector() [2/2]
vectorD PMNS_Base::AvgProbVector (vectorC nu_in, double E, double dE = 0) virtual inherited
Compute the average probability vector over a bin of energy
Compute the average probability of nu_in going to all flavours over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
nu_in - The neutrino initial state in flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1753 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if energy is not positive
  if (E <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Don't average zero width
  if (dE <= 0) return ProbVector(nu_in, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbVectorLoE(nu_in, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::ProbVector().
Referenced by OscProb::PMNS_Maltoni::AvgProbVector(), and OscProb::PMNS_Base::AvgProbVector().
AvgProbVectorLoE() [1/2]
vectorD PMNS_Maltoni::AvgProbVectorLoE (int flvi, double LoE, double dLoE) virtual inherited
Compute the average probability vector over a bin of L/E using a Taylor expansion
Compute the average probability of flvi going to any flavour over a bin of L/E with width dLoE using the Maltoni method.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average probability for all outgoing flavours
Reimplemented from OscProb::PMNS_Base.
Definition at line 708 of file PMNS_Maltoni.cxx.
{
  if (fIsOscProbAvg == true)
    return PMNS_Base::AvgProbVectorLoE(flvi, LoE, dLoE);
  vectorD probs(fNumNus, 0);
  if (LoE <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  double L = fPath.length;
  // Don't average zero width
  if (dLoE <= 0) return ProbVector(flvi, L / LoE);
  // Get sample points for this bin
  vectorD samples = GetSamplePointsAvgClass(LoE, dLoE);
  double sumw = 0;
  // Loop over all sample points
  for (int j = 1; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    for (int flvf = 0; flvf < fNumNus; flvf++) {
      if (flvf == 0)
        probs[flvf] += w * AvgAlgo(flvi, flvf, samples[j], samples[0], L);
      else
        probs[flvf] +=
            w * AvgFormula(flvi, flvf, fdInvE / kGeV2eV, flambdaInvE, fVInvE);
    }
    // Increment sum of weights
    sumw += w;
  }
  for (int flvf = 0; flvf < fNumNus; flvf++) {
    // Divide by total sampling weight
    probs[flvf] /= sumw;
  }
  // Return weighted average of probabilities
  return probs;
}
References OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Maltoni::fdInvE, OscProb::PMNS_Maltoni::fIsOscProbAvg, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Maltoni::fVInvE, OscProb::PMNS_Maltoni::GetSamplePointsAvgClass(), OscProb::PMNS_Base::kGeV2eV, OscProb::NuPath::length, and OscProb::PMNS_Base::ProbVector().
Referenced by OscProb::PMNS_Maltoni::AvgProbVector().
AvgProbVectorLoE() [2/2]
vectorD PMNS_Base::AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of nu_in going to all flavours over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
nu_in - The neutrino intial state in flavour basis.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Definition at line 1791 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if L/E is not positive
  if (LoE <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length / LoE);
  // Don't average zero width
  if (dLoE <= 0) return ProbVector(nu_in);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw   = 0;
  double length = fPath.length;
  // Loop over all sample points
  for (int j = 0; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    vectorD sample_probs = ProbVector(nu_in, length / samples[j]);
    for (int i = 0; i < fNumNus; i++) {
      // Add weighted probability
      probs[i] += w * sample_probs[i];
    }
    // Increment sum of weights
    sumw += w;
  }
  for (int i = 0; i < fNumNus; i++) {
    // Divide by total sampling weight
    probs[i] /= sumw;
  }
  // Return weighted average of probabilities
  return probs;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), and OscProb::PMNS_Base::AvgProbVectorLoE().
BuildHms()
void PMNS_SNSI::BuildHms () protected virtual
Reimplement vacuum Hms update
See also
PMNS_Base::BuildHms
Reimplemented from OscProb::PMNS_Base.
Definition at line 59 of file PMNS_SNSI.cxx.
{
  // Check if anything changed
  if (fBuiltHms) return;
  // Tag to recompute eigensystem
  fGotES = false;
  // Start with m1 = fM
  double m1 = fM;
  // Make sure all masses are larger than fM
  for (int i = 1; i < fNumNus; i++) {
    if (fDm[i] + m1 * m1 < fM * fM) m1 = sqrt(fabs(fM * fM - fDm[i]));
  }
  // Build M - m1
  fHms[0][0] = 0;
  for (int j = 1; j < fNumNus; j++) {
    // Set mass difference m_j - m_1
    fHms[j][j] = sqrt(fabs(fDm[j] + m1 * m1)) - m1;
    // Reset off-diagonal elements
    for (int i = 0; i < j; i++) { fHms[i][j] = 0; }
    // Rotate j neutrinos
    for (int i = 0; i < j; i++) { RotateH(i, j, fHms); }
  }
  // Add back m1
  for (int i = 0; i < fNumNus; i++) { fHms[i][i] += m1; }
  // Tag as built
  fBuiltHms = true;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fHms, fM, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::RotateH().
BuildKcosT()
void PMNS_Maltoni::BuildKcosT () protected virtual inherited
Build K matrix for the zenith angle in flavor basis.
Definition at line 111 of file PMNS_Maltoni.cxx.
{
  UpdateHam();
  double dL = LnDerivative() * kKm2eV;
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i <= j; i++) {
      fKflavor[i][j] = dL * fHam(i, j);
      if (i != j) { fKflavor[j][i] = conj(fKflavor[i][j]); }
    }
  }
}
References OscProb::PMNS_Maltoni::fHam, OscProb::PMNS_Maltoni::fKflavor, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::kKm2eV, OscProb::PMNS_Maltoni::LnDerivative(), and OscProb::PMNS_Maltoni::UpdateHam().
Referenced by OscProb::PMNS_Maltoni::PropagatePathTaylor().
BuildKE()
void PMNS_Maltoni::BuildKE (double L) protected virtual inherited
Build K matrix for the inverse of energy in mass basis.
The variable for which a Taylor expansion is done here is not directly the energy but the inverse of it. This change of variable allow to express the hamiltonien as linear with respect to this new variable.
Parameters
L - The length of the layer in km
Definition at line 136 of file PMNS_Maltoni.cxx.
{
  double lenghtEV = L * kKm2eV;     // L in eV-1
  double bufK     = lenghtEV * 0.5; // L/2 in eV-1
  complexD buffer[fNumNus];
  for (int i = 0; i < fNumNus; i++) {
    complexD Hms_kl;
    for (int l = 0; l < fNumNus; l++) {
      buffer[l] = 0;
      for (int k = 0; k < fNumNus; k++) {
        if (k <= l)
          Hms_kl = fHms[k][l];
        else
          Hms_kl = conj(fHms[l][k]);
        if (fIsNuBar && k != l) Hms_kl = conj(Hms_kl);
        buffer[l] += conj(fEvec[k][i]) * Hms_kl;
      }
    }
    for (int j = 0; j <= i; j++) {
      fKmass[i][j] = 0;
      for (int l = 0; l < fNumNus; l++) {
        fKmass[i][j] += buffer[l] * fEvec[l][j];
      }
      complexD C;
      if (i == j) { C = complexD(1, 0); }
      else {
        double arg = (fEval[i] - fEval[j]) * lenghtEV;
        C = (complexD(cos(arg), sin(arg)) - complexD(1, 0.0)) /
            complexD(0.0, arg);
      }
      fKmass[i][j] *= bufK * C;
      if (i != j) fKmass[j][i] = conj(fKmass[i][j]);
    }
  }
}
References OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Maltoni::fKmass, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::kKm2eV.
Referenced by OscProb::PMNS_Maltoni::PropagatePathTaylor().
ClearCache()
void PMNS_Base::ClearCache () virtual inherited
Clear the cache
Definition at line 111 of file PMNS_Base.cxx.
{
  fMixCache.clear();
  // Set some better hash table parameters
  fMixCache.max_load_factor(0.25);
  fMixCache.reserve(512);
}
References OscProb::PMNS_Base::fMixCache.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_NUNM::SetAlpha(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_NSI::SetEps(), and OscProb::PMNS_NUNM::SetFracVnc().
ClearPath()
void PMNS_Base::ClearPath () virtual inherited
Clear the path vector.
Definition at line 287 of file PMNS_Base.cxx.
{ fNuPaths.clear(); }
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
ConvertEtoLoE()
vectorD PMNS_Base::ConvertEtoLoE (double E, double dE) protected virtual inherited
Convert a bin of energy into a bin of L/E
Parameters
E - energy bin center in GeV
dE - energy bin width in GeV
Returns
The L/E bin center and width in km/GeV
Definition at line 1516 of file PMNS_Base.cxx.
{
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Define L/E variables
  vectorD LoEbin(2);
  // Set a minimum energy
  double minE = 0.1 * E;
  // Transform range to L/E
  // Full range if low edge > minE
  if (E - dE / 2 > minE) {
    LoEbin[0] =
        0.5 * (fPath.length / (E - dE / 2) + fPath.length / (E + dE / 2));
    LoEbin[1] = fPath.length / (E - dE / 2) - fPath.length / (E + dE / 2);
  }
  // Else start at minE
  else {
    LoEbin[0] = 0.5 * (fPath.length / minE + fPath.length / (E + dE / 2));
    LoEbin[1] = fPath.length / minE - fPath.length / (E + dE / 2);
  }
  return LoEbin;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::NuPath::length, and OscProb::PMNS_Base::SetCurPath().
Referenced by OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Maltoni::AvgProbMatrix(), OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Maltoni::AvgProbVector(), and OscProb::PMNS_Base::AvgProbVector().
ExtrapolationProb()
double PMNS_Maltoni::ExtrapolationProb (int flvi, int flvf, double E, double dE) virtual inherited
Compute the propability for flvi going to flvf for an energy E+dE using the Maltoni method from a reference energy E.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The reference energy in GeV
dE - The energy variation in GeV
Returns
Neutrino oscillation probability
Definition at line 1341 of file PMNS_Maltoni.cxx.
{
  // reset K et S et Ve et lambdaE
  InitializeTaylorsVectors();
  SetEnergy(E);
  SetwidthBin(1 / (E + dE) - 1 / E, 0);
  // Propagate -> get S and K matrix (on the whole path)
  PropagateTaylor();
  // DiagolK -> get VE and lambdaE
  SolveK(fKInvE, flambdaInvE, fVInvE);
  return AvgFormulaExtrapolation(flvi, flvf, fdInvE / kGeV2eV, flambdaInvE,
                                 fVInvE);
}
References OscProb::PMNS_Maltoni::AvgFormulaExtrapolation(), OscProb::PMNS_Maltoni::fdInvE, OscProb::PMNS_Maltoni::fKInvE, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Maltoni::fVInvE, OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Maltoni::SetwidthBin(), and OscProb::PMNS_Maltoni::SolveK().
ExtrapolationProbCosT()
double PMNS_Maltoni::ExtrapolationProbCosT (int flvi, int flvf, double cosT, double dcosT) virtual inherited
Compute the propability for flvi going to flvf for an angle cosT+dcosT using the Maltoni method from a reference angle cosT.
IMPORTANT: The PremModel object used must be set by this class using the function SetPremModel.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
cosT - The reference angle
dcosT - The angle variation
Returns
Neutrino oscillation probability
Definition at line 1420 of file PMNS_Maltoni.cxx.
{
  fPrem.FillPath(cosT);
  SetPath(fPrem.GetNuPath());
  // reset K et S et Ve et lambdaE
  InitializeTaylorsVectors();
  // SetEnergy(E);
  SetCosT(cosT);
  SetwidthBin(0, dcosT);
  fminRsq = pow(fDetRadius * sqrt(1 - cosT * cosT), 2);
  // Propagate -> get S and K matrix (on the whole path)
  PropagateTaylor();
  // DiagolK -> get VE and lambdaE
  SolveK(fKcosT, flambdaCosT, fVcosT);
  return AvgFormulaExtrapolation(flvi, flvf, fdcosT, flambdaCosT, fVcosT);
}
References OscProb::PMNS_Maltoni::AvgFormulaExtrapolation(), OscProb::PMNS_Maltoni::fdcosT, OscProb::PMNS_Maltoni::fDetRadius, OscProb::PremModel::FillPath(), OscProb::PMNS_Maltoni::fKcosT, OscProb::PMNS_Maltoni::flambdaCosT, OscProb::PMNS_Maltoni::fminRsq, OscProb::PMNS_Maltoni::fPrem, OscProb::PMNS_Maltoni::fVcosT, OscProb::EarthModelBase::GetNuPath(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Maltoni::SetCosT(), OscProb::PMNS_Base::SetPath(), OscProb::PMNS_Maltoni::SetwidthBin(), and OscProb::PMNS_Maltoni::SolveK().
ExtrapolationProbLoE()
double PMNS_Maltoni::ExtrapolationProbLoE (int flvi, int flvf, double LoE, double dLoE) virtual inherited
Compute the propability for flvi going to flvf for an energy LoE+dLoE using the Maltoni method from a reference value LoE.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The reference energy in GeV
dLoE - The energy variation in GeV
Returns
Neutrino oscillation probability
Definition at line 1377 of file PMNS_Maltoni.cxx.
{
  // reset K et S et Ve et lambdaE
  InitializeTaylorsVectors();
  SetCurPath(AvgPath(fNuPaths));
  double L = fPath.length;
  SetEnergy(L / LoE);
  SetwidthBin(dLoE / L, 0);
  // Propagate -> get S and K matrix (on the whole path)
  PropagateTaylor();
  // DiagolK -> get VE and lambdaE
  SolveK(fKInvE, flambdaInvE, fVInvE);
  return AvgFormulaExtrapolation(flvi, flvf, dLoE * kGeV2eV / L, flambdaInvE,
                                 fVInvE);
}
References OscProb::PMNS_Maltoni::AvgFormulaExtrapolation(), OscProb::AvgPath(), OscProb::PMNS_Maltoni::fKInvE, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Maltoni::fVInvE, OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Base::kGeV2eV, OscProb::NuPath::length, OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Maltoni::SetwidthBin(), and OscProb::PMNS_Maltoni::SolveK().
FillCache()
virtual void OscProb::PMNS_SNSI::FillCache () inline protected virtual
Reimplemented from OscProb::PMNS_Base.
Definition at line 44 of file PMNS_SNSI.h.
GetAngle()
double PMNS_Base::GetAngle (int i, int j) virtual inherited
Get the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of theta_ij
Definition at line 570 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Theta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fTheta[i - 1][j - 1];
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
GetDelta()
double PMNS_Base::GetDelta (int i, int j) virtual inherited
Get the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of delta_ij
Definition at line 638 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Delta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  if (i + 1 == j) {
    cerr << "WARNING: Rotation " << i << j << " is real. Returning zero."
         << endl;
    return 0;
  }
  return fDelta[i - 1][j - 1];
}
References OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
GetDm()
double PMNS_Base::GetDm (int j) virtual inherited
Get the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 696 of file PMNS_Base.cxx.
{
  if (j < 2 || j > fNumNus) {
    cerr << "ERROR: Dm" << j << "1 not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fDm[j - 1];
}
References OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
GetDmEff()
double PMNS_Base::GetDmEff (int j) virtual inherited
Get the effective mass-splitting dm_j1 in matter in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 732 of file PMNS_Base.cxx.
{
  if (j < 2 || j > fNumNus) {
    cerr << "ERROR: Dm_" << j << "1 not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  // Solve the Hamiltonian to update eigenvalues
  SolveHam();
  // Sort eigenvalues in same order as vacuum Dm^2
  vectorI dm_idx = GetSortedIndices(fDm);
  vectorD dm_idx_double(dm_idx.begin(), dm_idx.end());
  dm_idx         = GetSortedIndices(dm_idx_double);
  vectorI ev_idx = GetSortedIndices(fEval);
  // Return difference in eigenvalues * 2E
  return (fEval[ev_idx[dm_idx[j - 1]]] - fEval[ev_idx[dm_idx[0]]]) * 2 *
         fEnergy * kGeV2eV;
}
References OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::GetSortedIndices(), OscProb::PMNS_Base::kGeV2eV, and OscProb::PMNS_Base::SolveHam().
GetDownCoup()
double PMNS_NSI::GetDownCoup () virtual inherited
Get the NSI relative coupling to d-quarks.
Definition at line 335 of file PMNS_NSI.cxx.
{ return fNSIcoup[2]; }
References OscProb::PMNS_NSI::fNSIcoup.
GetElecCoup()
double PMNS_NSI::GetElecCoup () virtual inherited
Get the NSI relative coupling to electrons.
Definition at line 323 of file PMNS_NSI.cxx.
{ return fNSIcoup[0]; }
References OscProb::PMNS_NSI::fNSIcoup.
GetEnergy()
double PMNS_Base::GetEnergy () virtual inherited
Get the neutrino energy in GeV.
Definition at line 255 of file PMNS_Base.cxx.
{ return fEnergy; }
References OscProb::PMNS_Base::fEnergy.
GetEps()
complexD PMNS_NSI::GetEps (int flvi, int flvj) virtual inherited
Get any given NSI parameter.
Flavours are:
0 = nue, 1 = numu, 2 = nutau
Requires that flvi < flvj. Will notify you if input is wrong. If flvi > flvj, will assume reverse order and swap flvi and flvj.
Parameters
flvi - The first flavour index
flvj - The second flavour index
Definition at line 129 of file PMNS_NSI.cxx.
{
  if (flvi > flvj) {
    cerr << "WARNING: First argument should be smaller or equal to second "
            "argument"
         << endl
         << "Setting reverse order (Eps_" << flvj << flvi << "). " << endl;
    int temp = flvi;
    flvi     = flvj;
    flvj     = temp;
  }
  if (flvi < 0 || flvi > 2 || flvj < flvi || flvj > 2) {
    cerr << "WARNING: Eps_" << flvi << flvj << " not valid for " << fNumNus
         << " neutrinos. Returning 0." << endl;
    return zero;
  }
  return fEps[flvi][flvj];
}
References OscProb::PMNS_NSI::fEps, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::zero.
GetIsNuBar()
bool PMNS_Base::GetIsNuBar () virtual inherited
Get the anti-neutrino flag.
Definition at line 261 of file PMNS_Base.cxx.
{ return fIsNuBar; }
References OscProb::PMNS_Base::fIsNuBar.
GetLowestMass()
double PMNS_SNSI::GetLowestMass () virtual
Get lightest neutrino mass
Returns
The lightest mass in eV
Definition at line 51 of file PMNS_SNSI.cxx.
{ return fM; }
References fM.
GetMassEigenstate()
vectorC PMNS_Base::GetMassEigenstate (int mi) virtual inherited
Get the neutrino mass eigenstate in vacuum
States are:
  0 = m_1, 1 = m_2, 2 = m_3, etc.
Parameters
mi - the mass eigenstate index
Returns
The mass eigenstate
Definition at line 795 of file PMNS_Base.cxx.
{
  vectorC oldState = fNuState;
  ResetToFlavour(mi);
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i < j; i++) { RotateState(i, j); }
  }
  vectorC newState = fNuState;
  fNuState         = oldState;
  return newState;
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_Base::RotateState().
GetPath()
vector< NuPath > PMNS_Base::GetPath () virtual inherited
Get the vector of neutrino paths.
Definition at line 300 of file PMNS_Base.cxx.
{ return fNuPaths; }
References OscProb::PMNS_Base::fNuPaths.
GetProbVector()
vectorD PMNS_Base::GetProbVector () protected virtual inherited
Return vector of probabilities from final state
Get the vector of probabilities for current state
Returns
Neutrino oscillation probabilities
Definition at line 1233 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus);
  for (int i = 0; i < probs.size(); i++) { probs[i] = P(i); }
  return probs;
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::P().
Referenced by OscProb::PMNS_Base::ProbVector().
GetSamplePoints()
vectorD PMNS_Base::GetSamplePoints (double LoE, double dLoE) virtual inherited
Compute the sample points for a bin of L/E with width dLoE
This is used for averaging the probability over a bin of L/E. It should be a private function, but I'm keeping it public for now for debugging purposes. The number of sample points seems too high for most purposes. The number of subdivisions needs to be optimized.
Parameters
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Definition at line 1985 of file PMNS_Base.cxx.
{
  // Solve Hamiltonian to get eigenvalues
  SolveHam();
  // Define conversion factor [km/GeV -> 1/(4 eV^2)]
  const double k1267 = kKm2eV / (4 * kGeV2eV);
  // Get list of all effective Dm^2
  vectorD effDm;
  for (int i = 0; i < fNumNus - 1; i++) {
    for (int j = i + 1; j < fNumNus; j++) {
      effDm.push_back(2 * kGeV2eV * fEnergy * fabs(fEval[j] - fEval[i]));
    }
  }
  int numDm = effDm.size();
  // Sort the effective Dm^2 list
  sort(effDm.begin(), effDm.end());
  // Set a number of sub-divisions to achieve "good" accuracy
  // This needs to be studied better
  int n_div = ceil(200 * pow(dLoE / LoE, 0.8) / sqrt(fAvgProbPrec / 1e-4));
  // int n_div = 1;
  // A vector to store sample points
  vectorD allSamples;
  // Loop over sub-divisions
  for (int k = 0; k < n_div; k++) {
    // Define sub-division center and width
    double bctr = LoE - dLoE / 2 + (k + 0.5) * dLoE / n_div;
    double bwdt = dLoE / n_div;
    // Make a vector of L/E sample values
    // Initialized in the sub-division center
    vectorD samples;
    samples.push_back(bctr);
    // Loop over all Dm^2 to average each frequency
    // This will recursively sample points in smaller
    // bins so that all relevant frequencies are used
    for (int i = 0; i < numDm; i++) {
      // Copy the list of sample L/E values
      vectorD prev = samples;
      // Redefine bin width to lie within full sub-division
      double Width =
          2 * min(prev[0] - (bctr - bwdt / 2), (bctr + bwdt / 2) - prev[0]);
      // Compute oscillation argument sorted from lowest  to highest
      const double arg = k1267 * effDm[i] * Width;
      // Skip small oscillation values.
      // If it's the last one, lower the tolerance
      if (i < numDm - 1) {
        if (arg < 0.9) continue;
      }
      else {
        if (arg < 0.1) continue;
      }
      // Reset samples to redefine them
      samples.clear();
      // Loop over previous samples
      for (int j = 0; j < int(prev.size()); j++) {
        // Compute new sample points around old samples
        // This is based on a oscillatory quadrature rule
        double sample = (1 / sqrt(3)) * (Width / 2);
        if (arg != 0) sample = acos(sin(arg) / arg) / arg * (Width / 2);
        // Add samples above and below center
        samples.push_back(prev[j] - sample);
        samples.push_back(prev[j] + sample);
      }
    } // End of loop over Dm^2
    // Add sub-division samples to the end of allSamples vector
    allSamples.insert(allSamples.end(), samples.begin(), samples.end());
  } // End of loop over sub-divisions
  // Return all sample points
  return allSamples;
}
References OscProb::PMNS_Base::fAvgProbPrec, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kKm2eV, and OscProb::PMNS_Base::SolveHam().
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), and OscProb::PMNS_Base::AvgProbVectorLoE().
GetSamplePointsAvgClass() [1/3]
vectorD PMNS_Maltoni::GetSamplePointsAvgClass (double E, double cosT, double dcosT) protected virtual inherited
Compute the sample points for a bin of cosTheta with width dcosTheta
This is used to increase the precision of the average probability over a bin of cosT, calculated using the Maltoni method.
Parameters
E - The neutrino Energy value GeV
cosT - The neutrino cosT value in the bin center
dcosT - The cosT bin width
Returns
Vector of sample cosT points
Definition at line 1243 of file PMNS_Maltoni.cxx.
{
  // Set a number of sub-divisions to achieve "good" accuracy
  // This needs to be studied better
  int n_div = ceil(35 * pow(E, -0.4) * pow(abs(dcosT / cosT), 0.8) /
                   sqrt(fAvgProbPrec / 1e-4));
  // A vector to store sample points
  vectorD Samples;
  // Define sub-division width
  Samples.push_back(dcosT / n_div);
  // Loop over sub-divisions
  for (int k = 0; k < n_div; k++) {
    // Define sub-division center
    double bctr = cosT - dcosT / 2 + (k + 0.5) * dcosT / n_div;
    Samples.push_back(bctr);
  } // End of loop over sub-divisions
  // Return sample points
  return Samples;
}
References OscProb::PMNS_Base::fAvgProbPrec.
GetSamplePointsAvgClass() [2/3]
matrixC PMNS_Maltoni::GetSamplePointsAvgClass (double InvE, double dInvE, double cosT, double dcosT) protected virtual inherited
Compute the sample points for a bin of E and cosT with width dE and dcosT
Compute the sample points for a bin of 1oE and cosTheta with width d1oE and dcosTheta
This is used to increase the precision of the average probability over a bin of L/E and cosT, calculated using the Maltoni method.
Parameters
InvE - The neutrino 1/E value in the bin center in GeV-1
dInvE - The 1/E bin width in GeV-1
cosT - The neutrino cosT value in the bin center
dcosT - The cosT bin width
Returns
Matrix of sample InvE and cosT points
Definition at line 1131 of file PMNS_Maltoni.cxx.
{
  // Set a number of sub-divisions to achieve "good" accuracy
  // This needs to be studied better
  int n_divCosT = ceil(380 * pow(InvE, 0.5) * pow(abs(dcosT / cosT), 0.8) /
                       sqrt(fAvgProbPrec / 1e-4));
  int n_divE    = ceil(260 * pow(dInvE / InvE, 0.8) * pow(InvE, 0.6) /
                       sqrt(fAvgProbPrec / 1e-4));
  // A matrix to store sample points
  matrixC Samples = matrixC(n_divE + 1, vectorC(n_divCosT + 1, 0));
  // Define sub-division width
  Samples[0][0] = complexD(dInvE / n_divE, dcosT / n_divCosT);
  // Loop over sub-divisions
  for (int k = 0; k < n_divE; k++) {
    // Define sub-division center for energy
    double bctr_InvE = InvE - dInvE / 2 + (k + 0.5) * dInvE / n_divE;
    for (int l = 0; l < n_divCosT; l++) {
      // Define sub-division center for angle
      double bctr_CosT = cosT - dcosT / 2 + (l + 0.5) * dcosT / n_divCosT;
      Samples[k + 1][l + 1] = complexD(bctr_InvE, bctr_CosT);
    }
  } // End of loop over sub-divisions
  // Return sample points
  return Samples;
}
References OscProb::PMNS_Base::fAvgProbPrec.
GetSamplePointsAvgClass() [3/3]
vectorD PMNS_Maltoni::GetSamplePointsAvgClass (double LoE, double dLoE) protected virtual inherited
Compute the sample points for a bin of L/E with width dLoE.
This is used to increase the precision of the average probability over a bin of L/E, calculated using the Maltoni method.
Parameters
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Vector of sample L/E points
Definition at line 628 of file PMNS_Maltoni.cxx.
{
  // Set a number of sub-divisions to achieve "good" accuracy
  // This needs to be studied better
  int n_div = ceil(3 * pow(dLoE / LoE, 0.8) * pow(LoE, 0.3) /
                   sqrt(fAvgProbPrec / 1e-4));
  // A vector to store sample points
  vectorD Samples;
  // Define sub-division width
  Samples.push_back(dLoE / n_div);
  // Loop over sub-divisions
  for (int k = 0; k < n_div; k++) {
    // Define sub-division center
    double bctr = LoE - dLoE / 2 + (k + 0.5) * dLoE / n_div;
    Samples.push_back(bctr);
  } // End of loop over sub-divisions
  // Return sample points
  return Samples;
}
References OscProb::PMNS_Base::fAvgProbPrec.
Referenced by OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), and OscProb::PMNS_Maltoni::AvgProbVectorLoE().
GetSortedIndices()
vectorI PMNS_Base::GetSortedIndices (const vectorD x) protected virtual inherited
Get the indices of the sorted x vector
Parameters
x - input vector
Returns
The vector of sorted indices
Definition at line 715 of file PMNS_Base.cxx.
{
  vectorI idx(x.size(), 0);
  for (int i = 0; i < x.size(); i++) idx[i] = i;
  sort(idx.begin(), idx.end(), IdxCompare(x));
  return idx;
}
Referenced by OscProb::PMNS_Base::GetDmEff().
GetUpCoup()
double PMNS_NSI::GetUpCoup () virtual inherited
Get the NSI relative coupling to u-quarks.
Definition at line 329 of file PMNS_NSI.cxx.
{ return fNSIcoup[1]; }
References OscProb::PMNS_NSI::fNSIcoup.
GetZoACoup()
double PMNS_NSI::GetZoACoup () virtual inherited
Get the effective NSI Z/A dependence.
Definition at line 341 of file PMNS_NSI.cxx.
{
  return fNSIcoup[0] * fPath.zoa          // electrons: Z
         + fNSIcoup[1] * (1 + fPath.zoa)  // u-quarks:  A + Z
         + fNSIcoup[2] * (2 - fPath.zoa); // d-quarks: 2A - Z
}
References OscProb::PMNS_NSI::fNSIcoup, OscProb::PMNS_Base::fPath, and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_NSI::UpdateHam(), and UpdateHam().
HadamardProduct()
void PMNS_Maltoni::HadamardProduct (vectorD lambda, double dbin) protected virtual inherited
Apply an Hadamard Product to the density matrix
Parameters
lambda - Eigenvalues of the K matrix
dbin - Width of the bin
Definition at line 1209 of file PMNS_Maltoni.cxx.
{
  matrixC sinc = matrixC(fNumNus, vectorC(fNumNus, 0));
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i < j; i++) {
      double arg = (lambda[i] - lambda[j]) * dbin;
      sinc[i][j] = sin(arg) / arg;
      sinc[j][i] = sinc[i][j];
    }
  }
  for (int i = 0; i < fNumNus; i++) { sinc[i][i] = 1; }
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i < fNumNus; i++) {
      fdensityMatrix[i][j] = fdensityMatrix[i][j] * sinc[i][j];
    }
  }
}
References OscProb::PMNS_Maltoni::fdensityMatrix, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix().
InitializeTaylorsVectors()
void PMNS_Maltoni::InitializeTaylorsVectors () protected virtual inherited
Set vector sizes and initialize elements to zero. Initialize diagonal elements of S to one
Definition at line 37 of file PMNS_Maltoni.cxx.
{
  fdensityMatrix = matrixC(fNumNus, vectorC(fNumNus, 0));
  flambdaInvE = vectorD(fNumNus, 0);
  fVInvE      = matrixC(fNumNus, vectorC(fNumNus, 0));
  fKInvE      = Eigen::MatrixXcd::Zero(fNumNus, fNumNus);
  flambdaCosT = vectorD(fNumNus, 0);
  fVcosT      = matrixC(fNumNus, vectorC(fNumNus, 0));
  fKcosT      = Eigen::MatrixXcd::Zero(fNumNus, fNumNus);
  fevolutionMatrixS = matrixC(fNumNus, vectorC(fNumNus, 0));
  fSflavor = matrixC(fNumNus, vectorC(fNumNus, 0));
  fKmass   = matrixC(fNumNus, vectorC(fNumNus, 0));
  fKflavor = matrixC(fNumNus, vectorC(fNumNus, 0));
  for (int i = 0; i < fNumNus; i++) { fevolutionMatrixS[i][i] = 1; }
  fLayer = fPrem.GetPremLayers().size() - 1;
  fdl = -1;
  fDetRadius = fPrem.GetDetRadius();
}
References OscProb::PMNS_Maltoni::fdensityMatrix, OscProb::PMNS_Maltoni::fDetRadius, OscProb::PMNS_Maltoni::fdl, OscProb::PMNS_Maltoni::fevolutionMatrixS, OscProb::PMNS_Maltoni::fKcosT, OscProb::PMNS_Maltoni::fKflavor, OscProb::PMNS_Maltoni::fKInvE, OscProb::PMNS_Maltoni::fKmass, OscProb::PMNS_Maltoni::flambdaCosT, OscProb::PMNS_Maltoni::flambdaInvE, OscProb::PMNS_Maltoni::fLayer, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Maltoni::fPrem, OscProb::PMNS_Maltoni::fSflavor, OscProb::PMNS_Maltoni::fVcosT, OscProb::PMNS_Maltoni::fVInvE, OscProb::PremModel::GetDetRadius(), and OscProb::PremModel::GetPremLayers().
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), and OscProb::PMNS_Maltoni::PMNS_Maltoni().
InitializeVectors()
void PMNS_Base::InitializeVectors () protected virtual inherited
Initialize all member vectors with zeros
Set vector sizes and initialize elements to zero.
Definition at line 79 of file PMNS_Base.cxx.
{
  fDm    = vectorD(fNumNus, 0);
  fTheta = matrixD(fNumNus, vectorD(fNumNus, 0));
  fDelta = matrixD(fNumNus, vectorD(fNumNus, 0));
  fNuState = vectorC(fNumNus, zero);
  fHms     = matrixC(fNumNus, vectorC(fNumNus, zero));
  fPhases = vectorC(fNumNus, zero);
  fBuffer = vectorC(fNumNus, zero);
  fEval = vectorD(fNumNus, 0);
  fEvec = matrixC(fNumNus, vectorC(fNumNus, zero));
}
Referenced by OscProb::PMNS_Base::PMNS_Base().
LnDerivative()
double PMNS_Maltoni::LnDerivative () protected virtual inherited
Compute the derivative of one layer's length depending on the angle
Definition at line 189 of file PMNS_Maltoni.cxx.
{
  double dL = 0;
  double L1 = pow(fPrem.GetPremLayers()[fLayer].radius, 2) - fminRsq;
  double L2 = -fminRsq;
  if (fLayer > 0) L2 += pow(fPrem.GetPremLayers()[fLayer - 1].radius, 2);
  bool ismin = (L2 <= 0 && fcosT < 0);
  if (ismin)
    dL = 2 * pow(fDetRadius, 2) * fcosT * pow(L1, -0.5);
  else
    dL = pow(fDetRadius, 2) * fcosT * (pow(L1, -0.5) - pow(L2, -0.5));
  if (ismin) fdl = 1;
  fLayer += fdl;
  return dL;
}
References OscProb::PMNS_Maltoni::fcosT, OscProb::PMNS_Maltoni::fDetRadius, OscProb::PMNS_Maltoni::fdl, OscProb::PMNS_Maltoni::fLayer, OscProb::PMNS_Maltoni::fminRsq, OscProb::PMNS_Maltoni::fPrem, and OscProb::PremModel::GetPremLayers().
Referenced by OscProb::PMNS_Maltoni::BuildKcosT().
MultiplicationRuleK()
void PMNS_Maltoni::MultiplicationRuleK (Eigen::MatrixXcd & K) protected virtual inherited
Product between two K matrices.
This is used to calculate the matrix K corresponding to the propagation between the beginning of the path and the end of the current layer.
The matrix fKflavor correspond to the propagation between the beginning and the end of the layer.
Parameters
K - The current K matrix
Definition at line 305 of file PMNS_Maltoni.cxx.
{
  for (int i = 0; i < fNumNus; i++) {
    complexD buffer[fNumNus];
    for (int l = 0; l < fNumNus; l++) {
      for (int k = 0; k < fNumNus; k++) {
        buffer[l] += conj(fevolutionMatrixS[k][i]) * fKflavor[k][l];
      }
    }
    for (int j = 0; j <= i; j++) {
      for (int l = 0; l < fNumNus; l++) {
        K(i, j) += buffer[l] * fevolutionMatrixS[l][j];
      }
      if (i != j) { K(j, i) = conj(K(i, j)); }
    }
  }
}
References OscProb::PMNS_Maltoni::fevolutionMatrixS, OscProb::PMNS_Maltoni::fKflavor, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Maltoni::PropagatePathTaylor().
MultiplicationRuleS()
void PMNS_Maltoni::MultiplicationRuleS () protected virtual inherited
Product between two S matrices.
This is used to calculate the matrix S corresponding to the propagation between the beginning of the path and the end of the current layer.
The matrix fevolutionMatrixS represent the propagation between the beginning of the path and the beginning of the current layer. This matrix is updated after every layer with this function. The matrix fSflavor represent the propagation between the beginning and the end of the layer.
Definition at line 276 of file PMNS_Maltoni.cxx.
{
  complexD save[fNumNus];
  for (int j = 0; j < fNumNus; j++) {
    for (int n = 0; n < fNumNus; n++) { save[n] = fevolutionMatrixS[n][j]; }
    for (int i = 0; i < fNumNus; i++) {
      fevolutionMatrixS[i][j] = 0;
      for (int k = 0; k < fNumNus; k++) {
        fevolutionMatrixS[i][j] += fSflavor[i][k] * save[k];
      }
    }
  }
}
References OscProb::PMNS_Maltoni::fevolutionMatrixS, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Maltoni::fSflavor.
Referenced by OscProb::PMNS_Maltoni::PropagatePathTaylor().
P()
double PMNS_Base::P (int flv) protected virtual inherited
Compute oscillation probability of flavour flv from current state
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino final flavour.
Returns
Neutrino oscillation probability
Reimplemented in OscProb::PMNS_DensityMatrix.
Definition at line 1058 of file PMNS_Base.cxx.
{
  assert(flv >= 0 && flv < fNumNus);
  return norm(fNuState[flv]);
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fNuState.
Referenced by OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Maltoni::AvgFormulaExtrapolation(), OscProb::PMNS_Base::GetProbVector(), and OscProb::PMNS_Base::Prob().
Prob() [1/6]
double PMNS_Base::Prob (int flvi, int flvf) virtual inherited
Compute the probability of flvi going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1091 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  Propagate();
  return P(flvf);
}
References OscProb::PMNS_Base::P(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::ResetToFlavour().
Prob() [2/6]
double PMNS_Base::Prob (int flvi, int flvf, double E) virtual inherited
Compute the probability of flvi going to flvf for energy E
Compute the probability of flvi going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1160 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(flvi, flvf);
}
References OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetEnergy().
Prob() [3/6]
double PMNS_Base::Prob (int flvi, int flvf, double E, double L) virtual inherited
Compute the probability of flvi going to flvf for energy E and distance L
Compute the probability of flvi going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1219 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(flvi, flvf);
}
References OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
Prob() [4/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf) virtual inherited
Compute the probability of nu_in going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1114 of file PMNS_Base.cxx.
{
  SetPureState(nu_in);
  Propagate();
  return P(flvf);
}
References OscProb::PMNS_Base::P(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::SetPureState().
Referenced by OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Base::AvgProbLoE(), and OscProb::PMNS_Base::Prob().
Prob() [5/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E) virtual inherited
Compute the probability of nu_in going to flvf for energy E
Compute the probability of nu_in going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1138 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(nu_in, flvf);
}
References OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetEnergy().
Prob() [6/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E, double L) virtual inherited
Compute the probability of nu_in going to flvf for energy E and distance L
Compute the probability of nu_in going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1189 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(nu_in, flvf);
}
References OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbMatrix() [1/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf) virtual inherited
Compute the probability matrix for the first nflvi and nflvf states.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
Returns
Neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_DensityMatrix, OscProb::PMNS_DensityMatrix, OscProb::PMNS_NUNM, and OscProb::PMNS_OQS.
Definition at line 1387 of file PMNS_Base.cxx.
{
  assert(nflvi <= fNumNus && nflvi >= 0);
  assert(nflvf <= fNumNus && nflvf >= 0);
  // Output probabilities
  matrixD probs(nflvi, vectorD(nflvf));
  // List of states
  matrixC allstates(nflvi, vectorC(fNumNus));
  // Reset all initial states
  for (int i = 0; i < nflvi; i++) {
    ResetToFlavour(i);
    allstates[i] = fNuState;
  }
  // Propagate all states in parallel
  for (int i = 0; i < int(fNuPaths.size()); i++) {
    for (int flvi = 0; flvi < nflvi; flvi++) {
      fNuState = allstates[flvi];
      PropagatePath(fNuPaths[i]);
      allstates[flvi] = fNuState;
    }
  }
  // Get all probabilities
  for (int flvi = 0; flvi < nflvi; flvi++) {
    for (int flvj = 0; flvj < nflvf; flvj++) {
      probs[flvi][flvj] = norm(allstates[flvi][flvj]);
    }
  }
  return probs;
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::PropagatePath(), and OscProb::PMNS_Base::ResetToFlavour().
Referenced by OscProb::PMNS_Maltoni::AvgProbMatrix(), OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), and OscProb::PMNS_Base::ProbMatrix().
ProbMatrix() [2/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E) virtual inherited
Compute the probability matrix for the first nflvi and nflvf states for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_DensityMatrix.
Definition at line 1439 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbMatrix(nflvi, nflvf);
}
References OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::SetEnergy().
ProbMatrix() [3/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E, double L) virtual inherited
Compute the probability matrix for energy E and distance L
Compute the probability matrix for the first nflvi and nflvf states for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_DensityMatrix.
Definition at line 1468 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbMatrix(nflvi, nflvf);
}
References OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbVector() [1/6]
vectorD PMNS_Base::ProbVector (int flvi) virtual inherited
Compute the probabilities of flvi going to all flavours
Compute the probability of flvi going to all flavours.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
Returns
Neutrino oscillation probabilities
Definition at line 1272 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  Propagate();
  return GetProbVector();
}
References OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::ResetToFlavour().
ProbVector() [2/6]
vectorD PMNS_Base::ProbVector (int flvi, double E) virtual inherited
Compute the probabilities of flvi going to all flavours for energy E
Compute the probability of flvi going to all flavours for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1313 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(flvi);
}
References OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_Base::SetEnergy().
ProbVector() [3/6]
vectorD PMNS_Base::ProbVector (int flvi, double E, double L) virtual inherited
Compute the probabilities of flvi going to all flavours for energy E and distance L
Compute the probability of flvi going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1365 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(flvi);
}
References OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbVector() [4/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in) virtual inherited
Compute the probabilities of nu_in going to all flavours
Compute the probability of nu_in going to all flavours.
Parameters
nu_in - The neutrino initial state in flavour basis.
Returns
Neutrino oscillation probabilities
Definition at line 1250 of file PMNS_Base.cxx.
{
  SetPureState(nu_in);
  Propagate();
  return GetProbVector();
}
References OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::SetPureState().
Referenced by OscProb::PMNS_Maltoni::AvgProbVector(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), and OscProb::PMNS_Base::ProbVector().
ProbVector() [5/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E) virtual inherited
Compute the probabilities of nu_in going to all
Compute the probability of nu_in going to all flavours for a given energy in GeV.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probabilities
Definition at line 1291 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(nu_in);
}
References OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_Base::SetEnergy().
ProbVector() [6/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E, double L) virtual inherited
Compute the probabilities of nu_in going to all flavours for energy E and distance L
Compute the probability of nu_in going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probabilities
Definition at line 1336 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(nu_in);
}
References OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
Propagate()
void PMNS_Base::Propagate () protected virtual inherited
Propagate neutrino state through full path
Reimplemented in OscProb::PMNS_NUNM, and OscProb::PMNS_OQS.
Definition at line 1018 of file PMNS_Base.cxx.
{
  for (int i = 0; i < int(fNuPaths.size()); i++) { PropagatePath(fNuPaths[i]); }
}
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::PropagatePath().
Referenced by OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_NUNM::Propagate(), and OscProb::PMNS_OQS::Propagate().
PropagatePath()
void PMNS_Base::PropagatePath (NuPath p) protected virtual inherited
Propagate the current neutrino state through a given path
Parameters
p - A neutrino path segment
Reimplemented in OscProb::PMNS_Decay, OscProb::PMNS_Deco, OscProb::PMNS_Iter, OscProb::PMNS_NUNM, OscProb::PMNS_OQS, and OscProb::PMNS_DensityMatrix.
Definition at line 983 of file PMNS_Base.cxx.
{
  // Set the neutrino path
  SetCurPath(p);
  // Solve for eigensystem
  SolveHam();
  double LengthIneV = kKm2eV * p.length;
  for (int i = 0; i < fNumNus; i++) {
    double arg = fEval[i] * LengthIneV;
    fPhases[i] = complexD(cos(arg), -sin(arg));
  }
  for (int i = 0; i < fNumNus; i++) {
    fBuffer[i] = 0;
    for (int j = 0; j < fNumNus; j++) {
      fBuffer[i] += conj(fEvec[j][i]) * fNuState[j];
    }
    fBuffer[i] *= fPhases[i];
  }
  // Propagate neutrino state
  for (int i = 0; i < fNumNus; i++) {
    fNuState[i] = 0;
    for (int j = 0; j < fNumNus; j++) {
      fNuState[i] += fEvec[i][j] * fBuffer[j];
    }
  }
}
References OscProb::PMNS_Base::fBuffer, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::fPhases, OscProb::PMNS_Base::kKm2eV, OscProb::NuPath::length, OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SolveHam().
Referenced by OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Base::Propagate(), OscProb::PMNS_Iter::PropagatePath(), and OscProb::PMNS_NUNM::PropagatePath().
PropagatePathTaylor()
void PMNS_Maltoni::PropagatePathTaylor (NuPath p) protected virtual inherited
Propagate the current neutrino state through a given path
Parameters
p - A neutrino path segment
Definition at line 343 of file PMNS_Maltoni.cxx.
{
  // Set the neutrino path
  SetCurPath(p);
  // Solve for eigensystem
  SolveHam();
  // Get the evolution matrix in mass basis
  double LengthIneV = kKm2eV * p.length;
  for (int i = 0; i < fNumNus; i++) {
    double arg = fEval[i] * LengthIneV;
    fPhases[i] = complexD(cos(arg), -sin(arg));
  }
  // Rotate S in flavor basis
  rotateS();
  // if avg on E
  if (fdInvE != 0) {
    // Build KE in mass basis
    BuildKE(p.length);
    // Rotate KE in flavor basis
    rotateK();
    // Multiply this layer K's with the previous path K's
    MultiplicationRuleK(fKInvE);
  }
  // if avg on cosT
  if (fdcosT != 0) {
    // Build KcosT in mass basis
    BuildKcosT();
    // Multiply this layer K's with the previous path K's
    MultiplicationRuleK(fKcosT);
  }
  // Multiply this layer S's with the previous path S's
  MultiplicationRuleS();
}
References OscProb::PMNS_Maltoni::BuildKcosT(), OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Maltoni::fdcosT, OscProb::PMNS_Maltoni::fdInvE, OscProb::PMNS_Base::fEval, OscProb::PMNS_Maltoni::fKcosT, OscProb::PMNS_Maltoni::fKInvE, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPhases, OscProb::PMNS_Base::kKm2eV, OscProb::NuPath::length, OscProb::PMNS_Maltoni::MultiplicationRuleK(), OscProb::PMNS_Maltoni::MultiplicationRuleS(), OscProb::PMNS_Maltoni::rotateK(), OscProb::PMNS_Maltoni::rotateS(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SolveHam().
Referenced by OscProb::PMNS_Maltoni::PropagateTaylor().
PropagateTaylor()
void PMNS_Maltoni::PropagateTaylor () protected virtual inherited
Propagate neutrino state through full path
Definition at line 330 of file PMNS_Maltoni.cxx.
{
  for (int i = 0; i < int(fNuPaths.size()); i++) {
    PropagatePathTaylor(fNuPaths[i]);
  }
}
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Maltoni::PropagatePathTaylor().
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), and OscProb::PMNS_Maltoni::ExtrapolationProbLoE().
ResetToFlavour()
void PMNS_Base::ResetToFlavour (int flv) protected virtual inherited
Reset the neutrino state back to a pure flavour where it starts
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino starting flavour.
Reimplemented in OscProb::PMNS_DensityMatrix.
Definition at line 1034 of file PMNS_Base.cxx.
{
  assert(flv >= 0 && flv < fNumNus);
  for (int i = 0; i < fNumNus; ++i) {
    if (i == flv)
      fNuState[i] = one;
    else
      fNuState[i] = zero;
  }
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::one, and OscProb::PMNS_Base::zero.
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_NUNM::ProbMatrix(), OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_DensityMatrix::ResetToFlavour().
RotateDensityM()
void PMNS_Maltoni::RotateDensityM (bool to_basis, matrixC V) protected virtual inherited
Apply rotation to the density matrix from or to the basis where V is diagonal
Parameters
to_basis - Rotation from (false) or to (true)
V - The matrix used for the denisty matrix rotation.
Definition at line 1173 of file PMNS_Maltoni.cxx.
{
  matrixC Buffer = matrixC(fNumNus, vectorC(fNumNus, 0));
  for (int i = 0; i < fNumNus; i++) {
    for (int j = 0; j < fNumNus; j++) {
      for (int k = 0; k < fNumNus; k++) {
        if (to_basis)
          Buffer[i][j] += fdensityMatrix[i][k] * V[k][j];
        else
          Buffer[i][j] += fdensityMatrix[i][k] * conj(V[j][k]);
      }
    }
  }
  for (int i = 0; i < fNumNus; i++) {
    for (int j = i; j < fNumNus; j++) {
      fdensityMatrix[i][j] = 0;
      for (int k = 0; k < fNumNus; k++) {
        if (to_basis)
          fdensityMatrix[i][j] += conj(V[k][i]) * Buffer[k][j];
        else
          fdensityMatrix[i][j] += V[i][k] * Buffer[k][j];
      }
      if (j > i) fdensityMatrix[j][i] = conj(fdensityMatrix[i][j]);
    }
  }
}
References OscProb::PMNS_Maltoni::fdensityMatrix, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix().
RotateH()
void PMNS_Base::RotateH (int i, int j, matrixC & Ham) protected virtual inherited
Rotate the Hamiltonian by the angle theta_ij and phase delta_ij.
The rotations assume all off-diagonal elements with i > j are zero. This is correct if the order of rotations is chosen appropriately and it speeds up computation by skipping null terms
Parameters
i,j - the indices of the rotation ij
Ham - the Hamiltonian to be rotated
Definition at line 822 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if (fTheta[i][j] == 0) return;
  double fSinBuffer = sin(fTheta[i][j]);
  double fCosBuffer = cos(fTheta[i][j]);
  double   fHmsBufferD;
  complexD fHmsBufferC;
  // With Delta
  if (i + 1 < j) {
    complexD fExpBuffer = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    // General case
    if (i > 0) {
      // Top columns
      for (int k = 0; k < i; k++) {
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer * conj(fExpBuffer);
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer * fExpBuffer;
      }
      // Middle row and column
      for (int k = i + 1; k < j; k++) {
        fHmsBufferC = Ham[k][j];
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
        Ham[i][k] += fSinBuffer * fExpBuffer * conj(fHmsBufferC);
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] +=
          2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -=
          2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j] * conj(fExpBuffer)) *
                   fSinBuffer * fExpBuffer;
      Ham[i][j] +=
          fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC) * fExpBuffer;
    }
    // First rotation on j (No top columns)
    else {
      // Middle rows and columns
      for (int k = i + 1; k < j; k++) {
        Ham[k][j] = -conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
      }
      // Nodes ij
      fHmsBufferD = real(Ham[i][i]);
      Ham[i][j] =
          fSinBuffer * fCosBuffer * (Ham[j][j] - fHmsBufferD) * fExpBuffer;
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferD * fSinBuffer;
    }
  }
  // Without Delta (No middle rows or columns: j = i+1)
  else {
    // General case
    if (i > 0) {
      // Top columns
      for (int k = 0; k < i; k++) {
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer;
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer;
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -= 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j]) * fSinBuffer;
      Ham[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC);
    }
    // First rotation (theta12)
    else {
      Ham[i][j] = fSinBuffer * fCosBuffer * Ham[j][j];
      Ham[i][i] = fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
    }
  }
}
References OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), and BuildHms().
rotateK()
void PMNS_Maltoni::rotateK () protected virtual inherited
Rotate the K matrix from mass to flavor basis
Definition at line 238 of file PMNS_Maltoni.cxx.
{
  complexD buffer[fNumNus];
  for (int j = 0; j < fNumNus; j++) {
    for (int k = 0; k < fNumNus; k++) {
      buffer[k] = 0;
      for (int l = 0; l < fNumNus; l++) {
        buffer[k] += fKmass[k][l] * conj(fEvec[j][l]);
      }
    }
    for (int i = 0; i <= j; i++) {
      fKflavor[i][j] = 0;
      for (int k = 0; k < fNumNus; k++) {
        fKflavor[i][j] += fEvec[i][k] * buffer[k];
      }
      if (i != j) { fKflavor[j][i] = conj(fKflavor[i][j]); }
    }
  }
}
References OscProb::PMNS_Base::fEvec, OscProb::PMNS_Maltoni::fKflavor, OscProb::PMNS_Maltoni::fKmass, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Maltoni::PropagatePathTaylor().
rotateS()
void PMNS_Maltoni::rotateS () protected virtual inherited
Rotate the S matrix for the current layer from mass to flavor basis
Definition at line 216 of file PMNS_Maltoni.cxx.
{
  complexD buffer[fNumNus];
  for (int j = 0; j < fNumNus; j++) {
    for (int k = 0; k < fNumNus; k++) {
      buffer[k] = fPhases[k] * conj(fEvec[j][k]);
    }
    for (int i = 0; i < fNumNus; i++) {
      fSflavor[i][j] = 0;
      for (int k = 0; k < fNumNus; k++) {
        fSflavor[i][j] += fEvec[i][k] * buffer[k];
      }
    }
  }
}
References OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPhases, and OscProb::PMNS_Maltoni::fSflavor.
Referenced by OscProb::PMNS_Maltoni::PropagatePathTaylor().
RotateState()
void PMNS_Base::RotateState (int i, int j) protected virtual inherited
Rotate the neutrino state by the angle theta_ij and phase delta_ij.
Parameters
i,j - the indices of the rotation ij
Definition at line 760 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if (fTheta[i][j] == 0) return;
  double sij = sin(fTheta[i][j]);
  double cij = cos(fTheta[i][j]);
  complexD buffer;
  if (i + 1 == j || fDelta[i][j] == 0) {
    buffer      = cij * fNuState[i] + sij * fNuState[j];
    fNuState[j] = cij * fNuState[j] - sij * fNuState[i];
  }
  else {
    complexD eij = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    buffer       = cij * fNuState[i] + sij * eij * fNuState[j];
    fNuState[j]  = cij * fNuState[j] - sij * conj(eij) * fNuState[i];
  }
  fNuState[i] = buffer;
}
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Base::GetMassEigenstate().
SetAngle()
void PMNS_Base::SetAngle (int i, int j, double th) virtual inherited
Set the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of theta_ij
th - the value of theta_ij
Definition at line 539 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Theta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fTheta[i - 1][j - 1] == th);
  fTheta[i - 1][j - 1] = th;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetMix(), OscProb::PMNS_Fast::SetMix(), SetNominalPars(), and OscProb::PMNS_Base::SetStdPars().
SetAtt() [1/2]
void PMNS_Base::SetAtt (double att, int idx) protected virtual inherited
Set some single path attribute.
An auxiliary function to set individual attributes in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
att - The value of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 364 of file PMNS_Base.cxx.
{
  if (fNuPaths.size() != 1) {
    cerr << "WARNING: Clearing path vector and starting new single path."
         << endl
         << "To avoid possible issues, use the SetPath function." << endl;
    SetStdPath();
  }
  switch (idx) {
    case 0: fNuPaths[0].length = att; break;
    case 1: fNuPaths[0].density = att; break;
    case 2: fNuPaths[0].zoa = att; break;
    case 3: fNuPaths[0].layer = att; break;
  }
}
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::SetStdPath().
Referenced by OscProb::PMNS_Base::SetDensity(), OscProb::PMNS_Base::SetLayers(), OscProb::PMNS_Base::SetLength(), and OscProb::PMNS_Base::SetZoA().
SetAtt() [2/2]
void PMNS_Base::SetAtt (vectorD att, int idx) protected virtual inherited
Set all values of a path attribute.
An auxiliary function to set individual attributes in a path sequence.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
att - The values of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 427 of file PMNS_Base.cxx.
{
  // Get the sizes of the attribute and
  // path sequence vectors
  int nA = att.size();
  int nP = fNuPaths.size();
  // If the vector sizes are equal, update this attribute
  if (nA == nP) {
    for (int i = 0; i < nP; i++) {
      switch (idx) {
        case 0: fNuPaths[i].length = att[i]; break;
        case 1: fNuPaths[i].density = att[i]; break;
        case 2: fNuPaths[i].zoa = att[i]; break;
        case 3: fNuPaths[i].layer = att[i]; break;
      }
    }
  }
  // If the vector sizes differ, create a new path sequence
  // and set value for this attribute. Other attributes will
  // be taken from default single path.
  else {
    cerr << "WARNING: New vector size. Starting new path vector." << endl
         << "To avoid possible issues, use the SetPath function." << endl;
    // Start a new standard path just
    // to set default values
    SetStdPath();
    // Create a path segment with default values
    NuPath p = fNuPaths[0];
    // Clear the path sequence
    ClearPath();
    // Set this particular attribute's value
    // and add the path segment to the sequence
    for (int i = 0; i < nA; i++) {
      switch (idx) {
        case 0: p.length = att[i]; break;
        case 1: p.density = att[i]; break;
        case 2: p.zoa = att[i]; break;
        case 3: p.layer = att[i]; break;
      }
      AddPath(p);
    }
  }
}
References OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::ClearPath(), OscProb::NuPath::density, OscProb::PMNS_Base::fNuPaths, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetStdPath(), and OscProb::NuPath::zoa.
SetAvgProbPrec()
void PMNS_Base::SetAvgProbPrec (double prec) virtual inherited
Set the precision for the AvgProb method
Parameters
prec - AvgProb precision
Definition at line 1962 of file PMNS_Base.cxx.
{
  if (prec < 1e-8) {
    cerr << "WARNING: Cannot set AvgProb precision lower that 1e-8."
         << "Setting to 1e-8." << endl;
    prec = 1e-8;
  }
  fAvgProbPrec = prec;
}
References OscProb::PMNS_Base::fAvgProbPrec.
Referenced by OscProb::PMNS_Base::PMNS_Base(), and OscProb::PMNS_Maltoni::PMNS_Maltoni().
SetCosT()
void PMNS_Maltoni::SetCosT (double cosT) protected virtual inherited
Set neutrino zenith angle.
Parameters
cosT - The cosine of the zenith angle
Definition at line 92 of file PMNS_Maltoni.cxx.
{ fcosT = cosT; }
References OscProb::PMNS_Maltoni::fcosT.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), and OscProb::PMNS_Maltoni::ExtrapolationProbCosT().
SetCoupByIndex()
void PMNS_NSI::SetCoupByIndex (double c, int i) virtual inherited
Set the NSI relative coupling to a given fermion. This factor represents what fraction of the fermion are seen by the interaction.
Parameters
c - fermion coupling strength
i - fermion index (0,1,2) -> (e,u,d)
Definition at line 261 of file PMNS_NSI.cxx.
{
  bool isSame = (fNSIcoup[i] == c);
  if (!isSame) ClearCache();
  fGotES *= isSame;
  fNSIcoup[i] = c;
}
References OscProb::PMNS_Base::ClearCache(), OscProb::PMNS_Base::fGotES, and OscProb::PMNS_NSI::fNSIcoup.
Referenced by OscProb::PMNS_NSI::SetDownCoup(), OscProb::PMNS_NSI::SetElecCoup(), and OscProb::PMNS_NSI::SetUpCoup().
SetCurPath()
void PMNS_Base::SetCurPath (NuPath p) protected virtual inherited
Set the path currentlyin use by the class.
This will be used to know what path to propagate through next.
It will also check if values are changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
p - A neutrino path segment
Definition at line 274 of file PMNS_Base.cxx.
{
  // Check if relevant value are actually changing
  fGotES *= (fPath.density == p.density);
  fGotES *= (fPath.zoa == p.zoa);
  fPath = p;
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fPath, and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), and OscProb::PMNS_Maltoni::PropagatePathTaylor().
SetDelta()
void PMNS_Base::SetDelta (int i, int j, double delta) virtual inherited
Set the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of delta_ij
delta - the value of delta_ij
Definition at line 602 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Delta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  if (i + 1 == j) {
    cerr << "WARNING: Rotation " << i << j << " is real. Doing nothing."
         << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDelta[i - 1][j - 1] == delta);
  fDelta[i - 1][j - 1] = delta;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Decay::SetMix(), OscProb::PMNS_Fast::SetMix(), and SetNominalPars().
SetDeltaMsqrs()
void PMNS_Fast::SetDeltaMsqrs (double dm21, double dm32) virtual inherited
Set both mass-splittings at once.
These are Dm_21 and Dm_32 in eV^2.
The corresponding Dm_31 is set in the class attributes.
Parameters
dm21 - The solar mass-splitting Dm_21
dm32 - The atmospheric mass-splitting Dm_32
Definition at line 55 of file PMNS_Fast.cxx.
{
  SetDm(2, dm21);
  SetDm(3, dm32 + dm21);
}
References OscProb::PMNS_Base::SetDm().
SetDensity() [1/2]
void PMNS_Base::SetDensity (double rho) virtual inherited
Set single path density.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The density of the path segment in g/cm^3
Definition at line 402 of file PMNS_Base.cxx.
{ SetAtt(rho, 1); }
References OscProb::PMNS_Base::SetAtt().
SetDensity() [2/2]
void PMNS_Base::SetDensity (vectorD rho) virtual inherited
Set multiple path densities.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The densities of the path segments in g/cm^3
Definition at line 497 of file PMNS_Base.cxx.
{ SetAtt(rho, 1); }
References OscProb::PMNS_Base::SetAtt().
SetDm()
void PMNS_Base::SetDm (int j, double dm) virtual inherited
Set the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
j - the index of dm_j1
dm - the value of dm_j1
Definition at line 674 of file PMNS_Base.cxx.
{
  if (j < 2 || j > fNumNus) {
    cerr << "ERROR: Dm" << j << "1 not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDm[j - 1] == dm);
  fDm[j - 1] = dm;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetDeltaMsqrs(), OscProb::PMNS_Fast::SetDeltaMsqrs(), SetNominalPars(), and OscProb::PMNS_Base::SetStdPars().
SetDownCoup()
void PMNS_NSI::SetDownCoup (double d) virtual inherited
Set the NSI relative coupling to d-quarks. This factor represents what fraction of the d-quarks are seen by the interaction.
Parameters
d - d-quark coupling strength
Definition at line 300 of file PMNS_NSI.cxx.
{ SetCoupByIndex(d, 2); }
References OscProb::PMNS_NSI::SetCoupByIndex().
Referenced by OscProb::PMNS_NSI::SetFermCoup().
SetElecCoup()
void PMNS_NSI::SetElecCoup (double e) virtual inherited
Set the NSI relative coupling to electrons. This factor represents what fraction of the electrons are seen by the interaction.
Parameters
e - electron coupling strength
Definition at line 280 of file PMNS_NSI.cxx.
{ SetCoupByIndex(e, 0); }
References OscProb::PMNS_NSI::SetCoupByIndex().
Referenced by OscProb::PMNS_NSI::SetFermCoup().
SetEnergy()
void PMNS_Base::SetEnergy (double E) virtual inherited
Set neutrino energy in GeV.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
E - The neutrino energy in GeV
Definition at line 226 of file PMNS_Base.cxx.
{
  // Check if value is actually changing
  fGotES *= (fEnergy == E);
  fEnergy = E;
}
References OscProb::PMNS_Base::fEnergy, and OscProb::PMNS_Base::fGotES.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::ProbVector().
SetEps()
void PMNS_NSI::SetEps (int flvi, int flvj, double val, double phase) virtual inherited
Set any given NSI parameter.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Flavours are:
0 = nue, 1 = numu, 2 = nutau
Requires that flvi < flvj. Will notify you if input is wrong. If flvi > flvj, will assume reverse order and swap flvi and flvj.
Parameters
flvi - The first flavour index
flvj - The second flavour index
val - The absolute value of the parameter
phase - The complex phase of the parameter in radians
Definition at line 86 of file PMNS_NSI.cxx.
{
  if (flvi > flvj) {
    cerr << "WARNING: First argument should be smaller or equal to second "
            "argument"
         << endl
         << "Setting reverse order (Eps_" << flvj << flvi << "). " << endl;
    int temp = flvi;
    flvi     = flvj;
    flvj     = temp;
  }
  if (flvi < 0 || flvi > 2 || flvj < flvi || flvj > 2) {
    cerr << "WARNING: Eps_" << flvi << flvj << " not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  complexD h = val;
  if (flvi != flvj) h *= complexD(cos(phase), sin(phase));
  bool isSame = (fEps[flvi][flvj] == h);
  if (!isSame) ClearCache();
  fGotES *= isSame;
  fEps[flvi][flvj] = h;
}
References OscProb::PMNS_Base::ClearCache(), OscProb::PMNS_NSI::fEps, OscProb::PMNS_Base::fGotES, and OscProb::PMNS_Base::fNumNus.
Referenced by GetNSI(), GetSNSI(), OscProb::PMNS_NSI::SetEps_ee(), OscProb::PMNS_NSI::SetEps_emu(), OscProb::PMNS_NSI::SetEps_etau(), OscProb::PMNS_NSI::SetEps_mumu(), OscProb::PMNS_NSI::SetEps_mutau(), OscProb::PMNS_NSI::SetEps_tautau(), and OscProb::PMNS_NSI::SetNSI().
SetEps_ee()
void PMNS_NSI::SetEps_ee (double a) virtual inherited
Set eps_ee parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The value of the real parameter eps_ee
Definition at line 158 of file PMNS_NSI.cxx.
{ SetEps(0, 0, a, 0); }
References OscProb::PMNS_NSI::SetEps().
SetEps_emu()
void PMNS_NSI::SetEps_emu (double a, double phi) virtual inherited
Set eps_emu parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The absolute value of the parameter eps_emu
phi - The phase of the complex parameter eps_emu in radians
Definition at line 192 of file PMNS_NSI.cxx.
{ SetEps(0, 1, a, phi); }
References OscProb::PMNS_NSI::SetEps().
SetEps_etau()
void PMNS_NSI::SetEps_etau (double a, double phi) virtual inherited
Set eps_etau parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The absolute value of the parameter eps_etau
phi - The phase of the complex parameter eps_etau in radians
Definition at line 204 of file PMNS_NSI.cxx.
{ SetEps(0, 2, a, phi); }
References OscProb::PMNS_NSI::SetEps().
SetEps_mumu()
void PMNS_NSI::SetEps_mumu (double a) virtual inherited
Set eps_mumu parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The value of the real parameter eps_mumu
Definition at line 169 of file PMNS_NSI.cxx.
{ SetEps(1, 1, a, 0); }
References OscProb::PMNS_NSI::SetEps().
SetEps_mutau()
void PMNS_NSI::SetEps_mutau (double a, double phi) virtual inherited
Set eps_mutau parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The absolute value of the parameter eps_mutau
phi - The phase of the complex parameter eps_mutau in radians
Definition at line 216 of file PMNS_NSI.cxx.
{ SetEps(1, 2, a, phi); }
References OscProb::PMNS_NSI::SetEps().
SetEps_tautau()
void PMNS_NSI::SetEps_tautau (double a) virtual inherited
Set eps_tautau parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The value of the real parameter eps_tautau
Definition at line 180 of file PMNS_NSI.cxx.
{ SetEps(2, 2, a, 0); }
References OscProb::PMNS_NSI::SetEps().
SetFermCoup()
void PMNS_NSI::SetFermCoup (double e, double u, double d) virtual inherited
Set the NSI relative couplings to each fermion. These factors represent what fraction of each fermion are seen by the interaction.
Parameters
e - electron coupling strength
u - u-quark coupling strength
d - d-quark coupling strength
Definition at line 312 of file PMNS_NSI.cxx.
{
  SetElecCoup(e); // electron coupling
  SetUpCoup(u);   // u-quark coupling
  SetDownCoup(d); // d-quark coupling
}
References OscProb::PMNS_NSI::SetDownCoup(), OscProb::PMNS_NSI::SetElecCoup(), and OscProb::PMNS_NSI::SetUpCoup().
Referenced by OscProb::PMNS_NSI::PMNS_NSI().
SetIsNuBar()
void PMNS_Base::SetIsNuBar (bool isNuBar) virtual inherited
Set anti-neutrino flag.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
isNuBar - Set to true for anti-neutrino and false for neutrino.
Reimplemented in OscProb::PMNS_Decay, OscProb::PMNS_Iter, and OscProb::PMNS_OQS.
Definition at line 243 of file PMNS_Base.cxx.
{
  // Check if value is actually changing
  fGotES *= (fIsNuBar == isNuBar);
  fIsNuBar = isNuBar;
}
References OscProb::PMNS_Base::fGotES, and OscProb::PMNS_Base::fIsNuBar.
Referenced by CheckProb(), OscProb::PMNS_Base::PMNS_Base(), SaveTestFile(), and OscProb::PMNS_OQS::SetIsNuBar().
SetIsOscProbAvg()
virtual void OscProb::PMNS_SNSI::SetIsOscProbAvg (bool isOscProbAvg) inline virtual
Reimplemented from OscProb::PMNS_Maltoni.
Definition at line 34 of file PMNS_SNSI.h.
References OscProb::PMNS_Maltoni::fIsOscProbAvg.
Referenced by PMNS_SNSI().
SetLayers()
void PMNS_Base::SetLayers (std::vector< int > lay) virtual inherited
Set multiple path layer indices.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
lay - Indices to identify the layer types (e.g. earth inner core)
Definition at line 519 of file PMNS_Base.cxx.
{
  vectorD lay_double(lay.begin(), lay.end());
  SetAtt(lay_double, 3);
}
References OscProb::PMNS_Base::SetAtt().
SetLength() [1/2]
void PMNS_Base::SetLength (double L) virtual inherited
Set the length for a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
L - The length of the path segment in km
Definition at line 391 of file PMNS_Base.cxx.
{ SetAtt(L, 0); }
References OscProb::PMNS_Base::SetAtt().
Referenced by OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::ProbVector().
SetLength() [2/2]
void PMNS_Base::SetLength (vectorD L) virtual inherited
Set multiple path lengths.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
L - The lengths of the path segments in km
Definition at line 486 of file PMNS_Base.cxx.
{ SetAtt(L, 0); }
References OscProb::PMNS_Base::SetAtt().
SetLowestMass()
void PMNS_SNSI::SetLowestMass (double m) virtual
Set lightest neutrino mass
Parameters
m - The lightest mass in eV
Definition at line 37 of file PMNS_SNSI.cxx.
{
  // Check if value is actually changing
  fBuiltHms *= (fM == m);
  fM = m;
}
References OscProb::PMNS_Base::fBuiltHms, and fM.
Referenced by PMNS_SNSI().
SetMaxCache()
void PMNS_Base::SetMaxCache (int mc = 1e6) virtual inherited
Set maximum number of cached eigensystems. Finding eigensystems can become slow and take up memory. This protects the cache from becoming too large.
Parameters
mc - Max cache size (default: 1e6)
Definition at line 128 of file PMNS_Base.cxx.
{ fMaxCache = mc; }
References OscProb::PMNS_Base::fMaxCache.
SetMix()
void PMNS_Fast::SetMix (double th12, double th23, double th13, double deltacp) virtual inherited
Set all mixing parameters at once.
Parameters
th12 - The value of the mixing angle theta_12
th23 - The value of the mixing angle theta_23
th13 - The value of the mixing angle theta_13
deltacp - The value of the CP phase delta_13
Definition at line 37 of file PMNS_Fast.cxx.
{
  SetAngle(1, 2, th12);
  SetAngle(1, 3, th13);
  SetAngle(2, 3, th23);
  SetDelta(1, 3, deltacp);
}
References OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDelta().
SetNSI()
void PMNS_NSI::SetNSI (double eps_ee, double eps_emu, double eps_etau, double eps_mumu, double eps_mutau, double eps_tautau, double delta_emu = 0, double delta_etau = 0, double delta_mutau = 0) inherited
Set all NSI parameters at once.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
eps_ee - The real parameter eps_ee
eps_emu - The absolute value of the complex parameter eps_emu
eps_etau - The absolute value of the complex parameter eps_etau
eps_mumu - The real parameter eps_mumu
eps_mutau - The absolute value of the complex parameter eps_mutau
eps_tautau - The real parameter eps_tautau
delta_emu - The phase of the complex parameter eps_emu in radians
delta_etau - The phase of the complex parameter eps_etau in radians
delta_mutau - The phase of the complex parameter eps_mutau in radians
Definition at line 55 of file PMNS_NSI.cxx.
{
  SetEps(0, 0, eps_ee, 0);
  SetEps(1, 1, eps_mumu, 0);
  SetEps(2, 2, eps_tautau, 0);
  SetEps(0, 1, eps_emu, delta_emu);
  SetEps(0, 2, eps_etau, delta_etau);
  SetEps(1, 2, eps_mutau, delta_mutau);
}
References OscProb::PMNS_NSI::SetEps().
Referenced by OscProb::PMNS_NSI::PMNS_NSI().
SetPath() [1/3]
void PMNS_Base::SetPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Set a single path defining attributes directly.
This destroys the current path sequence and creates a new first path.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 347 of file PMNS_Base.cxx.
{
  SetPath(NuPath(length, density, zoa, layer));
}
References OscProb::PMNS_Base::SetPath().
SetPath() [2/3]
void PMNS_Base::SetPath (NuPath p) virtual inherited
Set a single path.
This destroys the current path sequence and creates a new first path.
Parameters
p - A neutrino path segment
Definition at line 330 of file PMNS_Base.cxx.
{
  ClearPath();
  AddPath(p);
}
References OscProb::PMNS_Base::AddPath(), and OscProb::PMNS_Base::ClearPath().
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), OscProb::PMNS_Base::SetPath(), OscProb::PMNS_Base::SetStdPath(), and SetTestPath().
SetPath() [3/3]
void PMNS_Base::SetPath (std::vector< NuPath > paths) virtual inherited
Set vector of neutrino paths.
Parameters
paths - A sequence of neutrino paths
Definition at line 294 of file PMNS_Base.cxx.
{ fNuPaths = paths; }
References OscProb::PMNS_Base::fNuPaths.
SetPremModel()
void PMNS_Maltoni::SetPremModel (OscProb::PremModel & prem) virtual inherited
Set the earth model to be used.
This is done to get access to the PremLayer list to be used in the LnDerivative() function.
Parameters
prem - The earth model used
Definition at line 84 of file PMNS_Maltoni.cxx.
{ fPrem = prem; }
References OscProb::PMNS_Maltoni::fPrem.
SetPureState()
void PMNS_Base::SetPureState (vectorC nu_in) protected virtual inherited
Set the initial state from a pure state
Parameters
nu_in - The neutrino initial state in flavour basis.
Reimplemented in OscProb::PMNS_DensityMatrix.
Definition at line 1070 of file PMNS_Base.cxx.
{
  assert(nu_in.size() == fNumNus);
  fNuState = nu_in;
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fNuState.
Referenced by OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::ProbVector().
SetStdPars()
void PMNS_Base::SetStdPars () virtual inherited
Set standard oscillation parameters from PDG 2015.
For two neutrinos, Dm is set to the muon disappearance effective mass-splitting and mixing angle.
Definition at line 177 of file PMNS_Base.cxx.
{
  if (fNumNus > 2) {
    // PDG values for 3 neutrinos
    // Also applicable for 3+N neutrinos
    SetAngle(1, 2, asin(sqrt(0.304)));
    SetAngle(1, 3, asin(sqrt(0.0219)));
    SetAngle(2, 3, asin(sqrt(0.514)));
    SetDm(2, 7.53e-5);
    SetDm(3, 2.52e-3);
  }
  else if (fNumNus == 2) {
    // Effective muon disappearance values
    // for two-flavour approximation
    SetAngle(1, 2, 0.788);
    SetDm(2, 2.47e-3);
  }
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDm().
Referenced by OscProb::PMNS_Base::PMNS_Base().
SetStdPath()
void PMNS_Base::SetStdPath () virtual inherited
Set standard single path.
Length is 1000 km, so ~2 GeV peak energy.
Density is approximate from CRUST2.0 (~2.8 g/cm^3). Z/A is set to a round 0.5.
Definition at line 205 of file PMNS_Base.cxx.
{
  NuPath p;
  p.length  = 1000; // 1000 km default
  p.density = 2.8;  // Crust density
  p.zoa     = 0.5;  // Crust Z/A
  p.layer   = 0;    // Single layer
  SetPath(p);
}
References OscProb::NuPath::density, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetPath(), and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_LIV::PMNS_LIV(), OscProb::PMNS_NSI::PMNS_NSI(), OscProb::PMNS_NUNM::PMNS_NUNM(), and OscProb::PMNS_Base::SetAtt().
SetUpCoup()
void PMNS_NSI::SetUpCoup (double u) virtual inherited
Set the NSI relative coupling to u-quarks. This factor represents what fraction of the u-quarks are seen by the interaction.
Parameters
u - u-quark coupling strength
Definition at line 290 of file PMNS_NSI.cxx.
{ SetCoupByIndex(u, 1); }
References OscProb::PMNS_NSI::SetCoupByIndex().
Referenced by OscProb::PMNS_NSI::SetFermCoup().
SetUseCache()
void PMNS_Base::SetUseCache (bool u = true) virtual inherited
Turn on/off caching of eigensystems. This can save a lot of CPU time by avoiding recomputing eigensystems if we've already seen them recently. Especially useful when running over multiple earth layers and even more if multiple baselines will be computed, e.g. for atmospheric neutrinos.
Parameters
u - flag to set caching on (default: true)
Definition at line 105 of file PMNS_Base.cxx.
{ fUseCache = u; }
References OscProb::PMNS_Base::fUseCache.
Referenced by OscProb::PMNS_Base::PMNS_Base().
SetVacuumEigensystem()
void PMNS_Fast::SetVacuumEigensystem () protected virtual inherited
Set the eigensystem to the analytic solution in vacuum.
We know the vacuum eigensystem, so just write it explicitly
Definition at line 154 of file PMNS_Fast.cxx.
{
  double   s12, s23, s13, c12, c23, c13;
  complexD idelta(0.0, fDelta[0][2]);
  if (fIsNuBar) idelta = conj(idelta);
  s12 = sin(fTheta[0][1]);
  s23 = sin(fTheta[1][2]);
  s13 = sin(fTheta[0][2]);
  c12 = cos(fTheta[0][1]);
  c23 = cos(fTheta[1][2]);
  c13 = cos(fTheta[0][2]);
  fEvec[0][0] = c12 * c13;
  fEvec[0][1] = s12 * c13;
  fEvec[0][2] = s13 * exp(-idelta);
  fEvec[1][0] = -s12 * c23 - c12 * s23 * s13 * exp(idelta);
  fEvec[1][1] = c12 * c23 - s12 * s23 * s13 * exp(idelta);
  fEvec[1][2] = s23 * c13;
  fEvec[2][0] = s12 * s23 - c12 * c23 * s13 * exp(idelta);
  fEvec[2][1] = -c12 * s23 - s12 * c23 * s13 * exp(idelta);
  fEvec[2][2] = c23 * c13;
  fEval[0] = 0;
  fEval[1] = fDm[1] / (2 * kGeV2eV * fEnergy);
  fEval[2] = fDm[2] / (2 * kGeV2eV * fEnergy);
}
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fTheta, and OscProb::PMNS_Base::kGeV2eV.
Referenced by OscProb::PMNS_OQS::BuildHms(), OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Iter::SolveHam().
SetwidthBin()
void PMNS_Maltoni::SetwidthBin (double dE, double dcosT) protected virtual inherited
Set bin widths.
Parameters
dE - The width of the energy bin in GeV
dcosT - The width of the cos(theta_z) bin
Definition at line 101 of file PMNS_Maltoni.cxx.
{
  fdInvE = dE;
  fdcosT = dcosT;
}
References OscProb::PMNS_Maltoni::fdcosT, and OscProb::PMNS_Maltoni::fdInvE.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), and OscProb::PMNS_Maltoni::PMNS_Maltoni().
SetZoA() [1/2]
void PMNS_Base::SetZoA (double zoa) virtual inherited
Set single path Z/A.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segment
Definition at line 413 of file PMNS_Base.cxx.
{ SetAtt(zoa, 2); }
References OscProb::PMNS_Base::SetAtt().
SetZoA() [2/2]
void PMNS_Base::SetZoA (vectorD zoa) virtual inherited
Set multiple path Z/A values.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segments
Definition at line 508 of file PMNS_Base.cxx.
{ SetAtt(zoa, 2); }
References OscProb::PMNS_Base::SetAtt().
SolveHam()
void PMNS_Fast::SolveHam () protected virtual inherited
Solve the full Hamiltonian for eigenvectors and eigenvalues.
If vacuum, just use the PMNS matrix, otherwise solve in Matter using GLoBES.
Implements OscProb::PMNS_Base.
Reimplemented in OscProb::PMNS_Iter, and OscProb::PMNS_LIV.
Definition at line 98 of file PMNS_Fast.cxx.
{
  // Do vacuum oscillation in low density
  if (fPath.density < 1.0e-6) {
    SetVacuumEigensystem();
    return;
  }
  SolveHamMatter();
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fPath, OscProb::PMNS_Fast::SetVacuumEigensystem(), and OscProb::PMNS_Fast::SolveHamMatter().
Referenced by OscProb::PMNS_Deco::PropagatePath(), and OscProb::PMNS_OQS::PropagatePath().
SolveHamMatter()
void PMNS_Fast::SolveHamMatter () protected virtual inherited
Solve the full Hamiltonian for eigenvectors and eigenvalues.
This is using a method from the GLoBES software available at http://www.mpi-hd.mpg.de/personalhomes/globes/3x3/
We should cite them accordingly
Definition at line 117 of file PMNS_Fast.cxx.
{
  // Build Hamiltonian
  BuildHms();
  // Check if anything changed
  if (fGotES) return;
  // Try caching if activated
  if (TryCache()) return;
  UpdateHam();
  double   fEvalGLoBES[3];
  complexD fEvecGLoBES[3][3];
  // Solve Hamiltonian for eigensystem using the GLoBES method
  zheevh3(fHam, fEvecGLoBES, fEvalGLoBES);
  // Fill fEval and fEvec vectors from GLoBES arrays
  for (int i = 0; i < fNumNus; i++) {
    fEval[i] = fEvalGLoBES[i];
    for (int j = 0; j < fNumNus; j++) { fEvec[i][j] = fEvecGLoBES[i][j]; }
  }
  fGotES = true;
  // Fill cache if activated
  FillCache();
}
References OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Fast::fHam, OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Fast::UpdateHam(), and zheevh3().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_LIV::SolveHam().
SolveK()
void PMNS_Maltoni::SolveK (Eigen::MatrixXcd & K, vectorD & lambda, matrixC & V) protected inherited
Solve one K matrix for eigenvectors and eigenvalues.
This is using the Eigen methods appropriate for each matrix size.
Parameters
K - The K matrix
lambda - The eigenvalues of K
V - The eigenvectors of K
Definition at line 395 of file PMNS_Maltoni.cxx.
{
  if (fNumNus == 4) TemplateSolver<Eigen::Matrix4cd>(K, lambda, V);
  if (fNumNus == 3) TemplateSolver<Eigen::Matrix3cd>(K, lambda, V);
  if (fNumNus == 2)
    TemplateSolver<Eigen::Matrix2cd>(K, lambda, V);
  else
    TemplateSolver<Eigen::MatrixXcd>(K, lambda, V);
}
References OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), and OscProb::PMNS_Maltoni::ExtrapolationProbLoE().
TemplateSolver()
template<typename T > void PMNS_Maltoni::TemplateSolver (Eigen::MatrixXcd & K, vectorD & lambda, matrixC & V) protected inherited
Auxiliary function to convert a generic Xcd matrix into a specific size so Eigen can optimize the eigensolver method used.
Parameters
K - The K matrix
lambda - The eigenvalues of K
V - The eigenvectors of K
Definition at line 415 of file PMNS_Maltoni.cxx.
{
  Eigen::Ref<T> R(K);
  Eigen::SelfAdjointEigenSolver<T> eigensolver(R);
  // Fill flambdaInvE and fVInvE vectors from GLoBES arrays
  for (int i = 0; i < fNumNus; i++) {
    lambda[i] = eigensolver.eigenvalues()(i);
    for (int j = 0; j < fNumNus; j++) {
      V[i][j] = eigensolver.eigenvectors()(i, j);
    }
  }
}
References OscProb::PMNS_Base::fNumNus.
TryCache()
bool PMNS_Base::TryCache () protected virtual inherited
Try to find a cached version of this eigensystem.
Definition at line 134 of file PMNS_Base.cxx.
{
  if (fUseCache && !fMixCache.empty()) {
    fProbe.SetVars(fEnergy, fPath, fIsNuBar);
    unordered_set<EigenPoint>::iterator it = fMixCache.find(fProbe);
    if (it != fMixCache.end()) {
      for (int i = 0; i < fNumNus; i++) {
        fEval[i] = (*it).fEval[i] * (*it).fEnergy / fEnergy;
        for (int j = 0; j < fNumNus; j++) { fEvec[i][j] = (*it).fEvec[i][j]; }
      }
      return true;
    }
  }
  return false;
}
References OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fMixCache, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::fProbe, OscProb::PMNS_Base::fUseCache, and OscProb::EigenPoint::SetVars().
Referenced by OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHamMatter().
UpdateHam()
void PMNS_SNSI::UpdateHam () protected virtual
Reimplement Hamiltonian update for scalar NSI
Here we divide the mass squared matrix Hms by the 2E to obtain the vacuum Hamiltonian in eV. Then, the matter potential is added to the electron component.
Reimplemented from OscProb::PMNS_NSI.
Definition at line 124 of file PMNS_SNSI.cxx.
{
  double sqrtlv = sqrt(2 * kGeV2eV * fEnergy); // sqrt(2*E) in eV^1/2
  // Effective density of fermions in eV * MeV^2
  double nsiCoup = 1e6 * kK2 * fPath.density * GetZoACoup();
  // Add the dM matrix
  for (int i = 0; i < fNumNus; i++) {
    for (int j = i; j < fNumNus; j++) {
      fHam[i][j] = (fHms[i][j] + nsiCoup * fEps[i][j]) / sqrtlv;
      if (fIsNuBar) fHam[i][j] = conj(fHam[i][j]);
    }
  }
  // Square fHam
  HermitianSquare(fHam);
  // Add matter potential in eV
  double kr2GNe = kK2 * M_SQRT2 * kGf * fPath.density * fPath.zoa;
  if (!fIsNuBar)
    fHam[0][0] += kr2GNe;
  else
    fHam[0][0] -= kr2GNe;
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_NSI::fEps, OscProb::PMNS_Fast::fHam, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_NSI::GetZoACoup(), HermitianSquare(), OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kGf, OscProb::PMNS_Base::kK2, and OscProb::NuPath::zoa.
Member Data Documentation
fAvgProbPrec
double OscProb::PMNS_Base::fAvgProbPrec protected inherited
Definition at line 305 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Maltoni::GetSamplePointsAvgClass(), and OscProb::PMNS_Base::SetAvgProbPrec().
fBuffer
vectorC OscProb::PMNS_Base::fBuffer protected inherited
Definition at line 287 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::PropagatePath(), and OscProb::PMNS_Decay::PropagatePath().
fBuiltHms
bool OscProb::PMNS_Base::fBuiltHms protected inherited
Definition at line 298 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_OQS::BuildHms(), BuildHms(), OscProb::PMNS_Decay::SetAlpha2(), OscProb::PMNS_Decay::SetAlpha3(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_Base::SetDelta(), OscProb::PMNS_Base::SetDm(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Iter::SetIsNuBar(), OscProb::PMNS_OQS::SetIsNuBar(), SetLowestMass(), and OscProb::PMNS_Iter::SolveHam().
fCachePrec
double OscProb::PMNS_Base::fCachePrec protected inherited
Definition at line 302 of file PMNS_Base.h.
fcosT
double OscProb::PMNS_Maltoni::fcosT protected inherited
Definition at line 184 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::LnDerivative(), and OscProb::PMNS_Maltoni::SetCosT().
fdcosT
double OscProb::PMNS_Maltoni::fdcosT protected inherited
Definition at line 187 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), OscProb::PMNS_Maltoni::PropagatePathTaylor(), and OscProb::PMNS_Maltoni::SetwidthBin().
fDelta
matrixD OscProb::PMNS_Base::fDelta protected inherited
Definition at line 281 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::RotateState(), OscProb::PMNS_Base::SetDelta(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fdensityMatrix
matrixC OscProb::PMNS_Maltoni::fdensityMatrix protected inherited
Definition at line 206 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::HadamardProduct(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), and OscProb::PMNS_Maltoni::RotateDensityM().
fDetRadius
double OscProb::PMNS_Maltoni::fDetRadius protected inherited
Definition at line 211 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), and OscProb::PMNS_Maltoni::LnDerivative().
fdInvE
double OscProb::PMNS_Maltoni::fdInvE protected inherited
Definition at line 186 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::PropagatePathTaylor(), and OscProb::PMNS_Maltoni::SetwidthBin().
fdl
int OscProb::PMNS_Maltoni::fdl protected inherited
Definition at line 210 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), and OscProb::PMNS_Maltoni::LnDerivative().
fDm
vectorD OscProb::PMNS_Base::fDm protected inherited
Definition at line 279 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), BuildHms(), OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_Base::GetDm(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Base::SetDm(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fEnergy
double OscProb::PMNS_Base::fEnergy protected inherited
Definition at line 292 of file PMNS_Base.h.
Referenced by OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_OQS::BuildM(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetEnergy(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fEps
complexD OscProb::PMNS_NSI::fEps[3][3] protected inherited
Definition at line 76 of file PMNS_NSI.h.
Referenced by OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_NSI::UpdateHam(), and UpdateHam().
fEval
vectorD OscProb::PMNS_Base::fEval protected inherited
Definition at line 289 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Maltoni::PropagatePathTaylor(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Fast::SolveHamMatter(), and OscProb::PMNS_Base::TryCache().
fEvec
matrixC OscProb::PMNS_Base::fEvec protected inherited
Definition at line 290 of file PMNS_Base.h.
Referenced by OscProb::PMNS_OQS::BuildHms(), OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Maltoni::rotateK(), OscProb::PMNS_Maltoni::rotateS(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Fast::SolveHamMatter(), and OscProb::PMNS_Base::TryCache().
fevolutionMatrixS
matrixC OscProb::PMNS_Maltoni::fevolutionMatrixS protected inherited
Evolution matrix S for reference energy and angle for the entire path
Definition at line 200 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Maltoni::AvgFormulaExtrapolation(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::MultiplicationRuleK(), and OscProb::PMNS_Maltoni::MultiplicationRuleS().
fGotES
bool OscProb::PMNS_Base::fGotES protected inherited
Definition at line 299 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), BuildHms(), OscProb::PMNS_NUNM::SetAlpha(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_NUNM::SetFracVnc(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHamMatter().
fHam
complexD OscProb::PMNS_Fast::fHam[3][3] protected inherited
Definition at line 64 of file PMNS_Fast.h.
Referenced by OscProb::PMNS_Fast::SolveHamMatter(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), and UpdateHam().
fHms
matrixC OscProb::PMNS_Base::fHms protected inherited
Definition at line 284 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), BuildHms(), OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fIsNuBar
bool OscProb::PMNS_Base::fIsNuBar protected inherited
Definition at line 293 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetIsNuBar(), OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Iter::SetIsNuBar(), OscProb::PMNS_OQS::SetIsNuBar(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fIsOscProbAvg
bool OscProb::PMNS_Maltoni::fIsOscProbAvg protected inherited
Definition at line 219 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Maltoni::AvgProbMatrix(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::AvgProbVector(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_DensityMatrix::SetIsOscProbAvg(), OscProb::PMNS_LIV::SetIsOscProbAvg(), OscProb::PMNS_Maltoni::SetIsOscProbAvg(), OscProb::PMNS_NUNM::SetIsOscProbAvg(), and SetIsOscProbAvg().
fKcosT
Eigen::MatrixXcd OscProb::PMNS_Maltoni::fKcosT protected inherited
Definition at line 196 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), and OscProb::PMNS_Maltoni::PropagatePathTaylor().
fKflavor
matrixC OscProb::PMNS_Maltoni::fKflavor protected inherited
Definition at line 204 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::BuildKcosT(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::MultiplicationRuleK(), and OscProb::PMNS_Maltoni::rotateK().
fKInvE
Eigen::MatrixXcd OscProb::PMNS_Maltoni::fKInvE protected inherited
Definition at line 194 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), and OscProb::PMNS_Maltoni::PropagatePathTaylor().
fKmass
matrixC OscProb::PMNS_Maltoni::fKmass protected inherited
Definition at line 203 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), and OscProb::PMNS_Maltoni::rotateK().
flambdaCosT
vectorD OscProb::PMNS_Maltoni::flambdaCosT protected inherited
Definition at line 190 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), and OscProb::PMNS_Maltoni::InitializeTaylorsVectors().
flambdaInvE
vectorD OscProb::PMNS_Maltoni::flambdaInvE protected inherited
Definition at line 189 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), and OscProb::PMNS_Maltoni::InitializeTaylorsVectors().
fLayer
int OscProb::PMNS_Maltoni::fLayer protected inherited
Definition at line 209 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), and OscProb::PMNS_Maltoni::LnDerivative().
fM
double OscProb::PMNS_SNSI::fM protected
Definition at line 46 of file PMNS_SNSI.h.
Referenced by BuildHms(), GetLowestMass(), and SetLowestMass().
fMaxCache
int OscProb::PMNS_Base::fMaxCache protected inherited
Definition at line 303 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::SetMaxCache().
fminRsq
double OscProb::PMNS_Maltoni::fminRsq protected inherited
Definition at line 212 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), and OscProb::PMNS_Maltoni::LnDerivative().
fMixCache
std::unordered_set<EigenPoint> OscProb::PMNS_Base::fMixCache protected inherited
Definition at line 307 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::ClearCache(), OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::TryCache().
fNSIcoup
double OscProb::PMNS_NSI::fNSIcoup[3] protected inherited
Definition at line 78 of file PMNS_NSI.h.
Referenced by OscProb::PMNS_NSI::GetDownCoup(), OscProb::PMNS_NSI::GetElecCoup(), OscProb::PMNS_NSI::GetUpCoup(), OscProb::PMNS_NSI::GetZoACoup(), and OscProb::PMNS_NSI::SetCoupByIndex().
fNumNus
int OscProb::PMNS_Base::fNumNus protected inherited
Definition at line 277 of file PMNS_Base.h.
Referenced by OscProb::PMNS_NUNM::ApplyAlphaDagger(), OscProb::PMNS_Maltoni::AvgFormula(), OscProb::PMNS_Maltoni::AvgFormulaExtrapolation(), OscProb::PMNS_Maltoni::AvgProbVector(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), BuildHms(), OscProb::PMNS_Maltoni::BuildKcosT(), OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_NUNM::GetAlpha(), OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::GetDm(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Maltoni::HadamardProduct(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::MultiplicationRuleK(), OscProb::PMNS_Maltoni::MultiplicationRuleS(), OscProb::PMNS_Base::P(), OscProb::PMNS_DensityMatrix::P(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Decay::PMNS_Decay(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_NUNM::ProbMatrix(), OscProb::PMNS_OQS::ProbMatrix(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Maltoni::PropagatePathTaylor(), OscProb::PMNS_Base::ResetToFlavour(), OscProb::PMNS_DensityMatrix::ResetToFlavour(), OscProb::PMNS_Maltoni::RotateDensityM(), OscProb::PMNS_Maltoni::rotateK(), OscProb::PMNS_Maltoni::rotateS(), OscProb::PMNS_DensityMatrix::RotateState(), OscProb::PMNS_NUNM::SetAlpha(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_Base::SetDelta(), OscProb::PMNS_Base::SetDm(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_DensityMatrix::SetInitialRho(), OscProb::PMNS_Base::SetPureState(), OscProb::PMNS_DensityMatrix::SetPureState(), OscProb::PMNS_Base::SetStdPars(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::SolveHamMatter(), OscProb::PMNS_Maltoni::SolveK(), OscProb::PMNS_Maltoni::TemplateSolver(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fNuPaths
std::vector<NuPath> OscProb::PMNS_Base::fNuPaths protected inherited
Definition at line 295 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Maltoni::AvgProbMatrix(), OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::AvgProbVector(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ClearPath(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), OscProb::PMNS_Base::GetPath(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_NUNM::ProbMatrix(), OscProb::PMNS_OQS::ProbMatrix(), OscProb::PMNS_Base::Propagate(), OscProb::PMNS_Maltoni::PropagateTaylor(), OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
fNuState
vectorC OscProb::PMNS_Base::fNuState protected inherited
Definition at line 283 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::P(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_NUNM::ProbMatrix(), OscProb::PMNS_NUNM::Propagate(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Iter::PropMatter(), OscProb::PMNS_Base::ResetToFlavour(), OscProb::PMNS_Base::RotateState(), and OscProb::PMNS_Base::SetPureState().
fPath
NuPath OscProb::PMNS_Base::fPath protected inherited
Definition at line 296 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Maltoni::AvgProbLoE(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_NSI::GetZoACoup(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fPhases
vectorC OscProb::PMNS_Base::fPhases protected inherited
Definition at line 286 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Maltoni::PropagatePathTaylor(), and OscProb::PMNS_Maltoni::rotateS().
fPrem
OscProb::PremModel OscProb::PMNS_Maltoni::fPrem protected inherited
Definition at line 215 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::LnDerivative(), OscProb::PMNS_Maltoni::PMNS_Maltoni(), and OscProb::PMNS_Maltoni::SetPremModel().
fProbe
EigenPoint OscProb::PMNS_Base::fProbe protected inherited
Definition at line 308 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::TryCache().
fSflavor
matrixC OscProb::PMNS_Maltoni::fSflavor protected inherited
Definition at line 202 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::InitializeTaylorsVectors(), OscProb::PMNS_Maltoni::MultiplicationRuleS(), and OscProb::PMNS_Maltoni::rotateS().
fTheta
matrixD OscProb::PMNS_Base::fTheta protected inherited
Definition at line 280 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::RotateState(), OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fUseCache
bool OscProb::PMNS_Base::fUseCache protected inherited
Definition at line 301 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::SetUseCache(), and OscProb::PMNS_Base::TryCache().
fVcosT
matrixC OscProb::PMNS_Maltoni::fVcosT protected inherited
Definition at line 201 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgAlgoCosT(), OscProb::PMNS_Maltoni::AvgProb(), OscProb::PMNS_Maltoni::ExtrapolationProbCosT(), and OscProb::PMNS_Maltoni::InitializeTaylorsVectors().
fVInvE
matrixC OscProb::PMNS_Maltoni::fVInvE protected inherited
Definition at line 191 of file PMNS_Maltoni.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), and OscProb::PMNS_Maltoni::InitializeTaylorsVectors().
kGeV2eV
const double PMNS_Base::kGeV2eV = 1.0e+09 static protected inherited
Definition at line 217 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Maltoni::AlgorithmDensityMatrix(), OscProb::PMNS_Maltoni::AvgAlgo(), OscProb::PMNS_Maltoni::AvgProbMatrixLoE(), OscProb::PMNS_Maltoni::AvgProbVectorLoE(), OscProb::PMNS_OQS::BuildDissipator(), OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_Maltoni::ExtrapolationProb(), OscProb::PMNS_Maltoni::ExtrapolationProbLoE(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kGf
const double PMNS_Base::kGf = 1.1663787e-05 static protected inherited
Definition at line 220 of file PMNS_Base.h.
Referenced by OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kK2
const double PMNS_Base::kK2 static protected inherited
Initial value:
=
    1e-3 * kNA / pow(kKm2eV, 3)
Definition at line 216 of file PMNS_Base.h.
Referenced by OscProb::PMNS_OQS::BuildHVMB(), OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kKm2eV
const double PMNS_Base::kKm2eV = 1.0 / 1.973269788e-10 static protected inherited
Definition at line 215 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Maltoni::BuildKcosT(), OscProb::PMNS_Maltoni::BuildKE(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_OQS::PropagatePath(), OscProb::PMNS_Maltoni::PropagatePathTaylor(), and OscProb::PMNS_Iter::SetExpVL().
kNA
const double PMNS_Base::kNA = 6.022140857e23 static protected inherited
Definition at line 218 of file PMNS_Base.h.
one
const complexD PMNS_Base::one static protected inherited
Definition at line 212 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_DensityMatrix::ResetToFlavour().
zero
const complexD PMNS_Base::zero static protected inherited
Definition at line 211 of file PMNS_Base.h.
Referenced by OscProb::PMNS_NUNM::GetAlpha(), OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_Decay::PMNS_Decay(), OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_DensityMatrix::ResetToFlavour().
The documentation for this class was generated from the following files:
inc/PMNS_SNSI.h
src/PMNS_SNSI.cxx