OscProb: OscProb::PremModel Class Reference
OscProb::PremModel Class Reference
Implements an earth model with spherical shells.
#include <PremModel.h>
Public Member Functions
PremModel (std::string filename="")
Constructor.
virtual ~PremModel ()
Destructor.
void SetDetPos (double rad, double lat=0, double lon=0)
int FillPath (double cosT, double phi=0)
Fill the path sequence in a vector.
virtual void LoadModel (std::string filename)
Load an earth model from a file.
virtual std::vector< PremLayer > GetPremLayers ()
virtual void SetLayerZoA (int layer, double zoa)
Set Z/A of all layers of a given type.
virtual double GetLayerZoA (int layer)
Get Z/A of all layers of a given type.
virtual void SetTopLayerSize (double thick)
Set the outermost layer thickness in km.
virtual double GetDetRadius ()
virtual std::vector< NuPath > GetNuPath ()
virtual std::vector< NuPath > GetMergedPaths (double prec=0.25)
Get merged path sequence in a vector.
virtual double GetTotalL (double cosT)
Get the total baseline for a given cosTheta.
virtual double GetCosT (double L)
Get the cosTheta for a given total baseline.
virtual void SetRemoveSmallPaths (bool rp=true)
Set tag to remove small paths.
Protected Member Functions
virtual void ClearModel ()
Clear the earth model information.
virtual void AddLayer (double radius, double density, double zoa, double layer)
Add a layer to the model.
virtual void AddPath (double length, PremLayer pl)
Add a path segment to the sequence.
virtual void AddDetLayer ()
Add the detector layer.
virtual void CleanIdentical ()
Clear identical consecutive layers.
ClassDef (PremModel, 1)
virtual void SetDetectorCoordinates (double rad, double lat, double lon)
virtual void AddPathSegment (double length, double density, double zoa, int index)
Add a path segment to the sequence.
ClassDef (EarthModelBase, 1)
Protected Attributes
std::vector< PremLayer > fPremLayers
The layers in the earth model.
int fDetLayer
The layer index of the detector.
std::string fFilename
The input filename.
std::vector< NuPath > fNuPath
The current neutrino path sequence.
double fRadiusMax
Maximum radius in Earth model (in km)
double fDetRadius
The radius where the detector sits (in km)
double fDetLat
The latitude (in rad) where the detector sits.
double fDetLon
The longitude (in rad) where the detector sits.
bool fRemoveSmallPaths
Tag whether to merge small paths.
Static Protected Attributes
static const double DET_TOL = 0.2
The detector position tolerance near boundaries.
Detailed Description
This class implements a spherically symmetric model of the earth using PremLayer's to store spherical shells with different properties.
The class is then able to produce path sequences through the different earth layers as a function of the cosine of the zenith angle with respect to the detector.
The detector can be positioned at any radius within the model and the path sequences will take into account the fact that some layers are above the detector.
By default this implements the model stored in PremTables/prem_default.txt with the detector at the bottom of the ocean layer (radius = 6368 km).
This class inherits from EarthModelBase and can be saved in ROOT files.
Author
jcoelho@apc.in2p3.fr
Definition at line 33 of file PremModel.h.
Constructor & Destructor Documentation
PremModel()
PremModel::PremModel (std::string filename = "")
Constructor.
By default this implements the model stored in PremTables/prem_default.txt with the detector at the bottom of the ocean layer (radius = 6368 km).
Parameters
filename - The txt file containing a table of earth layers
Definition at line 35 of file PremModel.cxx.
                                    : fDetLayer(0)
{
  SetRemoveSmallPaths(false);
  SetDetPos(6368);
  LoadModel(filename);
}
References LoadModel(), SetDetPos(), and OscProb::EarthModelBase::SetRemoveSmallPaths().
~PremModel()
PremModel::~PremModel () virtual
Nothing to clean.
Definition at line 46 of file PremModel.cxx.
{}
Member Function Documentation
AddDetLayer()
void PremModel::AddDetLayer () protected virtual
Add a detector layer at the detector position if needed. If not, set the detector layer to an existing boundary.
Definition at line 73 of file PremModel.cxx.
{
  CleanIdentical();
  fDetLayer = fPremLayers.size() - 1;
  if (fPremLayers.size() && fDetRadius > fPremLayers.back().radius) {
    cerr << "WARNING: Detector must be inside Earth model." << endl
         << "WARNING: Adjusting detector radius from " << fDetRadius
         << " km to " << fPremLayers.back().radius << " km." << endl;
    fDetRadius = fPremLayers.back().radius;
    return;
  }
  for (int i = 0; i < fPremLayers.size(); i++) {
    double radius = fPremLayers[i].radius;
    // See if we passed the detector and decide whether
    // to create a special layer for it
    if (radius > fDetRadius - DET_TOL) {
      fDetLayer = i;
      // If detector is not near boundary, add a special layer
      if (radius > fDetRadius + DET_TOL) {
        PremLayer det_layer = fPremLayers[i];
        det_layer.radius    = fDetRadius;
        fPremLayers.insert(fPremLayers.begin() + fDetLayer, det_layer);
      }
      else if (radius != fDetRadius) {
        // update detector radius
        cerr << "WARNING: Adjusting detector radius from " << fDetRadius
             << " km to " << radius << " km." << endl;
        fDetRadius = radius;
      }
      break;
    }
  }
}
References CleanIdentical(), DET_TOL, fDetLayer, OscProb::EarthModelBase::fDetRadius, fPremLayers, and OscProb::PremLayer::radius.
Referenced by LoadModel(), and SetDetPos().
AddLayer()
void PremModel::AddLayer (double radius, double density, double zoa, double layer) protected virtual
Add a layer to the earth model.
Parameters
radius - The outer radius of the layer in km
density - The density of the layer in g/cm^3
zoa - The effective Z/A value of the layer
layer - An index to identify the matter type (e.g. earth inner core)
Definition at line 167 of file PremModel.cxx.
{
  fPremLayers.push_back(PremLayer(radius, density, zoa, layer));
}
References fPremLayers.
Referenced by LoadModel().
AddPath()
void PremModel::AddPath (double length, PremLayer pl) protected virtual
Add a path segment to the sequence.
For a given PremLayer, adds a path of a given length in that material
Parameters
length - The length of the path segment in km
pl - The layer we are crossing
Definition at line 325 of file PremModel.cxx.
{
  AddPathSegment(length, pl.density, pl.zoa, pl.layer);
}
References OscProb::EarthModelBase::AddPathSegment(), OscProb::PremLayer::density, OscProb::PremLayer::layer, and OscProb::PremLayer::zoa.
Referenced by FillPath().
AddPathSegment()
void EarthModelBase::AddPathSegment (double length, double density, double zoa, int index) protected virtual inherited
Add a path segment to the sequence.
For a given EarthBin, adds a path of a given length in that material
Parameters
length - The length of the path segment in km
density - The density along the path segment
zoa - Z/A along the path segment
index - Index for the matter along the path segment
Definition at line 65 of file EarthModelBase.cxx.
{
  fNuPath.push_back(NuPath(length, density, zoa, index));
}
References OscProb::EarthModelBase::fNuPath.
Referenced by OscProb::EarthModelBinned::AddPath(), and AddPath().
ClassDef() [1/2]
OscProb::EarthModelBase::ClassDef (EarthModelBase , 1) protected inherited
ClassDef() [2/2]
OscProb::PremModel::ClassDef (PremModel , 1) protected
CleanIdentical()
void PremModel::CleanIdentical () protected virtual
Clean identical consecutive layers. This is used in particular to remove previously added detector layers.
Definition at line 54 of file PremModel.cxx.
{
  int i = 0;
  while (i < int(fPremLayers.size()) - 1) {
    if (fPremLayers[i] == fPremLayers[i + 1]) {
      fPremLayers.erase(fPremLayers.begin() + i);
      continue;
    }
    i++;
  }
}
References fPremLayers.
Referenced by AddDetLayer().
ClearModel()
void PremModel::ClearModel () protected virtual
Clear the earth model information.
Definition at line 151 of file PremModel.cxx.
{
  fDetLayer = 0;
  fPremLayers.clear();
}
References fDetLayer, and fPremLayers.
Referenced by LoadModel().
FillPath()
int PremModel::FillPath (double cosT, double phi = 0) virtual
Fill the path sequence in a vector.
This will start at the upper-most layer and find straight paths to the boundary of the next layer down. When reaching the inner-most layer in the given direction, the paths move back to outer layers until hitting the detector.
The path sequence is stored as an attribute and can be retrieved with the function GetNuPath.
Parameters
cosT - The cosine of the zenith angle of the neutrino direction
phi - The azimuthal angle of the neutrino direction (default = 0; not used)
Returns
The number of path segments in the sequence
Implements OscProb::EarthModelBase.
Definition at line 347 of file PremModel.cxx.
{
  // Clear current path sequence
  fNuPath.clear();
  // Do nothing if cosine is unphysical
  if (fabs(cosT) > 1) return 0;
  // Define the minimum path radius
  double minR   = fDetRadius * sqrt(1 - cosT * cosT);
  double minRsq = minR * minR;
  // Set the top layer index
  int toplayer = fPremLayers.size() - 1;
  // Find the inner-most crossed layer
  int minlayer = 0;
  while (fPremLayers[minlayer].radius < minR) minlayer++;
  // Compute the number of path segments needed
  int nsteps = toplayer - fDetLayer;
  if (cosT < 0) nsteps += 2 * (fDetLayer - minlayer) + 1;
  // Start at the top layer and go down
  int layer = toplayer;
  int dl    = -1;
  // Loop over all path segments
  for (int i = 0; i < nsteps; i++) {
    // Get square of the path length between this layer's
    // outer radius and  inner-most radius
    double L1 = pow(fPremLayers[layer].radius, 2) - minRsq;
    // If L1 is negative, outer radius is not crossed.
    // This only happens if detector is at the top layer and the
    // neutrino is coming from above.
    if (L1 < 0) return true;
    // Get square of the path length between this layer's
    // inner radius and  inner-most radius
    double L2 = -minRsq;
    if (layer > 0) L2 += pow(fPremLayers[layer - 1].radius, 2);
    // If L2 is negative, inner radius is not crossed,
    // so set this as the minimum layer.
    bool ismin = (L2 <= 0 && cosT < 0);
    // Store the path segment length
    double dL;
    // If it's the minimum layer, connect two outer radius
    // crossing points. If not, compute difference between
    // inner and outer radius crossings.
    if (ismin)
      dL = 2 * sqrt(L1);
    else if (L2 >= 0)
      dL = sqrt(L1) - sqrt(L2);
    else
      dL = sqrt(L1); // This should never actually happen,
                     // but protect in case L2 is slightly
                     // negative when it should be zero.
                     // e.g. arriving at the detector from above.
    // Add this path segment to the sequence
    AddPath(dL, fPremLayers[layer]);
    // If we reached the inner-most layer,
    // start moving up again.
    if (ismin) dl = 1;
    // Move to next layer
    layer += dl;
  }
  // Return the number of path segments
  return fNuPath.size();
}
References AddPath(), fDetLayer, OscProb::EarthModelBase::fDetRadius, OscProb::EarthModelBase::fNuPath, and fPremLayers.
Referenced by OscProb::PMNS_Avg::AvgAlgo(), OscProb::PMNS_Avg::AvgAlgoCosT(), and OscProb::PMNS_Avg::ExtrapolationProbCosT().
GetCosT()
double EarthModelBase::GetCosT (double L) virtual inherited
Get the cosTheta for a given total baseline.
Given a baseline, find the direction of the neutrino. This could be useful for experiments with fixed baselines for example.
The baseline must be within the range of possible values in this earth model. Will return vertical neutrinos otherwise.
Parameters
L - The total baseline of the neutrino
Definition at line 99 of file EarthModelBase.cxx.
{
  if (L < fRadiusMax - fDetRadius) return 1;
  if (L > fRadiusMax + fDetRadius) return -1;
  return (fRadiusMax * fRadiusMax - fDetRadius * fDetRadius - L * L) /
         (2 * fDetRadius * L);
}
References OscProb::EarthModelBase::fDetRadius, and OscProb::EarthModelBase::fRadiusMax.
GetDetRadius()
double PremModel::GetDetRadius () virtual
Get the radius where the detector sits (in km)
Definition at line 429 of file PremModel.cxx.
{ return fDetRadius; }
References OscProb::EarthModelBase::fDetRadius.
Referenced by OscProb::PMNS_Avg::InitializeTaylorsVectors().
GetLayerZoA()
double PremModel::GetLayerZoA (int layer) virtual
Get the effective Z/A value for all layers of a given type, e.g. all outer-core layers.
Parameters
layer - The index of the layer type
Returns
Z/A corresponding to layer
Definition at line 256 of file PremModel.cxx.
{
  int nlayers = fPremLayers.size();
  // This check assumes the layer types are in increasing order
  if (layer > fPremLayers.back().layer) {
    cerr << "ERROR: Not that many layer types. Returning 0" << endl;
    return 0;
  }
  for (int i = 0; i < nlayers; i++) {
    if (fPremLayers[i].layer != layer)
      continue;
    else
      return fPremLayers[i].zoa;
  }
  // End of vector reached without finding input type
  cerr << "ERROR: layer type not found. Returning 0" << endl;
  return 0;
}
References fPremLayers.
GetMergedPaths()
vector< NuPath > EarthModelBase::GetMergedPaths (double prec = 0.25) virtual inherited
Merge similar paths to reduce number of steps
This method will merge consecutive paths and take their averages until it finds a large enough gap to start a new merged path.
The merged paths will be returned, and the original detailed path will not be changed and will stay stored as an attribute.
Parameters
prec - The precision to merge paths in g/cm^3
Returns
The vector of merged path segments
Definition at line 121 of file EarthModelBase.cxx.
{
  // The output vector
  vector<NuPath> mergedPath;
  // Start with the first path
  NuPath path = fNuPath[0];
  // Track the total length
  double totL = 0;
  // Loop over all paths starting from second
  for (int i = 1; i < fNuPath.size(); i++) {
    // If this path electron density is beyond the tolerance
    if (fabs(path.density * path.zoa - fNuPath[i].density * fNuPath[i].zoa) >
        prec * path.zoa) {
      // Add merged path to vector
      mergedPath.push_back(path);
      // Set this path as new merged path
      path = fNuPath[i];
    }
    else { // If path is within tolerance
      // Merge the path with current merged path
      path = AvgPath(path, fNuPath[i]);
    }
    // Increment total length
    totL += fNuPath[i].length;
  } // End of loop over paths
  // Add the final merged path to vector
  mergedPath.push_back(path);
  // If tag is true, remove small paths
  if (fRemoveSmallPaths) {
    // Start at first path
    int k = 0;
    // While not at the end of vector
    while (k + 1 < mergedPath.size()) {
      // If length is less than 1% of total
      if (mergedPath[k].length < 0.01 * totL) {
        // Merge path with following path
        mergedPath = MergePaths(mergedPath, k, k + 1);
      }
      // If path is long enough skip it
      else
        k++;
    } // End of while loop
  } // End of if statement
  // return the merged vector
  return mergedPath;
}
References OscProb::AvgPath(), OscProb::NuPath::density, OscProb::EarthModelBase::fNuPath, OscProb::EarthModelBase::fRemoveSmallPaths, OscProb::MergePaths(), and OscProb::NuPath::zoa.
GetNuPath()
vector< NuPath > EarthModelBase::GetNuPath () virtual inherited
Get the current neutrino path sequence
Get the current neutrino path sequence
The path needs to be filled for a given cosTheta before calling this function.
Definition at line 52 of file EarthModelBase.cxx.
{ return fNuPath; }
References OscProb::EarthModelBase::fNuPath.
Referenced by OscProb::PMNS_Avg::AvgAlgo(), OscProb::PMNS_Avg::AvgAlgoCosT(), and OscProb::PMNS_Avg::ExtrapolationProbCosT().
GetPremLayers()
vector< PremLayer > PremModel::GetPremLayers () virtual
Get the set of earth layers
Get the set of earth layers
This returns the set of PremLayer's for this earth model and detector position.
Definition at line 145 of file PremModel.cxx.
{ return fPremLayers; }
References fPremLayers.
Referenced by OscProb::PMNS_Avg::InitializeTaylorsVectors(), and OscProb::PMNS_Avg::LnDerivative().
GetTotalL()
double EarthModelBase::GetTotalL (double cosT) virtual inherited
Get the total baseline for a given cosTheta.
Parameters
cosT - The cosine of the neutrino direction
Definition at line 77 of file EarthModelBase.cxx.
{
  if (fabs(cosT) > 1) return 0;
  double sinsqrT = 1 - cosT * cosT;
  return -fDetRadius * cosT +
         sqrt(fRadiusMax * fRadiusMax - fDetRadius * fDetRadius * sinsqrT);
}
References OscProb::EarthModelBase::fDetRadius, and OscProb::EarthModelBase::fRadiusMax.
LoadModel()
void PremModel::LoadModel (std::string filename) virtual
Load an earth model from a file.
By default it loads the model stored in PremTables/prem_default.txt
Parameters
filename - The txt file containing a table of earth layers
Definition at line 181 of file PremModel.cxx.
{
  // Clear the current model
  ClearModel();
  // Use default if no file provided
  if (filename == "") { filename = PREM_DEFAULT; }
  // Open the file
  ifstream fin;
  fin.open(filename.c_str());
  if (!fin) {
    cerr << "ERROR: File " << filename << " not found!" << endl;
    return;
  }
  // Variables for storing table rows
  float radius, density, zoa, layer;
  // Keep track of previous radius
  double rprev = 0;
  // Loop over table rows
  while (fin >> radius >> density >> zoa >> layer) {
    // Radii must be ordered in model file
    if (radius <= rprev) {
      cerr
          << "ERROR: Radii are not sorted in increasing order in the model file"
          << endl;
      ClearModel();
      return;
    }
    // Add this layer to the model
    AddLayer(radius, density, zoa, layer);
  }
  AddDetLayer();
  // Set the maximum radius in the model
  fRadiusMax = fPremLayers.back().radius;
}
References AddDetLayer(), AddLayer(), ClearModel(), fPremLayers, and OscProb::EarthModelBase::fRadiusMax.
Referenced by OscProb::PMNS_Avg::PMNS_Avg(), and PremModel().
SetDetectorCoordinates()
void EarthModelBase::SetDetectorCoordinates (double rad, double lat, double lon) protected virtual inherited
Set the coordinates of the detector (rad = radius in km, lat/lon in deg)
Set the coordinates of the detector: radius in km, latitude in degrees, longitude in degrees
Parameters
rad - The distance from the detector to the Earth's center in km
lat - The latitude of the detector in deg N (between -90 and 90)
lon - The longitude of the detector in deg E (between 0 and 360)
Definition at line 25 of file EarthModelBase.cxx.
{
  // Force radius to be non-negative
  if (rad < 0) {
    cerr << "WARNING: Negative radius detected. Setting to absolute value."
         << endl;
    rad = -rad;
  }
  fDetRadius = rad;
  // Force latitude to be between -90 and 90 deg
  lat -= floor((lat + 90.0) / 360.0) * 360.0;
  if (lat > 90) { lat = 180.0 - lat; }
  fDetLat = lat / 180.0 * M_PI; // convert to radians
  // Force longitude to be between 0 and 360 deg
  lon -= floor(lon / 360.0) * 360.0;
  fDetLon = lon / 180.0 * M_PI; // convert to radians
}
References OscProb::EarthModelBase::fDetLat, OscProb::EarthModelBase::fDetLon, and OscProb::EarthModelBase::fDetRadius.
Referenced by OscProb::EarthModelBinned::SetDetPos(), and SetDetPos().
SetDetPos()
void PremModel::SetDetPos (double rad, double lat = 0, double lon = 0) virtual
Set the detector position (rad = radius in km, lat/lon in deg)
Set the coordinates of the detector: radius in km, latitude in degrees, longitude in degrees The latitude and longitude are not actually used in PremModel functions.
If the position is within 200m of a layer boundary, the detector is considered to be on the boundary. If not, an extra boundary is inserted in the detector position to distinguish what parts of the earth are above and below the detector.
Parameters
rad - The distance from the detector to the Earth's center in km
lat - The latitude of the detector in deg N (between -90 and 90)
lon - The longitude of the detector in deg E (between 0 and 360)
Implements OscProb::EarthModelBase.
Definition at line 131 of file PremModel.cxx.
{
  SetDetectorCoordinates(rad, lat, lon);
  if (fPremLayers.size()) AddDetLayer();
}
References AddDetLayer(), fPremLayers, and OscProb::EarthModelBase::SetDetectorCoordinates().
Referenced by PremModel().
SetLayerZoA()
void PremModel::SetLayerZoA (int layer, double zoa) virtual
Set the effective Z/A value for all layers of a given type.
Use this to change the Z/A of indexed layer, e.g. all outer-core layers
Parameters
layer - The index of the layer type
zoa - The effective Z/A value to use
Definition at line 235 of file PremModel.cxx.
{
  int nlayers = fPremLayers.size();
  // Loop over all layers and change the ones
  // with the given index
  for (int i = 0; i < nlayers; i++) {
    if (fPremLayers[i].layer != layer) continue;
    fPremLayers[i].zoa = zoa;
  }
}
References fPremLayers.
SetRemoveSmallPaths()
void EarthModelBase::SetRemoveSmallPaths (bool rp = true) virtual inherited
Set the boolean to tag whether to remove small paths when merging Small is defined as <1% of the total baseline
Parameters
rp - Boolean value to set
Definition at line 188 of file EarthModelBase.cxx.
{ fRemoveSmallPaths = rp; }
References OscProb::EarthModelBase::fRemoveSmallPaths.
Referenced by OscProb::EarthModelBinned::EarthModelBinned(), and PremModel().
SetTopLayerSize()
void PremModel::SetTopLayerSize (double thick) virtual
Set the radius of the outermost layer of the model.
This usually corresponds to the atmosphere and is useful for computing oscillations with variable neutrino production height.
Parameters
thick - The thickness of the outer layer in km
Definition at line 288 of file PremModel.cxx.
{
  if (thick <= 0) {
    cerr << "WARNING: Layer thickness should be positive. Do nothing." << endl;
    return;
  }
  int nlayers = fPremLayers.size();
  if (nlayers < 1) {
    cerr << "WARNING: PremModel has no layers. Do nothing." << endl;
    return;
  }
  double bottomRadius;
  if (nlayers > 1)
    bottomRadius = fPremLayers[nlayers - 2].radius;
  else
    bottomRadius = 0;
  double topRadius = bottomRadius + thick;
  fPremLayers[nlayers - 1].radius = topRadius;
  // Update max radius
  fRadiusMax = fPremLayers.back().radius;
}
References fPremLayers, and OscProb::EarthModelBase::fRadiusMax.
Member Data Documentation
DET_TOL
const double PremModel::DET_TOL = 0.2 static protected
Define the tolerance of the detector around a boundary when considering whether to add a new layer for the detector position.
Definition at line 81 of file PremModel.h.
Referenced by AddDetLayer().
fDetLat
double OscProb::EarthModelBase::fDetLat protected inherited
Definition at line 78 of file EarthModelBase.h.
Referenced by OscProb::EarthModelBinned::FillPath(), OscProb::EarthModelBase::SetDetectorCoordinates(), and OscProb::EarthModelBinned::SetDetPos().
fDetLayer
int OscProb::PremModel::fDetLayer protected
Definition at line 76 of file PremModel.h.
Referenced by AddDetLayer(), ClearModel(), and FillPath().
fDetLon
double OscProb::EarthModelBase::fDetLon protected inherited
Definition at line 79 of file EarthModelBase.h.
Referenced by OscProb::EarthModelBinned::FillPath(), OscProb::EarthModelBase::SetDetectorCoordinates(), and OscProb::EarthModelBinned::SetDetPos().
fDetRadius
double OscProb::EarthModelBase::fDetRadius protected inherited
Definition at line 77 of file EarthModelBase.h.
Referenced by AddDetLayer(), OscProb::EarthModelBinned::FillPath(), FillPath(), OscProb::EarthModelBase::GetCosT(), GetDetRadius(), OscProb::EarthModelBase::GetTotalL(), OscProb::EarthModelBase::SetDetectorCoordinates(), and OscProb::EarthModelBinned::SetDetPos().
fFilename
std::string OscProb::PremModel::fFilename protected
Definition at line 78 of file PremModel.h.
fNuPath
std::vector<NuPath> OscProb::EarthModelBase::fNuPath protected inherited
Definition at line 74 of file EarthModelBase.h.
Referenced by OscProb::EarthModelBase::AddPathSegment(), OscProb::EarthModelBinned::FillPath(), FillPath(), OscProb::EarthModelBase::GetMergedPaths(), and OscProb::EarthModelBase::GetNuPath().
fPremLayers
std::vector<PremLayer> OscProb::PremModel::fPremLayers protected
Definition at line 74 of file PremModel.h.
Referenced by AddDetLayer(), AddLayer(), CleanIdentical(), ClearModel(), FillPath(), GetLayerZoA(), GetPremLayers(), LoadModel(), SetDetPos(), SetLayerZoA(), and SetTopLayerSize().
fRadiusMax
double OscProb::EarthModelBase::fRadiusMax protected inherited
Definition at line 76 of file EarthModelBase.h.
Referenced by OscProb::EarthModelBinned::FillPath(), OscProb::EarthModelBase::GetCosT(), OscProb::EarthModelBase::GetTotalL(), OscProb::EarthModelBinned::LoadModel(), LoadModel(), and SetTopLayerSize().
fRemoveSmallPaths
bool OscProb::EarthModelBase::fRemoveSmallPaths protected inherited
Definition at line 81 of file EarthModelBase.h.
Referenced by OscProb::EarthModelBase::GetMergedPaths(), and OscProb::EarthModelBase::SetRemoveSmallPaths().
The documentation for this class was generated from the following files:
inc/PremModel.h
src/PremModel.cxx