OscProb: OscProb::PMNS_OQS Class Reference
OscProb::PMNS_OQS Class Reference
Implements neutrino oscillations using an open quantum system approach.
#include <PMNS_OQS.h>
Public Member Functions
PMNS_OQS ()
Constructor.
virtual ~PMNS_OQS ()
Destructor.
virtual void SetPower (int n)
virtual void SetDecoElement (int i, double val)
Set value of the a_i decoherence element in Gell-Mann basis.
virtual void SetDecoAngle (int i, int j, double th)
Set mixing angle between two decoherence parameters a_i, a_j.
virtual int GetPower ()
Get the currently set power-law index for decoherence parameters.
virtual double GetDecoElement (int i)
Get the value of the a_i decoherence parameter in Gell-Mann basis.
virtual double GetDecoAngle (int i, int j)
Get mixing angle between two decoherence parameters a_i, a_j.
virtual double GetHGM (int i, int j)
Get element i,j of the dissipator matrix in Gell-Mann basis.
virtual double GetDissipatorElement (int i, int j)
Get dissipator element in Gell-Mann basis.
virtual void SetIsNuBar (bool isNuBar)
Reimplemented from PMNS_Base.
virtual matrixD ProbMatrix (int nflvi, int nflvf)
Reimplemented from PMNS_DensityMatrix.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E)
Compute the probability matrix.
virtual matrixD ProbMatrix (int nflvi, int nflvf, double E, double L)
Compute the probability matrix.
virtual void SetMix (double th12, double th23, double th13, double deltacp)
Set the all mixing parameters at once.
virtual void SetDeltaMsqrs (double dm21, double dm32)
Set both mass-splittings at once.
virtual double Prob (vectorC nu_in, int flvf)
Compute the probability of nu_in going to flvf.
virtual double Prob (vectorC nu_in, int flvf, double E)
virtual double Prob (vectorC nu_in, int flvf, double E, double L)
virtual double Prob (int flvi, int flvf)
Compute the probability of flvi going to flvf.
virtual double Prob (int flvi, int flvf, double E)
virtual double Prob (int flvi, int flvf, double E, double L)
virtual vectorD ProbVector (vectorC nu_in)
virtual vectorD ProbVector (vectorC nu_in, double E)
flavours for energy E
virtual vectorD ProbVector (vectorC nu_in, double E, double L)
virtual vectorD ProbVector (int flvi)
virtual vectorD ProbVector (int flvi, double E)
virtual vectorD ProbVector (int flvi, double E, double L)
virtual double AvgProb (vectorC nu_in, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProb (int flvi, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual double AvgProbLoE (int flvi, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual vectorD AvgProbVector (vectorC nu_in, double E, double dE=0)
virtual vectorD AvgProbVector (int flvi, double E, double dE=0)
virtual vectorD AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE=0)
Compute the average probability vector over a bin of L/E.
virtual vectorD AvgProbVectorLoE (int flvi, double LoE, double dLoE=0)
Compute the average probability vector over a bin of L/E.
virtual matrixD AvgProbMatrix (int nflvi, int nflvf, double E, double dE=0)
virtual matrixD AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE=0)
Compute the average probability matrix over a bin of L/E.
virtual vectorC GetMassEigenstate (int mi)
Get a neutrino mass eigenstate.
virtual void SetAngle (int i, int j, double th)
Set the mixing angle theta_ij.
virtual void SetDelta (int i, int j, double delta)
Set the CP phase delta_ij.
virtual void SetDm (int j, double dm)
Set the mass-splitting dm_j1 in eV^2.
virtual double GetAngle (int i, int j)
Get the mixing angle theta_ij.
virtual double GetDelta (int i, int j)
Get the CP phase delta_ij.
virtual double GetDm (int j)
Get the mass-splitting dm_j1 in eV^2.
virtual double GetDmEff (int j)
Get the effective mass-splitting dm_j1 in eV^2.
virtual void SetStdPars ()
Set PDG 3-flavor parameters.
virtual void SetEnergy (double E)
Set the neutrino energy in GeV.
virtual double GetEnergy ()
Get the neutrino energy in GeV.
virtual bool GetIsNuBar ()
Get the anti-neutrino flag.
virtual void SetPath (NuPath p)
Set a single path.
virtual void SetPath (double length, double density, double zoa=0.5, int layer=0)
Set a single path.
virtual void SetPath (std::vector< NuPath > paths)
Set a path sequence.
virtual void AddPath (NuPath p)
Add a path to the sequence.
virtual void AddPath (double length, double density, double zoa=0.5, int layer=0)
Add a path to the sequence.
virtual void ClearPath ()
Clear the path vector.
virtual void SetLength (double L)
Set a single path lentgh in km.
virtual void SetLength (vectorD L)
Set multiple path lengths.
virtual void SetDensity (double rho)
Set single path density in g/cm^3.
virtual void SetDensity (vectorD rho)
Set multiple path densities.
virtual void SetZoA (double zoa)
Set Z/A value for single path.
virtual void SetZoA (vectorD zoa)
Set multiple path Z/A values.
virtual void SetLayers (std::vector< int > lay)
Set multiple path layer indices.
virtual void SetStdPath ()
Set standard neutrino path.
virtual std::vector< NuPath > GetPath ()
Get the neutrino path sequence.
virtual vectorD GetSamplePoints (double LoE, double dLoE)
Compute the sample points for a bin of L/E with width dLoE.
virtual void SetUseCache (bool u=true)
Set caching on/off.
virtual void ClearCache ()
Clear the cache.
virtual void SetMaxCache (int mc=1e6)
Set max cache size.
virtual void SetAvgProbPrec (double prec)
Set the AvgProb precision.
Static Public Attributes
static constexpr int SU3_DIM = 9
Dimension of the SU(3) Gell-Mann basis.
Protected Member Functions
virtual void BuildHms ()
Reimplemented from PMNS_Base.
virtual void BuildHVMB (NuPath p)
Build effective Hamiltonian in Vacuum Mass Basis (VMB).
virtual void BuildHGM (NuPath p)
Build effective Hamiltonian in Gell-Mann representation (GM).
virtual void BuildDissipator ()
Build the dissipator in Gell-Mann representation.
virtual void BuildM (NuPath p)
Build the matrix M used in evolution equations.
virtual void RotateState (bool to_mass)
Rotate rho to/from mass basis.
virtual void BuildR ()
Build Gell-Mann representation of density matrix.
virtual void UpdateRho ()
Update density matrix from Gell-Mann representation.
virtual void Propagate ()
Reimplemented from PMNS_Base.
virtual void PropagatePath (NuPath p)
Reimplemented from PMNS_Base.
virtual void ResetToFlavour (int flv)
Reset neutrino state to pure flavour flv.
virtual void SetPureState (vectorC nu_in)
Set the density matrix from a pure state.
virtual void SetInitialRho (matrixC rho_in)
Set the density matrix from an arbitrary state.
virtual double P (int flv)
Return the probability of final state in flavour flv.
virtual void RotateState (bool to_basis, matrixC U)
Rotate rho to/from a given basis.
virtual void RotateState (int i, int j)
Rotate the neutrino state by theta_ij and delta_ij.
virtual void UpdateHam ()
Build the full Hamiltonian.
virtual void SolveHam ()
Solve the full Hamiltonian for eigenvectors and eigenvalues.
virtual void SolveHamMatter ()
Solve the full Hamiltonian in matter.
virtual void SetVacuumEigensystem ()
Set the eigensystem to the analytic solution of the vacuum Hamiltonian.
virtual void InitializeVectors ()
virtual bool TryCache ()
Try to find a cached eigensystem.
virtual void FillCache ()
Cache the current eigensystem.
virtual void SetCurPath (NuPath p)
Set the path currently in use by the class.
virtual void SetAtt (double att, int idx)
Set one of the path attributes.
virtual void SetAtt (vectorD att, int idx)
Set all values of a path attribute.
virtual void RotateH (int i, int j, matrixC &Ham)
Rotate the Hamiltonian by theta_ij and delta_ij.
virtual vectorD GetProbVector ()
virtual std::vector< int > GetSortedIndices (const vectorD x)
Get indices that sort a vector.
virtual vectorD ConvertEtoLoE (double E, double dE)
Protected Attributes
int fPower
Power-law index (n).
vectorD fa
Dissipator parameters |a_i|.
matrixD fcos
cosines ai . aj
vectorD fR
Initial state of density matrix in Gell-Mann basis.
vectorD fRt
Time evolution of density matrix in Gell-Mann basis.
matrixC fUM
PMNS Matrix.
matrixC fHVMB
Effective Hamiltonian in VMB (3x3).
matrixD fHGM
Effective Hamiltonian in GMB (9x9).
matrixD fD
Off-diagonal, 9x9 dissipator.
Eigen::MatrixXd fM
Buffer matrix for exponential.
bool fBuiltDissipator
Flag to rebuild dissipator.
matrixC fRho
The neutrino density matrix state.
matrixC fMBuffer
Some memory buffer for matrix operations.
complexD fHam [3][3]
The full hamiltonian.
int fNumNus
Number of neutrino flavours.
vectorD fDm
m^2_i - m^2_1 in vacuum
matrixD fTheta
theta[i][j] mixing angle
matrixD fDelta
delta[i][j] CP violating phase
vectorC fNuState
The neutrino current state.
matrixC fHms
matrix H*2E in eV^2
vectorC fPhases
Buffer for oscillation phases.
vectorC fBuffer
Buffer for neutrino state tranformations.
vectorD fEval
Eigenvalues of the Hamiltonian.
matrixC fEvec
Eigenvectors of the Hamiltonian.
double fEnergy
Neutrino energy.
bool fIsNuBar
Anti-neutrino flag.
std::vector< NuPath > fNuPaths
Vector of neutrino paths.
NuPath fPath
Current neutrino path.
bool fBuiltHms
Tag to avoid rebuilding Hms.
bool fGotES
Tag to avoid recalculating eigensystem.
bool fUseCache
Flag for whether to use caching.
double fCachePrec
Precision of cache matching.
int fMaxCache
Maximum cache size.
double fAvgProbPrec
AvgProb precision.
std::unordered_set< EigenPoint > fMixCache
Caching set of eigensystems.
EigenPoint fProbe
EigenpPoint to try.
Static Protected Attributes
static const complexD zero
zero in complex
static const complexD one
one in complex
static const double kKm2eV = 1.0 / 1.973269788e-10
km to eV^-1
static const double kK2
mol/GeV^2/cm^3 to eV
static const double kGeV2eV = 1.0e+09
GeV to eV.
static const double kNA = 6.022140857e23
Avogadro constant.
static const double kGf = 1.1663787e-05
G_F in units of GeV^-2.
Detailed Description
Implementation of three-flavor neutrino oscillations in vacuum and matter, incorporating quantum dissipation effects. Based on the formalism described in: https://doi.org/10.48550/arXiv.hep-ph/0208166.
This developement is part of the QGRANT project (ID: 101068013), founded by the HORIZON-MSCA-2021-PF-01-01 programme.
Author
Alba Domi - alba.domi@fau.de
Joao Coelho - jcoelho@apc.in2p3.fr
Definition at line 28 of file PMNS_OQS.h.
Constructor & Destructor Documentation
PMNS_OQS()
PMNS_OQS::PMNS_OQS ()
Constructor.
See also
PMNS_Base::PMNS_Base
This class is restricted to 3 neutrino flavours.
Definition at line 27 of file PMNS_OQS.cxx.
    : PMNS_DensityMatrix(), fUM(3, vectorC(3, 0)), fHVMB(3, vectorC(3, 0)),
      fHGM(SU3_DIM, vectorD(SU3_DIM, 0)), fD(SU3_DIM, vectorD(SU3_DIM, 0)),
      fcos(SU3_DIM, vectorD(SU3_DIM, 1)), fa(SU3_DIM, 0), fR(SU3_DIM),
      fRt(SU3_DIM), fM(8, 8)
{
  SetPower(0);
  fBuiltDissipator = false;
}
References fBuiltDissipator, and SetPower().
~PMNS_OQS()
PMNS_OQS::~PMNS_OQS () virtual
Nothing to clean.
Definition at line 41 of file PMNS_OQS.cxx.
{}
Member Function Documentation
AddPath() [1/2]
void PMNS_Base::AddPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Add a path to the sequence defining attributes directly.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 317 of file PMNS_Base.cxx.
{
  AddPath(NuPath(length, density, zoa, layer));
}
References OscProb::PMNS_Base::AddPath().
AddPath() [2/2]
void PMNS_Base::AddPath (NuPath p) virtual inherited
Add a path to the sequence.
Parameters
p - A neutrino path segment
Definition at line 307 of file PMNS_Base.cxx.
{ fNuPaths.push_back(p); }
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::SetAtt(), OscProb::PMNS_Base::SetPath(), and SetTestPath().
AvgProb() [1/2]
double PMNS_Base::AvgProb (int flvi, int flvf, double E, double dE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Reimplemented in OscProb::PMNS_Avg, and OscProb::PMNS_Avg.
Definition at line 1500 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProb(fNuState, flvf, E, dE);
}
References OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProb() [2/2]
double PMNS_Base::AvgProb (vectorC nu_in, int flvf, double E, double dE = 0) virtual inherited
Compute the average probability of nu_in going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Reimplemented in OscProb::PMNS_Avg.
Definition at line 1568 of file PMNS_Base.cxx.
{
  // Do nothing if energy is not positive
  if (E <= 0) return 0;
  if (fNuPaths.empty()) return 0;
  // Don't average zero width
  if (dE <= 0) return Prob(nu_in, flvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbLoE(nu_in, flvf, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::Prob().
Referenced by OscProb::PMNS_Base::AvgProb(), CheckProb(), and SaveTestFile().
AvgProbLoE() [1/2]
double PMNS_Base::AvgProbLoE (int flvi, int flvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Reimplemented in OscProb::PMNS_Avg, and OscProb::PMNS_Avg.
Definition at line 1610 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbLoE(fNuState, flvf, LoE, dLoE);
}
References OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProbLoE() [2/2]
double PMNS_Base::AvgProbLoE (vectorC nu_in, int flvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of nu_in going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino intial state in flavour basis.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Reimplemented in OscProb::PMNS_Avg.
Definition at line 1643 of file PMNS_Base.cxx.
{
  // Do nothing if L/E is not positive
  if (LoE <= 0) return 0;
  if (fNuPaths.empty()) return 0;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length / LoE);
  // Don't average zero width
  if (dLoE <= 0) return Prob(nu_in, flvf);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw   = 0;
  double prob   = 0;
  double length = fPath.length;
  // Loop over all sample points
  for (int j = 0; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    // Add weighted probability
    prob += w * Prob(nu_in, flvf, length / samples[j]);
    // Increment sum of weights
    sumw += w;
  }
  // Return weighted average of probabilities
  return prob / sumw;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProb(), and OscProb::PMNS_Base::AvgProbLoE().
AvgProbMatrix()
matrixD PMNS_Base::AvgProbMatrix (int nflvi, int nflvf, double E, double dE = 0) virtual inherited
Compute the average probability matrix over a bin of energy
Compute the average probability matrix for nflvi and nflvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Avg.
Definition at line 1861 of file PMNS_Base.cxx.
{
  matrixD probs(nflvi, vectorD(nflvf, 0));
  // Do nothing if energy is not positive
  if (E <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Don't average zero width
  if (dE <= 0) return ProbMatrix(nflvi, nflvf, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbMatrixLoE(nflvi, nflvf, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::ProbMatrix().
AvgProbMatrixLoE()
matrixD PMNS_Base::AvgProbMatrixLoE (int nflvi, int nflvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability matrix for nflvi and nflvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Avg.
Definition at line 1900 of file PMNS_Base.cxx.
{
  matrixD probs(nflvi, vectorD(nflvf, 0));
  // Do nothing if L/E is not positive
  if (LoE <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length / LoE);
  // Don't average zero width
  if (dLoE <= 0) return ProbMatrix(nflvi, nflvf);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw   = 0;
  double length = fPath.length;
  // Loop over all sample points
  for (int j = 0; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    matrixD sample_probs = ProbMatrix(nflvi, nflvf, length / samples[j]);
    for (int flvi = 0; flvi < nflvi; flvi++) {
      for (int flvf = 0; flvf < nflvf; flvf++) {
        // Add weighted probability
        probs[flvi][flvf] += w * sample_probs[flvi][flvf];
      }
    }
    // Increment sum of weights
    sumw += w;
  }
  for (int flvi = 0; flvi < nflvi; flvi++) {
    for (int flvf = 0; flvf < nflvf; flvf++) {
      // Divide by total sampling weight
      probs[flvi][flvf] /= sumw;
    }
  }
  // Return weighted average of probabilities
  return probs;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProbMatrix().
AvgProbVector() [1/2]
vectorD PMNS_Base::AvgProbVector (int flvi, double E, double dE = 0) virtual inherited
Compute the average probability vector over a bin of energy
Compute the average probability of nu_in going to all flavours over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Avg, and OscProb::PMNS_Avg.
Definition at line 1729 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbVector(fNuState, E, dE);
}
References OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProbVector() [2/2]
vectorD PMNS_Base::AvgProbVector (vectorC nu_in, double E, double dE = 0) virtual inherited
Compute the average probability vector over a bin of energy
Compute the average probability of nu_in going to all flavours over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller energy ranges.
Parameters
nu_in - The neutrino initial state in flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Avg.
Definition at line 1753 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if energy is not positive
  if (E <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Don't average zero width
  if (dE <= 0) return ProbVector(nu_in, E);
  vectorD LoEbin = ConvertEtoLoE(E, dE);
  // Compute average in LoE
  return AvgProbVectorLoE(nu_in, LoEbin[0], LoEbin[1]);
}
References OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::ProbVector().
Referenced by OscProb::PMNS_Base::AvgProbVector().
AvgProbVectorLoE() [1/2]
vectorD PMNS_Base::AvgProbVectorLoE (int flvi, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of flvi going to all flavours over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
flvi - The neutrino starting flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Avg, and OscProb::PMNS_Avg.
Definition at line 1705 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  return AvgProbVectorLoE(fNuState, LoE, dLoE);
}
References OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::ResetToFlavour().
AvgProbVectorLoE() [2/2]
vectorD PMNS_Base::AvgProbVectorLoE (vectorC nu_in, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of nu_in going to all flavours over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function works best for single paths. In multiple paths the accuracy may be somewhat worse. If needed, average over smaller L/E ranges.
Parameters
nu_in - The neutrino intial state in flavour basis.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probabilities
Reimplemented in OscProb::PMNS_Avg.
Definition at line 1791 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus, 0);
  // Do nothing if L/E is not positive
  if (LoE <= 0) return probs;
  if (fNuPaths.empty()) return probs;
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Set the energy at bin center
  SetEnergy(fPath.length / LoE);
  // Don't average zero width
  if (dLoE <= 0) return ProbVector(nu_in);
  // Get sample points for this bin
  vectorD samples = GetSamplePoints(LoE, dLoE);
  // Variables to fill sample
  // probabilities and weights
  double sumw   = 0;
  double length = fPath.length;
  // Loop over all sample points
  for (int j = 0; j < int(samples.size()); j++) {
    // Set (L/E)^-2 weights
    double w = 1. / pow(samples[j], 2);
    vectorD sample_probs = ProbVector(nu_in, length / samples[j]);
    for (int i = 0; i < fNumNus; i++) {
      // Add weighted probability
      probs[i] += w * sample_probs[i];
    }
    // Increment sum of weights
    sumw += w;
  }
  for (int i = 0; i < fNumNus; i++) {
    // Divide by total sampling weight
    probs[i] /= sumw;
  }
  // Return weighted average of probabilities
  return probs;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProbVector(), and OscProb::PMNS_Base::AvgProbVectorLoE().
BuildDissipator()
void PMNS_OQS::BuildDissipator () protected virtual
Build dissipator in Gell-Mann representation.
Definition at line 343 of file PMNS_OQS.cxx.
{
  if (fBuiltDissipator) return;
  double aa[SU3_DIM][SU3_DIM];
  for (int i = 1; i < SU3_DIM; i++) {
    for (int j = i; j < SU3_DIM; j++) {
      aa[i][j] = fa[i] * fa[j];
      if (i == 8) aa[i][j] *= sqrt(3);
      if (j == 8) aa[i][j] *= sqrt(3);
      if (i < j) aa[i][j] *= fcos[i][j];
    }
  }
  double sum12   = aa[1][1] + aa[2][2];
  double sum45   = aa[4][4] + aa[5][5];
  double sum67   = aa[6][6] + aa[7][7];
  double gamma21 = aa[3][3];
  double gamma31 = (aa[3][3] + aa[8][8] + 2 * aa[3][8]) / 4;
  double gamma32 = (aa[3][3] + aa[8][8] - 2 * aa[3][8]) / 4;
  fD[1][1] = gamma21 + aa[2][2] + (sum45 + sum67) / 4;
  fD[2][2] = gamma21 + aa[1][1] + (sum45 + sum67) / 4;
  fD[3][3] = sum12 + (sum45 + sum67) / 4;
  fD[4][4] = gamma31 + aa[5][5] + (sum12 + sum67) / 4;
  fD[5][5] = gamma31 + aa[4][4] + (sum12 + sum67) / 4;
  fD[6][6] = gamma32 + aa[7][7] + (sum12 + sum45) / 4;
  fD[7][7] = gamma32 + aa[6][6] + (sum12 + sum45) / 4;
  fD[8][8] = (sum45 + sum67) * 3 / 4;
  fD[3][8] = (sum45 - sum67) * sqrt(3) / 4;
  fD[1][2] = -aa[1][2];
  fD[1][3] = -aa[1][3];
  fD[2][3] = -aa[2][3];
  fD[4][5] = -aa[4][5];
  fD[6][7] = -aa[6][7];
  fD[1][8] = (aa[4][6] + aa[5][7]) * sqrt(3) / 2;
  fD[2][8] = (aa[5][6] - aa[4][7]) * sqrt(3) / 2;
  fD[4][6] = -(aa[4][6] - 2 * aa[1][8] - 3 * aa[5][7]) / 4;
  fD[4][7] = -(aa[4][7] + 2 * aa[2][8] + 3 * aa[5][6]) / 4;
  fD[5][6] = -(aa[5][6] - 2 * aa[2][8] + 3 * aa[4][7]) / 4;
  fD[5][7] = -(aa[5][7] - 2 * aa[1][8] - 3 * aa[4][6]) / 4;
  fD[1][4] = -(aa[1][4] - 3 * (aa[2][5] - aa[3][6]) + aa[6][8]) / 4;
  fD[1][5] = -(aa[1][5] + 3 * (aa[2][4] + aa[3][7]) + aa[7][8]) / 4;
  fD[1][6] = -(aa[1][6] + 3 * (aa[2][7] - aa[3][4]) + aa[4][8]) / 4;
  fD[1][7] = -(aa[1][7] - 3 * (aa[2][6] + aa[3][5]) + aa[5][8]) / 4;
  fD[2][4] = -(aa[2][4] + 3 * (aa[1][5] - aa[3][7]) - aa[7][8]) / 4;
  fD[2][5] = -(aa[2][5] - 3 * (aa[1][4] - aa[3][6]) + aa[6][8]) / 4;
  fD[2][6] = -(aa[2][6] - 3 * (aa[1][7] + aa[3][5]) + aa[5][8]) / 4;
  fD[2][7] = -(aa[2][7] + 3 * (aa[1][6] + aa[3][4]) - aa[4][8]) / 4;
  fD[3][4] = -(aa[3][4] - 3 * (aa[1][6] - aa[2][7]) + aa[4][8]) / 4;
  fD[3][5] = -(aa[3][5] - 3 * (aa[1][7] + aa[2][6]) + aa[5][8]) / 4;
  fD[3][6] = -(aa[3][6] + 3 * (aa[1][4] + aa[2][5]) - aa[6][8]) / 4;
  fD[3][7] = -(aa[3][7] + 3 * (aa[1][5] - aa[2][4]) - aa[7][8]) / 4;
  fD[4][8] = -(aa[1][6] - aa[2][7] + aa[3][4] + aa[4][8]) * sqrt(3) / 4;
  fD[5][8] = -(aa[1][7] + aa[2][6] + aa[3][5] + aa[5][8]) * sqrt(3) / 4;
  fD[6][8] = -(aa[1][4] + aa[2][5] - aa[3][6] + aa[6][8]) * sqrt(3) / 4;
  fD[7][8] = -(aa[1][5] - aa[2][4] - aa[3][7] + aa[7][8]) * sqrt(3) / 4;
  for (int j = 1; j < SU3_DIM; j++) {
    for (int k = j; k < SU3_DIM; k++) {
      fD[j][k] = -fD[j][k] * kGeV2eV;
      fD[k][j] = fD[j][k];
    }
  }
  fBuiltDissipator = true;
}
References fa, fBuiltDissipator, fcos, fD, OscProb::PMNS_Base::kGeV2eV, and SU3_DIM.
Referenced by BuildM().
BuildHGM()
void PMNS_OQS::BuildHGM (NuPath p) protected virtual
Build the effective Hamiltonian in Gell-Mann representation.
Parameters
p - Neutrino path segment.
Definition at line 333 of file PMNS_OQS.cxx.
{
  BuildHVMB(p);
  get_GMOP(fHVMB, fHGM);
}
References BuildHVMB(), fHGM, fHVMB, and get_GMOP().
Referenced by BuildM().
BuildHms()
void PMNS_OQS::BuildHms () protected virtual
Reimplement from PMNS_Base and save the PMNS matrix for later use.
Reimplemented from OscProb::PMNS_Base.
Definition at line 187 of file PMNS_OQS.cxx.
{
  if (fBuiltHms) return;
  SetVacuumEigensystem();
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) { fUM[i][j] = conj(fEvec[i][j]); }
  }
  PMNS_Base::BuildHms();
}
References OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fEvec, fUM, and OscProb::PMNS_Fast::SetVacuumEigensystem().
Referenced by BuildHVMB(), and RotateState().
BuildHVMB()
void PMNS_OQS::BuildHVMB (NuPath p) protected virtual
Build the effective Hamiltonian in VMB for a given propagation path.
Parameters
p - Neutrino path segment.
Definition at line 203 of file PMNS_OQS.cxx.
{
  // Set the neutrino path
  SetCurPath(p);
  double kr2GNe = kK2 * M_SQRT2 * kGf;
  kr2GNe *= fPath.density * fPath.zoa; // Matter potential in eV
  double Ve = 0;
  if (!fIsNuBar)
    Ve = kr2GNe;
  else
    Ve = -kr2GNe;
  BuildHms();
  for (int i = 0; i < 3; i++) {
    for (int j = i; j < 3; j++) {
      fHVMB[i][j] = conj(fUM[0][i]) * Ve * fUM[0][j];
      if (i > j) fHVMB[j][i] = conj(fHVMB[i][j]);
    }
  }
  double lv = 2 * kGeV2eV * fEnergy; // 2E in eV
  // add mass terms
  fHVMB[1][1] += fDm[1] / lv;
  fHVMB[2][2] += fDm[2] / lv;
}
References BuildHms(), OscProb::NuPath::density, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, fHVMB, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fPath, fUM, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kGf, OscProb::PMNS_Base::kK2, OscProb::PMNS_Base::SetCurPath(), and OscProb::NuPath::zoa.
Referenced by BuildHGM().
BuildM()
void PMNS_OQS::BuildM (NuPath p) protected virtual
Build the matrix M used in evolution equations.
Parameters
p - Neutrino path segment.
Definition at line 423 of file PMNS_OQS.cxx.
{
  BuildHGM(p);
  BuildDissipator();
  double energyCorr = pow(fEnergy, fPower);
  for (int k = 1; k < SU3_DIM; ++k) {
    for (int j = 1; j < SU3_DIM; ++j) {
      fM(k - 1, j - 1) = fHGM[k][j] + fD[k][j] * energyCorr;
    }
  }
}
References BuildDissipator(), BuildHGM(), fD, OscProb::PMNS_Base::fEnergy, fHGM, fM, fPower, and SU3_DIM.
Referenced by PropagatePath().
BuildR()
void PMNS_OQS::BuildR () protected virtual
Build Gell-Mann representation of density matrix.
Definition at line 439 of file PMNS_OQS.cxx.
{ get_GM(fRho, fR); }
References fR, OscProb::PMNS_DensityMatrix::fRho, and get_GM().
Referenced by RotateState().
ClearCache()
void PMNS_Base::ClearCache () virtual inherited
Clear the cache
Definition at line 111 of file PMNS_Base.cxx.
{
  fMixCache.clear();
  // Set some better hash table parameters
  fMixCache.max_load_factor(0.25);
  fMixCache.reserve(512);
}
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_NUNM::SetAlpha(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_NSI::SetEps(), and OscProb::PMNS_NUNM::SetFracVnc().
ClearPath()
void PMNS_Base::ClearPath () virtual inherited
Clear the path vector.
Definition at line 287 of file PMNS_Base.cxx.
{ fNuPaths.clear(); }
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
ConvertEtoLoE()
vectorD PMNS_Base::ConvertEtoLoE (double E, double dE) protected virtual inherited
Convert a bin of energy into a bin of L/E
Parameters
E - energy bin center in GeV
dE - energy bin width in GeV
Returns
The L/E bin center and width in km/GeV
Definition at line 1516 of file PMNS_Base.cxx.
{
  // Make sure fPath is set
  // Use average if multiple paths
  SetCurPath(AvgPath(fNuPaths));
  // Define L/E variables
  vectorD LoEbin(2);
  // Set a minimum energy
  double minE = 0.1 * E;
  // Transform range to L/E
  // Full range if low edge > minE
  if (E - dE / 2 > minE) {
    LoEbin[0] =
        0.5 * (fPath.length / (E - dE / 2) + fPath.length / (E + dE / 2));
    LoEbin[1] = fPath.length / (E - dE / 2) - fPath.length / (E + dE / 2);
  }
  // Else start at minE
  else {
    LoEbin[0] = 0.5 * (fPath.length / minE + fPath.length / (E + dE / 2));
    LoEbin[1] = fPath.length / minE - fPath.length / (E + dE / 2);
  }
  return LoEbin;
}
References OscProb::AvgPath(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::NuPath::length, and OscProb::PMNS_Base::SetCurPath().
Referenced by OscProb::PMNS_Avg::AvgProb(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Avg::AvgProbMatrix(), OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Avg::AvgProbVector(), and OscProb::PMNS_Base::AvgProbVector().
FillCache()
void PMNS_Base::FillCache () protected virtual inherited
If using caching, save the eigensystem in memory
Reimplemented in OscProb::PMNS_LIV, and OscProb::PMNS_SNSI.
Definition at line 157 of file PMNS_Base.cxx.
{
  if (fUseCache) {
    if (fMixCache.size() > fMaxCache) { fMixCache.erase(fMixCache.begin()); }
    fProbe.SetVars(fEnergy, fPath, fIsNuBar);
    for (int i = 0; i < fNumNus; i++) {
      fProbe.fEval[i] = fEval[i];
      for (int j = 0; j < fNumNus; j++) { fProbe.fEvec[i][j] = fEvec[i][j]; }
    }
    fMixCache.insert(fProbe);
  }
}
References OscProb::PMNS_Base::fEnergy, OscProb::EigenPoint::fEval, OscProb::PMNS_Base::fEval, OscProb::EigenPoint::fEvec, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fMaxCache, OscProb::PMNS_Base::fMixCache, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::fProbe, OscProb::PMNS_Base::fUseCache, and OscProb::EigenPoint::SetVars().
Referenced by OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHamMatter().
GetAngle()
double PMNS_Base::GetAngle (int i, int j) virtual inherited
Get the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of theta_ij
Definition at line 570 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Theta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fTheta[i - 1][j - 1];
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
GetDecoAngle()
double PMNS_OQS::GetDecoAngle (int i, int j) virtual
Get mixing angle between two decoherence vectors a_i and a_j.
Parameters
i - First index in GM representation in range [1, 8].
j - Second index in GM representation in range [2, 8].
Returns
Decoherence angle between a_i and a_j.
Definition at line 122 of file PMNS_OQS.cxx.
{
  THROW_ON_INVALID_ARG(i > 0, i);
  THROW_ON_INVALID_ARG(i < SU3_DIM, i, SU3_DIM);
  THROW_ON_INVALID_ARG(j > 0, i);
  THROW_ON_INVALID_ARG(j < SU3_DIM, j, SU3_DIM);
  THROW_ON_INVALID_ARG(i != j, i, j);
  return acos(fcos[i][j]);
}
References fcos, SU3_DIM, and THROW_ON_INVALID_ARG.
GetDecoElement()
double PMNS_OQS::GetDecoElement (int i) virtual
Get the value of a_i decoherence parameter in GM representation.
Parameters
i - Index of the parameter in range [1, 8].
Returns
Decoherence parameter a_i.
Definition at line 105 of file PMNS_OQS.cxx.
{
  THROW_ON_INVALID_ARG(i > 0, i);
  THROW_ON_INVALID_ARG(i < SU3_DIM, i, SU3_DIM);
  return fa[i];
}
References fa, SU3_DIM, and THROW_ON_INVALID_ARG.
GetDelta()
double PMNS_Base::GetDelta (int i, int j) virtual inherited
Get the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of delta_ij
Definition at line 638 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Delta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  if (i + 1 == j) {
    cerr << "WARNING: Rotation " << i << j << " is real. Returning zero."
         << endl;
    return 0;
  }
  return fDelta[i - 1][j - 1];
}
References OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
GetDissipatorElement()
double PMNS_OQS::GetDissipatorElement (int i, int j) virtual
Get specific element of the dissipator matrix in the GM representation.
Parameters
i Row index in range [0, 8].
j Column index in range [0, 8].
Returns
Dissipator element i,j.
Definition at line 161 of file PMNS_OQS.cxx.
{
  THROW_ON_INVALID_ARG(i >= 0, i);
  THROW_ON_INVALID_ARG(i < SU3_DIM, i, SU3_DIM);
  THROW_ON_INVALID_ARG(j >= 0, i);
  THROW_ON_INVALID_ARG(j < SU3_DIM, j, SU3_DIM);
  return fD[i][j];
}
References fD, SU3_DIM, and THROW_ON_INVALID_ARG.
GetDm()
double PMNS_Base::GetDm (int j) virtual inherited
Get the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 696 of file PMNS_Base.cxx.
{
  if (j < 2 || j > fNumNus) {
    cerr << "ERROR: Dm" << j << "1 not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  return fDm[j - 1];
}
References OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
GetDmEff()
double PMNS_Base::GetDmEff (int j) virtual inherited
Get the effective mass-splitting dm_j1 in matter in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 732 of file PMNS_Base.cxx.
{
  if (j < 2 || j > fNumNus) {
    cerr << "ERROR: Dm_" << j << "1 not valid for " << fNumNus
         << " neutrinos. Returning zero." << endl;
    return 0;
  }
  // Solve the Hamiltonian to update eigenvalues
  SolveHam();
  // Sort eigenvalues in same order as vacuum Dm^2
  vectorI dm_idx = GetSortedIndices(fDm);
  vectorD dm_idx_double(dm_idx.begin(), dm_idx.end());
  dm_idx         = GetSortedIndices(dm_idx_double);
  vectorI ev_idx = GetSortedIndices(fEval);
  // Return difference in eigenvalues * 2E
  return (fEval[ev_idx[dm_idx[j - 1]]] - fEval[ev_idx[dm_idx[0]]]) * 2 *
         fEnergy * kGeV2eV;
}
References OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::GetSortedIndices(), OscProb::PMNS_Base::kGeV2eV, and OscProb::PMNS_Base::SolveHam().
GetEnergy()
double PMNS_Base::GetEnergy () virtual inherited
Get the neutrino energy in GeV.
Definition at line 255 of file PMNS_Base.cxx.
{ return fEnergy; }
References OscProb::PMNS_Base::fEnergy.
GetHGM()
double PMNS_OQS::GetHGM (int i, int j) virtual
Get element of the Hamiltonian in GM representation.
Parameters
i - Row index in range [0, 8].
j - Column index in range [0, 8].
Returns
Hamiltonian element i,j in GM representation.
Definition at line 142 of file PMNS_OQS.cxx.
{
  THROW_ON_INVALID_ARG(i >= 0, i);
  THROW_ON_INVALID_ARG(i < SU3_DIM, i, SU3_DIM);
  THROW_ON_INVALID_ARG(j >= 0, i);
  THROW_ON_INVALID_ARG(j < SU3_DIM, j, SU3_DIM);
  return fHGM[i][j];
}
References fHGM, SU3_DIM, and THROW_ON_INVALID_ARG.
GetIsNuBar()
bool PMNS_Base::GetIsNuBar () virtual inherited
Get the anti-neutrino flag.
Definition at line 261 of file PMNS_Base.cxx.
{ return fIsNuBar; }
References OscProb::PMNS_Base::fIsNuBar.
GetMassEigenstate()
vectorC PMNS_Base::GetMassEigenstate (int mi) virtual inherited
Get the neutrino mass eigenstate in vacuum
States are:
  0 = m_1, 1 = m_2, 2 = m_3, etc.
Parameters
mi - the mass eigenstate index
Returns
The mass eigenstate
Definition at line 795 of file PMNS_Base.cxx.
{
  vectorC oldState = fNuState;
  ResetToFlavour(mi);
  for (int j = 0; j < fNumNus; j++) {
    for (int i = 0; i < j; i++) { RotateState(i, j); }
  }
  vectorC newState = fNuState;
  fNuState         = oldState;
  return newState;
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_Base::RotateState().
GetPath()
vector< NuPath > PMNS_Base::GetPath () virtual inherited
Get the vector of neutrino paths.
Definition at line 300 of file PMNS_Base.cxx.
{ return fNuPaths; }
References OscProb::PMNS_Base::fNuPaths.
GetPower()
int PMNS_OQS::GetPower () virtual
Get the currently set power-law index for decoherence parameters.
Returns
Power-law index.
Definition at line 95 of file PMNS_OQS.cxx.
{ return fPower; }
References fPower.
GetProbVector()
vectorD PMNS_Base::GetProbVector () protected virtual inherited
Return vector of probabilities from final state
Get the vector of probabilities for current state
Returns
Neutrino oscillation probabilities
Definition at line 1233 of file PMNS_Base.cxx.
{
  vectorD probs(fNumNus);
  for (int i = 0; i < probs.size(); i++) { probs[i] = P(i); }
  return probs;
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::P().
Referenced by OscProb::PMNS_Base::ProbVector().
GetSamplePoints()
vectorD PMNS_Base::GetSamplePoints (double LoE, double dLoE) virtual inherited
Compute the sample points for a bin of L/E with width dLoE
This is used for averaging the probability over a bin of L/E. It should be a private function, but I'm keeping it public for now for debugging purposes. The number of sample points seems too high for most purposes. The number of subdivisions needs to be optimized.
Parameters
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Definition at line 1985 of file PMNS_Base.cxx.
{
  // Solve Hamiltonian to get eigenvalues
  SolveHam();
  // Define conversion factor [km/GeV -> 1/(4 eV^2)]
  const double k1267 = kKm2eV / (4 * kGeV2eV);
  // Get list of all effective Dm^2
  vectorD effDm;
  for (int i = 0; i < fNumNus - 1; i++) {
    for (int j = i + 1; j < fNumNus; j++) {
      effDm.push_back(2 * kGeV2eV * fEnergy * fabs(fEval[j] - fEval[i]));
    }
  }
  int numDm = effDm.size();
  // Sort the effective Dm^2 list
  sort(effDm.begin(), effDm.end());
  // Set a number of sub-divisions to achieve "good" accuracy
  // This needs to be studied better
  int n_div = ceil(200 * pow(dLoE / LoE, 0.8) / sqrt(fAvgProbPrec / 1e-4));
  // int n_div = 1;
  // A vector to store sample points
  vectorD allSamples;
  // Loop over sub-divisions
  for (int k = 0; k < n_div; k++) {
    // Define sub-division center and width
    double bctr = LoE - dLoE / 2 + (k + 0.5) * dLoE / n_div;
    double bwdt = dLoE / n_div;
    // Make a vector of L/E sample values
    // Initialized in the sub-division center
    vectorD samples;
    samples.push_back(bctr);
    // Loop over all Dm^2 to average each frequency
    // This will recursively sample points in smaller
    // bins so that all relevant frequencies are used
    for (int i = 0; i < numDm; i++) {
      // Copy the list of sample L/E values
      vectorD prev = samples;
      // Redefine bin width to lie within full sub-division
      double Width =
          2 * min(prev[0] - (bctr - bwdt / 2), (bctr + bwdt / 2) - prev[0]);
      // Compute oscillation argument sorted from lowest  to highest
      const double arg = k1267 * effDm[i] * Width;
      // Skip small oscillation values.
      // If it's the last one, lower the tolerance
      if (i < numDm - 1) {
        if (arg < 0.9) continue;
      }
      else {
        if (arg < 0.1) continue;
      }
      // Reset samples to redefine them
      samples.clear();
      // Loop over previous samples
      for (int j = 0; j < int(prev.size()); j++) {
        // Compute new sample points around old samples
        // This is based on a oscillatory quadrature rule
        double sample = (1 / sqrt(3)) * (Width / 2);
        if (arg != 0) sample = acos(sin(arg) / arg) / arg * (Width / 2);
        // Add samples above and below center
        samples.push_back(prev[j] - sample);
        samples.push_back(prev[j] + sample);
      }
    } // End of loop over Dm^2
    // Add sub-division samples to the end of allSamples vector
    allSamples.insert(allSamples.end(), samples.begin(), samples.end());
  } // End of loop over sub-divisions
  // Return all sample points
  return allSamples;
}
References OscProb::PMNS_Base::fAvgProbPrec, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kKm2eV, and OscProb::PMNS_Base::SolveHam().
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), and OscProb::PMNS_Base::AvgProbVectorLoE().
GetSortedIndices()
vectorI PMNS_Base::GetSortedIndices (const vectorD x) protected virtual inherited
Get the indices of the sorted x vector
Parameters
x - input vector
Returns
The vector of sorted indices
Definition at line 715 of file PMNS_Base.cxx.
{
  vectorI idx(x.size(), 0);
  for (int i = 0; i < x.size(); i++) idx[i] = i;
  sort(idx.begin(), idx.end(), IdxCompare(x));
  return idx;
}
Referenced by OscProb::PMNS_Base::GetDmEff().
InitializeVectors()
void PMNS_Base::InitializeVectors () protected virtual inherited
Initialize all member vectors with zeros
Set vector sizes and initialize elements to zero.
Definition at line 79 of file PMNS_Base.cxx.
{
  fDm    = vectorD(fNumNus, 0);
  fTheta = matrixD(fNumNus, vectorD(fNumNus, 0));
  fDelta = matrixD(fNumNus, vectorD(fNumNus, 0));
  fNuState = vectorC(fNumNus, zero);
  fHms     = matrixC(fNumNus, vectorC(fNumNus, zero));
  fPhases = vectorC(fNumNus, zero);
  fBuffer = vectorC(fNumNus, zero);
  fEval = vectorD(fNumNus, 0);
  fEvec = matrixC(fNumNus, vectorC(fNumNus, zero));
}
Referenced by OscProb::PMNS_Base::PMNS_Base().
P()
double PMNS_DensityMatrix::P (int flv) protected virtual inherited
Compute oscillation probability of flavour flv from current state
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino final flavour.
Returns
Neutrino oscillation probability
Reimplemented from OscProb::PMNS_Base.
Definition at line 116 of file PMNS_DensityMatrix.cxx.
{
  assert(flv >= 0 && flv < fNumNus);
  return abs(fRho[flv][flv]);
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_DensityMatrix::fRho.
Referenced by ProbMatrix().
Prob() [1/6]
double PMNS_Base::Prob (int flvi, int flvf) virtual inherited
Compute the probability of flvi going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1091 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  Propagate();
  return P(flvf);
}
References OscProb::PMNS_Base::P(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::ResetToFlavour().
Prob() [2/6]
double PMNS_Base::Prob (int flvi, int flvf, double E) virtual inherited
Compute the probability of flvi going to flvf for energy E
Compute the probability of flvi going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1160 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(flvi, flvf);
}
References OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetEnergy().
Prob() [3/6]
double PMNS_Base::Prob (int flvi, int flvf, double E, double L) virtual inherited
Compute the probability of flvi going to flvf for energy E and distance L
Compute the probability of flvi going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1219 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(flvi, flvf);
}
References OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
Prob() [4/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf) virtual inherited
Compute the probability of nu_in going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 1114 of file PMNS_Base.cxx.
{
  SetPureState(nu_in);
  Propagate();
  return P(flvf);
}
References OscProb::PMNS_Base::P(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::SetPureState().
Referenced by OscProb::PMNS_Avg::AvgProb(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Avg::AvgProbLoE(), OscProb::PMNS_Base::AvgProbLoE(), and OscProb::PMNS_Base::Prob().
Prob() [5/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E) virtual inherited
Compute the probability of nu_in going to flvf for energy E
Compute the probability of nu_in going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1138 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return Prob(nu_in, flvf);
}
References OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetEnergy().
Prob() [6/6]
double PMNS_Base::Prob (vectorC nu_in, int flvf, double E, double L) virtual inherited
Compute the probability of nu_in going to flvf for energy E and distance L
Compute the probability of nu_in going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nu_in - The neutrino initial state in flavour basis.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1189 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return Prob(nu_in, flvf);
}
References OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbMatrix() [1/3]
matrixD PMNS_OQS::ProbMatrix (int nflvi, int nflvf) virtual
Compute the probability matrix for the first nflvi and nflvf states.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
nflvi - The number of initial flavours in the matrix.
nflvf - The number of final flavours in the matrix.
Returns
Neutrino oscillation probabilities.
Reimplemented from OscProb::PMNS_DensityMatrix.
Definition at line 514 of file PMNS_OQS.cxx.
{
  THROW_ON_INVALID_ARG(nflvi >= 0, nflvi);
  THROW_ON_INVALID_ARG(nflvi <= fNumNus, nflvi, fNumNus);
  THROW_ON_INVALID_ARG(nflvf >= 0, nflvf);
  THROW_ON_INVALID_ARG(nflvf <= fNumNus, nflvf, fNumNus);
  // Output probabilities
  matrixD probs(nflvi, vectorD(nflvf));
  // List of states
  vector<vectorD> allstates(nflvi, vectorD(9));
  // Reset all initial states
  for (int i = 0; i < nflvi; i++) {
    ResetToFlavour(i);
    RotateState(true);
    allstates[i] = fR;
  }
  // Propagate all states in parallel
  for (int i = 0; i < int(fNuPaths.size()); i++) {
    for (int flvi = 0; flvi < nflvi; flvi++) {
      fR = allstates[flvi];
      PropagatePath(fNuPaths[i]);
      allstates[flvi] = fR;
    }
  }
  // Get all probabilities
  for (int flvi = 0; flvi < nflvi; flvi++) {
    fR = allstates[flvi];
    RotateState(false);
    for (int flvj = 0; flvj < nflvf; flvj++) { probs[flvi][flvj] = P(flvj); }
  }
  return probs;
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuPaths, fR, OscProb::PMNS_DensityMatrix::P(), PropagatePath(), OscProb::PMNS_DensityMatrix::ResetToFlavour(), RotateState(), and THROW_ON_INVALID_ARG.
ProbMatrix() [2/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E) virtual inherited
Reimplemented from OscProb::PMNS_Base.
Definition at line 80 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbMatrix(nflvi, nflvf);
}
References OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
ProbMatrix() [3/3]
matrixD PMNS_Base::ProbMatrix (int nflvi, int nflvf, double E, double L) virtual inherited
Reimplemented from OscProb::PMNS_Base.
Definition at line 83 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbMatrix(nflvi, nflvf);
}
ProbVector() [1/6]
vectorD PMNS_Base::ProbVector (int flvi) virtual inherited
Compute the probabilities of flvi going to all flavours
Compute the probability of flvi going to all flavours.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
Returns
Neutrino oscillation probabilities
Definition at line 1272 of file PMNS_Base.cxx.
{
  ResetToFlavour(flvi);
  Propagate();
  return GetProbVector();
}
References OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::ResetToFlavour().
ProbVector() [2/6]
vectorD PMNS_Base::ProbVector (int flvi, double E) virtual inherited
Compute the probabilities of flvi going to all flavours for energy E
Compute the probability of flvi going to all flavours for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1313 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(flvi);
}
References OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_Base::SetEnergy().
ProbVector() [3/6]
vectorD PMNS_Base::ProbVector (int flvi, double E, double L) virtual inherited
Compute the probabilities of flvi going to all flavours for energy E and distance L
Compute the probability of flvi going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1365 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(flvi);
}
References OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
ProbVector() [4/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in) virtual inherited
Compute the probabilities of nu_in going to all flavours
Compute the probability of nu_in going to all flavours.
Parameters
nu_in - The neutrino initial state in flavour basis.
Returns
Neutrino oscillation probabilities
Definition at line 1250 of file PMNS_Base.cxx.
{
  SetPureState(nu_in);
  Propagate();
  return GetProbVector();
}
References OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::SetPureState().
Referenced by OscProb::PMNS_Avg::AvgProbVector(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Avg::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), and OscProb::PMNS_Base::ProbVector().
ProbVector() [5/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E) virtual inherited
Compute the probabilities of nu_in going to all
Compute the probability of nu_in going to all flavours for a given energy in GeV.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probabilities
Definition at line 1291 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  return ProbVector(nu_in);
}
References OscProb::PMNS_Base::ProbVector(), and OscProb::PMNS_Base::SetEnergy().
ProbVector() [6/6]
vectorD PMNS_Base::ProbVector (vectorC nu_in, double E, double L) virtual inherited
Compute the probabilities of nu_in going to all flavours for energy E and distance L
Compute the probability of nu_in going to all flavours for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Parameters
nu_in - The neutrino initial state in flavour basis.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probabilities
Definition at line 1336 of file PMNS_Base.cxx.
{
  SetEnergy(E);
  SetLength(L);
  return ProbVector(nu_in);
}
References OscProb::PMNS_Base::ProbVector(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
Propagate()
void PMNS_OQS::Propagate () protected virtual
Reimplemented from PMNS_Base to rotate to mass basis before propagation.
Reimplemented from OscProb::PMNS_Base.
Definition at line 465 of file PMNS_OQS.cxx.
{
  RotateState(true);
  PMNS_Base::Propagate();
  RotateState(false);
}
References OscProb::PMNS_Base::Propagate(), and RotateState().
PropagatePath()
void PMNS_OQS::PropagatePath (NuPath p) protected virtual
Propagate the current neutrino state through a given path.
Parameters
p - A neutrino path segment.
Implements OscProb::PMNS_DensityMatrix.
Definition at line 478 of file PMNS_OQS.cxx.
{
  BuildM(p);
  // Solve for eigensystem
  SolveHam();
  // Convert path length to eV
  double lengthIneV = kKm2eV * p.length;
  fM *= lengthIneV;
  fM = fM.exp();
  fRt[0] = fR[0];
  for (int i = 1; i < SU3_DIM; ++i) {
    fRt[i] = 0;
    for (int j = 1; j < SU3_DIM; ++j) { fRt[i] += fM(i - 1, j - 1) * fR[j]; }
  }
  fR = fRt;
}
References BuildM(), fM, fR, fRt, OscProb::PMNS_Base::kKm2eV, OscProb::NuPath::length, OscProb::PMNS_Fast::SolveHam(), and SU3_DIM.
Referenced by ProbMatrix().
ResetToFlavour()
void PMNS_DensityMatrix::ResetToFlavour (int flv) protected virtual inherited
Reset the neutrino state back to a pure flavour where it starts
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino starting flavour.
Reimplemented from OscProb::PMNS_Base.
Definition at line 87 of file PMNS_DensityMatrix.cxx.
{
  assert(flv >= 0 && flv < fNumNus);
  PMNS_Base::ResetToFlavour(flv);
  for (int i = 0; i < fNumNus; ++i) {
    for (int j = 0; j < fNumNus; ++j) {
      if (i == flv && i == j)
        fRho[i][j] = one;
      else
        fRho[i][j] = zero;
    }
  }
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_DensityMatrix::fRho, OscProb::PMNS_Base::one, OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_Base::zero.
Referenced by OscProb::PMNS_DensityMatrix::ProbMatrix(), and ProbMatrix().
RotateH()
void PMNS_Base::RotateH (int i, int j, matrixC & Ham) protected virtual inherited
Rotate the Hamiltonian by the angle theta_ij and phase delta_ij.
The rotations assume all off-diagonal elements with i > j are zero. This is correct if the order of rotations is chosen appropriately and it speeds up computation by skipping null terms
Parameters
i,j - the indices of the rotation ij
Ham - the Hamiltonian to be rotated
Definition at line 822 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if (fTheta[i][j] == 0) return;
  double fSinBuffer = sin(fTheta[i][j]);
  double fCosBuffer = cos(fTheta[i][j]);
  double   fHmsBufferD;
  complexD fHmsBufferC;
  // With Delta
  if (i + 1 < j) {
    complexD fExpBuffer = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    // General case
    if (i > 0) {
      // Top columns
      for (int k = 0; k < i; k++) {
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer * conj(fExpBuffer);
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer * fExpBuffer;
      }
      // Middle row and column
      for (int k = i + 1; k < j; k++) {
        fHmsBufferC = Ham[k][j];
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
        Ham[i][k] += fSinBuffer * fExpBuffer * conj(fHmsBufferC);
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] +=
          2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -=
          2 * fSinBuffer * fCosBuffer * real(Ham[i][j] * conj(fExpBuffer));
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j] * conj(fExpBuffer)) *
                   fSinBuffer * fExpBuffer;
      Ham[i][j] +=
          fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC) * fExpBuffer;
    }
    // First rotation on j (No top columns)
    else {
      // Middle rows and columns
      for (int k = i + 1; k < j; k++) {
        Ham[k][j] = -conj(Ham[i][k]) * fSinBuffer * fExpBuffer;
        Ham[i][k] *= fCosBuffer;
      }
      // Nodes ij
      fHmsBufferD = real(Ham[i][i]);
      Ham[i][j] =
          fSinBuffer * fCosBuffer * (Ham[j][j] - fHmsBufferD) * fExpBuffer;
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferD * fSinBuffer;
    }
  }
  // Without Delta (No middle rows or columns: j = i+1)
  else {
    // General case
    if (i > 0) {
      // Top columns
      for (int k = 0; k < i; k++) {
        fHmsBufferC = Ham[k][i];
        Ham[k][i] *= fCosBuffer;
        Ham[k][i] += Ham[k][j] * fSinBuffer;
        Ham[k][j] *= fCosBuffer;
        Ham[k][j] -= fHmsBufferC * fSinBuffer;
      }
      // Nodes ij
      fHmsBufferC = Ham[i][i];
      fHmsBufferD = real(Ham[j][j]);
      Ham[i][i] *= fCosBuffer * fCosBuffer;
      Ham[i][i] += 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][i] += fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
      Ham[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
      Ham[j][j] -= 2 * fSinBuffer * fCosBuffer * real(Ham[i][j]);
      Ham[i][j] -= 2 * fSinBuffer * real(Ham[i][j]) * fSinBuffer;
      Ham[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC);
    }
    // First rotation (theta12)
    else {
      Ham[i][j] = fSinBuffer * fCosBuffer * Ham[j][j];
      Ham[i][i] = fSinBuffer * Ham[j][j] * fSinBuffer;
      Ham[j][j] *= fCosBuffer * fCosBuffer;
    }
  }
}
References OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), and OscProb::PMNS_SNSI::BuildHms().
RotateState() [1/3]
void PMNS_DensityMatrix::RotateState (bool to_basis, matrixC U) protected virtual inherited
Rotate the density matrix to or from a basis given by U
Parameters
to_basis - true if to the given basis
U - the rotation matrix to the given basis
Definition at line 45 of file PMNS_DensityMatrix.cxx.
{
  // buffer = rho . U
  for (int i = 0; i < fNumNus; i++) {
    for (int j = 0; j < fNumNus; j++) {
      fMBuffer[i][j] = 0;
      for (int k = 0; k < fNumNus; k++) {
        if (to_basis)
          fMBuffer[i][j] += fRho[i][k] * U[k][j];
        else
          fMBuffer[i][j] += fRho[i][k] * conj(U[j][k]);
      }
    }
  }
  // rho = U^\dagger . buffer = U^\dagger . rho . U
  // Final matrix is Hermitian, so copy upper to lower triangle
  for (int i = 0; i < fNumNus; i++) {
    for (int j = i; j < fNumNus; j++) {
      fRho[i][j] = 0;
      for (int k = 0; k < fNumNus; k++) {
        if (to_basis)
          fRho[i][j] += conj(U[k][i]) * fMBuffer[k][j];
        else
          fRho[i][j] += U[i][k] * fMBuffer[k][j];
      }
      if (j > i) fRho[j][i] = conj(fRho[i][j]);
    }
  }
}
References OscProb::PMNS_DensityMatrix::fMBuffer, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_DensityMatrix::fRho.
Referenced by OscProb::PMNS_Deco::PropagatePath(), and RotateState().
RotateState() [2/3]
void PMNS_OQS::RotateState (bool to_mass) protected virtual
Rotate the density matrix to or from the mass basis.
Parameters
to_mass - true if to mass basis.
Definition at line 453 of file PMNS_OQS.cxx.
{
  BuildHms();
  if (!to_mass) UpdateRho();
  PMNS_DensityMatrix::RotateState(to_mass, fUM);
  if (to_mass) BuildR();
}
References BuildHms(), BuildR(), fUM, OscProb::PMNS_DensityMatrix::RotateState(), and UpdateRho().
Referenced by ProbMatrix(), and Propagate().
RotateState() [3/3]
void PMNS_Base::RotateState (int i, int j) protected virtual inherited
Rotate the neutrino state by the angle theta_ij and phase delta_ij.
Parameters
i,j - the indices of the rotation ij
Definition at line 760 of file PMNS_Base.cxx.
{
  // Do nothing if angle is zero
  if (fTheta[i][j] == 0) return;
  double sij = sin(fTheta[i][j]);
  double cij = cos(fTheta[i][j]);
  complexD buffer;
  if (i + 1 == j || fDelta[i][j] == 0) {
    buffer      = cij * fNuState[i] + sij * fNuState[j];
    fNuState[j] = cij * fNuState[j] - sij * fNuState[i];
  }
  else {
    complexD eij = complexD(cos(fDelta[i][j]), -sin(fDelta[i][j]));
    buffer       = cij * fNuState[i] + sij * eij * fNuState[j];
    fNuState[j]  = cij * fNuState[j] - sij * conj(eij) * fNuState[i];
  }
  fNuState[i] = buffer;
}
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fNuState, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Base::GetMassEigenstate().
SetAngle()
void PMNS_Base::SetAngle (int i, int j, double th) virtual inherited
Set the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of theta_ij
th - the value of theta_ij
Definition at line 539 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Theta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Theta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fTheta[i - 1][j - 1] == th);
  fTheta[i - 1][j - 1] = th;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetMix(), OscProb::PMNS_Fast::SetMix(), SetNominalPars(), and OscProb::PMNS_Base::SetStdPars().
SetAtt() [1/2]
void PMNS_Base::SetAtt (double att, int idx) protected virtual inherited
Set some single path attribute.
An auxiliary function to set individual attributes in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
att - The value of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 364 of file PMNS_Base.cxx.
{
  if (fNuPaths.size() != 1) {
    cerr << "WARNING: Clearing path vector and starting new single path."
         << endl
         << "To avoid possible issues, use the SetPath function." << endl;
    SetStdPath();
  }
  switch (idx) {
    case 0: fNuPaths[0].length = att; break;
    case 1: fNuPaths[0].density = att; break;
    case 2: fNuPaths[0].zoa = att; break;
    case 3: fNuPaths[0].layer = att; break;
  }
}
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::SetStdPath().
Referenced by OscProb::PMNS_Base::SetDensity(), OscProb::PMNS_Base::SetLayers(), OscProb::PMNS_Base::SetLength(), and OscProb::PMNS_Base::SetZoA().
SetAtt() [2/2]
void PMNS_Base::SetAtt (vectorD att, int idx) protected virtual inherited
Set all values of a path attribute.
An auxiliary function to set individual attributes in a path sequence.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
att - The values of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 427 of file PMNS_Base.cxx.
{
  // Get the sizes of the attribute and
  // path sequence vectors
  int nA = att.size();
  int nP = fNuPaths.size();
  // If the vector sizes are equal, update this attribute
  if (nA == nP) {
    for (int i = 0; i < nP; i++) {
      switch (idx) {
        case 0: fNuPaths[i].length = att[i]; break;
        case 1: fNuPaths[i].density = att[i]; break;
        case 2: fNuPaths[i].zoa = att[i]; break;
        case 3: fNuPaths[i].layer = att[i]; break;
      }
    }
  }
  // If the vector sizes differ, create a new path sequence
  // and set value for this attribute. Other attributes will
  // be taken from default single path.
  else {
    cerr << "WARNING: New vector size. Starting new path vector." << endl
         << "To avoid possible issues, use the SetPath function." << endl;
    // Start a new standard path just
    // to set default values
    SetStdPath();
    // Create a path segment with default values
    NuPath p = fNuPaths[0];
    // Clear the path sequence
    ClearPath();
    // Set this particular attribute's value
    // and add the path segment to the sequence
    for (int i = 0; i < nA; i++) {
      switch (idx) {
        case 0: p.length = att[i]; break;
        case 1: p.density = att[i]; break;
        case 2: p.zoa = att[i]; break;
        case 3: p.layer = att[i]; break;
      }
      AddPath(p);
    }
  }
}
References OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::ClearPath(), OscProb::NuPath::density, OscProb::PMNS_Base::fNuPaths, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetStdPath(), and OscProb::NuPath::zoa.
SetAvgProbPrec()
void PMNS_Base::SetAvgProbPrec (double prec) virtual inherited
Set the precision for the AvgProb method
Parameters
prec - AvgProb precision
Definition at line 1962 of file PMNS_Base.cxx.
{
  if (prec < 1e-8) {
    cerr << "WARNING: Cannot set AvgProb precision lower that 1e-8."
         << "Setting to 1e-8." << endl;
    prec = 1e-8;
  }
  fAvgProbPrec = prec;
}
References OscProb::PMNS_Base::fAvgProbPrec.
Referenced by OscProb::PMNS_Avg::PMNS_Avg(), and OscProb::PMNS_Base::PMNS_Base().
SetCurPath()
void PMNS_Base::SetCurPath (NuPath p) protected virtual inherited
Set the path currentlyin use by the class.
This will be used to know what path to propagate through next.
It will also check if values are changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
p - A neutrino path segment
Definition at line 274 of file PMNS_Base.cxx.
{
  // Check if relevant value are actually changing
  fGotES *= (fPath.density == p.density);
  fGotES *= (fPath.zoa == p.zoa);
  fPath = p;
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fPath, and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), BuildHVMB(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Avg::ExtrapolationProbLoE(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), and OscProb::PMNS_Avg::PropagatePathTaylor().
SetDecoAngle()
void PMNS_OQS::SetDecoAngle (int i, int j, double th) virtual
Set angle between two decoherence vectors a_i and a_j.
Parameters
i - First index in GM representation in range [1, 8].
j - Second index in GM representation in range [2, 8].
th - Angle in radians.
Definition at line 75 of file PMNS_OQS.cxx.
{
  THROW_ON_INVALID_ARG(i > 0, i);
  THROW_ON_INVALID_ARG(i < SU3_DIM, i, SU3_DIM);
  THROW_ON_INVALID_ARG(j > 0, i);
  THROW_ON_INVALID_ARG(j < SU3_DIM, j, SU3_DIM);
  THROW_ON_INVALID_ARG(i != j, i, j);
  double val = cos(th);
  fBuiltDissipator *= (fcos[i][j] == val);
  fcos[i][j] = val;
  fcos[j][i] = val;
}
References fBuiltDissipator, fcos, SU3_DIM, and THROW_ON_INVALID_ARG.
Referenced by GetOQS().
SetDecoElement()
void PMNS_OQS::SetDecoElement (int i, double val) virtual
Set the value of decoherence parameter |a_i| in Gell-Mann representation.
Parameters
i - Index of the parameter in range [1, 8].
val - Value to assign.
Definition at line 58 of file PMNS_OQS.cxx.
{
  THROW_ON_INVALID_ARG(i > 0, i);
  THROW_ON_INVALID_ARG(i < SU3_DIM, i, SU3_DIM);
  fBuiltDissipator *= (fa[i] == abs(val));
  fa[i] = abs(val);
}
References fa, fBuiltDissipator, SU3_DIM, and THROW_ON_INVALID_ARG.
Referenced by GetOQS().
SetDelta()
void PMNS_Base::SetDelta (int i, int j, double delta) virtual inherited
Set the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of delta_ij
delta - the value of delta_ij
Definition at line 602 of file PMNS_Base.cxx.
{
  if (i > j) {
    cerr << "WARNING: First argument should be smaller than second argument"
         << endl
         << "         Setting reverse order (Delta" << j << i << "). " << endl;
    int temp = i;
    i        = j;
    j        = temp;
  }
  if (i < 1 || i > fNumNus - 1 || j < 2 || j > fNumNus) {
    cerr << "ERROR: Delta" << i << j << " not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  if (i + 1 == j) {
    cerr << "WARNING: Rotation " << i << j << " is real. Doing nothing."
         << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDelta[i - 1][j - 1] == delta);
  fDelta[i - 1][j - 1] = delta;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Decay::SetMix(), OscProb::PMNS_Fast::SetMix(), and SetNominalPars().
SetDeltaMsqrs()
void PMNS_Fast::SetDeltaMsqrs (double dm21, double dm32) virtual inherited
Set both mass-splittings at once.
These are Dm_21 and Dm_32 in eV^2.
The corresponding Dm_31 is set in the class attributes.
Parameters
dm21 - The solar mass-splitting Dm_21
dm32 - The atmospheric mass-splitting Dm_32
Definition at line 55 of file PMNS_Fast.cxx.
{
  SetDm(2, dm21);
  SetDm(3, dm32 + dm21);
}
References OscProb::PMNS_Base::SetDm().
SetDensity() [1/2]
void PMNS_Base::SetDensity (double rho) virtual inherited
Set single path density.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The density of the path segment in g/cm^3
Definition at line 402 of file PMNS_Base.cxx.
{ SetAtt(rho, 1); }
References OscProb::PMNS_Base::SetAtt().
SetDensity() [2/2]
void PMNS_Base::SetDensity (vectorD rho) virtual inherited
Set multiple path densities.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The densities of the path segments in g/cm^3
Definition at line 497 of file PMNS_Base.cxx.
{ SetAtt(rho, 1); }
References OscProb::PMNS_Base::SetAtt().
SetDm()
void PMNS_Base::SetDm (int j, double dm) virtual inherited
Set the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
j - the index of dm_j1
dm - the value of dm_j1
Definition at line 674 of file PMNS_Base.cxx.
{
  if (j < 2 || j > fNumNus) {
    cerr << "ERROR: Dm" << j << "1 not valid for " << fNumNus
         << " neutrinos. Doing nothing." << endl;
    return;
  }
  // Check if value is actually changing
  fBuiltHms *= (fDm[j - 1] == dm);
  fDm[j - 1] = dm;
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
Referenced by GetSterile(), OscProb::PMNS_Decay::SetDeltaMsqrs(), OscProb::PMNS_Fast::SetDeltaMsqrs(), SetNominalPars(), and OscProb::PMNS_Base::SetStdPars().
SetEnergy()
void PMNS_Base::SetEnergy (double E) virtual inherited
Set neutrino energy in GeV.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
E - The neutrino energy in GeV
Definition at line 226 of file PMNS_Base.cxx.
{
  // Check if value is actually changing
  fGotES *= (fEnergy == E);
  fEnergy = E;
}
References OscProb::PMNS_Base::fEnergy, and OscProb::PMNS_Base::fGotES.
Referenced by OscProb::PMNS_Avg::AvgAlgo(), OscProb::PMNS_Avg::AvgAlgoCosT(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Avg::ExtrapolationProb(), OscProb::PMNS_Avg::ExtrapolationProbLoE(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::ProbVector().
SetInitialRho()
void PMNS_DensityMatrix::SetInitialRho (matrixC rho_in) protected virtual inherited
Set the density matrix from an arbitrary initial matrix
The initial matrix needs to satisfy the basic conditions:
Hermitian matrix
Trace = 1
Positive semidefinite
Parameters
rho_in - The initial density matrix in flavour basis.
Definition at line 150 of file PMNS_DensityMatrix.cxx.
{
  assert(rho_in.size() == fNumNus);
  assert(rho_in[0].size() == fNumNus);
  double eps = 1e-12;
  double   trace = 0;
  complexD rho_array[3][3];
  for (int i = 0; i < fNumNus; i++) {
    trace += abs(rho_in[i][i]);
    for (int j = i; j < fNumNus; j++) {
      // Ensure rho_in is hermitian
      assert(abs(rho_in[i][j] - conj(rho_in[j][i])) < eps);
      rho_array[i][j] = rho_in[i][j];
    }
  }
  // Ensure rho_in has trace 1
  assert(abs(trace - 1) < eps);
  double   fEvalGLoBES[3];
  complexD fEvecGLoBES[3][3];
  // Find the eigenvalues of rho_in
  zheevh3(rho_array, fEvecGLoBES, fEvalGLoBES);
  // Ensure rho_in is positive definite
  for (int i = 0; i < fNumNus; i++) assert(fEvalGLoBES[i] >= -eps);
  fRho = rho_in;
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_DensityMatrix::fRho, and zheevh3().
SetIsNuBar()
void PMNS_OQS::SetIsNuBar (bool isNuBar) virtual
Reimplement from PMNS_Base flagging to rebuild Hamiltonian.
Parameters
isNuBar - Flag for anti-neutrinos.
Reimplemented from OscProb::PMNS_Base.
Definition at line 177 of file PMNS_OQS.cxx.
{
  fBuiltHms *= (fIsNuBar == isNuBar);
  PMNS_Base::SetIsNuBar(isNuBar);
}
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fIsNuBar, and OscProb::PMNS_Base::SetIsNuBar().
SetLayers()
void PMNS_Base::SetLayers (std::vector< int > lay) virtual inherited
Set multiple path layer indices.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
lay - Indices to identify the layer types (e.g. earth inner core)
Definition at line 519 of file PMNS_Base.cxx.
{
  vectorD lay_double(lay.begin(), lay.end());
  SetAtt(lay_double, 3);
}
References OscProb::PMNS_Base::SetAtt().
SetLength() [1/2]
void PMNS_Base::SetLength (double L) virtual inherited
Set the length for a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
L - The length of the path segment in km
Definition at line 391 of file PMNS_Base.cxx.
{ SetAtt(L, 0); }
References OscProb::PMNS_Base::SetAtt().
Referenced by OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::ProbMatrix(), and OscProb::PMNS_Base::ProbVector().
SetLength() [2/2]
void PMNS_Base::SetLength (vectorD L) virtual inherited
Set multiple path lengths.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
L - The lengths of the path segments in km
Definition at line 486 of file PMNS_Base.cxx.
{ SetAtt(L, 0); }
References OscProb::PMNS_Base::SetAtt().
SetMaxCache()
void PMNS_Base::SetMaxCache (int mc = 1e6) virtual inherited
Set maximum number of cached eigensystems. Finding eigensystems can become slow and take up memory. This protects the cache from becoming too large.
Parameters
mc - Max cache size (default: 1e6)
Definition at line 128 of file PMNS_Base.cxx.
{ fMaxCache = mc; }
References OscProb::PMNS_Base::fMaxCache.
SetMix()
void PMNS_Fast::SetMix (double th12, double th23, double th13, double deltacp) virtual inherited
Set all mixing parameters at once.
Parameters
th12 - The value of the mixing angle theta_12
th23 - The value of the mixing angle theta_23
th13 - The value of the mixing angle theta_13
deltacp - The value of the CP phase delta_13
Definition at line 37 of file PMNS_Fast.cxx.
{
  SetAngle(1, 2, th12);
  SetAngle(1, 3, th13);
  SetAngle(2, 3, th23);
  SetDelta(1, 3, deltacp);
}
References OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDelta().
SetPath() [1/3]
void PMNS_Base::SetPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Set a single path defining attributes directly.
This destroys the current path sequence and creates a new first path.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 347 of file PMNS_Base.cxx.
{
  SetPath(NuPath(length, density, zoa, layer));
}
References OscProb::PMNS_Base::SetPath().
SetPath() [2/3]
void PMNS_Base::SetPath (NuPath p) virtual inherited
Set a single path.
This destroys the current path sequence and creates a new first path.
Parameters
p - A neutrino path segment
Definition at line 330 of file PMNS_Base.cxx.
{
  ClearPath();
  AddPath(p);
}
References OscProb::PMNS_Base::AddPath(), and OscProb::PMNS_Base::ClearPath().
Referenced by OscProb::PMNS_Avg::AvgAlgo(), OscProb::PMNS_Avg::AvgAlgoCosT(), OscProb::PMNS_Avg::ExtrapolationProbCosT(), OscProb::PMNS_Base::SetPath(), OscProb::PMNS_Base::SetStdPath(), and SetTestPath().
SetPath() [3/3]
void PMNS_Base::SetPath (std::vector< NuPath > paths) virtual inherited
Set vector of neutrino paths.
Parameters
paths - A sequence of neutrino paths
Definition at line 294 of file PMNS_Base.cxx.
{ fNuPaths = paths; }
References OscProb::PMNS_Base::fNuPaths.
SetPower()
void PMNS_OQS::SetPower (int n) virtual
Set power-law index for the energy dependence of decoherence parameters.
Set the power-law index for the energy dependence of decoherence parameters.
Parameters
n - Power-law index.
Definition at line 49 of file PMNS_OQS.cxx.
{ fPower = n; }
References fPower.
Referenced by PMNS_OQS().
SetPureState()
void PMNS_DensityMatrix::SetPureState (vectorC nu_in) protected virtual inherited
Set the density matrix from a pure state
Parameters
nu_in - The neutrino initial state in flavour basis.
Reimplemented from OscProb::PMNS_Base.
Definition at line 128 of file PMNS_DensityMatrix.cxx.
{
  assert(nu_in.size() == fNumNus);
  for (int i = 0; i < fNumNus; i++) {
    for (int j = 0; j < fNumNus; j++) {
      fRho[i][j] = conj(nu_in[i]) * nu_in[j];
    }
  }
}
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_DensityMatrix::fRho.
SetStdPars()
void PMNS_Base::SetStdPars () virtual inherited
Set standard oscillation parameters from PDG 2015.
For two neutrinos, Dm is set to the muon disappearance effective mass-splitting and mixing angle.
Definition at line 177 of file PMNS_Base.cxx.
{
  if (fNumNus > 2) {
    // PDG values for 3 neutrinos
    // Also applicable for 3+N neutrinos
    SetAngle(1, 2, asin(sqrt(0.304)));
    SetAngle(1, 3, asin(sqrt(0.0219)));
    SetAngle(2, 3, asin(sqrt(0.514)));
    SetDm(2, 7.53e-5);
    SetDm(3, 2.52e-3);
  }
  else if (fNumNus == 2) {
    // Effective muon disappearance values
    // for two-flavour approximation
    SetAngle(1, 2, 0.788);
    SetDm(2, 2.47e-3);
  }
}
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDm().
Referenced by OscProb::PMNS_Base::PMNS_Base().
SetStdPath()
void PMNS_Base::SetStdPath () virtual inherited
Set standard single path.
Length is 1000 km, so ~2 GeV peak energy.
Density is approximate from CRUST2.0 (~2.8 g/cm^3). Z/A is set to a round 0.5.
Definition at line 205 of file PMNS_Base.cxx.
{
  NuPath p;
  p.length  = 1000; // 1000 km default
  p.density = 2.8;  // Crust density
  p.zoa     = 0.5;  // Crust Z/A
  p.layer   = 0;    // Single layer
  SetPath(p);
}
References OscProb::NuPath::density, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetPath(), and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_LIV::PMNS_LIV(), OscProb::PMNS_NSI::PMNS_NSI(), OscProb::PMNS_NUNM::PMNS_NUNM(), and OscProb::PMNS_Base::SetAtt().
SetUseCache()
void PMNS_Base::SetUseCache (bool u = true) virtual inherited
Turn on/off caching of eigensystems. This can save a lot of CPU time by avoiding recomputing eigensystems if we've already seen them recently. Especially useful when running over multiple earth layers and even more if multiple baselines will be computed, e.g. for atmospheric neutrinos.
Parameters
u - flag to set caching on (default: true)
Definition at line 105 of file PMNS_Base.cxx.
{ fUseCache = u; }
References OscProb::PMNS_Base::fUseCache.
Referenced by OscProb::PMNS_Base::PMNS_Base().
SetVacuumEigensystem()
void PMNS_Fast::SetVacuumEigensystem () protected virtual inherited
Set the eigensystem to the analytic solution in vacuum.
We know the vacuum eigensystem, so just write it explicitly
Definition at line 154 of file PMNS_Fast.cxx.
{
  double   s12, s23, s13, c12, c23, c13;
  complexD idelta(0.0, fDelta[0][2]);
  if (fIsNuBar) idelta = conj(idelta);
  s12 = sin(fTheta[0][1]);
  s23 = sin(fTheta[1][2]);
  s13 = sin(fTheta[0][2]);
  c12 = cos(fTheta[0][1]);
  c23 = cos(fTheta[1][2]);
  c13 = cos(fTheta[0][2]);
  fEvec[0][0] = c12 * c13;
  fEvec[0][1] = s12 * c13;
  fEvec[0][2] = s13 * exp(-idelta);
  fEvec[1][0] = -s12 * c23 - c12 * s23 * s13 * exp(idelta);
  fEvec[1][1] = c12 * c23 - s12 * s23 * s13 * exp(idelta);
  fEvec[1][2] = s23 * c13;
  fEvec[2][0] = s12 * s23 - c12 * c23 * s13 * exp(idelta);
  fEvec[2][1] = -c12 * s23 - s12 * c23 * s13 * exp(idelta);
  fEvec[2][2] = c23 * c13;
  fEval[0] = 0;
  fEval[1] = fDm[1] / (2 * kGeV2eV * fEnergy);
  fEval[2] = fDm[2] / (2 * kGeV2eV * fEnergy);
}
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fTheta, and OscProb::PMNS_Base::kGeV2eV.
Referenced by BuildHms(), OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_Iter::SolveHam().
SetZoA() [1/2]
void PMNS_Base::SetZoA (double zoa) virtual inherited
Set single path Z/A.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segment
Definition at line 413 of file PMNS_Base.cxx.
{ SetAtt(zoa, 2); }
References OscProb::PMNS_Base::SetAtt().
SetZoA() [2/2]
void PMNS_Base::SetZoA (vectorD zoa) virtual inherited
Set multiple path Z/A values.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segments
Definition at line 508 of file PMNS_Base.cxx.
{ SetAtt(zoa, 2); }
References OscProb::PMNS_Base::SetAtt().
SolveHam()
void PMNS_Fast::SolveHam () protected virtual inherited
Solve the full Hamiltonian for eigenvectors and eigenvalues.
If vacuum, just use the PMNS matrix, otherwise solve in Matter using GLoBES.
Implements OscProb::PMNS_Base.
Reimplemented in OscProb::PMNS_Iter, and OscProb::PMNS_LIV.
Definition at line 98 of file PMNS_Fast.cxx.
{
  // Do vacuum oscillation in low density
  if (fPath.density < 1.0e-6) {
    SetVacuumEigensystem();
    return;
  }
  SolveHamMatter();
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fPath, OscProb::PMNS_Fast::SetVacuumEigensystem(), and OscProb::PMNS_Fast::SolveHamMatter().
Referenced by OscProb::PMNS_Deco::PropagatePath(), PropagatePath(), and OscProb::PMNS_Avg::PropagatePathTaylor().
SolveHamMatter()
void PMNS_Fast::SolveHamMatter () protected virtual inherited
Solve the full Hamiltonian for eigenvectors and eigenvalues.
This is using a method from the GLoBES software available at http://www.mpi-hd.mpg.de/personalhomes/globes/3x3/
We should cite them accordingly
Definition at line 117 of file PMNS_Fast.cxx.
{
  // Build Hamiltonian
  BuildHms();
  // Check if anything changed
  if (fGotES) return;
  // Try caching if activated
  if (TryCache()) return;
  UpdateHam();
  double   fEvalGLoBES[3];
  complexD fEvecGLoBES[3][3];
  // Solve Hamiltonian for eigensystem using the GLoBES method
  zheevh3(fHam, fEvecGLoBES, fEvalGLoBES);
  // Fill fEval and fEvec vectors from GLoBES arrays
  for (int i = 0; i < fNumNus; i++) {
    fEval[i] = fEvalGLoBES[i];
    for (int j = 0; j < fNumNus; j++) { fEvec[i][j] = fEvecGLoBES[i][j]; }
  }
  fGotES = true;
  // Fill cache if activated
  FillCache();
}
References OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Fast::fHam, OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Fast::UpdateHam(), and zheevh3().
Referenced by OscProb::PMNS_Fast::SolveHam(), and OscProb::PMNS_LIV::SolveHam().
TryCache()
bool PMNS_Base::TryCache () protected virtual inherited
Try to find a cached version of this eigensystem.
Definition at line 134 of file PMNS_Base.cxx.
{
  if (fUseCache && !fMixCache.empty()) {
    fProbe.SetVars(fEnergy, fPath, fIsNuBar);
    unordered_set<EigenPoint>::iterator it = fMixCache.find(fProbe);
    if (it != fMixCache.end()) {
      for (int i = 0; i < fNumNus; i++) {
        fEval[i] = (*it).fEval[i] * (*it).fEnergy / fEnergy;
        for (int j = 0; j < fNumNus; j++) { fEvec[i][j] = (*it).fEvec[i][j]; }
      }
      return true;
    }
  }
  return false;
}
References OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fMixCache, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::fProbe, OscProb::PMNS_Base::fUseCache, and OscProb::EigenPoint::SetVars().
Referenced by OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHamMatter().
UpdateHam()
void PMNS_Fast::UpdateHam () protected virtual inherited
Build the full Hamiltonian in matter.
Here we divide the mass squared matrix Hms by the 2E to obtain the vacuum Hamiltonian in eV. Then, the matter potential is added to the electron component.
Reimplemented in OscProb::PMNS_LIV, OscProb::PMNS_NSI, OscProb::PMNS_NUNM, and OscProb::PMNS_SNSI.
Definition at line 69 of file PMNS_Fast.cxx.
{
  double lv = 2 * kGeV2eV * fEnergy; // 2E in eV
  double kr2GNe = kK2 * M_SQRT2 * kGf;
  kr2GNe *= fPath.density * fPath.zoa; // Matter potential in eV
  // Finish building Hamiltonian in matter with dimension of eV
  for (int i = 0; i < fNumNus; i++) {
    fHam[i][i] = fHms[i][i] / lv;
    for (int j = i + 1; j < fNumNus; j++) {
      if (!fIsNuBar)
        fHam[i][j] = fHms[i][j] / lv;
      else
        fHam[i][j] = conj(fHms[i][j]) / lv;
    }
  }
  if (!fIsNuBar)
    fHam[0][0] += kr2GNe;
  else
    fHam[0][0] -= kr2GNe;
}
References OscProb::NuPath::density, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Fast::fHam, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kGf, OscProb::PMNS_Base::kK2, and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Avg::BuildKcosT(), and OscProb::PMNS_Fast::SolveHamMatter().
UpdateRho()
void PMNS_OQS::UpdateRho () protected virtual
Update density matrix from Gell-Mann representation.
Definition at line 445 of file PMNS_OQS.cxx.
{ get_SU3(fR, fRho); }
References fR, OscProb::PMNS_DensityMatrix::fRho, and get_SU3().
Referenced by RotateState().
Member Data Documentation
fa
vectorD OscProb::PMNS_OQS::fa protected
Definition at line 87 of file PMNS_OQS.h.
Referenced by BuildDissipator(), GetDecoElement(), and SetDecoElement().
fAvgProbPrec
double OscProb::PMNS_Base::fAvgProbPrec protected inherited
Definition at line 305 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Avg::GetSamplePointsAvgClass(), and OscProb::PMNS_Base::SetAvgProbPrec().
fBuffer
vectorC OscProb::PMNS_Base::fBuffer protected inherited
Definition at line 287 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::PropagatePath(), and OscProb::PMNS_Decay::PropagatePath().
fBuiltDissipator
bool OscProb::PMNS_OQS::fBuiltDissipator protected
Definition at line 99 of file PMNS_OQS.h.
Referenced by BuildDissipator(), PMNS_OQS(), SetDecoAngle(), and SetDecoElement().
fBuiltHms
bool OscProb::PMNS_Base::fBuiltHms protected inherited
Definition at line 298 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_Decay::SetAlpha2(), OscProb::PMNS_Decay::SetAlpha3(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_Base::SetDelta(), OscProb::PMNS_Base::SetDm(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Iter::SetIsNuBar(), SetIsNuBar(), OscProb::PMNS_SNSI::SetLowestMass(), and OscProb::PMNS_Iter::SolveHam().
fCachePrec
double OscProb::PMNS_Base::fCachePrec protected inherited
Definition at line 302 of file PMNS_Base.h.
fcos
matrixD OscProb::PMNS_OQS::fcos protected
Definition at line 88 of file PMNS_OQS.h.
Referenced by BuildDissipator(), GetDecoAngle(), and SetDecoAngle().
fD
matrixD OscProb::PMNS_OQS::fD protected
Definition at line 95 of file PMNS_OQS.h.
Referenced by BuildDissipator(), BuildM(), and GetDissipatorElement().
fDelta
matrixD OscProb::PMNS_Base::fDelta protected inherited
Definition at line 281 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::RotateState(), OscProb::PMNS_Base::SetDelta(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fDm
vectorD OscProb::PMNS_Base::fDm protected inherited
Definition at line 279 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), BuildHVMB(), OscProb::PMNS_Base::GetDm(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Base::SetDm(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fEnergy
double OscProb::PMNS_Base::fEnergy protected inherited
Definition at line 292 of file PMNS_Base.h.
Referenced by BuildHVMB(), BuildM(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetEnergy(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fEval
vectorD OscProb::PMNS_Base::fEval protected inherited
Definition at line 289 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Avg::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Avg::PropagatePathTaylor(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Fast::SolveHamMatter(), and OscProb::PMNS_Base::TryCache().
fEvec
matrixC OscProb::PMNS_Base::fEvec protected inherited
Definition at line 290 of file PMNS_Base.h.
Referenced by BuildHms(), OscProb::PMNS_Avg::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Avg::rotateK(), OscProb::PMNS_Avg::rotateS(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Fast::SolveHamMatter(), and OscProb::PMNS_Base::TryCache().
fGotES
bool OscProb::PMNS_Base::fGotES protected inherited
Definition at line 299 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_NUNM::SetAlpha(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_NSI::SetCoupByIndex(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_NUNM::SetFracVnc(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Decay::SolveHam(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHamMatter().
fHam
complexD OscProb::PMNS_Fast::fHam[3][3] protected inherited
Definition at line 64 of file PMNS_Fast.h.
Referenced by OscProb::PMNS_Avg::BuildKcosT(), OscProb::PMNS_Fast::SolveHamMatter(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), and OscProb::PMNS_SNSI::UpdateHam().
fHGM
matrixD OscProb::PMNS_OQS::fHGM protected
Definition at line 94 of file PMNS_OQS.h.
Referenced by BuildHGM(), BuildM(), and GetHGM().
fHms
matrixC OscProb::PMNS_Base::fHms protected inherited
Definition at line 284 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_Avg::BuildKE(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fHVMB
matrixC OscProb::PMNS_OQS::fHVMB protected
Definition at line 93 of file PMNS_OQS.h.
Referenced by BuildHGM(), and BuildHVMB().
fIsNuBar
bool OscProb::PMNS_Base::fIsNuBar protected inherited
Definition at line 293 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Decay::BuildHms(), BuildHVMB(), OscProb::PMNS_Avg::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::GetIsNuBar(), OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Decay::SetIsNuBar(), OscProb::PMNS_Iter::SetIsNuBar(), SetIsNuBar(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fM
Eigen::MatrixXd OscProb::PMNS_OQS::fM protected
Definition at line 97 of file PMNS_OQS.h.
Referenced by BuildM(), and PropagatePath().
fMaxCache
int OscProb::PMNS_Base::fMaxCache protected inherited
Definition at line 303 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::SetMaxCache().
fMBuffer
matrixC OscProb::PMNS_DensityMatrix::fMBuffer protected inherited
Definition at line 49 of file PMNS_DensityMatrix.h.
Referenced by OscProb::PMNS_DensityMatrix::RotateState().
fMixCache
std::unordered_set<EigenPoint> OscProb::PMNS_Base::fMixCache protected inherited
Definition at line 307 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Avg::AvgProbVectorLoE(), OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::TryCache().
fNumNus
int OscProb::PMNS_Base::fNumNus protected inherited
Definition at line 277 of file PMNS_Base.h.
Referenced by OscProb::PMNS_NUNM::ApplyAlphaDagger(), OscProb::PMNS_Avg::AvgFormula(), OscProb::PMNS_Avg::AvgFormulaExtrapolation(), OscProb::PMNS_Avg::AvgProbVector(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Avg::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Decay::BuildHms(), OscProb::PMNS_SNSI::BuildHms(), OscProb::PMNS_Avg::BuildKcosT(), OscProb::PMNS_Avg::BuildKE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_NUNM::GetAlpha(), OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::GetDm(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::GetProbVector(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Avg::HadamardProduct(), OscProb::PMNS_Avg::InitializeTaylorsVectors(), OscProb::PMNS_Avg::MultiplicationRuleK(), OscProb::PMNS_Avg::MultiplicationRuleS(), OscProb::PMNS_Base::P(), OscProb::PMNS_DensityMatrix::P(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Decay::PMNS_Decay(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_NUNM::ProbMatrix(), ProbMatrix(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Avg::PropagatePathTaylor(), OscProb::PMNS_Base::ResetToFlavour(), OscProb::PMNS_DensityMatrix::ResetToFlavour(), OscProb::PMNS_Avg::RotateDensityM(), OscProb::PMNS_Avg::rotateK(), OscProb::PMNS_Avg::rotateS(), OscProb::PMNS_DensityMatrix::RotateState(), OscProb::PMNS_NUNM::SetAlpha(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_LIV::SetaT(), OscProb::PMNS_LIV::SetcT(), OscProb::PMNS_Base::SetDelta(), OscProb::PMNS_Base::SetDm(), OscProb::PMNS_NSI::SetEps(), OscProb::PMNS_DensityMatrix::SetInitialRho(), OscProb::PMNS_Base::SetPureState(), OscProb::PMNS_DensityMatrix::SetPureState(), OscProb::PMNS_Base::SetStdPars(), OscProb::PMNS_Sterile::SolveEigenSystem(), OscProb::PMNS_Iter::SolveHam(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::SolveHamMatter(), OscProb::PMNS_Avg::SolveK(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fNuPaths
std::vector<NuPath> OscProb::PMNS_Base::fNuPaths protected inherited
Definition at line 295 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Avg::AvgProb(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Avg::AvgProbLoE(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Avg::AvgProbMatrix(), OscProb::PMNS_Base::AvgProbMatrix(), OscProb::PMNS_Avg::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Avg::AvgProbVector(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Avg::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ClearPath(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Avg::ExtrapolationProbLoE(), OscProb::PMNS_Base::GetPath(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_NUNM::ProbMatrix(), ProbMatrix(), OscProb::PMNS_Base::Propagate(), OscProb::PMNS_Avg::PropagateTaylor(), OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
fNuState
vectorC OscProb::PMNS_Base::fNuState protected inherited
Definition at line 283 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbVector(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::GetMassEigenstate(), OscProb::PMNS_Base::P(), OscProb::PMNS_Base::ProbMatrix(), OscProb::PMNS_NUNM::ProbMatrix(), OscProb::PMNS_NUNM::Propagate(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Iter::PropMatter(), OscProb::PMNS_Base::ResetToFlavour(), OscProb::PMNS_Base::RotateState(), and OscProb::PMNS_Base::SetPureState().
fPath
NuPath OscProb::PMNS_Base::fPath protected inherited
Definition at line 296 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Avg::AvgProbLoE(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Avg::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Avg::AvgProbVectorLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), BuildHVMB(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Avg::ExtrapolationProbLoE(), OscProb::PMNS_Base::FillCache(), OscProb::PMNS_NSI::GetZoACoup(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Base::TryCache(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
fPhases
vectorC OscProb::PMNS_Base::fPhases protected inherited
Definition at line 286 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Avg::PropagatePathTaylor(), and OscProb::PMNS_Avg::rotateS().
fPower
int OscProb::PMNS_OQS::fPower protected
Definition at line 86 of file PMNS_OQS.h.
Referenced by BuildM(), GetPower(), and SetPower().
fProbe
EigenPoint OscProb::PMNS_Base::fProbe protected inherited
Definition at line 308 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), and OscProb::PMNS_Base::TryCache().
fR
vectorD OscProb::PMNS_OQS::fR protected
Definition at line 90 of file PMNS_OQS.h.
Referenced by BuildR(), ProbMatrix(), PropagatePath(), and UpdateRho().
fRho
matrixC OscProb::PMNS_DensityMatrix::fRho protected inherited
Definition at line 47 of file PMNS_DensityMatrix.h.
Referenced by BuildR(), OscProb::PMNS_DensityMatrix::P(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_DensityMatrix::ResetToFlavour(), OscProb::PMNS_DensityMatrix::RotateState(), OscProb::PMNS_DensityMatrix::SetInitialRho(), OscProb::PMNS_DensityMatrix::SetPureState(), and UpdateRho().
fRt
vectorD OscProb::PMNS_OQS::fRt protected
Definition at line 91 of file PMNS_OQS.h.
Referenced by PropagatePath().
fTheta
matrixD OscProb::PMNS_Base::fTheta protected inherited
Definition at line 280 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_DensityMatrix::ProbMatrix(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::RotateState(), OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fUM
matrixC OscProb::PMNS_OQS::fUM protected
Definition at line 92 of file PMNS_OQS.h.
Referenced by BuildHms(), BuildHVMB(), and RotateState().
fUseCache
bool OscProb::PMNS_Base::fUseCache protected inherited
Definition at line 301 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::FillCache(), OscProb::PMNS_Base::SetUseCache(), and OscProb::PMNS_Base::TryCache().
kGeV2eV
const double PMNS_Base::kGeV2eV = 1.0e+09 static protected inherited
Definition at line 217 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Avg::AlgorithmDensityMatrix(), OscProb::PMNS_Avg::AvgAlgo(), OscProb::PMNS_Avg::AvgProbMatrixLoE(), OscProb::PMNS_Avg::AvgProbVectorLoE(), BuildDissipator(), BuildHVMB(), OscProb::PMNS_Avg::ExtrapolationProb(), OscProb::PMNS_Avg::ExtrapolationProbLoE(), OscProb::PMNS_Base::GetDmEff(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kGf
const double PMNS_Base::kGf = 1.1663787e-05 static protected inherited
Definition at line 220 of file PMNS_Base.h.
Referenced by BuildHVMB(), OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kK2
const double PMNS_Base::kK2 static protected inherited
Initial value:
=
    1e-3 * kNA / pow(kKm2eV, 3)
Definition at line 216 of file PMNS_Base.h.
Referenced by BuildHVMB(), OscProb::PMNS_Iter::SetExpVL(), OscProb::PMNS_Decay::UpdateHam(), OscProb::PMNS_Fast::UpdateHam(), OscProb::PMNS_LIV::UpdateHam(), OscProb::PMNS_NSI::UpdateHam(), OscProb::PMNS_NUNM::UpdateHam(), OscProb::PMNS_SNSI::UpdateHam(), and OscProb::PMNS_Sterile::UpdateHam().
kKm2eV
const double PMNS_Base::kKm2eV = 1.0 / 1.973269788e-10 static protected inherited
Definition at line 215 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Avg::BuildKcosT(), OscProb::PMNS_Avg::BuildKE(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Decay::PropagatePath(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Iter::PropagatePath(), PropagatePath(), OscProb::PMNS_Avg::PropagatePathTaylor(), and OscProb::PMNS_Iter::SetExpVL().
kNA
const double PMNS_Base::kNA = 6.022140857e23 static protected inherited
Definition at line 218 of file PMNS_Base.h.
one
const complexD PMNS_Base::one static protected inherited
Definition at line 212 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_DensityMatrix::ResetToFlavour().
SU3_DIM
constexpr int OscProb::PMNS_OQS::SU3_DIM = 9 static constexpr
Definition at line 34 of file PMNS_OQS.h.
Referenced by BuildDissipator(), BuildM(), GetDecoAngle(), GetDecoElement(), GetDissipatorElement(), GetHGM(), PropagatePath(), SetDecoAngle(), and SetDecoElement().
zero
const complexD PMNS_Base::zero static protected inherited
Definition at line 211 of file PMNS_Base.h.
Referenced by OscProb::PMNS_NUNM::GetAlpha(), OscProb::PMNS_LIV::GetaT(), OscProb::PMNS_LIV::GetcT(), OscProb::PMNS_NSI::GetEps(), OscProb::PMNS_Decay::PMNS_Decay(), OscProb::PMNS_Base::ResetToFlavour(), and OscProb::PMNS_DensityMatrix::ResetToFlavour().
The documentation for this class was generated from the following files:
inc/PMNS_OQS.h
src/PMNS_OQS.cxx