OscProb: OscProb Namespace Reference
OscProb Namespace Reference
Some useful general definitions.
Classes
class Absorption
struct EarthBin
class EarthModelBase
Base class for implementing an earth model.
class EarthModelBinned
Implements an earth model with depth/latitude/longitude bins.
struct EigenPoint
Struct to organise eigensystems for caching.
struct IdxCompare
An index sorting comparator.
struct NuPath
A struct representing a neutrino path segment.
class PMNS_Avg
Implementation of oscillations of neutrinos in matter in a three-neutrino framework with a first order Taylor expansion.
class PMNS_Base
Base class implementing general functions for computing neutrino oscillations.
class PMNS_Decay
Implementation of neutrino decay in a three-neutrino framework.
class PMNS_Deco
Implementation of oscillations of neutrinos in matter in a three-neutrino framework with decoherence.
class PMNS_DensityMatrix
Base class for methods based on density matrices.
class PMNS_Fast
Implementation of oscillations of neutrinos in matter in a three-neutrino framework.
class PMNS_Iter
Implementation of oscillations of neutrinos in matter in a three-neutrino framework.
class PMNS_LIV
Implements oscillations with LIV as modelled by SME.
class PMNS_NSI
Implementation of oscillations of neutrinos in matter in a three-neutrino framework with NSI.
class PMNS_NUNM
Implementation of oscillations of neutrinos in matter in a three-neutrino framework with Non unitary Neutrino Mixing (NUNM).
class PMNS_OQS
Implements neutrino oscillations using an open quantum system approach.
class PMNS_SNSI
Implementation of oscillations of neutrinos in matter in a three-neutrino framework with scalar NSI.
class PMNS_Sterile
Implementation of oscillations of neutrinos in matter in a N-neutrino framework.
struct PremLayer
A struct representing a spherical shell of matter for earth models.
class PremModel
Implements an earth model with spherical shells.
struct TrajConstants
A struct holding useful combinations of trajectory variables.
Typedefs
typedef std::vector< int > vectorI
typedef std::vector< double > vectorD
typedef std::vector< vectorD > matrixD
typedef std::complex< double > complexD
typedef std::vector< complexD > vectorC
typedef std::vector< vectorC > matrixC
Functions
NuPath AvgPath (NuPath &p1, NuPath &p2)
Get the average of two paths.
NuPath AvgPath (std::vector< NuPath > &pv)
Get the average of a vector of paths.
std::vector< NuPath > MergePaths (std::vector< NuPath > &inputPath, int j, int k)
Merge paths j and k in vector.
std::vector< std::string > split (const std::string &s, char delimiter)
Helper function to split a string by a delimiter.
template<typename... Args>
std::string format_args (const std::string &names, const Args &... args)
The main variadic template function to log the arguments.
Detailed Description
Author
Joao Coelho - jcoelho@apc.in2p3.fr
Typedef Documentation
complexD
typedef std::complex<double> OscProb::complexD
Definition at line 21 of file Definitions.h.
matrixC
typedef std::vector<vectorC> OscProb::matrixC
Definition at line 23 of file Definitions.h.
matrixD
typedef std::vector<vectorD> OscProb::matrixD
Definition at line 19 of file Definitions.h.
vectorC
typedef std::vector<complexD> OscProb::vectorC
Definition at line 22 of file Definitions.h.
vectorD
typedef std::vector<double> OscProb::vectorD
Definition at line 18 of file Definitions.h.
vectorI
typedef std::vector<int> OscProb::vectorI
Definition at line 16 of file Definitions.h.
Function Documentation
AvgPath() [1/2]
NuPath OscProb::AvgPath (NuPath & p1, NuPath & p2)
Get the merged average of two paths
This method will merge two paths and take their average density weighted by Z/A and path length.
The Z/A will be the average weighted by path length
Parameters
p1 - The first path to merge
p2 - The second path to merge
Returns
The merged path
Definition at line 27 of file NuPath.cxx.
{
  // Start with the first path
  NuPath mergedPath = p1;
  // Add the second length
  mergedPath.length += p2.length;
  // Compute weighted average of Z/A
  mergedPath.zoa =
      (p1.zoa * p1.length + p2.zoa * p2.length) / (p1.length + p2.length);
  // Compute weighted average of density
  mergedPath.density =
      (p1.density * p1.zoa * p1.length + p2.density * p2.zoa * p2.length) /
      (p1.zoa * p1.length + p2.zoa * p2.length);
  // return merged path
  return mergedPath;
}
References OscProb::NuPath::density, OscProb::NuPath::length, and OscProb::NuPath::zoa.
Referenced by AvgPath(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::AvgProbMatrixLoE(), OscProb::PMNS_Base::AvgProbVectorLoE(), OscProb::PMNS_Base::ConvertEtoLoE(), OscProb::PMNS_Avg::ExtrapolationProbLoE(), OscProb::EarthModelBase::GetMergedPaths(), and MergePaths().
AvgPath() [2/2]
NuPath OscProb::AvgPath (std::vector< NuPath > & pv)
Get the merged average of a vector of paths
This method will merge a set of paths and take their average density weighted by Z/A and path length.
The Z/A will be the average weighted by path length
Parameters
pv - vector of paths to merge
Returns
The merged path
Definition at line 60 of file NuPath.cxx.
{
  // Get size of vector
  int np = pv.size();
  // Start with the first path
  NuPath mergedPath;
  // If vector is not empty, start on first path
  if (np > 0)
    mergedPath = pv[0];
  else
    return mergedPath;
  // Merge each of the following paths
  for (int i = 1; i < np; i++) { mergedPath = AvgPath(mergedPath, pv[i]); }
  // return merged path
  return mergedPath;
}
References AvgPath().
format_args()
template<typename... Args> std::string OscProb::format_args (const std::string & names, const Args &... args)
It unpacks the names and values from the macro call and returns a string of name = value pairs.
Template Parameters
Args The types of the arguments.
Parameters
names - The comma-separated string of argument names.
args - The actual argument values.
Returns
The string containing the formatted log message.
Definition at line 55 of file exceptions.h.
  {
    std::stringstream ss;
    std::vector<std::string> arg_names = split(names, ',');
    std::size_t i = 0;
    // Lambda to iterate and print each argument.
    auto printer = [&](const auto& arg_value) {
      if (i < arg_names.size()) {
        if (i > 0) ss << ", ";
        ss << arg_names[i] << " = " << arg_value;
      }
      i++;
    };
    // Unpack the arguments and print them using the lambda.
    (printer(args), ...);
    return ss.str();
  }
References split().
MergePaths()
vector< NuPath > OscProb::MergePaths (std::vector< NuPath > & inputPath, int j, int k)
Merge two specific paths by their indices in a path vector
Parameters
inputPath - The original vector of paths to merge
j,k - The indices of the two paths to merge
Returns
The merged vector of paths
Definition at line 89 of file NuPath.cxx.
{
  // Output vector
  vector<NuPath> mergedPath;
  // Loop over input paths
  for (int i = 0; i < inputPath.size(); i++) {
    // If first index, merge the paths j and k
    if (i == j) mergedPath.push_back(AvgPath(inputPath[j], inputPath[k]));
    // If not second index add the path as is
    else if (i != k)
      mergedPath.push_back(inputPath[i]);
  } // End of loop
  // return merged vector
  return mergedPath;
}
References AvgPath().
Referenced by OscProb::EarthModelBase::GetMergedPaths().
split()
std::vector< std::string > OscProb::split (const std::string & s, char delimiter) inline
This is used to parse the comma-separated argument names.
Parameters
s - The string to split.
delimiter - The character delimiter.
Returns
A vector of the split strings.
Definition at line 21 of file exceptions.h.
  {
    std::string              token;
    std::vector<std::string> tokens;
    std::istringstream       tokenStream(s);
    while (std::getline(tokenStream, token, delimiter)) {
      // Trim leading/trailing whitespace
      size_t first = token.find_first_not_of(" \t\n\r");
      if (std::string::npos != first) {
        size_t last = token.find_last_not_of(" \t\n\r");
        tokens.push_back(token.substr(first, (last - first + 1)));
      }
      else {
        tokens.push_back("");
      }
    }
    return tokens;
  }
Referenced by format_args().