OscProb: src/PMNS_OQS.cxx File Reference
PMNS_OQS.cxx File Reference
#include <unsupported/Eigen/MatrixFunctions>
#include "PMNS_OQS.h"
#include "exceptions.h"
#include <iostream>
Functions
void get_GM (const matrixC &A, vectorD &v)
void get_SU3 (const vectorD &v, matrixC &A)
void get_GMOP (const matrixC &A, matrixD &B)
Variables
constexpr int SU3_DIM = PMNS_OQS::SU3_DIM
Function Documentation
get_GM()
void get_GM (const matrixC & A, vectorD & v)
Auxiliary function to convert Hermitian 3x3 matrices to GM representation vectors.
Parameters
A - The input Hermitian 3x3 matrix.
v - The output real 9-vector.
Definition at line 242 of file PMNS_OQS.cxx.
{
  v[0] = real(A[0][0] + A[1][1] + A[2][2]) / sqrt(6);
  v[3] = real(A[0][0] - A[1][1]) / 2;
  v[8] = real(A[0][0] + A[1][1] - 2. * A[2][2]) / sqrt(12);
  v[1] = real(A[0][1]);
  v[4] = real(A[0][2]);
  v[6] = real(A[1][2]);
  v[2] = -imag(A[0][1]);
  v[5] = -imag(A[0][2]);
  v[7] = -imag(A[1][2]);
}
Referenced by OscProb::PMNS_OQS::BuildR().
get_GMOP()
void get_GMOP (const matrixC & A, matrixD & B)
Auxiliary function to convert Hermitian 3x3 matrices to GM representation 9x9 operators.
Parameters
A - The input Hermitian 3x3 matrix.
B - The output real 9x9 matrix.
Definition at line 288 of file PMNS_OQS.cxx.
{
  B[1][2] = real(A[0][0] - A[1][1]);
  B[1][3] = 2 * imag(A[0][1]);
  B[1][4] = -imag(A[1][2]);
  B[1][5] = -real(A[1][2]);
  B[1][6] = -imag(A[0][2]);
  B[1][7] = -real(A[0][2]);
  B[2][3] = 2 * real(A[0][1]);
  B[2][4] = real(A[1][2]);
  B[2][5] = -imag(A[1][2]);
  B[2][6] = -real(A[0][2]);
  B[2][7] = imag(A[0][2]);
  B[3][4] = -imag(A[0][2]);
  B[3][5] = -real(A[0][2]);
  B[3][6] = imag(A[1][2]);
  B[3][7] = real(A[1][2]);
  B[4][5] = real(A[0][0] - A[2][2]);
  B[4][6] = -imag(A[0][1]);
  B[4][7] = real(A[0][1]);
  B[4][8] = sqrt(3) * imag(A[0][2]);
  B[5][6] = -real(A[0][1]);
  B[5][7] = -imag(A[0][1]);
  B[5][8] = sqrt(3) * real(A[0][2]);
  B[6][7] = real(A[1][1] - A[2][2]);
  B[6][8] = sqrt(3) * imag(A[1][2]);
  B[7][8] = sqrt(3) * real(A[1][2]);
  for (int i = 1; i < SU3_DIM; ++i) {
    for (int j = i + 1; j < SU3_DIM; ++j) { B[j][i] = -B[i][j]; }
  }
}
References SU3_DIM.
Referenced by OscProb::PMNS_OQS::BuildHGM().
get_SU3()
void get_SU3 (const vectorD & v, matrixC & A)
Auxiliary function to convert GM representation vectors to Hermitian 3x3 matrices.
Parameters
v - The input real 9-vector.
A - The output Hermitian 3x3 matrix.
Definition at line 265 of file PMNS_OQS.cxx.
{
  A[0][0] = v[0] * sqrt(2 / 3.) + v[3] + v[8] / sqrt(3);
  A[1][1] = v[0] * sqrt(2 / 3.) - v[3] + v[8] / sqrt(3);
  A[2][2] = v[0] * sqrt(2 / 3.) - 2 * v[8] / sqrt(3);
  A[1][0] = complexD(v[1], v[2]);
  A[2][0] = complexD(v[4], v[5]);
  A[2][1] = complexD(v[6], v[7]);
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < i; j++) { A[j][i] = conj(A[i][j]); }
  }
}
Referenced by OscProb::PMNS_OQS::UpdateRho().
Variable Documentation
SU3_DIM
constexpr int SU3_DIM = PMNS_OQS::SU3_DIM constexpr
Definition at line 19 of file PMNS_OQS.cxx.
Referenced by get_GMOP().