OscProb: test/profile/inc/Utils.h File Reference
Utils.h File Reference
#include "PMNS_LIV.h"
#include "PMNS_SNSI.h"
#include "PMNS_Deco.h"
#include "PMNS_Iter.h"
#include "PMNS_Decay.h"
#include "PMNS_Sterile.h"
Functions
OscProb::PMNS_Fast * GetFast ()
OscProb::PMNS_Iter * GetIter ()
OscProb::PMNS_Deco * GetDeco ()
OscProb::PMNS_Sterile * GetSterile ()
OscProb::PMNS_Decay * GetDecay ()
OscProb::PMNS_NSI * GetNSI ()
OscProb::PMNS_SNSI * GetSNSI ()
OscProb::PMNS_LIV * GetLIV ()
OscProb::PMNS_Base * GetModel (std::string model)
Function Documentation
GetDecay()
OscProb::PMNS_Decay * GetDecay ()
Definition at line 48 of file Utils.h.
{
  OscProb::PMNS_Decay* p = new OscProb::PMNS_Decay();
  p->SetAlpha3(1e-4);
  return p;
}
References OscProb::PMNS_Decay::SetAlpha3().
Referenced by GetModel().
GetDeco()
OscProb::PMNS_Deco * GetDeco ()
Definition at line 24 of file Utils.h.
{
  OscProb::PMNS_Deco* p = new OscProb::PMNS_Deco();
  p->SetGamma(2, 1e-23);
  p->SetGamma(3, 1e-22);
  return p;
}
References OscProb::PMNS_Deco::SetGamma().
Referenced by GetModel().
GetFast()
OscProb::PMNS_Fast * GetFast ()
Definition at line 10 of file Utils.h.
{
  return new OscProb::PMNS_Fast();
}
Referenced by GetModel().
GetIter()
OscProb::PMNS_Iter * GetIter ()
Definition at line 17 of file Utils.h.
{
  return new OscProb::PMNS_Iter();
}
Referenced by GetModel().
GetLIV()
OscProb::PMNS_LIV * GetLIV ()
Definition at line 88 of file Utils.h.
{
  OscProb::PMNS_LIV* p = new OscProb::PMNS_LIV();
  p->SetaT(0,0, 0.1e-22, 0);
  p->SetaT(0,1, 0.2e-22, 0);
  p->SetaT(0,2, 0.3e-22, 0);
  p->SetaT(1,1, 0.4e-22, 0);
  p->SetaT(1,2, 0.5e-22, 0);
  p->SetaT(2,2, 0.6e-22, 0);
  p->SetcT(0,0, 0.1e-22, 0);
  p->SetcT(0,1, 0.2e-22, 0);
  p->SetcT(0,2, 0.3e-22, 0);
  p->SetcT(1,1, 0.4e-22, 0);
  p->SetcT(1,2, 0.5e-22, 0);
  p->SetcT(2,2, 0.6e-22, 0);
  return p;
}
References OscProb::PMNS_LIV::SetaT(), and OscProb::PMNS_LIV::SetcT().
Referenced by GetModel().
GetModel()
OscProb::PMNS_Base * GetModel (std::string model)
Definition at line 109 of file Utils.h.
{
  if(model == "Iter")    return GetIter();
  if(model == "Deco")    return GetDeco();
  if(model == "Sterile") return GetSterile();
  if(model == "Decay")   return GetDecay();
  if(model == "NSI")     return GetNSI();
  if(model == "LIV")     return GetLIV();
  if(model == "SNSI")    return GetSNSI();
  return GetFast();
}
References GetDecay(), GetDeco(), GetFast(), GetIter(), GetLIV(), GetNSI(), GetSNSI(), and GetSterile().
GetNSI()
OscProb::PMNS_NSI * GetNSI ()
Definition at line 58 of file Utils.h.
{
  OscProb::PMNS_NSI* p = new OscProb::PMNS_NSI();
  p->SetEps(0,0, 0.1, 0);
  p->SetEps(0,1, 0.2, 0);
  p->SetEps(0,2, 0.3, 0);
  p->SetEps(1,1, 0.4, 0);
  p->SetEps(1,2, 0.5, 0);
  p->SetEps(2,2, 0.6, 0);
  return p;
}
References OscProb::PMNS_NSI::SetEps().
Referenced by GetModel().
GetSNSI()
OscProb::PMNS_SNSI * GetSNSI ()
Definition at line 73 of file Utils.h.
{
  OscProb::PMNS_SNSI* p = new OscProb::PMNS_SNSI();
  p->SetEps(0,0, 0.1, 0);
  p->SetEps(0,1, 0.2, 0);
  p->SetEps(0,2, 0.3, 0);
  p->SetEps(1,1, 0.4, 0);
  p->SetEps(1,2, 0.5, 0);
  p->SetEps(2,2, 0.6, 0);
  return p;
}
References OscProb::PMNS_NSI::SetEps().
Referenced by GetModel().
GetSterile()
OscProb::PMNS_Sterile * GetSterile ()
Definition at line 35 of file Utils.h.
{
  OscProb::PMNS_Sterile* p = new OscProb::PMNS_Sterile(4);
  p->SetDm(4, 0.1);
  p->SetAngle(1,4, 0.1);
  p->SetAngle(2,4, 0.1);
  p->SetAngle(3,4, 0.1);
  return p;
}
References OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDm().
Referenced by GetModel().