OscProb: OscProb::PMNS_NSI Class Reference
OscProb::PMNS_NSI Class Reference
Implementation of oscillations of neutrinos in matter in a three-neutrino framework with NSI.
#include <PMNS_NSI.h>
Public Types
typedef std::complex< double > complex
Public Member Functions
PMNS_NSI ()
Constructor.
virtual ~PMNS_NSI ()
Destructor.
virtual void SetEps (int flvi, int flvj, double val, double phase)
Set any given NSI parameter.
virtual complex GetEps (int flvi, int flvj)
Get any given NSI parameter.
void SetNSI (double eps_ee, double eps_emu, double eps_etau, double eps_mumu, double eps_mutau, double eps_tautau, double delta_emu=0, double delta_etau=0, double delta_mutau=0)
Set the NSI parameters all at once.
virtual void SetEps_ee (double a)
Set eps_ee parameter.
virtual void SetEps_mumu (double a)
Set eps_mumu parameter.
virtual void SetEps_tautau (double a)
Set eps_tautau parameter.
virtual void SetEps_emu (double a, double phi)
Set eps_emu parameter.
virtual void SetEps_etau (double a, double phi)
Set eps_etau parameter.
virtual void SetEps_mutau (double a, double phi)
Set eps_mutau parameter.
virtual void SetMix (double th12, double th23, double th13, double deltacp)
Set the all mixing parameters at once.
virtual void SetDeltaMsqrs (double dm21, double dm32)
Set both mass-splittings at once.
virtual double Prob (int flvi, int flvf)
Compute the probability of flvi going to flvf.
virtual double Prob (int flvi, int flvf, double E)
Compute the probability of flvi going to flvf for energy E.
virtual double Prob (int flvi, int flvf, double E, double L)
Compute the probability of flvi going to flvf for energy E and distance L.
virtual double AvgProb (int flvi, int flvf, double E, double dE=0)
Compute the average probability over a bin of energy.
virtual double AvgProbLoE (int flvi, int flvf, double LoE, double dLoE=0)
Compute the average probability over a bin of L/E.
virtual void SetAngle (int i, int j, double th)
Set the mixing angle theta_ij.
virtual void SetDelta (int i, int j, double delta)
Set the CP phase delta_ij.
virtual void SetDm (int j, double dm)
Set the mass-splitting dm_j1 in eV^2.
virtual double GetAngle (int i, int j)
Get the mixing angle theta_ij.
virtual double GetDelta (int i, int j)
Get the CP phase delta_ij.
virtual double GetDm (int j)
Get the mass-splitting dm_j1 in eV^2.
virtual void SetStdPars ()
Set PDG 3-flavor parameters.
virtual void SetEnergy (double E)
Set the neutrino energy in GeV.
virtual void SetIsNuBar (bool isNuBar)
Set the anti-neutrino flag.
virtual double GetEnergy ()
Get the neutrino energy in GeV.
virtual bool GetIsNuBar ()
Get the anti-neutrino flag.
virtual void SetPath (OscProb::NuPath p)
Set a single path.
virtual void SetPath (double length, double density, double zoa=0.5, int layer=0)
Set a single path.
virtual void SetPath (std::vector< OscProb::NuPath > paths)
Set a path sequence.
virtual void AddPath (OscProb::NuPath p)
Add a path to the sequence.
virtual void AddPath (double length, double density, double zoa=0.5, int layer=0)
Add a path to the sequence.
virtual void ClearPath ()
Clear the path vector.
virtual void SetLength (double L)
Set a single path lentgh in km.
virtual void SetLength (std::vector< double > L)
Set multiple path lengths.
virtual void SetDensity (double rho)
Set single path density in g/cm^3.
virtual void SetDensity (std::vector< double > rho)
Set multiple path densities.
virtual void SetZoA (double zoa)
Set Z/A value for single path.
virtual void SetZoA (std::vector< double > zoa)
Set multiple path Z/A values.
virtual void SetLayers (std::vector< int > lay)
Set multiple path layer indices.
virtual void SetStdPath ()
Set standard neutrino path.
virtual std::vector< OscProb::NuPath > GetPath ()
Get the neutrino path sequence.
virtual std::vector< double > GetSamplePoints (double LoE, double dLoE)
Compute the sample points for a bin of L/E with width dLoE.
Protected Member Functions
virtual void UpdateHam ()
Build the full Hamiltonian.
virtual void SolveHam ()
Solve the full Hamiltonian for eigenvectors and eigenvalues.
virtual void SetVacuumEigensystem ()
Set the eigensystem to the analytic solution of the vacuum Hamiltonian.
virtual void InitializeVectors ()
Initialize all member vectors with zeros.
virtual void SetCurPath (OscProb::NuPath p)
Set the path currently in use by the class.
virtual void SetAtt (double att, int idx)
Set one of the path attributes.
virtual void SetAtt (std::vector< double > att, int idx)
Set all values of a path attribute.
virtual void RotateH (int i, int j)
Rotate the Hamiltonian by theta_ij and delta_ij.
virtual void BuildHms ()
Build the matrix of masses squared.
virtual void ResetToFlavour (int flv)
Reset neutrino state to pure flavour flv.
virtual void PropagatePath (OscProb::NuPath p)
Propagate neutrino through a single path.
virtual void Propagate ()
Propagate neutrino through full path.
virtual double P (int flv)
Return the probability of final state in flavour flv.
Protected Attributes
complex fEps [3][3]
Stores each NSI parameter.
complex fHam [3][3]
The full hamiltonian.
int fNumNus
Number of neutrino flavours.
std::vector< double > fDm
m^2_i - m^2_1 in vacuum
std::vector< std::vector< double > > fTheta
theta[i][j] mixing angle
std::vector< std::vector< double > > fDelta
delta[i][j] CP violating phase
std::vector< complex > fNuState
The neutrino current state.
std::vector< std::vector< complex > > fHms
matrix H*2E in eV^2
std::vector< complex > fPhases
Buffer for oscillation phases.
std::vector< complex > fBuffer
Buffer for neutrino state tranformations.
std::vector< double > fEval
Eigenvalues of the Hamiltonian.
std::vector< std::vector< complex > > fEvec
Eigenvectors of the Hamiltonian.
double fEnergy
Neutrino energy.
bool fIsNuBar
Anti-neutrino flag.
std::vector< OscProb::NuPath > fNuPaths
Vector of neutrino paths.
OscProb::NuPath fPath
Current neutrino path.
bool fBuiltHms
Tag to avoid rebuilding Hms.
bool fGotES
Tag to avoid recalculating eigensystem.
Static Protected Attributes
static const complex zero
zero in complex
static const complex one
one in complex
static const double kKm2eV = 1.0 / 1.973269788e-10
km to eV^-1
static const double kK2 = 1e-3 * kNA / pow(kKm2eV,3)
mol/GeV^2/cm^3 to eV
static const double kGeV2eV = 1.0e+09
GeV to eV.
static const double kNA = 6.022140857e23
Avogadro constant.
static const double kGf = 1.1663787e-05
G_F in units of GeV^-2.
Detailed Description
This class expands the PMNS_Fast class including a general matter potential matrix describing Non-Standard Interactions (NSI).
The matter potential is parametrized by dimensionless quantities epsilon which quantify the intensity of the NSI with respect to the standard matter effects from coherent forward scattering with electrons.
See also
PMNS_Fast
Author
coelho@lal.in2p3.fr
Definition at line 25 of file PMNS_NSI.h.
Member Typedef Documentation
complex
typedef std::complex<double> OscProb::PMNS_Base::complex inherited
Definition at line 104 of file PMNS_Base.h.
Constructor & Destructor Documentation
PMNS_NSI()
PMNS_NSI::PMNS_NSI ()
Constructor.
See also
PMNS_Base::PMNS_Base
This class is restricted to 3 neutrino flavours.
Definition at line 29 of file PMNS_NSI.cxx.
References SetNSI(), and OscProb::PMNS_Base::SetStdPath().
                    : PMNS_Fast(), fEps()
 {
   SetStdPath();
   SetNSI(0.,0.,0.,0.,0.,0.,0.,0.,0.);
 }
~PMNS_NSI()
PMNS_NSI::~PMNS_NSI () virtual
Nothing to clean.
Definition at line 39 of file PMNS_NSI.cxx.
 {}
Member Function Documentation
AddPath() [1/2]
void PMNS_Base::AddPath (OscProb::NuPath p) virtual inherited
Add a path to the sequence.
Parameters
p - A neutrino path segment
Definition at line 260 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
{
   fNuPaths.push_back(p);
 }
AddPath() [2/2]
void PMNS_Base::AddPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Add a path to the sequence defining attributes directly.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 274 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::AddPath().
{
   AddPath(NuPath(length, density, zoa, layer));
 }
AvgProb()
double PMNS_Base::AvgProb (int flvi, int flvf, double E, double dE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of energy E with width dE.
This gets transformed into L/E, since the oscillation terms have arguments linear in L/E and not E.
This function currently only works for single paths.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in the bin center in GeV
dE - The energy bin width in GeV
Returns
Average neutrino oscillation probability
Definition at line 1084 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::NuPath::length, OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetCurPath().
 {
   // Do nothing if energy is not positive
   if(E<=0) return 0;
   if(fNuPaths.empty()) return 0;
   if(fNuPaths.size() != 1){
     cout << "ERROR: AvgProb not implemented for multiple paths." << endl;
     cout << "       Returning probability at bin center." << endl;
     return Prob(flvi, flvf, E);
   }
   // Don't average zero width
   if(dE<=0) return Prob(flvi, flvf, E);
   // Make sure fPath is set
   SetCurPath(fNuPaths[0]);
   // Define L/E variables
   double LoE = 0;
   double dLoE = 0;
   // Set a minimum energy
   double minE = 0.1 * E;
   // Transform range to L/E
   // Full range if low edge > minE
   if(E-dE/2 > minE){
     LoE = 0.5 * (fPath.length/(E-dE/2) + fPath.length/(E+dE/2));
     dLoE = fPath.length/(E-dE/2) - fPath.length/(E+dE/2);
   }
   // Else start at minE
   else{
     LoE = 0.5 * (fPath.length/minE + fPath.length/(E+dE/2));
     dLoE = fPath.length/minE - fPath.length/(E+dE/2);
   }
   // Compute average in LoE
   return AvgProbLoE(flvi, flvf, LoE, dLoE);
 }
AvgProbLoE()
double PMNS_Base::AvgProbLoE (int flvi, int flvf, double LoE, double dLoE = 0) virtual inherited
Compute the average probability of flvi going to flvf over a bin of L/E with width dLoE.
The probabilities are weighted by (L/E)^-2 so that event density is flat in energy. This avoids giving too much weight to low energies. Better approximations would be achieved if we used an interpolated event density.
This function currently only works for single paths.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Returns
Average neutrino oscillation probability
Definition at line 1152 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNuPaths, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::GetSamplePoints(), OscProb::NuPath::length, OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SetEnergy().
Referenced by OscProb::PMNS_Base::AvgProb().
 {
   // Do nothing if L/E is not positive
   if(LoE<=0) return 0;
   if(fNuPaths.empty()) return 0;
   if(fNuPaths.size() > 1){
     cout << "ERROR: AvgProb not implemented for multiple paths." << endl;
     cout << "       Returning probability at bin center." << endl;
     double L = 0;
     for(int i=0; i<int(fNuPaths.size()); i++){
       L += fNuPaths[i].length;
     }
     return Prob(flvi, flvf, L/LoE);
   }
   // Make sure fPath is set
   SetCurPath(fNuPaths[0]);
   // Set the energy at bin center
   SetEnergy(fPath.length/LoE);
   // Don't average zero width
   if(dLoE<=0) return Prob(flvi, flvf);
   // Get sample points for this bin
   vector<double> samples = GetSamplePoints(LoE, dLoE);
   // Variables to fill sample
   // probabilities and weights
   double sumw = 0;
   double prob = 0;
   // Loop over all sample points
   for(int j=0; j<int(samples.size()); j++){
     // Set (L/E)^-2 weights
     double w = 1./pow(samples[j],2);
     // Add weighted probability
     prob += w * Prob(flvi, flvf, fPath.length / samples[j]);
     // Increment sum of weights
     sumw += w;
   }
   // Return weighted average of probabilities
   return prob / sumw;
 }
BuildHms()
void PMNS_Base::BuildHms () protected virtual inherited
Build Hms = H*2E, where H is the Hamiltonian in vacuum on flavour basis and E is the neutrino energy in eV. Hms is effectively the matrix of masses squared.
This is a hermitian matrix, so only the upper triangular part needs to be filled
The construction of the Hamiltonian avoids computing terms that are simply zero. This has a big impact in the computation time.
Definition at line 855 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::RotateH().
Referenced by OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHam().
 {
   // Check if anything changed
   if(fBuiltHms) return;
   // Tag to recompute eigensystem
   fGotES = false;
   for(int j=0; j<fNumNus; j++){
     // Set mass splitting
     fHms[j][j] = fDm[j];
     // Reset off-diagonal elements
     for(int i=0; i<j; i++){
       fHms[i][j] = 0;
     }
     // Rotate j neutrinos
     for(int i=0; i<j; i++){
       RotateH(i,j);
     }
   }
   // Tag as built
   fBuiltHms = true;
 }
ClearPath()
void PMNS_Base::ClearPath () virtual inherited
Clear the path vector.
Definition at line 228 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNuPaths.
Referenced by OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
{
   fNuPaths.clear();
 }
GetAngle()
double PMNS_Base::GetAngle (int i, int j) virtual inherited
Get the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of theta_ij
Definition at line 567 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
 {
   if(i>j){
     cout << "Warning: First argument should be smaller than second argument" << endl;
     cout << "         Setting reverse order (Theta" << j << i << "). " << endl;
     int temp = i;
     i = j;
     j = temp;
   }
   if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
     cout << "ERROR: Theta" << i << j << " not valid for " << fNumNus;
     cout << " neutrinos. Returning zero." << endl;
     return 0;
   }
   return fTheta[i-1][j-1];
 }
GetDelta()
double PMNS_Base::GetDelta (int i, int j) virtual inherited
Get the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
Parameters
i,j - the indices of delta_ij
Definition at line 637 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
 {
   if(i>j){
     cout << "Warning: First argument should be smaller than second argument" << endl;
     cout << "         Setting reverse order (Delta" << j << i << "). " << endl;
     int temp = i;
     i = j;
     j = temp;
   }
   if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
     cout << "ERROR: Delta" << i << j << " not valid for " << fNumNus;
     cout << " neutrinos. Returning zero." << endl;
     return 0;
   }
   if(i+1==j){
     cout << "Warning: Rotation " << i << j << " is real. Returning zero." << endl;
     return 0;
   }
   return fDelta[i-1][j-1];
 }
GetDm()
double PMNS_Base::GetDm (int j) virtual inherited
Get the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
Parameters
j - the index of dm_j1
Definition at line 697 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
 {
   if(j<2 || j>fNumNus){
     cout << "ERROR: Dm" << j << "1 not valid for " << fNumNus;
     cout << " neutrinos. Returning zero." << endl;
     return 0;
   }
   return fDm[j-1];
 }
GetEnergy()
double PMNS_Base::GetEnergy () virtual inherited
Get the neutrino energy in GeV.
Definition at line 186 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fEnergy.
{
   return fEnergy;
 }
GetEps()
complex< double > PMNS_NSI::GetEps (int flvi, int flvj) virtual
Get any given NSI parameter.
Flavours are:
0 = nue, 1 = numu, 2 = nutau
Requires that flvi < flvj. Will notify you if input is wrong. If flvi > flvj, will assume reverse order and swap flvi and flvj.
Parameters
flvi - The first flavour index
flvj - The second flavour index
Definition at line 131 of file PMNS_NSI.cxx.
References fEps, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::zero.
{
   if(flvi > flvj){
     cout << "First argument should be smaller or equal to second argument" << endl;
     cout << "Setting reverse order (Eps_" << flvj << flvi << "). " << endl;
     int temp = flvi;
     flvi = flvj;
     flvj = temp;
   }
   if(flvi<0 || flvi>2 || flvj < flvi || flvj > 2){
     cout << "Eps_" << flvi << flvj << " not valid for " << fNumNus;
     cout << " neutrinos. Returning 0." << endl;
     return zero;
   }
   return fEps[flvi][flvj];
 }
GetIsNuBar()
bool PMNS_Base::GetIsNuBar () virtual inherited
Get the anti-neutrino flag.
Definition at line 196 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fIsNuBar.
{
   return fIsNuBar;
 }
GetPath()
vector< NuPath > PMNS_Base::GetPath () virtual inherited
Get the vector of neutrino paths.
Definition at line 249 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNuPaths.
{
   return fNuPaths;
 }
GetSamplePoints()
vector< double > PMNS_Base::GetSamplePoints (double LoE, double dLoE) virtual inherited
Compute the sample points for a bin of L/E with width dLoE
This is used for averaging the probability over a bin of L/E. It should be a private function, but I'm keeping it public for now for debugging purposes. The number of sample points seems too high for most purposes. The number of subdivisions needs to be optimized.
Parameters
LoE - The neutrino L/E value in the bin center in km/GeV
dLoE - The L/E bin width in km/GeV
Definition at line 1223 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kKm2eV, and OscProb::PMNS_Base::SolveHam().
Referenced by OscProb::PMNS_Base::AvgProbLoE().
 {
   // Solve Hamiltonian to get eigenvalues
   SolveHam();
   // Define conversion factor [km/GeV -> 1/(4 eV^2)]
   const double k1267 = kKm2eV / (4 * kGeV2eV);
   // Get list of all effective Dm^2
   vector<double> effDm;
   for(int i=0; i<fNumNus-1; i++){
     for(int j=i+1; j<fNumNus; j++){
       effDm.push_back( 2 * kGeV2eV * fEnergy * fabs(fEval[j] - fEval[i]) );
     }
   }
   int numDm = effDm.size();
   // Set a number of sub-divisions to achieve "good" accuracy
   // This needs to be studied better
   int n_div = ceil( 20 * pow(dLoE/LoE,0.8) );
   //int n_div = 1;
   // A vector to store sample points
   vector<double> allSamples;
   // Loop over sub-divisions
   for(int k=0; k<n_div; k++){
     // Define sub-division center and width
     double bctr = LoE - dLoE/2 + (k+0.5)*dLoE/n_div;
     double bwdt = dLoE/n_div;
     // Make a list of indices sorted by Dm^2 value
     vector<int> Idx(numDm, 0);
     for(int i=0; i<numDm; i++) Idx[i] = i;
     sort(Idx.begin(), Idx.end(), IdxCompare(effDm));
     // Make a vector of L/E sample values
     // Initialized in the sub-division center
     vector<double> samples;
     samples.push_back(bctr);
     // Loop over all Dm^2 to average each frequency
     // This will recursively sample points in smaller
     // bins so that all relevant frequencies are used
     for(int i=0; i<numDm; i++){
       // Copy the list of sample L/E values
       vector<double> prev = samples;
       // Redefine bin width to lie within full sub-division
       double Width = 2*min(prev[0] - (bctr - bwdt/2), (bctr + bwdt/2) - prev[0]);
       // Compute oscillation argument sorted from lowest  to highest
       const double arg = k1267 * effDm[Idx[i]] * Width;
       // Skip small oscillation values.
       // If it's the last one, lower the tolerance
       if(i < numDm-1){
         if(arg<0.9) continue;
       }
       else{
         if(arg<0.1) continue;
       }
       // Reset samples to redefine them
       samples.clear();
       // Loop over previous samples
       for(int j=0; j<int(prev.size()); j++){
         // Compute new sample points around old samples
         // This is based on a oscillatory quadrature rule
         double sample = (1/sqrt(3)) * (Width/2);
         if(arg!=0) sample = acos(sin(arg)/arg)/arg * (Width/2);
         // Add samples above and below center
         samples.push_back(prev[j]-sample);
         samples.push_back(prev[j]+sample);
       }
     }// End of loop over Dm^2
     // Add sub-division samples to the end of allSamples vector
     allSamples.insert(allSamples.end(), samples.begin(), samples.end());
   }// End of loop over sub-divisions
   // Return all sample points
   return allSamples;
 }
InitializeVectors()
void PMNS_Base::InitializeVectors () protected virtual inherited
Set vector sizes and initialize elements to zero.
Definition at line 76 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fBuffer, OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::fPhases, OscProb::PMNS_Base::fTheta, and OscProb::PMNS_Base::zero.
Referenced by OscProb::PMNS_Base::PMNS_Base().
 {
   fDm    = vector<double>(fNumNus, 0);
   fTheta = vector< vector<double> >(fNumNus, vector<double>(fNumNus,0));
   fDelta = vector< vector<double> >(fNumNus, vector<double>(fNumNus,0));
   fNuState = vector<complex>(fNumNus, zero);
   fHms     = vector< vector<complex> >(fNumNus, vector<complex>(fNumNus,zero));
   fPhases = vector<complex>(fNumNus, zero);
   fBuffer = vector<complex>(fNumNus, zero);
   fEval = vector<double>(fNumNus, 0);
   fEvec = vector< vector<complex> >(fNumNus, vector<complex>(fNumNus,zero));
 }
P()
double PMNS_Base::P (int flv) protected virtual inherited
Compute oscillation probability of flavour flv from current state
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino final flavour.
Returns
Neutrino oscillation probability
Reimplemented in OscProb::PMNS_Deco.
Definition at line 968 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fNuState.
Referenced by OscProb::PMNS_Base::Prob().
 {
   assert(flv>=0 && flv<fNumNus);
   return norm(fNuState[flv]);
 }
Prob() [1/3]
double PMNS_Base::Prob (int flvi, int flvf) virtual inherited
Compute the probability of flvi going to flvf.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
Returns
Neutrino oscillation probability
Definition at line 988 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::P(), OscProb::PMNS_Base::Propagate(), and OscProb::PMNS_Base::ResetToFlavour().
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), and OscProb::PMNS_Base::Prob().
 {
   if(flvi < 0 || flvi >= fNumNus){
     cout << "ERROR: Initial flavour not in range: 0 - " << fNumNus-1 << endl;
   }
   if(flvf < 0 || flvf >= fNumNus){
     cout << "ERROR: Final flavour not in range: 0 - " << fNumNus-1 << endl;
   }
   ResetToFlavour(flvi);
   Propagate();
   return P(flvf);
 }
Prob() [2/3]
double PMNS_Base::Prob (int flvi, int flvf, double E) virtual inherited
Compute the probability of flvi going to flvf for a given energy in GeV.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
Returns
Neutrino oscillation probability
Definition at line 1021 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::Prob(), and OscProb::PMNS_Base::SetEnergy().
 {
   SetEnergy(E);
   return Prob(flvi, flvf);
 }
Prob() [3/3]
double PMNS_Base::Prob (int flvi, int flvf, double E, double L) virtual inherited
Compute the probability of flvi going to flvf for a given energy in GeV and distance in km in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost.
Don't use this if you want to propagate over multiple path segments.
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flvi - The neutrino starting flavour.
flvf - The neutrino final flavour.
E - The neutrino energy in GeV
L - The neutrino path length in km
Returns
Neutrino oscillation probability
Definition at line 1052 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::SetEnergy(), and OscProb::PMNS_Base::SetLength().
 {
   SetEnergy(E);
   SetLength(L);
   return Prob(flvi, flvf);
 }
Propagate()
void PMNS_Base::Propagate () protected virtual inherited
Propagate neutrino state through full path
Definition at line 924 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::PropagatePath().
Referenced by OscProb::PMNS_Base::Prob().
 {
   for(int i=0; i<int(fNuPaths.size()); i++){
     PropagatePath(fNuPaths[i]);
   }
 }
PropagatePath()
void PMNS_Base::PropagatePath (OscProb::NuPath p) protected virtual inherited
Propagate the current neutrino state through a given path
Parameters
p - A neutrino path segment
Reimplemented in OscProb::PMNS_Deco.
Definition at line 887 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fBuffer, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::fPhases, OscProb::PMNS_Base::kKm2eV, OscProb::NuPath::length, OscProb::PMNS_Base::SetCurPath(), and OscProb::PMNS_Base::SolveHam().
Referenced by OscProb::PMNS_Base::Propagate().
 {
   // Set the neutrino path
   SetCurPath(p);
   // Solve for eigensystem
   SolveHam();
   double LengthIneV = kKm2eV * p.length;
   for(int i=0; i<fNumNus; i++){
     double arg = fEval[i] * LengthIneV;
     fPhases[i] = complex(cos(arg), -sin(arg));
   }
   for(int i=0;i<fNumNus;i++){
     fBuffer[i] = 0;
     for(int j=0;j<fNumNus;j++){
       fBuffer[i] += conj(fEvec[j][i]) * fNuState[j];
     }
     fBuffer[i] *= fPhases[i];
   }
   // Propagate neutrino state
   for(int i=0;i<fNumNus;i++){
     fNuState[i] = 0;
     for(int j=0;j<fNumNus;j++){
       fNuState[i] +=  fEvec[i][j] * fBuffer[j];
     }
   }
 }
ResetToFlavour()
void PMNS_Base::ResetToFlavour (int flv) protected virtual inherited
Reset the neutrino state back to a pure flavour where it starts
Flavours are:
  0 = nue, 1 = numu, 2 = nutau
  3 = sterile_1, 4 = sterile_2, etc.
Parameters
flv - The neutrino starting flavour.
Reimplemented in OscProb::PMNS_Deco.
Definition at line 946 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fNuState, OscProb::PMNS_Base::one, and OscProb::PMNS_Base::zero.
Referenced by OscProb::PMNS_Base::PMNS_Base(), and OscProb::PMNS_Base::Prob().
 {
   assert(flv>=0 && flv<fNumNus);
   for (int i=0; i<fNumNus; ++i){
     if (i==flv) fNuState[i] = one;
     else        fNuState[i] = zero;
   }
 }
RotateH()
void PMNS_Base::RotateH (int i, int j) protected virtual inherited
Rotate the Hamiltonian by the angle theta_ij and phase delta_ij.
The rotations assume all off-diagonal elements with i > j are zero. This is correct if the order of rotations is chosen appropriately and it speeds up computation by skipping null terms
Parameters
i,j - the indices of the rotation ij
Definition at line 721 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fHms, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Base::BuildHms().
{
   // Do nothing if angle is zero
   if(fTheta[i][j]==0) return;
   double fSinBuffer = sin(fTheta[i][j]);
   double fCosBuffer = cos(fTheta[i][j]);
   double  fHmsBufferD;
   complex fHmsBufferC;
   // With Delta
   if(i+1<j){
     complex fExpBuffer = complex(cos(fDelta[i][j]), -sin(fDelta[i][j]));
     // General case
     if(i>0){
       // Top columns
       for(int k=0; k<i; k++){
         fHmsBufferC = fHms[k][i];
         fHms[k][i] *= fCosBuffer;
         fHms[k][i] += fHms[k][j] * fSinBuffer * conj(fExpBuffer);
         fHms[k][j] *= fCosBuffer;
         fHms[k][j] -= fHmsBufferC * fSinBuffer * fExpBuffer;
       }
       // Middle row and column
       for(int k=i+1; k<j; k++){
         fHmsBufferC = fHms[k][j];
         fHms[k][j] *= fCosBuffer;
         fHms[k][j] -= conj(fHms[i][k]) * fSinBuffer * fExpBuffer;
         fHms[i][k] *= fCosBuffer;
         fHms[i][k] += fSinBuffer * fExpBuffer * conj(fHmsBufferC);
       }
       // Nodes ij
       fHmsBufferC = fHms[i][i];
       fHmsBufferD = real(fHms[j][j]);
       fHms[i][i] *= fCosBuffer * fCosBuffer;
       fHms[i][i] += 2 * fSinBuffer * fCosBuffer * real(fHms[i][j] * conj(fExpBuffer));
       fHms[i][i] += fSinBuffer * fHms[j][j] * fSinBuffer;
       fHms[j][j] *= fCosBuffer * fCosBuffer;
       fHms[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
       fHms[j][j] -= 2 * fSinBuffer * fCosBuffer * real(fHms[i][j] * conj(fExpBuffer));
       fHms[i][j] -= 2 * fSinBuffer * real(fHms[i][j] * conj(fExpBuffer)) * fSinBuffer * fExpBuffer;
       fHms[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC) * fExpBuffer;
     }
     // First rotation on j (No top columns)
     else{
       // Middle rows and columns
       for(int k=i+1; k<j; k++){
         fHms[k][j] = -conj(fHms[i][k]) * fSinBuffer * fExpBuffer;
         fHms[i][k] *= fCosBuffer;
       }
       // Nodes ij
       fHmsBufferD = real(fHms[i][i]);
       fHms[i][j] = fSinBuffer * fCosBuffer * (fHms[j][j] - fHmsBufferD) * fExpBuffer;
       fHms[i][i] *= fCosBuffer * fCosBuffer;
       fHms[i][i] += fSinBuffer * fHms[j][j] * fSinBuffer;
       fHms[j][j] *= fCosBuffer * fCosBuffer;
       fHms[j][j] += fSinBuffer * fHmsBufferD * fSinBuffer;
     }
   }
   // Without Delta (No middle rows or columns: j = i+1)
   else{
     // General case
     if(i>0){
       // Top columns
       for(int k=0; k<i; k++){
         fHmsBufferC = fHms[k][i];
         fHms[k][i] *= fCosBuffer;
         fHms[k][i] += fHms[k][j] * fSinBuffer;
         fHms[k][j] *= fCosBuffer;
         fHms[k][j] -= fHmsBufferC * fSinBuffer;
       }
       // Nodes ij
       fHmsBufferC = fHms[i][i];
       fHmsBufferD = real(fHms[j][j]);
       fHms[i][i] *= fCosBuffer * fCosBuffer;
       fHms[i][i] += 2 * fSinBuffer * fCosBuffer * real(fHms[i][j]);
       fHms[i][i] += fSinBuffer * fHms[j][j] * fSinBuffer;
       fHms[j][j] *= fCosBuffer * fCosBuffer;
       fHms[j][j] += fSinBuffer * fHmsBufferC * fSinBuffer;
       fHms[j][j] -= 2 * fSinBuffer * fCosBuffer * real(fHms[i][j]);
       fHms[i][j] -= 2 * fSinBuffer * real(fHms[i][j]) * fSinBuffer;
       fHms[i][j] += fSinBuffer * fCosBuffer * (fHmsBufferD - fHmsBufferC);
     }
     // First rotation (theta12)
     else{
       fHms[i][j] = fSinBuffer * fCosBuffer * fHms[j][j];
       fHms[i][i] = fSinBuffer * fHms[j][j] * fSinBuffer;
       fHms[j][j] *= fCosBuffer * fCosBuffer;
     }
   }
 }
SetAngle()
void PMNS_Base::SetAngle (int i, int j, double th) virtual inherited
Set the mixing angle theta_ij in radians.
Requires that i<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of theta_ij
th - the value of theta_ij
Definition at line 535 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fNumNus, and OscProb::PMNS_Base::fTheta.
Referenced by OscProb::PMNS_Fast::SetMix(), and OscProb::PMNS_Base::SetStdPars().
 {
   if(i>j){
     cout << "Warning: First argument should be smaller than second argument" << endl;
     cout << "         Setting reverse order (Theta" << j << i << "). " << endl;
     int temp = i;
     i = j;
     j = temp;
   }
   if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
     cout << "ERROR: Theta" << i << j << " not valid for " << fNumNus;
     cout << " neutrinos. Doing nothing." << endl;
     return;
   }
   // Check if value is actually changing
   fBuiltHms *= (fTheta[i-1][j-1] == th);
   fTheta[i-1][j-1] = th;
 }
SetAtt() [1/2]
void PMNS_Base::SetAtt (double att, int idx) protected virtual inherited
Set some single path attribute.
An auxiliary function to set individual attributes in a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
att - The value of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 324 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNuPaths, and OscProb::PMNS_Base::SetStdPath().
Referenced by OscProb::PMNS_Base::SetDensity(), OscProb::PMNS_Base::SetLayers(), OscProb::PMNS_Base::SetLength(), and OscProb::PMNS_Base::SetZoA().
{
   if(fNuPaths.size() != 1){
     cout << "Warning: Clearing path vector and starting new single path." << endl;
     cout << "To avoid possible issues, use the SetPath function." << endl;
     SetStdPath();
   }
   switch(idx){
     case 0: fNuPaths[0].length  = att; break;
     case 1: fNuPaths[0].density = att; break;
     case 2: fNuPaths[0].zoa     = att; break;
     case 3: fNuPaths[0].layer   = att; break;
   }
 }
SetAtt() [2/2]
void PMNS_Base::SetAtt (std::vector< double > att, int idx) protected virtual inherited
Set all values of a path attribute.
An auxiliary function to set individual attributes in a path sequence.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
att - The values of the attribute
idx - The index of the attribute (0,1,2,3) = (L, Rho, Z/A, Layer)
Definition at line 401 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::ClearPath(), OscProb::NuPath::density, OscProb::PMNS_Base::fNuPaths, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetStdPath(), and OscProb::NuPath::zoa.
{
   // Get the sizes of the attribute and
   // path sequence vectors
   int nA = att.size();
   int nP = fNuPaths.size();
   // If the vector sizes are equal, update this attribute
   if(nA == nP){
     for(int i=0; i<nP; i++){
       switch(idx){
         case 0: fNuPaths[i].length  = att[i]; break;
         case 1: fNuPaths[i].density = att[i]; break;
         case 2: fNuPaths[i].zoa     = att[i]; break;
         case 3: fNuPaths[i].layer   = att[i]; break;
       }
     }
   }
   // If the vector sizes differ, create a new path sequence
   // and set value for this attribute. Other attributes will
   // be taken from default single path.
   else{
     cout << "Warning: New vector size. Starting new path vector." << endl;
     cout << "To avoid possible issues, use the SetPath function." << endl;
     // Start a new standard path just
     // to set default values
     SetStdPath();
     // Create a path segment with default values
     NuPath p = fNuPaths[0];
     // Clear the path sequence
     ClearPath();
     // Set this particular attribute's value
     // and add the path segment to the sequence
     for(int i=0; i<nA; i++){
       switch(idx){
         case 0: p.length  = att[i]; break;
         case 1: p.density = att[i]; break;
         case 2: p.zoa     = att[i]; break;
         case 3: p.layer   = att[i]; break;
       }
       AddPath(p);
     }
   }
 }
SetCurPath()
void PMNS_Base::SetCurPath (OscProb::NuPath p) protected virtual inherited
Set the path currentlyin use by the class.
This will be used to know what path to propagate through next.
It will also check if values are changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
p - A neutrino path segment
Definition at line 213 of file PMNS_Base.cxx.
References OscProb::NuPath::density, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Base::fPath, and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Deco::PropagatePath(), and OscProb::PMNS_Base::PropagatePath().
 {
   // Check if relevant value are actually changing
   fGotES *= (fPath.density == p.density);
   fGotES *= (fPath.zoa == p.zoa);
   fPath = p;
 }
SetDelta()
void PMNS_Base::SetDelta (int i, int j, double delta) virtual inherited
Set the CP phase delta_ij in radians.
Requires that i+1<j. Will notify you if input is wrong. If i>j, will assume reverse order and swap i and j.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
i,j - the indices of delta_ij
delta - the value of delta_ij
Definition at line 601 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDelta, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Fast::SetMix().
 {
   if(i>j){
     cout << "Warning: First argument should be smaller than second argument" << endl;
     cout << "         Setting reverse order (Delta" << j << i << "). " << endl;
     int temp = i;
     i = j;
     j = temp;
   }
   if(i<1 || i>fNumNus-1 || j<2 || j>fNumNus){
     cout << "ERROR: Delta" << i << j << " not valid for " << fNumNus;
     cout << " neutrinos. Doing nothing." << endl;
     return;
   }
   if(i+1==j){
     cout << "Warning: Rotation " << i << j << " is real. Doing nothing." << endl;
     return;
   }
   // Check if value is actually changing
   fBuiltHms *= (fDelta[i-1][j-1] == delta);
   fDelta[i-1][j-1] = delta;
 }
SetDeltaMsqrs()
void PMNS_Fast::SetDeltaMsqrs (double dm21, double dm32) virtual inherited
Set both mass-splittings at once.
These are Dm_21 and Dm_32 in eV^2.
The corresponding Dm_31 is set in the class attributes.
Parameters
dm21 - The solar mass-splitting Dm_21
dm32 - The atmospheric mass-splitting Dm_32
Definition at line 60 of file PMNS_Fast.cxx.
References OscProb::PMNS_Base::SetDm().
 {
   SetDm(2, dm21);
   SetDm(3, dm32 + dm21);
 }
SetDensity() [1/2]
void PMNS_Base::SetDensity (double rho) virtual inherited
Set single path density.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The density of the path segment in g/cm^3
Definition at line 368 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetAtt().
{
   SetAtt(rho, 1);
 }
SetDensity() [2/2]
void PMNS_Base::SetDensity (std::vector< double > rho) virtual inherited
Set multiple path densities.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
rho - The densities of the path segments in g/cm^3
Definition at line 484 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetAtt().
{
   SetAtt(rho, 1);
 }
SetDm()
void PMNS_Base::SetDm (int j, double dm) virtual inherited
Set the mass-splitting dm_j1 = (m_j^2 - m_1^2) in eV^2
Requires that j>1. Will notify you if input is wrong.
This will check if value is changing to keep track of whether the hamiltonian needs to be rebuilt.
Parameters
j - the index of dm_j1
dm - the value of dm_j1
Definition at line 673 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fBuiltHms, OscProb::PMNS_Base::fDm, and OscProb::PMNS_Base::fNumNus.
Referenced by OscProb::PMNS_Fast::SetDeltaMsqrs(), and OscProb::PMNS_Base::SetStdPars().
 {
   if(j<2 || j>fNumNus){
     cout << "ERROR: Dm" << j << "1 not valid for " << fNumNus;
     cout << " neutrinos. Doing nothing." << endl;
     return;
   }
   // Check if value is actually changing
   fBuiltHms *= (fDm[j-1] == dm);
   fDm[j-1] = dm;
 }
SetEnergy()
void PMNS_Base::SetEnergy (double E) virtual inherited
Set neutrino energy in GeV.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
E - The neutrino energy in GeV
Definition at line 153 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fEnergy, and OscProb::PMNS_Base::fGotES.
Referenced by OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::PMNS_Base(), and OscProb::PMNS_Base::Prob().
 {
   // Check if value is actually changing
   fGotES *= (fEnergy == E);
   fEnergy = E;
 }
SetEps()
void PMNS_NSI::SetEps (int flvi, int flvj, double val, double phase) virtual
Set any given NSI parameter.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Flavours are:
0 = nue, 1 = numu, 2 = nutau
Requires that flvi < flvj. Will notify you if input is wrong. If flvi > flvj, will assume reverse order and swap flvi and flvj.
Parameters
flvi - The first flavour index
flvj - The second flavour index
val - The absolute value of the parameter
phase - The complex phase of the parameter in radians
Definition at line 91 of file PMNS_NSI.cxx.
References fEps, OscProb::PMNS_Base::fGotES, and OscProb::PMNS_Base::fNumNus.
Referenced by SetEps_ee(), SetEps_emu(), SetEps_etau(), SetEps_mumu(), SetEps_mutau(), SetEps_tautau(), and SetNSI().
{
   if(flvi > flvj){
     cout << "First argument should be smaller or equal to second argument" << endl;
     cout << "Setting reverse order (Eps_" << flvj << flvi << "). " << endl;
     int temp = flvi;
     flvi = flvj;
     flvj = temp;
   }
   if(flvi<0 || flvi>2 || flvj < flvi || flvj > 2){
     cout << "Eps_" << flvi << flvj << " not valid for " << fNumNus;
     cout << " neutrinos. Doing nothing." << endl;
     return;
   }
   complex h = val;
   if(flvi != flvj) h *= complex(cos(phase), sin(phase));
   else if(flvi == 0) h += 1;
   fGotES *= (fEps[flvi][flvj] == h);
   fEps[flvi][flvj] = h;
 }
SetEps_ee()
void PMNS_NSI::SetEps_ee (double a) virtual
Set eps_ee parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The value of the real parameter eps_ee
Definition at line 159 of file PMNS_NSI.cxx.
References SetEps().
 { SetEps(0,0, a, 0); }
SetEps_emu()
void PMNS_NSI::SetEps_emu (double a, double phi) virtual
Set eps_emu parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The absolute value of the parameter eps_emu
phi - The phase of the complex parameter eps_emu in radians
Definition at line 193 of file PMNS_NSI.cxx.
References SetEps().
 { SetEps(0,1, a, phi); }
SetEps_etau()
void PMNS_NSI::SetEps_etau (double a, double phi) virtual
Set eps_etau parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The absolute value of the parameter eps_etau
phi - The phase of the complex parameter eps_etau in radians
Definition at line 205 of file PMNS_NSI.cxx.
References SetEps().
 { SetEps(0,2, a, phi); }
SetEps_mumu()
void PMNS_NSI::SetEps_mumu (double a) virtual
Set eps_mumu parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The value of the real parameter eps_mumu
Definition at line 170 of file PMNS_NSI.cxx.
References SetEps().
 { SetEps(1,1, a, 0); }
SetEps_mutau()
void PMNS_NSI::SetEps_mutau (double a, double phi) virtual
Set eps_mutau parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The absolute value of the parameter eps_mutau
phi - The phase of the complex parameter eps_mutau in radians
Definition at line 217 of file PMNS_NSI.cxx.
References SetEps().
 { SetEps(1,2, a, phi); }
SetEps_tautau()
void PMNS_NSI::SetEps_tautau (double a) virtual
Set eps_tautau parameter
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
a - The value of the real parameter eps_tautau
Definition at line 181 of file PMNS_NSI.cxx.
References SetEps().
 { SetEps(2,2, a, 0); }
SetIsNuBar()
void PMNS_Base::SetIsNuBar (bool isNuBar) virtual inherited
Set anti-neutrino flag.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
isNuBar - Set to true for anti-neutrino and false for neutrino.
Definition at line 172 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fGotES, and OscProb::PMNS_Base::fIsNuBar.
Referenced by OscProb::PMNS_Base::PMNS_Base().
 {
   // Check if value is actually changing
   fGotES *= (fIsNuBar == isNuBar);
   fIsNuBar = isNuBar;
 }
SetLayers()
void PMNS_Base::SetLayers (std::vector< int > lay) virtual inherited
Set multiple path layer indices.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
lay - Indices to identify the layer types (e.g. earth inner core)
Definition at line 514 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetAtt().
{
   vector<double> lay_double(lay.begin(), lay.end());
   SetAtt(lay_double, 3);
 }
SetLength() [1/2]
void PMNS_Base::SetLength (double L) virtual inherited
Set the length for a single path.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
L - The length of the path segment in km
Definition at line 353 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetAtt().
Referenced by OscProb::PMNS_Base::Prob().
{
   SetAtt(L, 0);
 }
SetLength() [2/2]
void PMNS_Base::SetLength (std::vector< double > L) virtual inherited
Set multiple path lengths.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
L - The lengths of the path segments in km
Definition at line 469 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetAtt().
{
   SetAtt(L, 0);
 }
SetMix()
void PMNS_Fast::SetMix (double th12, double th23, double th13, double deltacp) virtual inherited
Set all mixing parameters at once.
Parameters
th12 - The value of the mixing angle theta_12
th23 - The value of the mixing angle theta_23
th13 - The value of the mixing angle theta_13
deltacp - The value of the CP phase delta_13
Definition at line 40 of file PMNS_Fast.cxx.
References OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDelta().
 {
   SetAngle(1,2, th12);
   SetAngle(1,3, th13);
   SetAngle(2,3, th23);
   SetDelta(1,3, deltacp);
 }
SetNSI()
void PMNS_NSI::SetNSI (double eps_ee, double eps_emu, double eps_etau, double eps_mumu, double eps_mutau, double eps_tautau, double delta_emu = 0, double delta_etau = 0, double delta_mutau = 0)
Set all NSI parameters at once.
This will check if value is changing to keep track of whether the eigensystem needs to be recomputed.
Parameters
eps_ee - The real parameter eps_ee
eps_emu - The absolute value of the complex parameter eps_emu
eps_etau - The absolute value of the complex parameter eps_etau
eps_mumu - The real parameter eps_mumu
eps_mutau - The absolute value of the complex parameter eps_mutau
eps_tautau - The real parameter eps_tautau
delta_emu - The phase of the complex parameter eps_emu in radians
delta_etau - The phase of the complex parameter eps_etau in radians
delta_mutau - The phase of the complex parameter eps_mutau in radians
Definition at line 58 of file PMNS_NSI.cxx.
References SetEps().
Referenced by PMNS_NSI().
 {
   SetEps(0,0, eps_ee,     0);
   SetEps(1,1, eps_mumu,   0);
   SetEps(2,2, eps_tautau, 0);
   SetEps(0,1, eps_emu,   delta_emu);
   SetEps(0,2, eps_etau,  delta_etau);
   SetEps(1,2, eps_mutau, delta_mutau);
 }
SetPath() [1/3]
void PMNS_Base::SetPath (OscProb::NuPath p) virtual inherited
Set a single path.
This destroys the current path sequence and creates a new first path.
Parameters
p - A neutrino path segment
Definition at line 288 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::AddPath(), and OscProb::PMNS_Base::ClearPath().
Referenced by OscProb::PMNS_Base::SetPath(), and OscProb::PMNS_Base::SetStdPath().
{
   ClearPath();
   AddPath(p);
 }
SetPath() [2/3]
void PMNS_Base::SetPath (double length, double density, double zoa = 0.5, int layer = 0) virtual inherited
Set a single path defining attributes directly.
This destroys the current path sequence and creates a new first path.
Parameters
length - The length of the path segment in km
density - The density of the path segment in g/cm^3
zoa - The effective Z/A of the path segment
layer - An index to identify the layer type (e.g. earth inner core)
Definition at line 306 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetPath().
{
   SetPath(NuPath(length, density, zoa, layer));
 }
SetPath() [3/3]
void PMNS_Base::SetPath (std::vector< OscProb::NuPath > paths) virtual inherited
Set vector of neutrino paths.
Parameters
paths - A sequence of neutrino paths
Definition at line 239 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNuPaths.
{
   fNuPaths=paths;
 }
SetStdPars()
void PMNS_Base::SetStdPars () virtual inherited
Set standard oscillation parameters from PDG 2015.
For two neutrinos, Dm is set to the muon disappearance effective mass-splitting and mixing angle.
Definition at line 101 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Base::SetDm().
Referenced by OscProb::PMNS_Base::PMNS_Base().
 {
   if(fNumNus>2){
     // PDG values for 3 neutrinos
     // Also applicable for 3+N neutrinos
     SetAngle(1,2, asin(sqrt(0.304)));
     SetAngle(1,3, asin(sqrt(0.0219)));
     SetAngle(2,3, asin(sqrt(0.514)));
     SetDm(2, 7.53e-5);
     SetDm(3, 2.52e-3);
   }
   else if(fNumNus==2){
     // Effective muon disappearance values
     // for two-flavour approximation
     SetAngle(1,2, 0.788);
     SetDm(2, 2.47e-3);
   }
 }
SetStdPath()
void PMNS_Base::SetStdPath () virtual inherited
Set standard single path.
Length is 1000 km, so ~2 GeV peak energy.
Density is approximate from CRUST2.0 (~2.8 g/cm^3). Z/A is set to a round 0.5.
Definition at line 131 of file PMNS_Base.cxx.
References OscProb::NuPath::density, OscProb::NuPath::layer, OscProb::NuPath::length, OscProb::PMNS_Base::SetPath(), and OscProb::NuPath::zoa.
Referenced by OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Deco::PMNS_Deco(), PMNS_NSI(), and OscProb::PMNS_Base::SetAtt().
{
   NuPath p;
   p.length  = 1000; // 1000 km default
   p.density = 2.8;  // Crust density
   p.zoa     = 0.5;  // Crust Z/A
   p.layer   = 0;    // Single layer
   SetPath(p);
 }
SetVacuumEigensystem()
void PMNS_Fast::SetVacuumEigensystem () protected virtual inherited
Set the eigensystem to the analytic solution in vacuum.
We know the vacuum eigensystem, so just write it explicitly
Definition at line 146 of file PMNS_Fast.cxx.
References OscProb::PMNS_Base::fDelta, OscProb::PMNS_Base::fDm, OscProb::PMNS_Base::fEnergy, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fTheta, and OscProb::PMNS_Base::kGeV2eV.
Referenced by OscProb::PMNS_Fast::SolveHam().
 {
   double  s12, s23, s13, c12, c23, c13;
   complex idelta(0.0, fDelta[0][2]);
   if(fIsNuBar) idelta = conj(idelta);
   s12 = sin(fTheta[0][1]);  s23 = sin(fTheta[1][2]);  s13 = sin(fTheta[0][2]);
   c12 = cos(fTheta[0][1]);  c23 = cos(fTheta[1][2]);  c13 = cos(fTheta[0][2]);
   fEvec[0][0] =  c12*c13;
   fEvec[0][1] =  s12*c13;
   fEvec[0][2] =  s13*exp(-idelta);
   fEvec[1][0] = -s12*c23-c12*s23*s13*exp(idelta);
   fEvec[1][1] =  c12*c23-s12*s23*s13*exp(idelta);
   fEvec[1][2] =  s23*c13;
   fEvec[2][0] =  s12*s23-c12*c23*s13*exp(idelta);
   fEvec[2][1] = -c12*s23-s12*c23*s13*exp(idelta);
   fEvec[2][2] =  c23*c13;
   fEval[0] = 0;
   fEval[1] = fDm[1] / (2 * kGeV2eV*fEnergy);
   fEval[2] = fDm[2] / (2 * kGeV2eV*fEnergy);
 }
SetZoA() [1/2]
void PMNS_Base::SetZoA (double zoa) virtual inherited
Set single path Z/A.
If the path sequence is not a single path, a new single path will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segment
Definition at line 383 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetAtt().
{
   SetAtt(zoa, 2);
 }
SetZoA() [2/2]
void PMNS_Base::SetZoA (std::vector< double > zoa) virtual inherited
Set multiple path Z/A values.
If the path sequence is of a different size, a new path sequence will be created and the previous sequence will be lost. Use with care.
Parameters
zoa - The effective Z/A of the path segments
Definition at line 499 of file PMNS_Base.cxx.
References OscProb::PMNS_Base::SetAtt().
{
   SetAtt(zoa, 2);
 }
SolveHam()
void PMNS_Fast::SolveHam () protected virtual inherited
Solve the full Hamiltonian for eigenvectors and eigenvalues.
This is using a method from the GLoBES software available at http://www.mpi-hd.mpg.de/personalhomes/globes/3x3/
We should cite them accordingly
Implements OscProb::PMNS_Base.
Definition at line 105 of file PMNS_Fast.cxx.
References OscProb::PMNS_Base::BuildHms(), OscProb::NuPath::density, OscProb::PMNS_Base::fEval, OscProb::PMNS_Base::fEvec, OscProb::PMNS_Base::fGotES, OscProb::PMNS_Fast::fHam, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Fast::UpdateHam(), and zheevh3().
Referenced by OscProb::PMNS_Deco::PropagatePath().
 {
   // Do vacuum oscillation in low density
   if(fPath.density < 1.0e-6){
     SetVacuumEigensystem();
     return;
   }
   // Build Hamiltonian
   BuildHms();
   // Check if anything changed
   if(fGotES) return;
   UpdateHam();
   double fEvalGLoBES[3];
   complex fEvecGLoBES[3][3];
   // Solve Hamiltonian for eigensystem using the GLoBES method
   zheevh3(fHam,fEvecGLoBES,fEvalGLoBES);
   // Fill fEval and fEvec vectors from GLoBES arrays
   for(int i=0;i<fNumNus;i++){
     fEval[i] = fEvalGLoBES[i];
     for(int j=0;j<fNumNus;j++){
       fEvec[i][j] = fEvecGLoBES[i][j];
     }
   }
   fGotES = true;
 }
UpdateHam()
void PMNS_NSI::UpdateHam () protected virtual
Build the full Hamiltonian in matter
Here we divide the mass squared matrix Hms by the 2E to obtain the vacuum Hamiltonian in eV. Then, the matter potential is added to each flavour pair.
Reimplemented from OscProb::PMNS_Fast.
Definition at line 227 of file PMNS_NSI.cxx.
References OscProb::NuPath::density, OscProb::PMNS_Base::fEnergy, fEps, OscProb::PMNS_Fast::fHam, OscProb::PMNS_Base::fHms, OscProb::PMNS_Base::fIsNuBar, OscProb::PMNS_Base::fNumNus, OscProb::PMNS_Base::fPath, OscProb::PMNS_Base::kGeV2eV, OscProb::PMNS_Base::kGf, OscProb::PMNS_Base::kK2, and OscProb::NuPath::zoa.
 {
   double lv = 2 * kGeV2eV*fEnergy;           // 2*E in eV
   double kr2GNe = kK2*M_SQRT2*kGf;
   kr2GNe *= fPath.density * fPath.zoa; // Matter potential in eV
   // Finish build Hamiltonian in matter with dimension of eV
   for(int i=0;i<fNumNus;i++){
     for(int j=i;j<fNumNus;j++){
       if(!fIsNuBar) fHam[i][j] = fHms[i][j]/lv + kr2GNe*fEps[i][j];
       else          fHam[i][j] = conj(fHms[i][j]/lv - kr2GNe*fEps[i][j]);
     }
   }
 }
Member Data Documentation
fBuffer
std::vector<complex> OscProb::PMNS_Base::fBuffer protected inherited
Definition at line 165 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::InitializeVectors(), and OscProb::PMNS_Base::PropagatePath().
fBuiltHms
bool OscProb::PMNS_Base::fBuiltHms protected inherited
Definition at line 176 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_Base::SetDelta(), and OscProb::PMNS_Base::SetDm().
fDelta
std::vector< std::vector<double> > OscProb::PMNS_Base::fDelta protected inherited
Definition at line 159 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::SetDelta(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fDm
std::vector<double> OscProb::PMNS_Base::fDm protected inherited
Definition at line 157 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::GetDm(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Base::SetDm(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
fEnergy
double OscProb::PMNS_Base::fEnergy protected inherited
Definition at line 170 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetEnergy(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::SetEnergy(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
fEps
complex OscProb::PMNS_NSI::fEps[3][3] protected
Definition at line 58 of file PMNS_NSI.h.
Referenced by GetEps(), SetEps(), and UpdateHam().
fEval
std::vector<double> OscProb::PMNS_Base::fEval protected inherited
Definition at line 167 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHam().
fEvec
std::vector< std::vector<complex> > OscProb::PMNS_Base::fEvec protected inherited
Definition at line 168 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHam().
fGotES
bool OscProb::PMNS_Base::fGotES protected inherited
Definition at line 177 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Deco::SetDecoAngle(), OscProb::PMNS_Base::SetEnergy(), SetEps(), OscProb::PMNS_Deco::SetGamma(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Sterile::SolveHam(), and OscProb::PMNS_Fast::SolveHam().
fHam
complex OscProb::PMNS_Fast::fHam[3][3] protected inherited
Definition at line 62 of file PMNS_Fast.h.
Referenced by OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
fHms
std::vector< std::vector<complex> > OscProb::PMNS_Base::fHms protected inherited
Definition at line 162 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
fIsNuBar
bool OscProb::PMNS_Base::fIsNuBar protected inherited
Definition at line 171 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetIsNuBar(), OscProb::PMNS_Base::SetIsNuBar(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
fNumNus
int OscProb::PMNS_Base::fNumNus protected inherited
Definition at line 155 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::BuildHms(), OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_Base::GetDelta(), OscProb::PMNS_Base::GetDm(), GetEps(), OscProb::PMNS_Deco::GetGamma(), OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Deco::P(), OscProb::PMNS_Base::P(), OscProb::PMNS_Base::PMNS_Base(), OscProb::PMNS_Sterile::PMNS_Sterile(), OscProb::PMNS_Base::Prob(), OscProb::PMNS_Base::PropagatePath(), OscProb::PMNS_Deco::ResetToFlavour(), OscProb::PMNS_Base::ResetToFlavour(), OscProb::PMNS_Base::SetAngle(), OscProb::PMNS_Base::SetDelta(), OscProb::PMNS_Base::SetDm(), SetEps(), OscProb::PMNS_Deco::SetGamma(), OscProb::PMNS_Base::SetStdPars(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
fNuPaths
std::vector<OscProb::NuPath> OscProb::PMNS_Base::fNuPaths protected inherited
Definition at line 173 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AddPath(), OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::ClearPath(), OscProb::PMNS_Base::GetPath(), OscProb::PMNS_Base::Propagate(), OscProb::PMNS_Base::SetAtt(), and OscProb::PMNS_Base::SetPath().
fNuState
std::vector<complex> OscProb::PMNS_Base::fNuState protected inherited
Definition at line 161 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::P(), OscProb::PMNS_Base::PropagatePath(), and OscProb::PMNS_Base::ResetToFlavour().
fPath
OscProb::NuPath OscProb::PMNS_Base::fPath protected inherited
Definition at line 174 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::AvgProb(), OscProb::PMNS_Base::AvgProbLoE(), OscProb::PMNS_Base::SetCurPath(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
fPhases
std::vector<complex> OscProb::PMNS_Base::fPhases protected inherited
Definition at line 164 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::InitializeVectors(), and OscProb::PMNS_Base::PropagatePath().
fTheta
std::vector< std::vector<double> > OscProb::PMNS_Base::fTheta protected inherited
Definition at line 158 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetAngle(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Base::RotateH(), OscProb::PMNS_Base::SetAngle(), and OscProb::PMNS_Fast::SetVacuumEigensystem().
kGeV2eV
const double PMNS_Base::kGeV2eV = 1.0e+09 static protected inherited
Definition at line 115 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), OscProb::PMNS_Fast::SetVacuumEigensystem(), OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
kGf
const double PMNS_Base::kGf = 1.1663787e-05 static protected inherited
Definition at line 118 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
kK2
const double PMNS_Base::kK2 = 1e-3 * kNA / pow(kKm2eV,3) static protected inherited
Definition at line 114 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Sterile::SolveHam(), OscProb::PMNS_Fast::UpdateHam(), and UpdateHam().
kKm2eV
const double PMNS_Base::kKm2eV = 1.0 / 1.973269788e-10 static protected inherited
Definition at line 113 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Base::GetSamplePoints(), OscProb::PMNS_Deco::PropagatePath(), and OscProb::PMNS_Base::PropagatePath().
kNA
const double PMNS_Base::kNA = 6.022140857e23 static protected inherited
Definition at line 116 of file PMNS_Base.h.
one
const complex< double > PMNS_Base::one static protected inherited
Definition at line 110 of file PMNS_Base.h.
Referenced by OscProb::PMNS_Deco::ResetToFlavour(), and OscProb::PMNS_Base::ResetToFlavour().
zero
const complex< double > PMNS_Base::zero static protected inherited
Definition at line 109 of file PMNS_Base.h.
Referenced by GetEps(), OscProb::PMNS_Base::InitializeVectors(), OscProb::PMNS_Deco::ResetToFlavour(), and OscProb::PMNS_Base::ResetToFlavour().
The documentation for this class was generated from the following files:
/home/jcoelho/OscProbGit/PMNS_NSI.h
/home/jcoelho/OscProbGit/PMNS_NSI.cxx