set(CPACK_PACKAGE_NAME oscprob)
set(CPACK_PACKAGE_VENDOR KM3NeT)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "Package to compute the neutrino oscillation probabilities")
set(CPACK_PACKAGE_INSTALL_DIRECTION ${CPACK_PACKAGE_NAME})
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_VERBATIM_VARIABLES YES)

# set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_LIST_DIR}/Description.txt)
# set(CPACK_PACKAGE_DESCRIPTION_WELCOME ${CMAKE_CURRENT_LIST_DIR}/Welcome.txt)
# set(CPACK_PACKAGE_DESCRIPTION_LICENSE ${CMAKE_CURRENT_LIST_DIR}/License.txt)
# set(CPACK_PACKAGE_DESCRIPTION_README ${CMAKE_CURRENT_LIST_DIR}/Readme.txt)

if(APPLE)
  # set(CPACK_GENERATOR TGZ productbuild DragNDrop) productbuild = .pkg file
  # installer DragNDrop = .dmg file
  set(CPACK_GENERATOR DragNDrop)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CPACK_GENERATOR TGZ RPM)
else()
  set(CPACK_GENERATOR TGZ)
endif()

include(CPack)
